### ISSUE TITLE
V3 commands return 422 status code instead of 400 for malformed requests

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/cloud_controller_ng#1011]
## Issue

Many V3 endpoints return `422 Unprocessable` instead of `400 Bad Request` when the request message is malformed.

## Context

In pattern of using message objects to represent the body of requests made to V3 endpoints, message validation is generally restricted to syntactic rather than semantic validation. In our view, a 400 status code would be more appropriate than a 422 when this validation fails, since a 422 indicates a semantically invalid request.

We searched for `unprocessable! (message.errors.full_messages) unless message.valid?` in the cloud controller code and found many hits in the v3 controllers. Since it's so widespread, we thought it'd be best to raise this as an issue instead of PR immediately to see if there's some context we're missing.

```
→ ag 'unprocessable!\(message.errors.full_messages\) unless message.valid?'
app/controllers/internal/packages_controller.rb
13:        unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/app_features_controller.rb
38:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/apps_controller.rb
49:    unprocessable!(message.errors.full_messages) unless message.valid?
70:    unprocessable!(message.errors.full_messages) unless message.valid?
184:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/builds_controller.rb
8:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/droplets_controller.rb
58:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/isolation_segments_controller.rb
24:    unprocessable!(message.errors.full_messages) unless message.valid?
77:    unprocessable!(message.errors.full_messages) unless message.valid?
158:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/organizations_controller.rb
41:    unprocessable!(message.errors.full_messages) unless message.valid?
69:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/packages_controller.rb
38:    unprocessable!(message.errors.full_messages) unless message.valid?
109:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/processes_controller.rb
46:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/route_mappings_controller.rb
36:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/service_bindings_controller.rb
15:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/service_instances_controller.rb
37:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/spaces_controller.rb
25:    unprocessable!(message.errors.full_messages) unless message.valid?
55:    unprocessable!(message.errors.full_messages) unless message.valid?

app/controllers/v3/tasks_controller.rb
45:    unprocessable!(message.errors.full_messages) unless message.valid?
```

## Steps to Reproduce

1. Run `cf curl /v3/organizations -X POST -d "{}"`
2. Observe the following error (status code is 422):
```
{
   "errors": [
      {
         "detail": "Name can't be blank",
         "title": "CF-UnprocessableEntity",
         "code": 10008
      }
   ]
}
```

## Expected result

```
{
   "errors": [
      {
         "detail": "Name can't be blank",
         "title": "CF-InvalidRequest",
         "code": 10008
      }
   ]
}
```

(Status code would be 400)

## Possible Fix

Change `unprocessable!(message.errors.full_messages) unless message.valid?` to `invalid_request!(message.errors.full_messages) unless message.valid?` (and look for other similar lines of code)

Thanks,
SAPI (Jen and @Samze)

**Comment by anniesing** [comment]
Hi @jenspinney and @Samze,

Thanks for raising this. You have some good points. We'll escalate to @zrob for what he thinks since this sounds like a feature request, and we don't have the context to make this call.

Thanks,
CAPI Community Pair (Annie and @ericpromislow)

**Comment by jenspinney** [comment]
Thanks @anniesing and @ericpromislow! It seems more like a bug than a feature request to me. There are also many places in the v3 API where 400 is being correctly returned. If you ag for "unless message.valid?" in the cloud controller codebase, you'll see a lot of inconsistencies (sometimes 400, sometimes 422).

**Comment by zrob** [comment]
The expected error codes when dealing with 400/422 across v3 are:

1. the message fails to be parseable (it isn't json), then return 400
1. the message is paresable (it is json), but we won't accept it b/c it lacks required information or it would result in failing business rules (exceed quota), then return 422

Essentially always return a 422 with an actionable error message.  Return a 400 if the request is totally unrecognizable.

How does that line up with what you're seeing across the code base?

**Comment by williammartin** [comment]
Thanks @zrob (also CC @Gerg). This doesn't seem to totally line up with the [Style Guide](https://github.com/cloudfoundry/cc-api-v3-style-guide).

The Style Guide says re: `Bad Request`:

```
This status MUST be returned for requests that provide malformed or invalid data. Examples: malformed request body, unexpected query parameters, or invalid request fields.
```

Specifically the *invalid request* fields would fall under 422 in your description. Does the style guide need updated, or has the world moved on in uhhh.. 18 months. Thanks!

**Comment by Gerg** [comment]
There are some places where we intentionally return 400s on v3: https://github.com/cloudfoundry/cloud_controller_ng/blob/4aad75b928a075bb7c936fa62b8f381f6b302896/app/controllers/v3/application_controller.rb#L5-L11

Not sure if usage of those methods line up with the style guide.
