### ISSUE TITLE
Add audit events for long running provisioning services

### ISSUE THREAD

**Issue by rossdega** [cloudfoundry/cloud_controller_ng#1015]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue
Some services, depending on their complexity, could take several minutes or even hours before their creation completes. There is no track in the audit events that such a long lasting action has been submitted.
Analogously for long lasting service deletions/updates.

## Context

Have the possibility to detect the service creation request in the audit events, similarly to what is done with delete-request events when you try to delete a cf app or a cf space.
When a request for a service instance creation is submitted, the broker is aware of that and it could be issuing a create-request event (analogously for the delete-request/update-request).

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result
extend /v2/events to get the list of events that occur when a service instance is created
(e.g. GET /v2/events?q=type:audit.service.create-request, /v2/events?q=type:audit.service.delete-request, /v2/events?q=type:audit.service.update-request)

## Current result

No API to be able to retrieve these event changes.

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by rossdega** [comment]
@ScarletTanager FYI and help

**Comment by maryamklabib** [comment]
Hi @rossdega,

Just to make sure we're on the same page. You are asking for a feature that creates audit events for the service creation requests as opposed to the audit events for when a service has already been created (https://apidocs.cloudfoundry.org/280/events/list_service_create_events.html).

Is that correct?

Thanks,
CAPI Community Pair (Maryam & @anniesing)

**Comment by rossdega** [comment]
Hi! @maryamklabib the idea is to have some additional events, not to replace the existing ones: there will be situations in which the provisioning of a service could take several minutes. In this case there is no evidence of the action until the service is fully provisioned, while it may be interesting, for auditing, security and debugging purpose to have an event that signals that somebody did a provision request

**Comment by mogul** [comment]
FYI, lack of these events cost the cloud.gov team hours trying to track down the source of an outage.

**Comment by mattmcneeney** [comment]
Hey @maryamklabib @anniesing @zrob Just an FYI that we have moved this into the Service API backlog as we will try to pick this up at some point

**Comment by rossdega** [comment]
I just found another case that could be considered in the same family: app package deletions. 
I found several cases in which the app package deletion starts and then the actual completion is after several seconds. The audit.app.package.delete event is sent when the action has been competed, but for the previous seconds there is no audit event that the deletion process started. 
This is quite an interesting case since in the meanwhile the app is stopped, there is no audit.app.stop event and there is no other event that can help understanding what happened in the meanwhile. 
Please let me know if you'd like to address this case in a separate issue.

**Comment by georgi-lozev** [comment]
Hey @rossdega thanks for opening this issue.

The problem related to service instances/bindings described in the first comment should be addressed with PR https://github.com/cloudfoundry/cloud_controller_ng/pull/1258

I believe it's better to open a separate issue to track the app related events, because they are following different code path and the same fix may not be applicable there.

BR,
Georgi and @nmaslarski on behalf of Services API Team
