### ISSUE TITLE
pending_droplets job never scheduled after failure

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/cloud_controller_ng#1022]
## Issue

If the the `pending_droplets` job on cc-clock failed and `last_started_at` is newer  than `last_completed_at` (for whatever reason the job never completed), the job will never be scheduled again.

## Context

`clock-jobs` on ccdb:

```
ccdb=> select * from clock_jobs;
 id |             name              |      last_started_at       |     last_completed_at
----+-------------------------------+----------------------------+----------------------------
  9 | app_events                    | 2017-09-05 19:00:00.004379 | 2017-09-05 19:00:00.015889
 10 | audit_events                  | 2017-12-03 20:00:00.059988 | 2017-12-03 20:00:00.071643
 11 | failed_jobs                   | 2017-12-03 21:00:00.006871 | 2017-12-03 21:00:00.017957
 13 | service_usage_events          | 2017-12-03 22:00:00.007465 | 2017-12-03 22:00:00.01958
  5 | expired_blob_cleanup          | 2017-12-04 00:00:00.007406 | 2017-12-04 00:00:00.020759
  3 | completed_tasks               | 2017-12-03 23:00:00.006685 | 2017-12-03 23:00:00.019645
  7 | expired_resource_cleanup      | 2017-12-04 00:30:00.00749  | 2017-12-04 00:30:00.01868
 15 | expired_orphaned_blob_cleanup | 2017-12-04 01:00:00.006574 | 2017-12-04 01:00:00.017141
 17 | orphaned_blobs_cleanup        | 2017-12-04 01:30:00.007297 | 2017-12-04 01:30:00.021403
 19 | pollable_job_cleanup          | 2017-12-04 02:00:00.00738  | 2017-12-04 02:00:00.01909
  8 | app_usage_events              | 2017-12-03 18:00:00.065967 | 2017-12-03 18:00:00.080339
  2 | diego_sync                    | 2017-12-04 12:20:55.007017 | 2017-12-04 12:20:46.695927
  1 | pending_droplets              | 2017-11-29 18:14:59.434878 | 2017-11-29 18:14:43.569721
 14 | pending_builds                | 2017-12-04 12:18:25.011871 | 2017-12-04 12:18:25.022132
(14 rows)
```

note the timestamps in row `pending_droplets`. This might also affect other jobs which do not have [explicitly configurable timeouts](https://github.com/cloudfoundry/capi-release/blob/75d74ff53828e02d6742f6d8dbecd55848f97962/jobs/cloud_controller_clock/spec#L71-L77)

## Steps to Reproduce
Manipulate `last_completed_at` to be older than `last_started_at` for `pending_droplets` in table `clock_jobs` after the global timeout of (default) [4 hours](https://github.com/cloudfoundry/capi-release/blob/75d74ff53828e02d6742f6d8dbecd55848f97962/jobs/cloud_controller_clock/spec#L70) the job should be scheduled again, but it's not.

## Expected result

`pending_droplets` should be scheduled even after a run failed to update `last_completed_at`.

## Current result

`pending_droplets` is never scheduled.
`Skipping enqueue for pending_droplets` can be seen in the logs of all cc-clock instances.

## Possible Fix

not sure but it looks like the global timeout should be used in this case.

## Workaround 

we had to manually update `last_completed_at` to be older than `last_started_at` :

```
ccdb=> UPDATE clock_jobs SET last_completed_at = '2017-11-29 18:15:59.434878' where id = 1;
```

after this job scheduling resumed with the expected interval.

**Comment by maryamklabib** [comment]
Hi @achawki,

Thanks for submitting. Pinging @zrob for prioritization.

CAPI Community Pair (Maryam and @anniesing)

**Comment by achawki** [comment]
Seems to be a duplicate of https://github.com/cloudfoundry/capi-release/issues/66
