### ISSUE TITLE
Compromising information in client message

### ISSUE THREAD

**Issue by ashishjain14** [cloudfoundry/cloud_controller_ng#1025]
## Issue
On a failed service creation the error message displays The IP:port and full path of the service

## Context
When trying to create a service instance, without having an entitlement, the message displayed in the client displays information that appears to be a security risk:
The service broker rejected the request to https://IP:9293/cf/v2/service_instances/691f1431-6fcd-4cbd-a3fb-d1510f0e675c?accepts_incomplete=true. Status Code: 403 Forbidden, Body:
{"status":403,"message":"Not entitled to create service instance"}

Currently the error message displays The IP:port and full path of the service. 

## Steps to Reproduce
Create a instance which results in a failed creation
## Expected result
Error message should just say "message":"Not entitled to create service instance" and error code.
## Current result
Currently the error message displays The IP:port and full path of the service. 
## Possible Fix
Remove uri from https://github.com/cloudfoundry/cloud_controller_ng/blob/173954d8ed2d2b9624d074ba2b277f7bd47c8432/lib/services/service_brokers/v2/errors/service_broker_request_rejected.rb#L15

**Comment by anniesing** [comment]
Hi @ashishjain14,

Thanks for submitting this issue. Pinging @zrob as this seems like a product question / feature request.

Annie

**Comment by ashishjain14** [comment]
Can you please provide an update on this?

**Comment by ashishjain14** [comment]
Can we get an update on this ticket, currently as per the Pivotal tracker this has not been scheduled.

**Comment by ashishjain14** [comment]
@anniesing @zrob any update on this ticket, as per the tracker currently this is not scheduled for implementation.

**Comment by Samze** [comment]
Hi @ashishjain14,

Thanks for raising this and sorry for the delayed response. Just to clarify, is your concern that the developer has access to the URL of the Service Broker?

**Comment by ashishjain14** [comment]
Hi @Samze ,
That is correct.
Best regards,
Ashish

**Comment by ashishjain14** [comment]
@Samze  thanks

**Comment by mattmcneeney** [comment]
Since basic auth credentials are required to access the service broker, we don't think that exposing the IP address and port of the service broker is a security concern at this time. Please reopen if you disagree, thanks!
