### ISSUE TITLE
Filter orgs and spaces by guid

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry/cloud_controller_ng#1031]
We (Loggregator) were recently working on a nozzle to detect noisy applications on the platform. As part of this nozzle we wanted to report the top 50 noisiest applications to Datadog. Originally we were tagging our metrics with the application guid, however thought it would be more helpful provide `org-name.space-name.app-name/index` rather than application guid. 

We found this somewhat difficult. The log messages the nozzle receives only have application guid, and in order to get application, space and org names we had to do the following:

- Request applications at `/v3/apps` filtered by `guid`.
- Use the space guids in relationships on the previous response to get `/v2/organizations` filtered by space guid.
- Use the organization guids in the previous response to get `/v3/spaces` filtered by organization guid

It would be nice if the V3 API for `/v3/spaces` and `/v3/organizations` supported `guids` filters like `/v3/apps`.

**Comment by anniesing** [comment]
Hi @bradylove,

Thanks for submitting this issue. Pinging @zrob as this looks like a feature request.

Annie

**Comment by christarazi** [comment]
Closing as this has been done. 

@christarazi && @cwlbraa
