### ISSUE TITLE
Organization ID not part of VCAP_APPLICATION environment variable

### ISSUE THREAD

**Issue by abh1kg** [cloudfoundry/cloud_controller_ng#1043]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

The `VCAP_APPLICATION` env variable contains `space_id` and `space_name` but `organization_id` is missing. It would be helpful to have the organization guid also as part of the environment variable

## Context

`VCAP_APPLICATION` does not publish organization ID

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

Check the environment of a CF application. Check the `VCAP_APPLICATION` environment variable. The `organization_id` is missing

## Current result

`Organization GUID` is missing

## Possible Fix

N/A

**Comment by anniesing** [comment]
Hi @abh1kg,

Thanks for submitting this issue. Pinging @zrob since this looks like a feature request.

Thanks,
Annie

**Comment by jimbasler-pivotal** [comment]
It would be ideal to see the Organization ID and the Organization Name in the VCAP_APPLICATION environment variable just as Space ID and Space Name are.

**Comment by christarazi** [comment]
Closing as this is implemented in https://github.com/cloudfoundry/cloud_controller_ng/commit/0f9ecb75a1081d64f84d1f3607cbf2050d1a38b1.

@christarazi && @cwlbraa
