### ISSUE TITLE
Attempting to repush / restage application with deleted buildpack will fail with "Specified unknown buildpack name"

### ISSUE THREAD

**Issue by pivotal-todd-robbins** [cloudfoundry/cloud_controller_ng#1045]
## Issue

Attempting to repush / restage application with deleted buildpack will fail with `Specified unknown buildpack name`

## Context

This is a customer reported issue. Previously they were using java buildpack 3.18 and wanted to switch applications to using new default java buildpack. After deleting the old buildpack and remove references in manifest, subsequent pushes of applications failed stating unknown buildpack.

## Steps to Reproduce

1. upload a custom buildpack (for instance java buildpack 3.18)
2.  push an application and specify custom buildpack in manifest
3. delete the custom buildpack from system 
4. remove buildpack entry from manifest (so it instead uses default java buildpack) and re-push or re-stage application.
5. app push will fail with "Specified unknown buildpack name" even though neither manifest or `cf buildpacks` reference old buildpack name. (`cf curl /v2/app/<guid>` still shows reference to old buildpack)

## Expected result

Since no buildpack is specified in manifest, then the application push should run buildpack detect and select highest priority java buildpack on system. 

## Current result

Re-pushing the application appears to be checking buildpack field on existing application and failing with "Specified unknown buildpack name" even though neither manifest or cf buildpacks contain entry for this buildpack.

~~~
cf push spring-music

Using manifest file /Users/trobbins/Downloads/spring-music-master/manifest.yml

Updating app spring-music in org punal / space punal as admin...
FAILED
Server error, status code: 400, error code: 100001, message: The app is invalid: buildpack java-buildpack-18 is not valid public url or a known buildpack name
~~~

**Comment by zrob** [comment]
Hey Todd,

This is an issue regarding how the cli applies manifest changes.  The app manifest is non-declarative, it is instead only additive.  This means when you remove things from the manifest, they will not be removed from the system.  I'm not sure if there is a way to "clear" the buildpack from the manifest.

Summoning some CLI folks to weigh in
@dkoper @jbpivotal

**Comment by dkoper** [comment]
`  buildpack: default` should do it.

**Comment by zrob** [comment]
Closing as this appears to be answered.  Please feel free to open a new issue if needed.
