### ISSUE TITLE
HTTP health check call timeout hardcoded to one second

### ISSUE THREAD

**Issue by schulzh** [cloudfoundry/cloud_controller_ng#1055]
This is a follow up of https://github.com/cloudfoundry/healthcheck/issues/5

## Issue
It is not possible to configure the timeout for HTTP health calls; it is hard coded to one second.
When the application takes longer than 1 second to respond to http calls, it is immediately marked as unhealthy and restarted by CF.

## Context
In many applications the HTTP health endpoint does more than just return 200, e.g. the spring actuator health endpoint tries to open a database connection (if one is configured). Under load, this easily takes longer than one second to succeed, and thus the application instance is restarted, even though it is perfectly healthy.

## Steps to Reproduce
Create an application which takes longer than one second to respond for the http health endpoint. It will never succeed to start up.

## Expected result
It should be possible to configure the HTTP health check connection timeout via the manifest and/or a push parameter.

**Comment by zrob** [comment]
Possible dupe #970

**Comment by zrob** [comment]
Implemented in this [story](https://www.pivotaltracker.com/story/show/156819169).  Available in capi-release [1.54.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.54.0)

Docs [here](http://v3-apidocs.cloudfoundry.org/version/3.43.0/index.html#the-health_check-object)

**Comment by keyurpd** [comment]
How to specify this within the deployment manifest.yml file?
