### ISSUE TITLE
Obtain Application Checksum from either CC or Diego

### ISSUE THREAD

**Issue by gowriln** [cloudfoundry/cloud_controller_ng#1056]
## I need to obtain checksum calculated against an application from CC 

 In reference to the post https://github.com/cloudfoundry/cloud_controller_ng/issues/943 , answer suggested by @ljfranklin , Is there a way to get the checksum value calculated for an application using CF API ? 

Currently, my requirement is that I need to push CF application to one environment and get checksum value for pushed app and push the same application to another CF environment after some operations. I need to ensure that the application is not modified or changed in between for which I am planning to use checksum .

The V3 API documents mentions concept of packages and a API to get package information (http://v3-apidocs.cloudfoundry.org/version/3.20.0/#get-a-package )  , this provides checksum in the response .
Sample Response - 
![image](https://user-images.githubusercontent.com/11055630/34823222-a33b7676-f6ef-11e7-9f23-191ada93105d.png)

 Can this be used as application checksum ? (Since package refers to source code of application )

Any suggestions ?

**Comment by gowriln** [comment]
I tried few scenarios by pushing sample apps . 

- App deployed after update in source code of  existing app creates a new package and a new checksum 
- Same app , deployed twice with different app names  results in different checksums . 
- App deployed after updating name ( but same source code) results in new app with new package and checksum 

With reference to above,How does CF calculate checksum of package ? If it is calculated on source code bits then why do I get new checksum on every push ? 

Can anyone point me towards any documentation  regarding this ?

**Comment by christarazi** [comment]
We think that two packages that with the same exact file contents, should have the same hash. You should be able to download the package and run some hash function, which should match what is returned in the API.

@ssisil @ankitjain1988

**Comment by selzoc** [comment]
Closing this as it has been inactive for a while, and there was a workaround proposed above.  Please feel free to reopen if you feel differently.
