### ISSUE TITLE
SpaceDeletionFailed error can be thrown after a space is destroyed

### ISSUE THREAD

**Issue by deniseyu** [cloudfoundry/cloud_controller_ng#1070]
## Issue

We noticed that in `app/actions/space_delete`, the space deletion can fail if there are errors as a result of unbinding apps, but it would not fail if there are errors when deleting service brokers or deleting roles. This determination of what is and isn't show-stopping makes sense, since failed unbinds could leave lots of unretrievable references in the ccdb, but brokers and roles are top-level and could theoretically be manually cleaned by the cf admin afterward.

The error-handling for role deletion occurs after `space.destroy` is called, which means that the `SpaceDeletionFailed` API error can potentially be displayed to the user even if the space deletion was successful.

Here is the code block in question: https://github.com/cloudfoundry-incubator/cloud_controller_ng_sapi/blob/master/app/actions/space_delete.rb#L25-L34

## Expected result

If role deletion failures should be show-stopping for a space deletion, we'd expect that role deletion errors are part of the check before `space.destroy` is called.

If role deletion failures should NOT be show-stopping, then we'd expect a different API error to be thrown, such as `SpaceRolesDeletionFailed`.

cc @Gerg @zrob @iredelmeier

**Comment by charleshansen** [comment]
The code block in question deletes perm roles, which are no longer enabled in capi, so can't fail anymore. We should probably just remove it at this point, but it is part of a larger question about what to do with the old perm code.

@deniseyu have you seen this issue at all recently without perm enabled?
