### ISSUE TITLE
Unable to get app stats with a read-only user

### ISSUE THREAD

**Issue by Rylon** [cloudfoundry/cloud_controller_ng#1076]
## Issue

When authenticated to CF with a read only user, you can not retrieve app statistics, instead you get a "503 Service Unavailable" error.

## Steps to Reproduce

1. Create a UAA user, which only belongs to the `cloud_controller.admin_read_only` group and no others.

2. Login to the CF CLI.

3. Try to retrieve app stats for a running app: `cf app $app_name`

## Expected result

You should see the app and it's instances along with their state.

## Current result

You receive the following error instead:

```
Unexpected Response
Response code: 503
CC code:       200002
CC error code: CF-StatsUnavailable
Request ID:    6ee8496f-03b8-4d11-46ef-2ebda10f5d92
Request ID:    cc95ab6a-cea8-4378-49d7-c36eed3f6edb::02189ff0-3e14-484f-ae3b-05e3b4506f0d
Description:   Stats unavailable: Stats server temporarily unavailable.
```

If we run again with trace mode (`CF_TRACE=true cf app $app_name`) we can see that the API call which fails is `/v2/apps/<app guid>/stats`:

```
RESPONSE: [2018-01-30T16:43:52Z]
HTTP/1.1 503 Service Unavailable
Content-Length: 137
Content-Type: application/json;charset=utf-8
Date: Tue, 30 Jan 2018 16:43:52 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: aee9a2a6-5ba0-4c6c-76f3-a019fb21498d
X-Vcap-Request-Id: 097445d5-f230-44c2-51c8-3d9879eacc29::2eec13c2-6701-487d-abe5-5e103cdbc734
{
  "code": 200002,
  "description": "Stats unavailable: Stats server temporarily unavailable.",
  "error_code": "CF-StatsUnavailable"
}
```

The other API calls appear to be successful.

To rule out an issue with the stats server itself, I tried the same request with a full admin user, and it worked as expected.

Am I missing a permission here, or is there an issue with the `cloud_controller.admin_read_only` scope?

Thanks for your help!

**Comment by zrob** [comment]
@Rylon 

Thanks for submitting this issue.  It was actually resolved in the latest [capi release](https://github.com/cloudfoundry/capi-release/releases/tag/1.48.0).  You can see it as the last story referenced in the cloud controller notes.

**Comment by Rylon** [comment]
Thanks @zrob !
