### ISSUE TITLE
CF API Valid Ops "IN" in filter doesnot work 

### ISSUE THREAD

**Issue by gowriln** [cloudfoundry/cloud_controller_ng#1081]
Hi  Team, 

I am trying to filter API response based on more than one event type . The syntax suggest  using 'q=filter IN a,b,c' , I tried the following -
` cf curl "/v2/events?q=type IN audit.app.update,audit.app.create&&order-by=timestamp&order-direction=desc&page=1&results-per-page=5"`
This results in 400 Bad Request
Is this the correct way to use IN ops ?

**Comment by Gerg** [comment]
Hey @gowriln,

Your request needs to be url encoded. It looks like `cf curl` is not doing this for you. Your curl should look something like this: `cf curl /v2/events?q=type+IN+audit.app.update,audit.app.create`

Thanks,
Greg
