### ISSUE TITLE
CloudFoundry mandates having dashboard_client object even though it is not a mandatory field in OSB API V2.13

### ISSUE THREAD

**Issue by subhankarc** [cloudfoundry/cloud_controller_ng#1086]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Cloud Foundry Service Broker Registration fails if dashboard_client is not specified in the service definition. But according to OSBAPI [v2.13](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#service-objects), it is not mandatory. Does it violate the OSBAPI contract in this case?

## Steps to Reproduce

Try to register a service broker having a service definition without dashboard_client object.

## Expected result

Registration should go through.

## Current result

$ cf update-service-broker service-fabrik-broker broker secret https://10.0.2.2:9293/cf
Updating service broker service-fabrik-broker as admin...
FAILED
Server error, status code: 502, error code: 270012, message: Service broker catalog is invalid:
Service blueprint
  Service dashboard client id is required
  Service dashboard client secret is required
  Service dashboard client redirect_uri is required

**Comment by zrob** [comment]
@mattmcneeney

**Comment by mattmcneeney** [comment]
Hi @subhankarc 
I can't seem to reproduce this issue. Please could you add the response to the `/v2/catalog` endpoint in this issue?
Thanks

**Comment by subhankarc** [comment]
The registration works successfully when the catalog response is like this.
```

{
  "services": [
    {
      "id": "24731fb8-7b84-4f57-914f-c3d55d793dd4",
      "name": "blueprint",
      "description": "Blueprint service for internal development, testing, and documentation purposes of the Service Fabrik",
      "bindable": true,
      "subnet": null,
      "tags": [
        "blueprint",
        "no-not-use"
      ],
      "metadata": {
        "displayName": "Blueprint",
        "longDescription": "Blueprint service for internal development, testing, and documentation purposes of the Service Fabrik",
        "providerDisplayName": "SAP SE",
        "documentationUrl": "https://sap.com/",
        "supportUrl": "https://sap.com/"
      },
      "requires": [],
      "plan_updateable": true,
      "dashboard_client": {
        "id": "abcd",
        "secret": "abcd",
        "redirect_uri": "https://service-fabrik-broker.bosh-lite.com/manage/auth/cf/callback"
      },
      "plans": [
        {
          "id": "bc158c9a-7934-401e-94ab-057082a5073f",
          "name": "v10-xsmall",
          "description": "Blueprint 1.0 service x-small (managed service in beta)",
          "metadata": {
            "costs": [
              {
                "amount": {
                  "usd": 0
                },
                "unit": "MONTHLY"
              }
            ],
            "bullets": [
              "Dedicated Deployment",
              "1 VM",
              "1 vCPUs",
              "1 GB Memory",
              "1 GB Disk"
            ],
            "supported_features": [
              "state",
              "lifecycle",
              "credentials"
            ]
          },
          "free": false
        }
      ]
    }
  ]
}
```

The request fails when it has the following format.

```
{
  "services": [
    {
      "id": "24731fb8-7b84-4f57-914f-c3d55d793dd4",
      "name": "blueprint",
      "description": "Blueprint service for internal development, testing, and documentation purposes of the Service Fabrik",
      "bindable": true,
      "subnet": null,
      "tags": [
        "blueprint",
        "no-not-use"
      ],
      "metadata": {
        "displayName": "Blueprint",
        "longDescription": "Blueprint service for internal development, testing, and documentation purposes of the Service Fabrik",
        "providerDisplayName": "SAP SE",
        "documentationUrl": "https://sap.com/",
        "supportUrl": "https://sap.com/"
      },
      "requires": [],
      "plan_updateable": true,
      "dashboard_client": {},
      "plans": [
        {
          "id": "bc158c9a-7934-401e-94ab-057082a5073f",
          "name": "v10-xsmall",
          "description": "Blueprint 1.0 service x-small (managed service in beta)",
          "metadata": {
            "costs": [
              {
                "amount": {
                  "usd": 0
                },
                "unit": "MONTHLY"
              }
            ],
            "bullets": [
              "Dedicated Deployment",
              "1 VM",
              "1 vCPUs",
              "1 GB Memory",
              "1 GB Disk"
            ],
            "supported_features": [
              "state",
              "lifecycle",
              "credentials"
            ]
          },
          "free": false
        }
      ]
    }
  ]
}
```

So, basically, if the dashboard_client is empty, it complains. However, it works when it is not present. Is this desired behaviour?

**Comment by mattmcneeney** [comment]
@subhankarc Thanks, that makes sense. When the field is present, Cloud Controller checks for the required fields `id`, `secret` and `redirect_uri`. Do you have a use case for which this is causing a problem or are you able to omit the field from the catalog?

**Comment by subhankarc** [comment]
@mattmcneeney It's not a blocker as such, I can omit it completely. Just that I was trying the same with Kubernetes service-catalog with an empty dashboard_client which doesn't seem to crib about it. But I guess they also do not have the whole Auth flow in place.

**Comment by subhankarc** [comment]
@mattmcneeney Sure!
