### ISSUE TITLE
The following CAPI is not giving any response: /v2/apps/<app-guid>/events

### ISSUE THREAD

**Issue by SnehaKumari22** [cloudfoundry/cloud_controller_ng#1090]
/v2/apps/<app-id>/events

**Comment by infews** [comment]
Hi @SnehaKumari22 ,

The way to get all audit events for an app is to query using the <app-guid> as the `actee` in the [list events endpoint](http://apidocs.cloudfoundry.org/4.3.0/events/list_events_associated_with_an_app_since_january_1,_2014.html)

Thanks,
@selzoc  && Davis
