### ISSUE TITLE
CC performs orphan mitigation inconsistently 

### ISSUE THREAD

**Issue by georgi-lozev** [cloudfoundry/cloud_controller_ng#1091]
## Issue
According to the [spec](https://github.com/mattmcneeney/servicebroker/blob/765df3a40cb88f5b2f2c6968171d829a0797c69f/spec.md#orphans) CC should not perform orphan mitigation if the broker responds with 200 and malformed response body. 

## Context

For more context have a look at [#154966738](https://www.pivotaltracker.com/n/projects/2105761/stories/154966738)

**Comment by zrob** [comment]
@mattmcneeney thoughts?

**Comment by mattmcneeney** [comment]
@zrob This looks like a legitimate bug from our investigation. We wanted to track this here so that the community had visibility into it as we may not get around to resolving this for a while.

**Comment by gberche-orange** [comment]
thanks @matthewmcnew for providing visibility into this inconsistency to the community. The  [Orphan mitigation google doc](https://docs.google.com/document/d/11iXxAciCIQpCvrnzmGoEqQIbIVxpn6VDYlm_SVuq9TU/edit) from this SAPI [tracker story](https://www.pivotaltracker.com/story/show/154966738) seems to also be useful to the community as it provides a broader status on current orphan migitation status in CF.

**Comment by kamath-prasad** [comment]
[We](https://github.com/cloudfoundry-incubator/service-fabrik-broker) have observed an issue recently where in , if the cloud controller fails to save certain information on creation of a service instance, it immediately fires a delete of the same instance which results in the CF service instance getting deleted and orphaned resources on the IAAS.

Please see the logs below : 

Broker logs : 

```
<134>2018-11-28T14:21:31+00:00 10.10.10.10 service-fabrik-broker [job=broker index=0]  [service-fabrik-broker] INFO  10.0.129.65 - broker [28/Nov/2018:14:21:31 +0000] "PUT /cf/v2/service_instances/267db7f5-5a55-484f-a84a-e37918d430ef?accepts_incomplete=true HTTP/1.1" 202 - "-" "HTTPClient/1.0 (2.8.3, ruby 2.4.2 (2017-09-14))"


 [service-fabrik-broker] INFO  11.11.11.11 - broker [28/Nov/2018:14:21:31 +0000] "DELETE /cf/v2/service_instances/267db7f5-5a55-484f-a84a-e37918d430ef?plan_id=7b956081-ebc8-45a2-b13f-def2f85be73a&service_id=6db542eb-8187-4afc-8a85-e08b4a3cc24e HTTP/1.1" 422 - "-" "HTTPClient/1.0 (2.8.3, ruby 2.4.2 (2017-09-14))"
```

CC Logs : 

```
<14>1 2018-11-28T14:21:31.747379Z 11.11.11.11 cloud_controller_ng rs2 - [instance@47450 director="bosh-hcp-live-us10" deployment="cf" group="api" az="z2" id="51c02c83-7a38-4cdc-9ef3-e7719359505e"] {"timestamp":1543414891.6485012,"message":"Failed to save while creating service instance 267db7f5-5a55-484f-a84a-e37918d430ef with exception: name unique.","log_level":"error","source":"cc.api","data":{"request_guid":"7a85bf01-ca4b-452c-499f-03e3e1a016be::c7266891-7d2a-4b48-bb33-3a7be6422af4"},"thread_id":47421286570660,"fiber_id":47421306260280,"process_id":1,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/actions/services/service_instance_create.rb","lineno":54,"method":"mitigate_orphan"}

<14>1 2018-11-28T14:21:31.747388Z 11.11.11.11 cloud_controller_ng rs2 - [instance@47450 director="bosh-hcp-live-us10" deployment="cf" group="api" az="z2" id="51c02c83-7a38-4cdc-9ef3-e7719359505e"] {"timestamp":1543414891.64867,"message":"Attempting synchronous orphan mitigation for service instance 267db7f5-5a55-484f-a84a-e37918d430ef","log_level":"info","source":"cc.api","data":{"request_guid":"7a85bf01-ca4b-452c-499f-03e3e1a016be::c7266891-7d2a-4b48-bb33-3a7be6422af4"},"thread_id":47421286570660,"fiber_id":47421306260280,"process_id":1,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/actions/services/synchronous_orphan_mitigate.rb","lineno":8,"method":"attempt_deprovision_instance"}


<14>1 2018-11-28T14:21:31.747389Z 11.11.11.11 cloud_controller_ng rs2 - [instance@47450 director="bosh-hcp-live-us10" deployment="cf" group="api" az="z2" id="51c02c83-7a38-4cdc-9ef3-e7719359505e"] {"timestamp":1543414891.66116,"message":"Unable to deprovision orphaned service instance 267db7f5-5a55-484f-a84a-e37918d430ef: Service instance postgresql-provisioning-request: This service plan requires client support for asynchronous service operations.","log_level":"error","source":"cc.api","data":{"request_guid":"7a85bf01-ca4b-452c-499f-03e3e1a016be::c7266891-7d2a-4b48-bb33-3a7be6422af4"},"thread_id":47421286570660,"fiber_id":47421306260280,"process_id":1,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/actions/services/synchronous_orphan_mitigate.rb","lineno":12,"method":"rescue in attempt_deprovision_instance"}
```

Can this issue also be fixed ?

**Comment by mattmcneeney** [comment]
Hey @kamath-prasad 
The Cloud Controller behaviour you described above is intentional; if CF can't save a service instance for whatever reason, then we want to mark the provision as having failed and send a deprovision request to the broker to ensure that an orphan is _not_ created.

I'm not sure I understand how an orphaned resource is being created on the IaaS. Could you help me understand?

**Comment by kamath-prasad** [comment]
cc: @subhankarc @jagadish-kb @amitmalav @ashishjain14

@mattmcneeney : Currently our [broker](https://github.com/cloudfoundry-incubator/service-fabrik-broker) maintains a lock internally for all lifecycle operations initiated via platform which in this case is CF. 

And for create and delete operations our expectation is that these should be mutually exclusive and hence when CF sends a delete request in this case since the create is in progress , we reject the delete. Hence once the create operation succeeds the entity on the IAAS representing the CF service instance ( which in our case is a BOSH deployment) would have been successfully created. However since at CF (platform) once the create fails / delete is fired there would not be corresponding entity which makes the service BOSH deployment an orphan for us.

Ideally we would like to propose OSBAPI to have brokers implement a "mitigate_orphans" API and then the platform can call this in scenario's like these ?

**Comment by subhankarc** [comment]
Just to add on to what @kamath-prasad already said, we do not want to delete a service instance while creation in progress. I know CF does not allow this call to come from user. But what if the other platforms like k8s do not adhere to that. How do we differentiate then if the delete is from platform or user initiated?

**Comment by mattmcneeney** [comment]
I think I understand now. It sounds like:
1. A user initiates a create service call with `cf create-service`
1. CF makes a `PUT /v2/service_instances/:guid` call to the service broker with `?accepts_incomplete=true`
1. The broker returns a `202 Accepted` with the `dashboard_url` and `operation` fields
1. CC fails to save one of those fields, and so returns a `422` to the user and initiates orphan mitigation (sends a `DELETE /v2/service_instances/:guid` request)

If this is the case, then I do think that this behaviour is aligned with the OSBAPI spec, but I can understand why it may be causing your broker a problem by leaving an orphaned instance. Can you check that the `dashboard_url` and `operation` fields conform to the spec?

**Comment by kamath-prasad** [comment]
@mattmcneeney : 

yes , your understanding w.r.t - 1,2,3 is correct. 

However for #4 , currently we see this error in CC when broker responds with 202 back for the PUT .

```
<14>1 2018-11-28T14:21:31.747379Z 11.11.11.11 cloud_controller_ng rs2 - [instance@47450 director="bosh-hcp-live-us10" deployment="cf" group="api" az="z2" id="51c02c83-7a38-4cdc-9ef3-e7719359505e"] {"timestamp":1543414891.6485012,"message":"Failed to save while creating service instance 267db7f5-5a55-484f-a84a-e37918d430ef with exception: name unique.","log_level":"error","source":"cc.api","data":{"request_guid":"7a85bf01-ca4b-452c-499f-03e3e1a016be::c7266891-7d2a-4b48-bb33-3a7be6422af4"},"thread_id":47421286570660,"fiber_id":47421306260280,"process_id":1,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/actions/services/service_instance_create.rb","lineno":54,"method":"mitigate_orphan"}
```
Not sure what the user see when this error is seen in CC - whether it will be "create failed" or "create in progress". I guess you should be able to answer that.

Now post this , CC sends a delete request to broker for orphan mitigation but broker responds with a 422 as broker still thinks the create is in progress and hence results in the orphaned resource.

And yes, dashboard_url & operation conform to the spec.

**Comment by georgi-lozev** [comment]
Hey @kamath-prasad ,

The error seems to be raised from this part of the code.
```ruby
      begin
        service_instance.save_with_new_operation(broker_response[:instance], broker_response[:last_operation])
      rescue => e
        cleanup_instance_without_db(e, service_instance)
      end

```

CC fails to save/insert either the service instance or the last operation associated with it in the DB. The exception message is ` name unique.`, which doesn't sound very descriptive. This kind of error happen if there is something wrong with your database and it's unable to do insert/update operations.

Are there any other error logs near that timestamp?
Are you able to reproduce this issue in a sustainable way?
I presume you're using a Postgres as a CCDB?

BR,
Georgi

**Comment by amitmalav** [comment]
Hi @georgi-lozev 
These are the only logs that I could find with `log_level=error` just around the incident.
```
<14>1 2018-11-28T13:42:35.149693Z 10.0.65.64 cloud_controller_ng rs2 - [instance@47450 director="bosh-hcp-live-us10" deployment="cf" group="api" az="z1" id="0758bb1c-68e8-4ef1-9b6f-8c36533c2183"] {"timestamp":1543412555.0303,"message":"stats_for_app.error","log_level":"error","source":"cc.diego.instances_reporter","data":{"request_guid":"ae3ae862-375a-4c0e-4c33-16942629d94d::98a36527-85b0-42e8-a274-8e499106b256","error":"failed with status: 401, body: "},"thread_id":46936161777600,"fiber_id":46936178583900,"process_id":1,"file":"/var/vcap/data/packages/cloud_controller_ng/506b92cab6354a779814ac4f419a5854ee0790fa/cloud_controller_ng/lib/cloud_controller/diego/reporters/instances_stats_reporter.rb","lineno":67,"method":"rescue in stats_for_app"}

<14>1 2018-11-28T14:13:56.293755Z 10.0.65.66 cloud_controller_ng rs2 - [instance@47450 director="bosh-hcp-live-us10" deployment="cf" group="api" az="z1" id="520d5ee3-5742-4cdc-80d7-a3a31cf20a7b"] {"timestamp":1543414435.8968978,"message":"diego.staging.completion-controller.staging-failed","log_level":"error","source":"cc.api","data":{"request_guid":"dfa118a4-c871-41cb-81b6-0410fc7b6110","task_guid":"57c110b6-81c2-4725-be4c-86f429bf9f79","failed":true,"failure_reason":"STG: Exited with status 222","result":"","created_at":1543414428270168566},"thread_id":47186385884180,"fiber_id":47186386954400,"process_id":1,"file":"/var/vcap/data/packages/cloud_controller_ng/506b92cab6354a779814ac4f419a5854ee0790fa/cloud_controller_ng/app/controllers/internal/staging_completion_controller.rb","lineno":89,"method":"parse_bbs_task_callback"}

<14>1 2018-11-28T14:17:25.90654Z 10.0.65.64 cloud_controller_ng rs2 - [instance@47450 director="bosh-hcp-live-us10" deployment="cf" group="api" az="z1" id="0758bb1c-68e8-4ef1-9b6f-8c36533c2183"] {"timestamp":1543414645.304577,"message":"diego.staging.completion-controller.staging-failed","log_level":"error","source":"cc.api","data":{"request_guid":"715c585d-0171-4ef2-94d1-846ecc27142b","task_guid":"17d7f74d-7b41-4ace-b771-0c057da570e3","failed":true,"failure_reason":"STG: Exited with status 222","result":"","created_at":1543414642543701026},"thread_id":46936179965200,"fiber_id":69844765932920,"process_id":1,"file":"/var/vcap/data/packages/cloud_controller_ng/506b92cab6354a779814ac4f419a5854ee0790fa/cloud_controller_ng/app/controllers/internal/staging_completion_controller.rb","lineno":89,"method":"parse_bbs_task_callback"}

<14>1 2018-11-28T14:21:31.747379Z 10.0.129.65 cloud_controller_ng rs2 - [instance@47450 director="bosh-hcp-live-us10" deployment="cf" group="api" az="z2" id="51c02c83-7a38-4cdc-9ef3-e7719359505e"] {"timestamp":1543414891.6485012,"message":"Failed to save while creating service instance 267db7f5-5a55-484f-a84a-e37918d430ef with exception: name unique.","log_level":"error","source":"cc.api","data":{"request_guid":"7a85bf01-ca4b-452c-499f-03e3e1a016be::c7266891-7d2a-4b48-bb33-3a7be6422af4"},"thread_id":47421286570660,"fiber_id":47421306260280,"process_id":1,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/actions/services/service_instance_create.rb","lineno":54,"method":"mitigate_orphan"}

<14>1 2018-11-28T14:21:31.747389Z 10.0.129.65 cloud_controller_ng rs2 - [instance@47450 director="bosh-hcp-live-us10" deployment="cf" group="api" az="z2" id="51c02c83-7a38-4cdc-9ef3-e7719359505e"] {"timestamp":1543414891.66116,"message":"Unable to deprovision orphaned service instance 267db7f5-5a55-484f-a84a-e37918d430ef: Service instance postgresql-provisioning-request: This service plan requires client support for asynchronous service operations.","log_level":"error","source":"cc.api","data":{"request_guid":"7a85bf01-ca4b-452c-499f-03e3e1a016be::c7266891-7d2a-4b48-bb33-3a7be6422af4"},"thread_id":47421286570660,"fiber_id":47421306260280,"process_id":1,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/actions/services/synchronous_orphan_mitigate.rb","lineno":12,"method":"rescue in attempt_deprovision_instance"}
```

I'm seeing similar (`STG: Exited with status 222"`) errors since long before this issue, I'm not really sure if this has something to do with the failure.
Yes, Postgres is being used as CCDB.

**Comment by georgi-lozev** [comment]
Hello @amitmalav ,
Thank you for the logs.
It doesn't look like those logs are somehow related

**Comment by kamath-prasad** [comment]
@georgi-lozev : So far no ... We observed this in one of our productive landscapes.

**Comment by georgi-lozev** [comment]
After looking into the code and the logs you've provided it seems that the problem is a pretty edge case for CC to deal with. 

The situation is the following:
1. CC sends a `PUT` with `accepts_incomplete=true` to initiate the provision. 
1. The broker responds with `202` accepted and some body.
1. CC tries to save the service instance and last operation(f.e. state "in progress") associated with that service instance in its database(DB). 
1. The DB fails the insert the state of the instance, due to an exception. From the logs you've provided the message seems to be not very clear `name unique.` There is no unique constrain on the `name` field of the `service_instances` table, so it's kind of very strange and misleading error message.
1. At this point in time CC thinks its DB is down/broken.
1. CC tries to at least inform the broker that there is something wrong with this instance and it could not create it as normal, so it sends a deprovision request with `accepts_incomplete=false`. The flag is `false`, because CC also relies on the DB to be able to schedule a background job to eventually fetch the state for the instance.
1. The broker rejects the synchronous deprovision, because it's not supported which is a valid behaviour from its side

Those circumstances are quite exceptional and currently there is not a good way to deal with them in CC. It does its best in order to inform the broker something pretty bad has happened on its end.

Have you seen a general instability or failing operations from the database that is backing this particular cf-deployment?
For example some infrastructure problems or network issues which might cause a failing DB operation?

CC could do something in order to mitigate this, f.e. retry logic or some kind of resilience, but it's a part of a more broader initiative and I don't think it's related to the initial idea of this issue.

In case you face this issue again and you'd like to troubleshoot it further I'll be happy to assist, so just contact me.

BR,
Georgi

**Comment by kamath-prasad** [comment]
> Have you seen a general instability or failing operations from the database that is backing this particular cf-deployment?
For example some infrastructure problems or network issues which might cause a failing DB operation?

@stephanme : can you please provide more inputs here ?

> CC could do something in order to mitigate this, f.e. retry logic or some kind of resilience, but it's a part of a more broader initiative and I don't think it's related to the initial idea of this issue.

@georgi-lozev  : should I create a new GitHub issue then for this bug ?

**Comment by ablease** [comment]
Hey @kamath-prasad. Given that the issue you are seeing is similar but not strictly related to this original issue, I would suggest opening a new GitHub issue to track your bug. 

Thanks. 
Alex
