### ISSUE TITLE
Push fails because of random route length

### ISSUE THREAD

**Issue by elgohr** [cloudfoundry/cloud_controller_ng#1098]
## Issue

In https://github.com/cloudfoundry/cloud_controller_ng/issues/581 a limited length of the app-name was introduced.
Our app-name has 43 characters. The app uses the random-route feature.
In this way the route _can_ become longer than the limit of 63 characters.

This results in 
`Server error, status code: 400, error code: 210001, message: The route is invalid: host must be no more than 63 characters`

## Steps to Reproduce

Push an app with >40 character app-name and use random-route.
Sometimes this will result in the described behavior.

## Expected result

CF push must be reproducible.

## Current result

They're not.

## Possible Fix

a) Use shorter suffix names in case of longer app-names.
b) Define a max-length for app-names, so they don't conflict with random-routes. (Didn't see documentation which defines the max-length of the suffix).

**Comment by zrob** [comment]
@elgohr The cli is the bit that generates random routes for an app. Please raise this issue on the cli repo https://github.com/cloudfoundry/cli.

**Comment by elgohr** [comment]
New issue at https://github.com/cloudfoundry/cli/issues/1331
