### ISSUE TITLE
Incorrect disk usage reporting with Docker images

### ISSUE THREAD

**Issue by alext** [cloudfoundry/cloud_controller_ng#1106]
## Issue

We're seeing the disk usage for application instances being incorrectly reported when deploying using a Docker image.

## Context

We have an application using a Docker image that's around 600M when uncompressed. the `cf app` output for this application when running indicates that there's a lot more disk space available than there actually is. This has led to applications running out of disk space within the container when the metrics indicate that there's still plenty of space available.

These incorrect numbers are also reported via the firehose metrics.

## Steps to Reproduce

Push an app using a docker image, and observe the reported disk usage:

```
cf push docker-test --docker-image ubuntu:16.04 -k 200M --no-route --health-check-type none -c 'while true; do sleep 10; done'
cf app docker-test
```
ssh into the app container and view the actual disk used and available:
```
cf ssh docker-test
df -h
```

## Expected result

I would expect `cf app` disk usage output to include the base container usage so that it accurately reflects the amount of space available.

## Current result

`cf app` output:
```
name:              docker-test
requested state:   started
instances:         1/1
usage:             1G x 1 instances
routes:            
last uploaded:     Tue 06 Mar 15:40:45 GMT 2018
stack:             cflinuxfs2
docker image:      ubuntu:16.04

     state     since                  cpu    memory       disk         details
#0   running   2018-03-06T15:41:58Z   0.0%   1.7M of 1G   8K of 200M   
```

Actual disk availability within the container:
```
root@c54a5b98-04a3-485c-44b9-9f3c:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          94M  8.0K   94M   1% /
tmpfs            15G     0   15G   0% /dev/shm
/dev/xvdb2      168G   24G  135G  16% /tmp/garden-init
tmpfs            15G     0   15G   0% /sys/fs/cgroup
udev             15G  4.0K   15G   1% /dev/tty
tmpfs            15G     0   15G   0% /proc/scsi
```

This shows that there is actually only 94M available within the container whereas the cf app output indicates that there's close to 200M available.

**Comment by zrob** [comment]
@emalm @julz do y'all have any thoughts on what's happening here?

**Comment by emalm** [comment]
@zrob As far as I can tell from https://github.com/cloudfoundry/executor/blob/cad64dd4aa984348819405360c0e5945cf47031d/containermetrics/stats_reporter.go#L159-L161, the Diego cell is relaying the disk metrics it gets from Garden directly into the Loggregator container-metrics message, so at first glance this seems like an issue with how Garden is calculating the disk usage for the Docker-image-based container. It does seem to be doing the correct enforcement for the [`DiskLimitScopeTotal`](https://godoc.org/code.cloudfoundry.org/garden#DiskLimitScope) disk-accounting mode, in terms of ensuring that the total disk usage of the rootfs layers and the per-instance files does not exceed the desired disk limit, but maybe it needs to add the base-layer usage back into the usage metric it reports.

**Comment by emalm** [comment]
also /cc @teddyking

**Comment by teddyking** [comment]
It looks to me like the CF CLI is printing the `ExclusiveBytesUsed` metric rather than the `TotalBytesUsed`, which is why the size of the base image has not been taken into account.

Poking around the executor code I can see that that's what we're grabbing [here](https://github.com/cloudfoundry/executor/blob/cad64dd4aa984348819405360c0e5945cf47031d/depot/containerstore/containerstore.go#L331) and then reporting [here](https://github.com/cloudfoundry/executor/blob/cad64dd4aa984348819405360c0e5945cf47031d/depot/metrics/reporter.go#L150-L153).

The Exclusive metric makes sense when pushing buildpack-based app, but perhaps we want to report the Total metric for docker-based apps instead? I can see why the metric currently being reported when using a docker-based app isn't really all that useful.

**Comment by emalm** [comment]
Thanks, @teddyking ! I hadn't realized there were two separate disk stats available. Added https://www.pivotaltracker.com/story/show/156310667 to the Diego tracker for the cell rep to report the Total one for Docker-image-based containers.

**Comment by infews** [comment]
Looks like this was handled in https://www.pivotaltracker.com/story/show/156310667, closing

@selzoc && Davis
