### ISSUE TITLE
Filter apps by state

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cloud_controller_ng#1109]
## Issue

Both v2 and v3 API currently don't support filtering by application state

https://apidocs.cloudfoundry.org/280/apps/list_all_apps.html
http://v3-apidocs.cloudfoundry.org/version/3.39.0/index.html#list-apps

## Context

As an operator, the ability to filter for STARTED applications would useful for us to avoid fetching thousands of STOPPED apps when performing platform-wide checks/operations.

## Steps to Reproduce

- Attempt to request a list of started apps using `cf curl`
- Notice that, according to the docs, there is no way to do it

## Expected result

`cf curl /v2/apps?q=state:STARTED`

should return the JSON response containing only STARTED apps

## Current result

The command above returns an error. The only workaround is to list all apps regardless of state and then filter.

**Comment by christarazi** [comment]
This seems like something we should do as it seems pretty straightforward and high value. @ankitjain1988 @ssisil 

@christarazi && @cwlbraa

**Comment by Gerg** [comment]
This was implemented in https://github.com/cloudfoundry/cloud_controller_ng/commit/226d9c117f5e69b1334c736a1aa58197127b211a and will be included in the next capi release.
