### ISSUE TITLE
Undocumented query parameter for 'GET /v2/organizations/:guid/user_roles'

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#1119]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

The query parameter `q=userguid:GUID` isn't documented (or tested).

## Context

See https://apidocs.cloudfoundry.org/280/organizations/retrieving_the_roles_of_all_users_in_the_organization.html -- no query parameter is documented, but there's something in the code.

Additionally, the code ignores the `X` part in `q=X:GUID`

**Comment by ericpromislow** [comment]
Pushed some unit tests to branch `issue-1119-undoc-userguid`

**Comment by zrob** [comment]
resolved by PR #1120
