### ISSUE TITLE
Unable to update service broker with new service GUID and same service name

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/cloud_controller_ng#1138]
## Issue

We are trying to change the GUID of our service broker's service. We'd like to keep the same service name. When we try to run `update-service-broker` and give it the new broker, we get the error `Service broker catalog is invalid: Service name must be unique"`.

## Context

The V1 of our broker had the name "credhub-service-broker" and this service catalog:

```
{
   "services":[
      {
         "name":"credhub",
         "id":"credhub",
         "plans":[
            {
               "name":"credhub",
               "id":"credhub"
            }
         ]
      }
   ]
}
```

The new version was intended to fix this oversight of not using GUIDs for our IDs:

```
{
   "services":[
      {
         "name":"credhub",
         "id":"ED8DA381-3997-451B-9419-07CF2033AC18",
         "plans":[
            {
               "name":"credhub",
               "id":"548CD622-51F6-4326-AB1E-79BC683F15E9"
            }
         ]
      }
   ]
}
```

When we try to run `cf update-service broker ...` and give it the URL for the V2 broker, it errors, complaining that the name of the service is not unique. We have no service instances created.

## Steps to Reproduce

- Create a broker with the V1 service catalog, register it, create a broker with the V2 service catalog, try to update the broker to point to V2.

## Expected result

The broker successfully updates.

**Comment by georgi-lozev** [comment]
The service name must be unique for all services within a platform's marketplace. 
So, effectively by changing only the `id` and keeping  the same name makes CC thinking that we add a brand new service with exactly the same name, which results in the error above.

You could solve this in a number of ways. Here are a couple I could come up with.

1. Merge V1 and V2 in a new catalog V3 where you rename the old service name to something like `deprecated-credhub`. Update the broker which now contains two services, one with name `credhub` and valid guid `id` and another with name `deprecated-credhub` with dummy guid. Ensure all service instances are gone and remove the deprecated service metadata from the catalog in a subsequent update. Basically two step update.

2. Delete the broker and recreate it with the new catalog where it contains only V2 of the catalog.

**Comment by Samze** [comment]
I believe this behaviour is the result of the ordering of `update-service-broker`.

CC uses the ID of services and plans as the unique identifier. At the moment CC will do the following in this order:

1. Create or update services references that exist in the newly fetched catalog.
1. For services that no longer exist in the newly fetched catalog
   1. If service instances exist, mark that service as deactivated.
   1. If no service instances exist then delete the service.

In your scenario, we are failing at the first check. This is despite the fact that the old reference would have been deleted later on. We could potentially reorder this to delete things first which would enable your workflow.

However, this will not work if service instances exist and I don't think we should support doing this switch when they do.

cc @mattmcneeney
