### ISSUE TITLE
/v2/resource_match on Azure takes 90s

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/cloud_controller_ng#1140]
## Issue

Updated `azure-storage` gem leads to long response times (i.e. 90s).

## Context

- cf-deployment v1.29.0
- capi release v1.54.0

## Steps to Reproduce

Calling the resource match API with an unknown sha1 with a size in the range between minimum and maximum resource sizes as defined in the [cc spec file](https://github.com/cloudfoundry/capi-release/blob/ddc02167ac84585988411fe9e613357be2a15941/jobs/cloud_controller_ng/spec#L329-L334) takes 90 seconds. This can be reproduced with the following command:

```
SHA1=$(dd if=/dev/urandom bs=100 count=1 2>&1 | sha1sum | tail -1 | awk '{print $1}'); CF_TRACE=true cf curl -v /v2/resource_match -X PUT -d "[{\"sha1\":\"$SHA1\",\"size\":65537}]"
```

## Expected result

On other infrastructures (and before updating to cf-deployment v1.29.0) the query is processed within seconds.

## Current result

Call to the api takes 90s. It is not possible to push apps with many files within the resource size range since the timeout of the gorouter is reached.

## Cause

Update to `azure-storage (0.15.0.preview)` with following commit seems to be the cause: https://github.com/cloudfoundry/cloud_controller_ng/commit/c65f488606172ad274209e935adef8d3d3e4fff1

We've manually downgraded to `azure-storage (0.14.0.preview)` and the issue did not occur anymore.

**Comment by zrob** [comment]
@philippthun 

We are tracking this here https://www.pivotaltracker.com/story/show/157577866

Should be in the next capi-release
