### ISSUE TITLE
The error occurs when  API /v2/apps/:guid/stats is called at the simulataneous.

### ISSUE THREAD

**Issue by NAGAI-Tsuyoshi** [cloudfoundry/cloud_controller_ng#1146]
## Issue

I called API /v2/apps/:guid/stats 20 times at the simulataneous. And, some calls returned CF-StatsUnavailable. 

## Context

I called 20 doppler's API containermetrics 20 times at the simulataneous. And, it returned normally. 
Therefore, I think that there is a cause in traffic_controller/client. 

## Steps to Reproduce

I called it as follows. 
  $ cf curl /v2/apps/6d5ef8cb-ada9-4132-8a28-aefd991eb86d/stats & cf curl /v2/apps/f6f5f5ce-7441-41f2-be01-206d38b6df3b/stats & cf curl /v2/apps/ef4af043-8607-46a1-ba7b-993cf3fd313e/stats & cf curl /v2/apps/a179184f-f2d2-4b36-8a29-c8ae43eaf376/stats & cf curl /v2/apps/68749946-d374-4aea-9364-5f6b69759d16/stats & cf curl /v2/apps/c63d064b-1462-4d30-8dd9-f7aac85a2cfb/stats & cf curl /v2/apps/10428e0e-fe24-4f09-9333-0592297100f9/stats & cf curl /v2/apps/62d0aab3-e18a-4faa-8b00-8df9a6cddb59/stats & cf curl /v2/apps/733130a3-90ed-4ff8-8100-61c3eee04ffd/stats & cf curl /v2/apps/c07af39a-ceac-4285-8fee-d31516405e80/stats & cf curl /v2/apps/9a0682bb-820f-43ba-b7d5-26b5097a9895/stats & cf curl /v2/apps/c38c341f-9255-494d-9f6e-0503ee1d123d/stats & cf curl /v2/apps/98514831-ac24-4ce6-8ed4-ac56db2b6f9b/stats & cf curl /v2/apps/857a9f9f-24a1-4016-a4da-31b4971447c7/stats & cf curl /v2/apps/c67d6340-28ba-47f6-b76d-f5d0d6f63756/stats & cf curl /v2/apps/4afdd26c-5eae-4206-b15f-7fa9b4fadf28/stats & cf curl /v2/apps/3662c02e-b5c5-45ba-8fc8-f9cd66836eb1/stats & \ cf curl /v2/apps/f70758bc-2b7f-4c84-8bf2-703526725448/stats & cf curl /v2/apps/c4788846-0365-4743-91d9-e27158440aa3/stats & \ cf curl /v2/apps/d4e26f85-bf4d-45b2-9c11-0a0863f1c8de/stats &

## Expected result

All calls return app's stats. 

## Current result

Some calls returned CF-StatsUnavailable. 

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by NAGAI-Tsuyoshi** [comment]
I have understood the reason why CF-StatsUnavailable is returned. 

CC API /v2/apps/:guid/stats call TC API containermetrics. And, TC API containermetrics calls CC API /internal/log_access.
20 is set to threadpool_size of thin. Therefore, Therefore,  "/internal/log_access" is not processed. As a result, /v2/apps/:guid/stats does the time-out.

**Comment by infews** [comment]
@NAGAI-Tsuyoshi sounds like you've figured out this issue.  Closing, please feel free to re-open with any follow-up questions.

Thanks,
@selzoc && Davis
