### ISSUE TITLE
Calls to /v3 count on rate_limiter.unauthenticated_limit

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/cloud_controller_ng#1161]
## Issue

Calls to /v3 count on rate_limiter.unauthenticated_limit in contrast to calls to "/" and "/v2/info".

## Context

cf-deployment 1.38.0
capi-release  1.59.0

We saw sporadic 429 responses from cloud controller in our pipelines after we upgraded from cf cli 6.36.1 to 6.37.0.
It turned out that they are related to /v3 calls that were introduced by cf cli 6.37.0 (at least we did not see these calls for our cf cli usage with cf cli 6.36.1).

## Steps to Reproduce

````
curl -v https://api.cf.stagingsc7.hanavlab.ondemand.com/v3
*   Trying 157.133.112.73...
* Connected to api.cf.stagingsc7.hanavlab.ondemand.com (157.133.112.73) port 443 (#0)
...
> GET /v3 HTTP/1.1
> Host: api.cf.stagingsc7.hanavlab.ondemand.com
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 429 Too Many Requests
< Content-Length: 89
< Content-Type: text/plain; charset=utf-8
< Date: Mon, 11 Jun 2018 15:55:49 GMT
< Retry-After: 1528733269
< Server: nginx
< X-Ratelimit-Limit: 500
< X-Ratelimit-Remaining: 0
< X-Ratelimit-Reset: 1528733269
< X-Vcap-Request-Id: 1837f05c-04fa-4830-43fe-bcd0a1030029::1cfd82cd-6266-4ee4-8927-65373f4e2caf
<
* Connection #0 to host api.cf.stagingsc7.hanavlab.ondemand.com left intact
{"errors":[{"detail":"Rate Limit Exceeded","title":"CF-RateLimitExceeded","code":10013}]}
````

A similar call to / doesn't return X-Ratelimit headers:

````
curl -v https://api.cf.stagingsc7.hanavlab.ondemand.com
* Rebuilt URL to: https://api.cf.stagingsc7.hanavlab.ondemand.com/
*   Trying 157.133.112.73...
* Connected to api.cf.stagingsc7.hanavlab.ondemand.com (157.133.112.73) port 443 (#0)
...
> GET / HTTP/1.1
> Host: api.cf.stagingsc7.hanavlab.ondemand.com
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 1108
< Content-Type: application/json;charset=utf-8
< Date: Mon, 11 Jun 2018 15:55:41 GMT
< Server: nginx
< X-Content-Type-Options: nosniff
< X-Vcap-Request-Id: f85c3a95-4d46-4f71-7b5a-c4458c80b252::97fb3fee-09e9-475b-8881-b9a172d056fe
<
{
  "links": {
    "self": {
      "href": "https://api.cf.stagingsc7.hanavlab.ondemand.com"
    },
    "cloud_controller_v2": {
      "href": "https://api.cf.stagingsc7.hanavlab.ondemand.com/v2",
      "meta": {
        "version": "2.113.0"
      }
    },
    "cloud_controller_v3": {
      "href": "https://api.cf.stagingsc7.hanavlab.ondemand.com/v3",
      "meta": {
        "version": "3.48.0"
      }
    },
  ...  
  }
````

## Expected result

Calls to /v3 don't count against the unauthenticated_limit, there are no X-Ratelimit headers and no 429 response code. Similar to a call to /.

## Current result

429 and X-Ratelimit headers. See above.

**Comment by ericpromislow** [comment]
Hi @stephanme 

From what I can tell this is working as designed. There is a config value that triggers rate-limiting : https://github.com/cloudfoundry/capi-release/blob/6f0c125f60b8586e9afba08d952334b41d9921a9/jobs/cloud_controller_ng/spec#L810 and I'm wondering if this was set to `true` when your deployment moved from 1.37.0 to 1.38.0

An unauthenticated requester has unlimited calls to `/` and `/v2/info`, and logged in users have unlimited calls to all the endpoints. The `/` and `/v2/info` endpoints return useful information, while `/v3` returns a set of links that need to be queried for more information on cloud controller resources, and all of those links require authentication. The rate-limiting actually applies to a small number of endpoints that can be used by unauthenticated users.

I'm curious—what's the need for making unlimited unauthenticated calls to /v3?

Regards
@ericpromislow - CAPI community support

**Comment by stephanme** [comment]
cf cli 6.37 runs two additional requests at the beginning of a cf-push compared to cf cli 6.36:

- GET /
- GET /v3

According to CF_TRACE, 'GET /' doesn't count against cc.rate_limiter.unauthenticated_limit (there are no X-Ratelimit headers in the response) while 'GET /v3' does count. This fits to your explanation above.

I don't know why cf cli 6.37 calls 'GET /v3' but if it is required, then it should be either unlimited or it should count against cc.rate_limiter.general_limit. Otherwise cf push is effectively limited by the unauthenticated limit.

**Comment by ericpromislow** [comment]
Thanks for the information. I'll talk to the CLI team about this. Could make a good case for excluding the /v3 endpoint from rate-limiting

**Comment by ericpromislow** [comment]
Done in commit 671c0fb23
