### ISSUE TITLE
Ruby version update

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/cloud_controller_ng#1176]
## Issue

Hello, with [ruby-buildpack v1.7.18](https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.7.18) the support for Ruby 2.4.2 was removed.

Wouldn't make sense to update the Ruby version used by the CC for the same reasons?
 

## Expected result

Have the CC to use an up to date Ruby version to avoid security issues.

Thank you.

**Comment by selzoc** [comment]
Hi @tyyko , thanks for opening this issue!  We have created a chore to do this in our backlog: https://www.pivotaltracker.com/story/show/160353044

Chris && @ericpromislow
