### ISSUE TITLE
GET /v2/apps/:guid/summary API does not return 'created_at' and 'updated_at' timestamps

### ISSUE THREAD

**Issue by riccardo-angelilli** [cloudfoundry/cloud_controller_ng#1177]
## Issue

The `GET /v2/apps/:guid/summary` API does not return `created_at` and `updated_at` timestamps, while the `GET /v2/apps/:guid`API does.

## Context

We use the summary API to index CF Apps data in our data store. We need to store create/update timestamps for apps as well, we want to avoid calling another API to get the two additional fields, we'd like the summary API to return those fields like the "non-summary" API currently does, e.g.:

```
"metadata": {
    "guid": "15b3885d-0351-4b9b-8697-86641668c123",
    "url": "/v2/apps/15b3885d-0351-4b9b-8697-86641668c123",
    "created_at": "2016-06-08T16:41:44Z",
    "updated_at": "2016-06-08T16:41:44Z"
 }
```

**Comment by selzoc** [comment]
Hi @riccardo-angelilli 

This endpoint is intended to give a limited summary. If `/v2/apps/:guid` returns more info than you need, you could run a command like this:

```
cf curl /v2/apps | jq '.resources[] | select(.metadata.guid == "APPGUID")'
```

Chris and @ericpromislow, Cloud Controller Community Team

**Comment by selzoc** [comment]
Hi @riccardo-angelilli ,

Yeah, we don't plan to modify the current `/v2/apps/:guid/summary` behavior.  Any new behavior is likely to come on the `/v3` api.  Have you taken a look at the `/v3/apps` endpoints? http://v3-apidocs.cloudfoundry.org/version/3.57.0/index.html#the-app-object

Thanks,
Chris

**Comment by riccardo-angelilli** [comment]
Ok thank you, we don't plan to support `/v3` api in the near future.
