### ISSUE TITLE
Info about max_cpu_proxy value 

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/cloud_controller_ng#1178]
Hello,
I am doing some testing with the parameter [cpu_quota_per_share_in_us](https://github.com/cloudfoundry/garden-runc-release/blob/f32baa3a343646229afbc843419e579fe9213d63/jobs/garden/spec#L146) and I saw that 8 GB and 16 GB apps are behaving the same in terms of cpu load.
Looking at the CC code, I found the following:

https://github.com/cloudfoundry/cloud_controller_ng/blob/d1e08a2749e5c289890854344487d4680fee85f4/lib/cloud_controller/diego/task_cpu_weight_calculator.rb#L5

this seems to explain the behavior I observed. May I ask what is the rationale behind this value?
And would it be possible to increase it?

Thanks a lot,

Best regards

**Comment by paolostivanin** [comment]
I increased the value to 32768, and I was able to solve the issue I was facing.
But, as I don't have the big picture here, I don't know what could be the side effects of quadrupling that value.
Any thoughts?

**Comment by cwlbraa** [comment]
@paolostivanin good find, it does appear as though the app recipe builder is using that [task] cpu weight calculator. I'm not entirely sure why we cap out cpu quotas like that, but perhaps @emalm could provide some historical context?

**Comment by emalm** [comment]
I believe the intent was that each app instance would be effectively limited to 1024 CPU shares on the Diego cell, regardless of its memory allocation. That decision was made long before garden-runc-release introduced the opt-in behavior to set a hard CPU quota proportional to that CPU shares allocation.

In any case, we're planning on moving forward with the proposal @julz put forth a few months ago at https://docs.google.com/document/d/16TvBsZSInjy7zoboSQWRJo30lmxr07tvd40_GzpfD3I/edit, with the Garden team having some of this work in flight already.

Best,
Eric

**Comment by selzoc** [comment]
Thanks for the info @emalm !!

Closing this issue as there is no cloud_controller action to take until the Garden/Diego work is done.
