### ISSUE TITLE
Unexpected enable/disable ssh behavior

### ISSUE THREAD

**Issue by oliverralbertini** [cloudfoundry/cloud_controller_ng#1189]
## Issue

Enabling and disabling ssh on an app is confusing. 

## Context

When an app is started with ssh enabled, we can disable/enable ssh and see immediate results for both.

When the app is started with ssh disabled, then we cannot disable/enable ssh.  SSHing will not work at all until the app is restarted with ssh enabled.

Also error messages are not very helpful when you fail to ssh into your app, and so this unique property of the CF system is difficult for a user to discover.

## Steps to Reproduce

```
>cf enable-ssh dora
>cf start dora
>cf ssh dora
<succeeds>

>cf disable-ssh dora
>cf ssh dora
FAILED
Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

------------------
>cf disable-ssh dora
>cf start dora
>cf ssh dora
FAILED
Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

>cf enable-ssh dora
>cf ssh dora
FAILED
Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

## Expected result

Ideally:
```
>cf enable-ssh dora
>cf start dora
>cf ssh dora
<succeeds>

>cf disable-ssh dora
>cf ssh dora
<fails with helpful error message>

------------------
>cf disable-ssh dora
>cf start dora
>cf ssh dora
<fails with helpful error message>

>cf enable-ssh dora
>cf ssh dora
<succeeds>
```

## Current result

See reproduction steps

## Possible Fix

The problem is that it is inconsistent whether the app needs to be restarted for ssh-enablement changes to take effect.  This is confusing to the user.

On the one hand, disabling ssh always seems to result in not being able to ssh on the app. However, enabling ssh may or may not require a restart.

Ideally, there would be a consistent experience between the two cases.  Either I always have to restart or I never have to restart for for ssh permission changes to take effect.

This could also be improved by better error messages from the CLI that allows the user to discover the correct actions to take to accomplish their goal.

## Dev notes

@tcdowney believes that this issue occurs because the LRP definition is not updated with an ssh port open until restart.

**Comment by selzoc** [comment]
Hi @oliverralbertini !  This looks like a `cf` cli issue - closing in favor of https://github.com/cloudfoundry/cli/issues/778

Thanks,
Chris && @ericpromislow
