### ISSUE TITLE
Call to  /v2/spaces/:guid/services doesn't return space-scoped services

### ISSUE THREAD

**Issue by irfanhabib** [cloudfoundry/cloud_controller_ng#1203]
## Issue

I have a space scoped service in a space. The response to list all services available in the space, doesn't include the space-scoped service.
Currently using PCF Dev 0.30.0

## Steps to Reproduce
1. Create a space-scoped service
2. Fetch services in the relevant space `cf curl  "/v2/spaces/:spaceGuid/services?results-per-page=100&inline-relations-depth=1&page=1"`

## Expected result

Response should contain space-scoped service entity.

## Current result

Response only contains services that are either public or have service plan visibilities mapped to the space.

**Comment by Samze** [comment]
Hey @irfanhabib thanks for raising this.

We just want to clarify what you mean here by a space-scoped service? Do you mean a service provided by a space-scoped service broker? 

Assuming that's what you mean, could you provide details on the steps you are taking to register the space-scoped broker and in additional tell us the result of the `cf service-access ` and `cf m` commands?

We could not reproduce this on the latest capi-release and while it looks like PCF Dev 0.30.0 uses an older release (1.28.0) we do not think this behaviour has changed.

```
$ cf create-service-broker overview-broker admin password https://some-broker.cf-app.com --space-scoped
$ cf curl "/v2/spaces/$(cf space dev --guid)/services"
{
   "total_results": 1,
   "total_pages": 1,
   "prev_url": null,
   "next_url": null,
   "resources": [
     ....service
      }
   ]
}
```

**Comment by irfanhabib** [comment]
Thanks @Samze!. I must've had something wrong with my setup when I created the issue. I'm unable to reproduce it.
