### ISSUE TITLE
Difficult to establish purge of Service Instances from Audit Events

### ISSUE THREAD

**Issue by akskap** [cloudfoundry/cloud_controller_ng#1208]
## Issue
CF Audit Events don't differentiate between 'delete' and 'purge' scenarios. 

## Context

`cf purge-service-instance <instance_name>` triggers a purge of the service instance which leaves behind an orphaned deployment on Bosh. Since purge of a service instance results in a forced deletion, service broker does not get notified in this case. This causes orphaned resources on IaaS platform which contribute to stale resources piling up + cost. We @ SAP wanted to automatically cleanup/monitor such orphaned deployments. At the same time we want to be doubly sure that such deployments are only a result of CF purge and not created via some different mechanism.

As of now we are unable to figure out this information from CF Events since it reports purge scenarios with `audit.service.delete`. Additionally we also see a log in CF deployment VM on Bosh which mentions a pattern like `DELETE "/v2/service_instances/<GUID>?async=true&purge=true"`. However, depending on CF events for such information seems to be a better way to establish such user actions.

What should be the ideal approach to handle cleanup of such deployments:

i) Should cf purge-service-instance internally call a `cf delete-service` before going for the actual purge - so that in case broker is up and running, can ensure a proper cleanup ?

ii) Should cleanup of such deployments be handled by broker automatically ? 

iii) Should CF differentiate a purge action explicitly in the Audit Events ?

## Steps to Reproduce

`cf purge-service-instance <instance_name>`

## Expected result

`audit.service.purge` audit event in CF

## Current result

`audit.service.delete` audit event is seen

**Comment by mattmcneeney** [comment]
Thanks for raising this @akskap

The `cf purge-service-instance` command is generally used when a broker is unresponsive, as it is in this scenario that `cf delete-service` tends to fail. I therefore believe that trying to ask the broker to do something during a purge is probably unlikely to succeed.

However, I agree that not being able to distinguish between a purge and a delete instance could make it difficult to understand when an admin/operator (probably) has to go and do some manual cleanup. We will take a look at this!

**Comment by akskap** [comment]
@mattmcneeney Thanks for your reply. Not sure if it makes sense, but is there a mechanism to somehow control the usage of `cf purge-service-instance` in the event of broker being healthy and available ?

Anyways, having a definitive mechanism to distinguish between a purge/delete would be great. Looking forward to this. Thanks !

**Comment by mattmcneeney** [comment]
I don't think we could do that; we don't know if a broker is healthy and available unless we ask it to do something (there is no health check API). We could work around this, but I think fixing the confusing audit events is the best next step!

**Comment by henryaj** [comment]
Hi @akskap - we have a story in our backlog to explore solutions to this. :)

**Comment by akskap** [comment]
@henryaj That's awesome.. Thanks for taking this up

**Comment by mattmcneeney** [comment]
We have explored solutions to this and will be implementing one soon! You can follow progress on [this story](https://www.pivotaltracker.com/story/show/161214647) and we will close this issue when it is completed.

**Comment by akskap** [comment]
@mattmcneeney Thanks a lot for the update 👍
