### ISSUE TITLE
Service Broker Plan Updates Require Strict Ordering

### ISSUE THREAD

**Issue by josephlewis42** [cloudfoundry/cloud_controller_ng#1216]
## Issue

Changing the order of the plans in the service catalog can cause registration of a service broker to fail. Semi-related to: #1138 

## Context

In V3 of the software, let's say we have the catalog: 

```
{
   "services":[
      {
         "name":"my-service",
         "id":"4b58ecf9-3683-456b-8aff-a32238cfaa20",
         "plans":[
            {
               "name":"standard",
               "id":"00000000-0000-0000-0000-000000000000"
            }
         ]
      }
   ]
}
```

and in V4, we need to deprecate the old `standard` plan by renaming it `legacy-standard` and replace it with a new plan `standard` that has a new UUID:

```
{
   "services":[
      {
         "name":"my-service",
         "id":"4b58ecf9-3683-456b-8aff-a32238cfaa20",
         "plans":[
            {
               "name":"standard",
               "id":"22222222-2222-2222-2222-222222222222"
            },
            {
               "name":"legacy-standard",
               "id":"00000000-0000-0000-0000-000000000000"
            }
         ]
      }
   ]
}
```

That will fail, but reversing the order of the plans will succeed:

```
{
   "services":[
      {
         "name":"my-service",
         "id":"4b58ecf9-3683-456b-8aff-a32238cfaa20",
         "plans":[
            {
               "name":"legacy-standard",
               "id":"00000000-0000-0000-0000-000000000000"
            },
			{
               "name":"standard",
               "id":"22222222-2222-2222-2222-222222222222"
            }
         ]
      }
   ]
}
```

The error returned like the following:

```
cf update-service-broker my-service-broker 5113be52cc15e1ad ******** https://my-service-broker.apps.pcf.xxx.yyy.com  
Updating service broker my-service-broker as system_services...  
FAILED  
Server error, status code: 502, error code: 270012, message: Service broker catalog is invalid: Plan names must be unique within a service. Service my--service already has a plan named standard  
```

## Steps to Reproduce

1. Rename a plan and create another with the same name.
2. Ensure the new plan gets returned by the service catalog endpoint before the renamed one.
3. Try to run a `cf update-service-broker`.

## Expected result

I expected order of the plans not to matter when determining if there were duplicate plans with the same name.

## Possible Fix

Do two passes over the plans, the first to update the plans in the cloud controller database and the second to validate them. Or, check consistency within the set of plans a service broker returns rather than against the database.

**Comment by jenspinney** [comment]
@josephlewis42 Thanks for reporting this. This is definitely not a great UX, and we agree that we should address it. We will look into a fix for this.

**Comment by josephlewis42** [comment]
Awesome, thank you so much @georgi-lozev and @ablease!
