### ISSUE TITLE
Blobstore Exceptions not logged

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cloud_controller_ng#1226]
## Issue

Uploads from CC worker jobs to blobstore run into 4 hour timeout. We would need better logging to understand the issue between the CC <-> blobstore connection.

## Context

On one of our Azure-based landscapes we had a problem with the Cloud Controller <-> blobstore connection. Some blobstore upload processes (e.g. BuildpackCacheUpload) ran into the global 4 hour job timeout. This caused the number of queued jobs to rise and some CC nodes were stalled.

We are not sure about the exact root cause. We couldn't see any problems in the blobstore itself. It's possible that the network connection was broken or extremely slow. The CC logs showed the beginning of the upload ("blobstore.cp-start"), but neither "blobstore.cp-skip" nor "blobstore.cp-finish" were logged. Can you please check the [cp_to_blobstore](https://github.com/cloudfoundry/cloud_controller_ng/blob/9bbebbf3f509dca1559b47eb0b427d61eb0199fd/lib/cloud_controller/blobstore/fog/fog_client.rb#L53-L83) coding if all possible exceptions are properly handled or logged?

Version is cf-deployment v2.6.0.

## Steps to Reproduce

Unknown.

## Expected result

All Exceptions occurring in the blobstore communication are properly handled or logged.

## Current result

Jobs like "BuildpackCacheUpload" run into the global 4 hour timeout and it's unclear why.

## Possible Fix

Log all Exceptions.

**Comment by cwlbraa** [comment]
logging of azure blobstore errors was improved dramatically in capi-release `1.67.0`. There was an issue in the the fog-azurerm gem that raised exceptions that would get handled very poorly. We think we fixed it here https://github.com/cloudfoundry/cloud_controller_ng/commit/cbece86e57de4b565be069b4e6026ca7a32b6b46. 

please reopen if you can reproduce with that commit.

Thanks!

**Comment by jochenehret** [comment]
Thanks for the information!
