### ISSUE TITLE
Unexpected behavior mixing v3-set-droplet with v2-restart

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#1230]
## Issue

I'm starting to mix in v3 commands with my applications.  One unexpected caveat is that if I rollback a droplet using `cf v3-set-droplet` then restart the application using `cf restart` then my application restages to the previously set package and restarts essentially undoing my `cf v3-set-droplet` command.

## Context

It can be difficult for users to know if a currently running application was rolled back and needs to use `v3-restart` instead of v2 `restart`.  It would be nice if this caveat could be improved.

## Steps to Reproduce

* Push application v1
* Push application v2
* cf-set-droplet to v1
* cf restart
* Note that application is still v2.

## Expected result

Application would be v1 or user would be not allowed to restart using the v2 api because the current droplet was set via `v3-set-droplet`

**Comment by charleshansen** [comment]
Hi @youngm, thanks for the input. Unfortunately, `cf v3-set-droplet` is not very compatible with the v2 commands. We hope to fix this eventually, but it is surprisingly tricky. 

In the meantime, we could certainly add a warning to that effect. We could add some warnings to our API endpoint https://v3-apidocs.cloudfoundry.org/version/3.63.0/index.html#set-current-droplet, let me know if there is somewhere else you would like to see this.

**Comment by youngm** [comment]
@charleshansen A warning message in the API docs would not be very useful.  I can imagine the complexity of making v2-restart work with an application that has had v3-set-droplet called on it.  However, would it be equally difficult to simply make v2-restart error out for an application in this state?  That would be a useful resolution.

**Comment by charleshansen** [comment]
Making it fail in this case is also kinda tricky. In the v2 code, this state is indistinguishable from a similar pending state where the app really does need to restage and use the most recent code (v2 in your example v2). I think this is pointing to larger questions about how we handle changing droplets and will be a focus of one of our next tracks of work. I'll add your example as a workflow we need to fix.

**Comment by youngm** [comment]
Thanks for the info @charleshansen.  As long as a better solution to this edge case is in the plans to be improved I'm happy.  I mostly wanted this issue to raise awareness.  I'm fine if you want to close this or keep it open whether you add a documentation note or not.  Thanks!

**Comment by sethboyles** [comment]
Closing as it's been over a year with no movement on this.  I don't believe we will get to this anytime soon, and at this point it is more likely cf cli v7 will come out of beta before then.
