### ISSUE TITLE
/v2/users/:userGuid/summary endpoint returns 403 for current user

### ISSUE THREAD

**Issue by reid47** [cloudfoundry/cloud_controller_ng#1235]
## Issue

When hitting `/v2/users/:userGuid/summary` for the *current* user guid (the guid of the user whose UAA token we're using), whether through `cf curl` or through Apps Manager's API calls, we get a `403` response code with the following body:

```
{
   "description": "You are not authorized to perform the requested action",
   "error_code": "CF-NotAuthorized",
   "code": 10003
}
```

## Context

The user that we encountered this with is a space developer of one space, an org manager of one org, and a member of that org.

## Steps to Reproduce

Find the user guid of a non-admin user (not sure of the impact of the user's roles on this issue). We found the user guid by logging in as an admin and running `cf curl /v2/users`.

Log in with the CF CLI as that user.

Run `cf curl /v2/users/:userGuid/summary`. Observe the `403` response above.

## Expected result

The actual user summary object, as documented: https://apidocs.cloudfoundry.org/5.1.0/users/get_user_summary.html

## Current result

A `403` (see above).

**Comment by charleshansen** [comment]
Users can now see their own summaries in 9949e3815de05177729ea51e4c66f00718d41a93

Just a warning, the user summary endpoint is potentially slow. Faster than space summary, but still not speedy. Also, summary endpoints in general will not be moved to v3.
