### ISSUE TITLE
App permissions should return read only for global auditor and cc.admin_read_only roles

### ISSUE THREAD

**Issue by Benjamintf1** [cloudfoundry/cloud_controller_ng#1242]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

App permissions should return read only for global auditor and cc.admin_read_only roles. 

https://docs.cloudfoundry.org/concepts/roles.html#roles

# Context
https://cloudfoundry.slack.com/archives/C07C04W4Q/p1540491354000100

https://github.com/cloudfoundry/cloud_controller_ng/blob/e5d5b39ebad0f0146bf3bdbb90c795414c98ca72/app/controllers/runtime/apps_controller.rb#L368-L397

**Comment by selzoc** [comment]
Hi @Benjamintf1 !  Thanks for bringing this issue to our attention.

We believe that the `admin_read_only` role should be able to read both `sensitive` and `basic` data about an app, which is reflected in the `/v2/apps/:guid/permissions` endpoint.

We just made a change in 95e99d1c2 to the `/v2/apps/:guid/permissions` endpoint to reflect that the `global_auditor` role can read only `basic` data about an app, and _not_ `sensitive` data.

Chris && @ericpromislow
Your friendly CAPI community pair
