### ISSUE TITLE
service bindings have async last_operation; but service keys do not

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cloud_controller_ng#1246]
A request to create/delete a service binding might be an asynchronous operation with the backend broker, so https://apidocs.cloudfoundry.org/5.4.0/service_bindings/retrieve_a_particular_service_binding.html include `last_operation.state` to describe state of async operation.

Creating a service key is the same operation to the service broker - and it might be asynchronous. But the API result for retrieving a service key does not include `last_operation.state` https://apidocs.cloudfoundry.org/5.4.0/service_keys/retrieve_a_particular_service_key.html

Could the service key API above also return the asynchronous state? and/or is it guaranteed to always block & succeed if the backend broker wants an asynchronous binding?

**Comment by mattmcneeney** [comment]
Hey @drnic 
We are going to tackle this as part of our CAPI v3 work, so are unlikely to solve this in v2.

**Comment by drnic** [comment]
Thanks for the answers. I'll close the ticket.

**Comment by drnic** [comment]
@mattmcneeney is there an epic/story for support of service keys in CAPI v3? At a glance they don't exist yet as a resource, is that right? http://v3-apidocs.cloudfoundry.org/version/3.68.0/index.html#service-bindings

**Comment by williammartin** [comment]
That's correct, there's no existing resource. We don't have a story right now, and there's some background discussions going on around v3 services in CC right now, and how it lines up with any Independent Services Marketplace work. Happy to chat more about this.

@laurzca for visibility (She's the SAPI PM now).
