### ISSUE TITLE
`v3/apps_controller/index` supports `order_direction` parameter, but it isn't documented

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#1247]
This is a likely reason for the issue https://github.com/cloudfoundry/cloud_controller_ng/issues/1245 -- `order_direction` should not have been supported in the v3 list classes, but it is for `AppsListMessage` and `IsolationSegmentsListMessage`. What do we do? Deprecate the use and eventually drop support?

**Comment by charleshansen** [comment]
Are you aware of anyone using `order_direction`? It looks like vestigial behavior from early v2 code. Given that it is completely undocumented I am tempted to simply delete it and mention that in the release notes.

**Comment by ericpromislow** [comment]
Don't we need to do this through at least one release, even if it isn't documented?  The next release deprecates it and issues a warning; the subsequent release drops it, giving a generic error message for unrecognized query options.

**Comment by charleshansen** [comment]
There isn't any mechanism for deprecating fields in CAPI other than through the documentation. We could add them to the documentation just to say they are deprecated and then remove them at a later point.

**Comment by ericpromislow** [comment]
sounds good

**Comment by tcdowney** [comment]
@charleshansen we added a preliminary comment to the code to make sure it doesn't get cargo-culted to other V3 messages. Not sure if you wanted anything else to be done since they aren't documented to begin with. See this Slack convo for additional context:
https://cloudfoundry.slack.com/archives/CBNDLQBB5/p1543419282053400

**Comment by zrob** [comment]
resolved in https://www.pivotaltracker.com/story/show/161637610
