### ISSUE TITLE
Experimentally querying Perm in `/v2/routes/:guid/apps` causes severe performance degradation (as non-admin)

### ISSUE THREAD

**Issue by djvdorp** [cloudfoundry/cloud_controller_ng#1272]
Submitting this issue to `cloud_controller_ng` after discussing this beforehand on [Slack](https://cloudfoundry.slack.com/archives/C07C04W4Q/p1544205744158200) with replies to confirm my hypothesis about what could be the performance issue/regression here with the help of @monamohebbi @tcdowney @selzoc (and @ericpromislow @Gerg CC'ed in Slack thread).

## Issue

We are reporting this issue as part of an upgrade of CF v249 -> CF v5.1.0 and we're aware this is not a validated upgrade path. This concerns a rather large foundation (~85k apps, but only a few 100's running at the same time). As we wrote before, we see a severe performance degradation between the old and the new version with a 100% CPU `ruby` processes on the API nodes from time to time (which we inspected with [rbspy](https://rbspy.github.io/) as suggested earlier). However, we now managed to pinpoint the specific call (we do that call ourselves, we know where and why), and it is this call:

`GET /v2/routes?inline-relations-depth=1&q=host:XXX`

(Please note that we did read the historical background about [inline-relations-depth](https://github.com/cloudfoundry/cloud_controller_ng/wiki/V2-API-Design-Notes#inlining-relationships) and its deprecation, changing it from `ird=1` to `ird=0` and then query the app details we needed ourselves afterwards will still show the routes query to keep on performing poorly if the slow code-path is picked, depending on perm)

The interesting part here is that we noted the following: depending on some variable (I currently suspect user role?) this call can choose 2 completely different code-paths, the one we see most often performs perfectly fine (sub-second) but the other one (more limited user role, suspected?) performs horrible at this scale; it literally takes 10-20 seconds to return on a huge RDS instance (AWS `db.m4.10xlarge` I believe) and during that time, the API (cc) seems pretty much blocked/busy with this request and unable to serve others at a fast rate, basically degrading the whole cluster performance by a lot.

## Context

It seems that the slow code-path is doing additional checking including, but not limited to this:

```
SELECT count(*) AS \"count\" FROM \"routes\" WHERE ((\"routes\".\"guid\" IN (HUGE-LIST-OF-UUIDs-HERE) [..]
SELECT * FROM \"routes\" WHERE ((\"routes\".\"guid\" IN (HUGE-LIST-OF-UUIDs-HERE) [..]
```

This (to me, with limited knowledge) clearly looks like an additional security check to make sure you are not able to get routes you're not supposed to see (which is why we suspect user roles play a role in this), can you confirm or deny this (the existence of two paths) and that one performs rather poorly at scale (while having ~85k apps in ~4 spaces, we know this scales badly and will fix that after this performance issue is resolved). Going through the `git` history for the `RoutesController` (`/app/controllers/runtime/routes_controller.rb`) seems rather interesting, mostly commit a09f3fb12ceb540b30c9216fbe964241135a463f that refers to [Pivotal Tracker issue #157581579](https://www.pivotaltracker.com/n/projects/966314/stories/157581579) that seems to describe this, if we understand it correctly? And later also a4d4364f09c98ab9b1a38e30ac6ffda40ba72e56 that refers to [Pivotal Tracker issue #157581627](https://www.pivotaltracker.com/n/projects/966314/stories/157581627) for a different endpoint (`/v2/routes/:guid/route_mappings`).

**Rough numbers of apps:** ~85k
**Rough number of routes:** ~85k
**Rough number of orgs:** ~5
**Rough number of spaces:** ~10 (2 per org)
**Rough number of apps/routes per space:** ~10-20k over ~5 spaces (poor man's sharding)

## Steps to Reproduce

As non-admin user, execute request on a rather large foundation, as described: 
`GET /v2/routes?inline-relations-depth=1&q=host:XXX` or `GET /v2/routes?inline-relations-depth=0&q=host:XXX`

## Expected result

A sub-second response for the request sent, as admin users would get.

## Current result

`ruby` 100% CPU with `top` on (one of the) API node(s). During that time, the API (cc) seems pretty much blocked/busy with this request and unable to serve others at a fast rate, basically degrading the whole cluster performance by a lot. The takes 10-20 seconds to return as a non-admin user.

## Possible Fix

Revert the (dead?) perm code commits mentioned above, or make sure they perform.

As per @monamohebbi: "there's a lot of historical context related to this question, perm (ie that commit you linked to), and inline-relations-depth generally. @tcdowney might know more. what I can tell you is that your suspicion about multiple perm code paths is almost certainly correct."

As per @selzoc: "it was definitely part of a perm effort to limit access, as you figured out.  unfortunately, that effort failed, but there is some code still resident in capi that changed shape to support it. we are in the process of trying to move everything to the v3 api, which is easier for us to make performant. and there's future work to add /v3/routes"

As per @tcdowney: "Since the perm work is stalled out, this might just be a change we need to revert -- you're the first I'm aware of to report perf issues from it though so the rough numbers of apps, routes, and apps/routes per space will help us repro/confirm the root cause"

## Possible Workaround

I think a user with the `cloud_controller.admin` or `cloud_controller.admin_readonly` would be able to bypass this since they can view everything, but yes definitely seems like a performance regression here. (as per @tcdowney)

Reverting back to an older `capi-release` (like before [v1.59.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.59.0)) is not a real option either for most.

`/v3/routes` does not exist in any version of `capi-release` yet, so that is no workaround. (as per @Gerg)

## End note

Please let me know if there is anything else I could/should provide to help resolve this issue!

**Comment by djvdorp** [comment]
Brief update: when grepping for `queryer.can_read_globally` (the check that seems to determine to use the perm code path or not), it seems this is present in the following (api v2) controllers?

`app/controllers/runtime/organizations_controller.rb` commit 601ed012ce388d23effb68cb0701a99fec366539
`app/controllers/runtime/routes_controller.rb` (commits already mentioned above)

And it seems to also match for the following api v3 controllers (which we don't use atm):

```
app/controllers/v3/tasks_controller.rb
app/controllers/v3/droplets_controller.rb
app/controllers/v3/isolation_segments_controller.rb
app/controllers/v3/packages_controller.rb
app/controllers/v3/route_mappings_controller.rb
app/controllers/v3/organizations_controller.rb
app/controllers/v3/service_instances_controller.rb
app/controllers/v3/service_bindings_controller.rb
app/controllers/v3/processes_controller.rb
app/controllers/v3/apps_controller.rb
app/controllers/v3/spaces_controller.rb
app/controllers/v3/builds_controller.rb
app/controllers/v3/deployments_controller.rb
```

**Comment by tcdowney** [comment]
@djvdorp thanks for the investigation you've done so far in to this performance issue. I'm especially grateful for the detailed information regarding the size and shape of your data since that will help us reproduce the issue and validate our code changes.

For context, this code came about due to our efforts last Spring to integrate with the ["perm"](https://github.com/cloudfoundry-incubator/perm) permissions service that would allow for user authorization via role-based access control instead of Cloud Controller's existing ideas of permissions. This service required us to send a list of resource identifiers (in this case app guids) to it so that it could make access control decisions for those resources. This work required changes to the existing Cloud Controller-based access control and, as you've discovered, these new queries are not performant for users that have access to a large number of apps.

Work on the RBAC perm service is on indefinite hiatus and will likely never be implemented in the v2 APIs since efforts are underway to reach feature parity in v3 and deprecate them (see: https://lists.cloudfoundry.org/g/cf-dev/topic/26659245#8305). Given that, I think we should remove perm integration from the v2 `organizations_controller.rb` and `routes_controller.rb` and have them revert back to using the queries that they used before.

Tagging our PMs @zrob and @ssisil so they're aware of this issue.

**Comment by tcdowney** [comment]
@djvdorp were you seeing issues with the OrganizationsController endpoints as well (`/v2/organizations`)?

**Comment by djvdorp** [comment]
@tcdowney no, we did not, sorry if that was unclear. Our use-case does not have a lot of orgs (and spaces) so we were not seeing issues there -- just wanted to share that similar commits are there :slightly_smiling_face:

**Comment by tcdowney** [comment]
Cool, I broke that work out in to a [separate story](https://www.pivotaltracker.com/story/show/16267) then. Commit e676a6e60adb4831081fb8e2c04b545d56e8b6da should address this, just need to deliver it to our PMs and it will work its way in to the next capi-release.
