### ISSUE TITLE
Suspicious log messages

### ISSUE THREAD

**Issue by poy** [cloudfoundry/cloud_controller_ng#1280]
I noticed the following log line in `/var/vcap/sys/log/cloud_controller_ng/cloud_controller_ng.stderr.log`:

```
/var/vcap/data/packages/cloud_controller_ng/fb7c7b2ae6c9fbabe1bbc4cbd5e51b6f22b122cb/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/clusivity.rb:8: warning: already initialized constant ActiveModel::Validations::Clusivity::ERROR_MESSAGE
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/clusivity.rb:8: warning: previous definition of ERROR_MESSAGE was here
```
I deployed capi-release v1.74.0.

Everything seems operational, but the log message doesn't give confidence.

**Comment by selzoc** [comment]
Hi @poy !

Thanks for the report!  This is due to a bug in Ruby and how it handles symlinked requires.  This is fixed in capi-release 1.75.0 since we bumped our Ruby version to one with the fix for that bug.

-- Chris && @ericpromislow
