### ISSUE TITLE
CF update-service behavior is inconsistent

### ISSUE THREAD

**Issue by subhankarc** [cloudfoundry/cloud_controller_ng#1286]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

[provide quick introduction so this issue can be triaged]

## Context
When we do a `cf update-service service-name`, it says no changes are made. But when we pass same plan name, like `cf update-service service-name -p same-plan-name`, then it says OK, even though no call is made to the broker. Isn't this behaviour inconsistent ?
## Steps to Reproduce
```
$ cf update-service test
OK
No changes were made

$ cf update-service test -p <same-plan>
Updating service instance test as admin_cf...
OK

```
[ordered list the process to finding and recreating the issue, example below]

## Expected result

Expectation would be to return no changes made for both.

## Current result

Current result of `cf update-service service-name -p same-plan-name` gives a feeling that it is making some changes, but broker is not called for the same.

**Comment by nmaslarski** [comment]
@laurzca @williammartin

**Comment by AartiKriplani** [comment]
@subhankarc: thank you for submitting this issue.
This behavior is part of the CLI and not cloud controller.
In the case when the plan is same as before, I assume this is to keep the update-command idempotent.
When no other args, apart from service-name are passed to the update-service command, the CLI does not make a call to CC, one option would be to make at least one other option mandatory.
Currently, we're refactoring the CLI command implementations, we would consider this, as part of the refactoring, you can follow the progress [here](https://www.pivotaltracker.com/story/show/126256751)

**Comment by henryaj** [comment]
Hi @subhankarc - as this is a CLI issue, I'm closing this out in favour of https://github.com/cloudfoundry/cli/issues/1575. You can follow along on progress we make there. Thanks! :)

**Comment by williammartin** [comment]
We've fixed this in https://www.pivotaltracker.com/n/projects/2105761/stories/163974651 so hopefully it will be resolved in the next release of CAPI. Thanks!
