### ISSUE TITLE
am facing issue with credential used for database service. I am using credential stored in vcap services for connecting database installed on AWS. while deploying I am binding the database service(managed service) with app and on startup it is correctly using database credential but for health check transaction credential is different and thus not able to connect database for health check.  I am struggling with this issue since last three days and I hope someone can help me to resolve this issue or let me know what could be the possible reason of this might happen.

### ISSUE THREAD

**Issue by ImJavaDeveloper** [cloudfoundry/cloud_controller_ng#1287]
I am facing issue with credential used for database service. I am using credential stored in vcap services for connecting database installed on AWS. while deploying I am binding the database service(managed service) with app and on startup it is correctly using database credential but for health check transaction credential is different and thus not able to connect database for health check.

I am struggling with this issue since last three days and I hope someone can help me to resolve this issue or let me know what could be the possible reason of this might happen.

**Comment by AartiKriplani** [comment]
Hello @ImJavaDeveloper, the credentials in vcap services are managed by the platform and might change on every deployment. If you want to connect to the database manually, or from another system for health check etc, it's recommended to use [Service Keys](https://docs.cloudfoundry.org/devguide/services/service-keys.html). I hope that clarifies.
