### ISSUE TITLE
Inconsistent behavior using env vars with '.' and '-'

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/cloud_controller_ng#1298]
Taken over from https://github.com/cloudfoundry/libbuildpack/issues/25 and moved here on suggestion of the colleagues there.

---

We are trying to chase down an intermittent issue that seems to be a combination of
* using the `cflinuxfs3` stack
* user-provided environment variables containing '.'s and '-'s like:
```
env.with.dot: something
env-with-dash: something
```
* Changes in the manifest (e.g. changing the start command) after first push

The result is that the above env vars do not show up in the process environment of the application. This is independent from the buildpack used and I was able to verify that indeed those variables are missing looking at `/proc/<pid>/environ` being `cf ssh`ed into the app.

Unfortunately, I so far wasn't able to narrow down the scenario to something that consistently works/fails, but here is the minimal app that I am using: https://gist.github.com/bkrannich/d77681d7ea5caf1b52a0ffda4fcfb6ff

Steps to (try and) reproduce:
* `cf push` the app
* Call it's URL in the browser
* Search for 'env.' or 'env-' - often times during initial `cf push` this is failing. Changing things like uncommenting the the `command` in `manifest.yml` and re-pushing sometimes changes the situation.

Additional observations:
* This issue doesn't seem to exist with `cflinuxfs2`.
* I have a hunch that it might be related to some conversion of YML to an intermediate format (BASH?) and/or back, but this does not explain why the issue is intermittent. Also, I found some places in https://github.com/cloudfoundry/libbuildpack/blob/master/stager.go as well as https://github.com/cloudfoundry/libbuildpack/blob/master/stager_unix.go#L14 that look suspicious in that respect, but modifying the stager_test.go, I wasn't able to provoke an error.

**Comment by cwlbraa** [comment]
here's another suspect one https://github.com/cloudfoundry/buildpackapplifecycle/blob/master/launcher/launcher_unix.go

**Comment by bkrannich** [comment]
Additional observation of a colleague:

> I left all my properties/variables as they are (dot notation in YAML file).
After setting them with underscores, you still see variables (names) with underscores if you call cf env <app_name> but at runtime all of them will have correct values.

**Comment by vtintillier** [comment]
Hi @bkrannich , this should be unrelated to CF, this is Spring that is looking for same property with `_` instead of `.` in case it cannot find it. See details in [1]

[1] https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/env/SystemEnvironmentPropertySource.html

**Comment by bkrannich** [comment]
Thanks for the pointer, @vtintillier - given your finding, I agree that this part is unrelated. However, the general issue remains for us.

**Comment by ericpromislow** [comment]
It's not the cloud controller, although the CC might be misleading.

When you run `cf env APP` CC just queries its database for the app environment.

The key, as @bkrannich mentions above, is to `cf ssh` to the app and look at the environment of each process:

`ps fauxww` gives output like this: ```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          86  0.0  0.0 108012  3344 ?        S<sl 20:26   0:00 /etc/cf-assets/healthcheck/healthcheck -port=8080 -timeout=1000ms -liveness-interval=30s
vcap          13  0.2  0.1 1066524 50196 ?       S<sl 20:26   0:00 npm
vcap          78  0.0  0.0   4632   720 ?        S<   20:26   0:00  \_ sh -c node index.js
vcap          79  0.0  0.0 747464 27028 ?        S<l  20:26   0:00      \_ node index.js
vcap           6  0.1  0.0 116344 10724 ?        S<sl 20:26   0:00 /tmp/lifecycle/diego-sshd --allowedKeyExchanges= --address=0.0.0.0:2222 --allowUnauthenticatedClients=false --inheritDaemonEnv=true --allowedCiphers= --allowedMACs= --logLevel=fatal --debugAddr=
vcap         102  0.0  0.0  70376  3936 pts/0    S<s  20:29   0:00  \_ /bin/bash
vcap         126  0.0  0.0  86268  3440 pts/0    R<+  20:30   0:00      \_ ps fauxww
root           1  0.0  0.0   1120     4 ?        S<s  20:26   0:00 /tmp/garden-init
```
Then looking at the env each app runs in: ```
for pid in 13 78 79 ; do echo $pid; perl -pe 's/\x00/\n/g' /proc/$pid/environ | grep env; done
13
env_with_underscore=underbar works
env-with-dash=dash works
envwithoutdot=nothing works
env.with.dot=dot works
78
env_with_underscore=underbar works
env-with-dash=dash works
envwithoutdot=nothing works
env.with.dot=dot works
npm_package_name=envtest
79
envwithoutdot=nothing works
npm_package_name=envtest
env_with_underscore=underbar works
```
Apparently the command `sh -c node index.js` (where `sh` is a symlink to `dash`) is culling the problematic environment variables.  Here's a demo with a simple Python script. Here's `child.py`: ```
import os
for k, v in os.environ.items():
    if 'testname' in k:
        print("key:", k, "value:", v)
```
called from `parent.py` in various forms: ```
import subprocess

env = {
    'testname.with.dot': "dot works",
    'testname-with-dash': "dash works",
    'testname_with_underscore': "underbar works",
    'testnamewithoutdot': "no punct works"
    }
# Without the shell
p = subprocess.Popen(["/usr/local/bin/python", "child.py"], env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
p.wait()
print("stderr: ", p.stderr.read())
print("stdout: ", p.stdout.read())

# Using the shell, call python directly
p = subprocess.Popen("python child.py", shell=True, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
p.wait()
print("stderr: ", p.stderr.read())
print("stdout: ", p.stdout.read())


# Using the shell through bash
p = subprocess.Popen("bash -c 'python child.py'", shell=True, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
p.wait()
print("stderr: ", p.stderr.read())
print("stdout: ", p.stdout.read())

# Using the shell through dash
p = subprocess.Popen("dash -c 'python child.py'", shell=True, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
p.wait()
print("stderr: ", p.stderr.read())
print("stdout: ", p.stdout.read())
```

You might need to install the dash shell to verify this.

**Comment by ericpromislow** [comment]
Just a note that further research shows dash is being posix-compliant, as it's not required to handle any environment variables that contain characters other than alnum's and underscores.

**Comment by ericpromislow** [comment]
I thought this was due to `cflinuxfs3` using `dash` to launch the commands, but that happens under `cflinuxfs2` as well.  The one diff is in the call trees for the default command.  With `cflinuxfs3` it was
```
vcap          13  0.2  0.1 1066524 50196 ?       S<sl 20:26   0:00 npm
vcap          78  0.0  0.0   4632   720 ?        S<   20:26   0:00  \_ sh -c node index.js
vcap          79  0.0  0.0 747464 27028 ?        S<l  20:26   0:00      \_ node index.js
```
with cflinuxfs2, it's
```
vcap           6  0.0  0.0   4456   672 ?        S<s  21:54   0:00 sh -c node index.js
vcap          71  0.0  0.0 809784 25848 ?        S<l  21:54   0:00  \_ node index.js
```
But when I did the analysis from python, I saw the problem was in the call to `dash -c ...`, not from `npm`.  So I'm less certain of the cause of the problem, but think this is the right track.

**Comment by bkrannich** [comment]
Thanks for the thorough analysis, @ericpromislow - I'll pass the information along to our developers.
