### ISSUE TITLE
Add audit event for app instance restart

### ISSUE THREAD

**Issue by kpschuck** [cloudfoundry/cloud_controller_ng#1306]
## Issue

The `instances_controller.kill_instance()` method is not currently creating an audit event. Therefore, `cf restart-app-instance APP_NAME INDEX` does not produce an audit event.

## Context

The `app_restart.restart()` method does create an audit event, I would expect the same from `instances_controller.kill_instance()`.

## Steps to Reproduce

```
cf restart-app-instance APP_NAME INDEX
cf events APP_NAME
```

## Expected result

There would be a corresponding audit event for the application instance restart.

## Current result

There is no corresponding audit event for the application instance restart.

## Possible Fix

Produce an audit event in `instances_controller.kill_instance()`

**Comment by sethboyles** [comment]
Closing this issue.  As far as I can tell, restarting the app has always recorded the `audit.app.process.terminate_instance` event.  

@kpschuck This is an old issue, but if for some reason the `terminate_instance` event is not sufficient, please let us know and I will reopen this issue.
