### ISSUE TITLE
Deal with infrequent error message complaining that resource already exists

### ISSUE THREAD

**Issue by nrxus** [cloudfoundry/cloud_controller_ng#1307]
## Issue

We saw a failure in this `bara`: 
```
[Fail] revisions deployment when there is a new droplet [It] creates a new revision 
/go/src/github.com/cloudfoundry/capi-bara-tests/baras/revisions.go:412

```

with error message:
```
[2019-03-06 21:24:22.48 (UTC)]> cf curl /v3/deployments -X POST -d {"relationships": {"app": {"data": {"guid": "ca6a20af-a696-488a-97eb-93e2767285af"}}}} 
{
   "errors": [
      {
         "detail": "Runner error: Process Guid: 61c34bfd-9649-47ba-86d0-68d968e62f28: the requested resource already exists",
         "title": "CF-RunnerError",
         "code": 170016
      }
   ]
}
```

Also reported by https://cloudfoundry.slack.com/archives/C07C04W4Q/p1551201149087000

## Context

This is triggered from the process_observer. Maybe in between the time the change was
made to create the process and the desire_app call was made, the process_sync job
was triggered and created the app. It's likey this error can be ignored.

## Steps to Reproduce

Make a temporary change in the code to have the process observer sleep for a few seconds before continuing

## Expected result

We should never see this error message if it is in fact bogus

## Current result

hard to predict when this happens

**Comment by ericpromislow** [comment]
Could we get a full traceback? There are at least two points in the code where this could happen, but "requested resource already exists" isn't specific enough.

**Comment by reneighbor** [comment]
(with @sethboyles): Thank you for reporting this, we've replicated the bug and it is another occurrence of a problem we've been seeing in CI. Being tracked at https://www.pivotaltracker.com/n/projects/966314/stories/167495930

**Comment by jspawar** [comment]
@nrxus do you still see this after using `capi-release` versions `1.85.x+`?
