### ISSUE TITLE
Killing `cloud_controller_ng` can cause counter metrics like `requests.outstanding` to get stuck

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cloud_controller_ng#1312]
## Issue
Logging this a Github issue for discoverability.

The  `cc.requests.outstanding` counter metric can get stuck if Cloud Controller is stopped/killed in the middle of handling requests.

## Context

Cloud Controller emits the `cc.requests.outstanding` to give operators insight into the number of active requests being handled by the `cloud_controller_ng` Ruby process.

> Number of requests that are currently being processed. Emitted for each Cloud Controller request.
More information on emitted metrics: https://docs.cloudfoundry.org/running/all_metrics.html

Cloud Controller manages this metric in https://github.com/cloudfoundry/cloud_controller_ng/blob/90bbddabf983a353297a11aa8a2bcc1f98b81503/middleware/request_metrics.rb#L14.

So if the Cloud Controller is stopped/killed before it has a chance to call `complete_request` [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/90bbddabf983a353297a11aa8a2bcc1f98b81503/lib/cloud_controller/metrics/request_metrics.rb#L14), none of the active requests can decrement the counter in statsd. This is similar to #1294 .

## Steps to Reproduce

1. Install the [CF Loggregator Firehose Plugin](https://docs.cloudfoundry.org/loggregator/cli-plugin.html)

2. Connect to the firehose and grep out the metric:
```
cf nozzle -f ValueMetric | grep --line-buffered cc.*outstanding
```

3. Hammer the Cloud Controllers with requests:
```
hey -n 1000000 -c 50 -H "Authorization: $(cf oauth-token)" http://api.arya.capi.land/v2/apps
```

4. Observe something similar to the following from `cf nozzle`
```
origin:"cc" eventType:ValueMetric timestamp:1553034399010006107 deployment:"cf" job:"api" index:"c032ab53-66f7-45fc-a229-d25d509967dc" ip:"10.0.1.11" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:19 unit:"counter" >
origin:"cc" eventType:ValueMetric timestamp:1553034399011308663 deployment:"cf" job:"api" index:"c032ab53-66f7-45fc-a229-d25d509967dc" ip:"10.0.1.11" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:20 unit:"counter" >
origin:"cc" eventType:ValueMetric timestamp:1553034398981292501 deployment:"cf" job:"api" index:"b55807af-8ebb-4a54-8bd7-1edc7b8264f9" ip:"10.0.1.10" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:20 unit:"counter" >
origin:"cc" eventType:ValueMetric timestamp:1553034399098849677 deployment:"cf" job:"api" index:"b55807af-8ebb-4a54-8bd7-1edc7b8264f9" ip:"10.0.1.10" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:19 unit:"counter" >
```

5. On an `api` vm, stop the `cloud_controller_ng` process:
```
monit stop cloud_controller_ng
```

Feel free to substitute a `kill -9` for the `monit stop` if monit is being too gentle in stopping the Cloud Controller.

6. Start it back up again:
```
monit start cloud_controller_ng
```

## Expected result

An **accurate** count for `requests.outstanding` continues to be emitted, capped at `20` (the default number of EventMachine threads).

## Current result
Since the Cloud Controller was stopped in the middle of handling all of the requests from `hey` it was not able to decrement the statsd counter, so now there is a baseline of `20` for all of the `cc.requests.outstanding` metrics from the `cloud_controller_ng` job on the VM that was stopped (in this test environment that was `b55807af-8ebb-4a54-8bd7-1edc7b8264f9`).

```
origin:"cc" eventType:ValueMetric timestamp:1553034630853046264 deployment:"cf" job:"api" index:"c032ab53-66f7-45fc-a229-d25d509967dc" ip:"10.0.1.11" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:3 unit:"counter" >
origin:"cc" eventType:ValueMetric timestamp:1553034630865535939 deployment:"cf" job:"api" index:"c032ab53-66f7-45fc-a229-d25d509967dc" ip:"10.0.1.11" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:2 unit:"counter" >
origin:"cc" eventType:ValueMetric timestamp:1553034630917230329 deployment:"cf" job:"api" index:"c032ab53-66f7-45fc-a229-d25d509967dc" ip:"10.0.1.11" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:3 unit:"counter" >
origin:"cc" eventType:ValueMetric timestamp:1553034630849778556 deployment:"cf" job:"api" index:"b55807af-8ebb-4a54-8bd7-1edc7b8264f9" ip:"10.0.1.10" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:40 unit:"counter" >
origin:"cc" eventType:ValueMetric timestamp:1553034630888060296 deployment:"cf" job:"api" index:"b55807af-8ebb-4a54-8bd7-1edc7b8264f9" ip:"10.0.1.10" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:39 unit:"counter" >
origin:"cc" eventType:ValueMetric timestamp:1553034630889439373 deployment:"cf" job:"api" index:"b55807af-8ebb-4a54-8bd7-1edc7b8264f9" ip:"10.0.1.10" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:40 unit:"counter" >
origin:"cc" eventType:ValueMetric timestamp:1553034630986481710 deployment:"cf" job:"api" index:"b55807af-8ebb-4a54-8bd7-1edc7b8264f9" ip:"10.0.1.10" tags:<key:"source_id" value:"cc" > valueMetric:<name:"requests.outstanding" value:39 unit:"counter" >
```

## Possible Fix
*Current mitigation:* restarting the `statsd_injector` by running `monit restart statsd_injector` resets the counter.

*Longer term:* Cloud Controller could potentially clear these statsd counters on startup so it always starts with a clean slate.

## Related
* https://github.com/cloudfoundry/cloud_controller_ng/issues/1294
* https://www.pivotaltracker.com/story/show/139866443

**Comment by jochenehret** [comment]
Can we expect a fix for this issue? As mentioned above, restarting the `statsd_injector` process whenever `cloud_controller_ng` is restarted would already help. We are trying to use this metric as scaling indicator (as recommended on https://docs.cloudfoundry.org/running/managing-cf/scaling-cloud-controller.html), but currently it's not reliable.

**Comment by cwlbraa** [comment]
IIRC clearing the counters is easy to say but not easy to do. @tcdowney do you remember if your "current mitigation" was already implemented?

**Comment by jochenehret** [comment]
Another option would be to emit an absolute value from cloud_controller_ng (instead of relative increment/decrement values). Can you estimate how difficult this would be to implement? Would accept a PR? We can try to reserve some capacity in our next sprint to provide a fix.

**Comment by reneighbor** [comment]
Thank you @jochenehret! If you're willing and have capacity, a PR would be great. One thing we discussed in tech forum today would be to use an absolute value and have the state stored as a variable in memory on the ccng side. Is that what you meant?

**Comment by jochenehret** [comment]
Yes, that's what we meant. We are trying to create a PR in our next sprint.

**Comment by cwlbraa** [comment]
would an "absolute value" be backwards-compatible in this case? or would it need to go under a different metric name?

**Comment by jochenehret** [comment]
I think if the Cloud Controller emits an absolute "requests.outstanding" metric, that should be backwards-compatible. I just don't know how the "statsd_injector" process behaves. It currently gets the relative metric in the format "ccc.requests.outstanding:1" or "ccc.requests.outstanding:-1". We must make sure that it forwards the absolute numbers without doing any additional calculations.

**Comment by dawu415** [comment]
Hello, just curious if there's any movement on this as I am currently seeing this bug as well. We're still investigating on our end but it seems connectivity to MySQL db dropped and the outstanding requests remain stuck at 20.

**Comment by sethboyles** [comment]
@dawu415 We have looked into this in the past week and unfortunately there doesn't seem to be a way to reset the counter to 0 on restart.  The statsd_injector doesn't provide the statsd admin interface, which provides the option to delete a counter.

We may be able to resolve this by changing the metric from a `counter` metric to a `gauge`.  However, we are still looking into this and considering the implications of making a change.

Perhaps, if gauges do provide a way to reset the metric without the admin interface, we can create a new metric with the gauge and deprecate this counter, but not remove it?  @Gerg

**Comment by Gerg** [comment]
@sethboyles How would CC know what value to set the gauge to? All the instances of CC would need need to have some shared state to track/manage outstanding requests.

**Comment by sethboyles** [comment]
We should be able to increment or decrement gauges just like we do with counters, using the delta option:

https://statsd.readthedocs.io/en/v3.2.1/types.html#gauge-deltas

**Comment by Gerg** [comment]
So, we could add a new metric `requests.outstanding.ng` (real name TBD). This metric would be a gauge that deltas +1/-1 whenever the `requests.outstanding` counter increments or decrements, respectively. Additionally, the gauge is set to 0 whenever CC starts. Does that sound right?

**Comment by sethboyles** [comment]
Yeah, I think that is something to look into at least.

**Comment by Gerg** [comment]
Quoting @belinda-liu:

> The current implementation uses a counter for this metric. There is no way to set the counter to 0 in the statsd client. There is a `delcounter` method, but this is only accessible for admin statsd users, and the `statsd-injector` does not expose this functionality...
> 
> We then explored using a gauge instead. In the github issue, there was a suggestion to use a gauge and leverage the `delta` functionality of a gauge to effectively increment/decrement the metric value. Unfortunately, the [statsd client](https://github.com/reinh/statsd/blob/3863a1a341d21b3c81a0ab9aebc6bd901da45323/lib/statsd.rb#L384) that we use does not support this functionality.
> 
> We did find that running `monit restart` on the statsd-injector process will reset any metrics that are incorrect.

**Comment by sethboyles** [comment]
We can potentially fork the statsd client (and make a PR) to expose the delta functionality.  But I'm not sure we should actually continue to invest in the statsd interface.

Another option that was suggested by the logging team here [in this conversation](https://cloudfoundry.slack.com/archives/CUW93AF3M/p1605223746109200) is to instead embrace Prometheus and create an endpoint that would expose an equivalent metric and be scraped by the prom_scraper.  I'm not really familiar with Prometheus and what that solution would look like, but its something we could look into.  

As far as I can tell, CCNG supports Prometheus via the statsd-exporter, which converts the existing statsd metrics to a prometheus scrapeable endpoint (see https://github.com/cloudfoundry/cf-for-k8s/pull/125).  However I think this was meant as a temporary solution: https://github.com/prometheus/statsd_exporter#without-statsd.

**Comment by zmb3** [comment]
+1 on on moving towards a Prometheus compatible endpoint. Was going to suggest the same. 

Is this issue limited to one or two metrics or are all counters impacted?

**Comment by jochenehret** [comment]
Here is a PR proposal for a fixed "requests.outstanding.total" metric: https://github.com/cloudfoundry/cloud_controller_ng/pull/2087
Here you can see how the existing metric behaves versus the new metric:
<img width="1864" alt="Screenshot 2021-01-27 at 16 44 00" src="https://user-images.githubusercontent.com/7871793/106120211-6389f780-6156-11eb-8646-07c6cdb9ab03.png">
With the new metric, you don't get "steps" when the "cloud_controller_ng" process is restarted.

What do you think? Is the new name ok? If yes, we can complete the PR with unit tests.

**Comment by sethboyles** [comment]
A simple solution like this would be great! 

As for the name `requests.outstanding.total`, to me that implies that the metric is for the total of requests across all api nodes.  Since this metric is per node I can imagine that might be confusing.  At the moment I don't have a better suggestion, but I will continue to think about it. 

My other concern is that we probably want to switch out the the metrics to use Prometheus at some point cc @Gerg @elenasharma.  Not sure when we will eventually get to that or how difficult it will be.  However, it would be yet another change in metrics like this.

**Comment by Gerg** [comment]
Hey @jochenehret,

Thank you for your PR. As Seth said, the results look great. 

We are curious why the metric is named `requests.outstanding.total`. This metric is a fixed version of the `requests.outstanding` metric, and the `.total` suffix could be misleading. What would you think about something like `requests.outstanding.gauge` or `requests.outstanding.enhanced`?

Thanks!
Greg & @sweinstein22

**Comment by zmb3** [comment]
I agree that the name is a bit misleading.

According to the naming practiced [endorsed by Prometheus](https://prometheus.io/docs/practices/naming/), the `total` suffix should be used for counters:

> should have a suffix describing the unit, in plural form. Note that an accumulating count has total as a suffix, in addition to the unit if applicable.

**Comment by jochenehret** [comment]
`requests.outstanding.gauge` sounds good. Or would something like `requests.outstanding.v2` make sense?

**Comment by Gerg** [comment]
We considered that, but we were worried that people might think it only applied to the v2 API.

**Comment by jochenehret** [comment]
Changed metric name to "requests.outstanding.gauge".

**Comment by stephanme** [comment]
Any chance to get PR #2087 merged?

The outstanding requests metric is interesting as scaling indicator but can't be used as long as it is broken.

**Comment by sethboyles** [comment]
Merged!

Not closing this issue yet until we complete documentation

**Comment by sethboyles** [comment]
We need to update these docs: 
https://docs.cloudfoundry.org/running/managing-cf/scaling-cloud-controller.html
https://docs.cloudfoundry.org/running/all_metrics.html

**Comment by sethboyles** [comment]
Closing as we have updated the relevant docs.
