### ISSUE TITLE
CC API V3 site redirections loose fragments

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cloud_controller_ng#1329]
## Issue

http://v3-apidocs.cloudfoundry.org/index.html#metadata redirects to http://v3-apidocs.cloudfoundry.org/version/3.69.0/index.html (i.e. without the fragment to the subsection)

## Context

As an API user, in order to add deep permalinks to the latest api version (e.g. in specs such as https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#cloud-foundry-context-object), I need the api website redirects to preserve fragments in the original url. See https://stackoverflow.com/a/2305927 for related http specifications .

## Steps to Reproduce

open in web browser http://v3-apidocs.cloudfoundry.org/index.html#metadata 

## Expected result

http://v3-apidocs.cloudfoundry.org/index.html#metadata redirects to http://v3-apidocs.cloudfoundry.org/version/3.69.0/index.html#metadata

## Current result

http://v3-apidocs.cloudfoundry.org/index.html#metadata redirects to http://v3-apidocs.cloudfoundry.org/version/3.69.0/index.html (i.e. without the fragment to the subsection)

**Comment by reid47** [comment]
Hi @gberche-orange, we have fixed this. As of yesterday, the URL hash is now preserved when redirecting. I'm going to close this, but feel free to reopen if you have more problems with it.

cc @selzoc

**Comment by gberche-orange** [comment]
great, thanks @reid47 and @selzoc !
