### ISSUE TITLE
Trying to delete a user provided service instance with a route_service_url returns 500 Internal Server Error

### ISSUE THREAD

**Issue by orhanco** [cloudfoundry/cloud_controller_ng#1337]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

I am a SpaceDeveloper and I provision a user provided service instance with a route service url.
If I try to delete the service instance before un-mapping the route then I get an HTTP/1.1 500 Internal Server Error:
{
  "description": "Database error",
  "error_code": "CF-DatabaseError",
  "code": 10011
}

## Context

I have had a test scenario I'm running to test the route service. I enhanced the scenario by adding some negative test cases and found out that error.

## Steps to Reproduce

1. Login to your space as SpaceDeveloper
2. Provision a user provided service instance with a route service url with a POST against /v2/user_provided_service_instances
3. Try to delete your ups via DELETE /v2/user_provided_service_instances/your_UPS_guid

## Expected result

I would expect to get an HTTP 400 Bad request with a better error description.

**Comment by tcdowney** [comment]
@orhanco, just noticed this issue and transferred it to the `cloud_controller_ng` repo where it should get some more visibility.

cc @williammartin @laurzca since this one is likely SAPI related.

**Comment by williammartin** [comment]
Thanks @tcdowney, we've pulled the tracker story across to our icebox.

**Comment by williammartin** [comment]
@orhanco Sorry, I am not able to reproduce this from the steps you've given. These are the steps I am following:

```
→ cf domains
Getting domains in org acceptance as space-developer...
name                         status   type   details
dawn-knave.sapi.cf-app.com   shared
```

```
→ cf routes
Getting routes for org acceptance / space dev as space-developer ...

space   host   domain                       port   path   type   apps   service
dev     r1     dawn-knave.sapi.cf-app.com
```

```
→ cf create-user-provided-service s1 -r https://example.com
Creating user provided service s1 in org acceptance / space dev as space-developer...
OK
```

```
→ cf bind-route-service dawn-knave.sapi.cf-app.com --hostname r1 s1
Binding route r1.dawn-knave.sapi.cf-app.com to service instance s1 in org acceptance / space dev as space-developer...
OK
```

```
→ cf delete-service s1

Really delete the service s1?> y
Deleting service s1 in org acceptance / space dev as space-developer...
FAILED
Server error, status code: 400, error code: 10006, message: Please delete the service_bindings, service_keys, and routes associations for your service_instances.
```

Now, you mentioned something about `unmapping` routes, but I'm not sure how that fits into the picture. Can you provide a more complete picture of the domains/routes/apps/services/mappings that you reproduced this with?

Thanks!

**Comment by orhanco** [comment]
seems like the issue has been fixed.
I'm closing the issue.
Thanks guys.

**Comment by williammartin** [comment]
The best kind of resolution. Thanks for the quick reply!
