### ISSUE TITLE
Tasks in pending state get start event

### ISSUE THREAD

**Issue by joyvuu-dave** [cloudfoundry/cloud_controller_ng#1365]
## Issue

The `v2/app_usage_events` API returns a start event for tasks in a pending state. If a client of cloud controller wishes to calculate the duration a task has been running, this results in an inaccurate answer. 

## Context

Normally, this isn't a problem, as typically tasks transition from the pending to running state quickly. However, in cases where a fast transition does not take place (typically an error), this means the runtime of a task as calculated by looking at the time of the start and stop events could be very off. Our system has sometimes had tasks stuck in a pending state for upwards of 90 days. 

## Steps to Reproduce
Create a task
<Somehow ensure that the task is still pending before the next step and not running yet>
curl `v2/app_usage_events` 

## Expected result
Should not return a TASK_STARTED event for the task.

## Current result
It is returning a TASK_STARTED event for the task

**Comment by sethboyles** [comment]
I believe this was fixed by https://github.com/cloudfoundry/cloud_controller_ng/pull/1459.  Please reopen if that is not the case.
