### ISSUE TITLE
Bad processes can get stuck in the Deployment train

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#1367]
Repro (uses the new cf zdt feature)
```
cf push dora -c bogus
cf push dora -c 'bundle exec rackup config.ru -p $PORT' --zdt
# This fails to get rid of the bogus dora web-process
cf push dora -c 'bundle exec rackup config.ru -p $PORT' --zdt
# Still fails to remove the bogus instance, and there will be downtime
```

If you're running something like `while : ; do curl dora.DOMAIN ; sleep 0.5 ; done` concurrently, you will see downtime because at some point the only running app is the bogus web process instance.

**Comment by tcdowney** [comment]
@ericpromislow I'm not familiar with the `--zdt` flag on `cf push`. Can you clarify what that is?

Is this `cf v3-zdt-push` on the V6 CLI, `cf push --strategy rolling` ([being introduced](https://www.pivotaltracker.com/story/show/165873203)) to the V7 CLI, or something else?

**Comment by ericpromislow** [comment]
Looks like it was a typo, and it was the `v3-zdt-push` command
