### ISSUE TITLE
Rolling deployments: erroneous command input persists in subsequent pushes

### ISSUE THREAD

**Issue by psparks123** [cloudfoundry/cloud_controller_ng#1377]
## Issue

We pushed a deliberately failing command:

`cf push dora -c 'bogus bogus' --strategy rolling`

When the first new instance crashed, we canceled the deployment and reissued a fixed command:

`cf push dora  --strategy rolling`

The new instance from this push is still failing, it looks like it's still using the `-c "bogus bogus"` option. 

Is this by design? It could potentially be misleading/counter-intuitive for customers. Is there a standard way of re-setting the -c option on subsequent pushes?

**Comment by sethboyles** [comment]
Hi @psparks123 !  Thanks for submitting an issue. 

If you run `cf push --help`, it states that the way to reset this is by passing null:

```
-c                           Startup command, set to null to reset to default start command
```

So I believe this is by design.  Something like `cf push dora -c null --strategy rolling` should do what you want.
