### ISSUE TITLE
UaaClient caches invalid tokens for service broker related workflows

### ISSUE THREAD

**Issue by georgi-lozev** [cloudfoundry/cloud_controller_ng#1382]
## Issue

Workflows related to service brokers fail with `500 - An unknown error occurred.`

The issues was result of the following discussion https://cloudfoundry.slack.com/archives/C07C04W4Q/p1561048345107100

## Context

When you have a service broker that includes a [dashboard_client](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#dashboard-client-object) information in its catalog the broker registration MAY fail with `500 - UnknownError` on the client side. If you have a look into the CC logs you can find `CF-InvalidToken` error.
```
{"timestamp":1561358310.079872,"message":"Started POST \"/v2/service_brokers\" for user: 3cbd84d7-1eab-4c92-b8ed-d40f242a0f03, ip: 193.57.20.15 with vcap-request-id: 2b269253-7980-4898-63e9-8b2970ea2f99::b716f7e0-6ccb-40c1-8163-08b24dc66b30 at 2019-06-24 06:38:30 UTC","log_level":"info","source":"cc.api","data":{"request_guid":"2b269253-7980-4898-63e9-8b2970ea2f
99::b716f7e0-6ccb-40c1-8163-08b24dc66b30"},"thread_id":47129415438980,"fiber_id":47129416899520,"process_id":9,"file":"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/cloud_controller_ng/middleware/request_logs.rb","lineno":12,"method":"call"}

{"timestamp":1561358310.2479775,"message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"error response\", \"error_code\"=>\"CF-InvalidToken\", \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/g
em_home/ruby/2.5.0/gems/cf-uaa-lib-3.14.3/lib/uaa/http.rb:123:in `json_parse_reply'\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/gem_home/ruby/2.5.0/gems/cf-uaa-lib-3.14.3/lib/uaa/http.rb:97:in `json_get'\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/gem_home/ruby/2.5.0/gems
/cf-uaa-lib-3.14.3/lib/uaa/scim.rb:261:in `get'\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/cloud_controller_ng/lib/cloud_controller/uaa/uaa_client.rb:32:in `block in get_clients'\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/cloud_controller_ng/lib/cloud_controller/uaa/uaa
_client.rb:30:in `map'\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/cloud_controller_ng/lib/cloud_controller/uaa/uaa_client.rb:30:in `get_clients'\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/cloud_controller_ng/lib/services/sso/uaa/uaa_client_manager.rb:14:in `get_clients'
\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/cloud_controller_ng/lib/services/sso/dashboard_client_manager.rb:94:in `fetch_clients_from_uaa'\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/cloud_controller_ng/lib/services/sso/dashboard_client_manager.rb:37:in `synchronize_cli
ents_with_catalog'\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/cloud_controller_ng/lib/services/service_brokers/service_broker_registration.rb:68:in `synchronize_dashboard_clients!'\", \"/var/vcap/data/packages/cloud_controller_ng/adca8e87a9d0822603620e2cda7e59e4dc6e594b/cloud_controller_ng/lib/services/service_broke
rs/service_broker_registration.rb:23:in `create'\"
...}
```

## Steps to Reproduce
1. Push a service broker that has [dashboard_client](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#dashboard-client-object) information in its catalog.
2.  Register/Deregister this service broker. 
  - F.e. using the cf CLI `cf create-service-broker`, `cf delete-service-broker `
  At this point everything should work as expected.
3. Re-set the [cc-service-dashboards](https://github.com/cloudfoundry/capi-release/blob/14f159bf0849e110eb16837a8dc5934877b633c8/jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb#L228) client secret to its old value. 
  - F.e. using the `uaac` CLI `uaac secret set cc-service-dashboards`
  This is not the only way we could achieve invalidating all old tokens, but it's relatively simple and real world, since a lot of people script their UAA clients provisioning/updates.
4. Try again to register the same broker. 
  - Now the registration should fail and CC should be in this weird state with a token that is not expired, but still invalid.
  - Keep in mind that we're using a bosh-lite env with a single CC API node, so if you try the steps on a real environment with multiple API nodes, the result may be slightly different depending where your requests are handled.

## Expected result

CC should handle invalid, but not expired tokens better. 
It looks like caching tokens was introduced with a relatively recent [CAPI release](https://github.com/cloudfoundry/cloud_controller_ng/commit/3720db44ed5883938ca3814c5e0064415c80d21e) and before there was not caching in place, thus the problem was not possible.

## Current result

Unable to register/deregister service brokers that work with dashboard_clients. 
It MAY potentially affect other workflows depending on where [get_clients](https://github.com/cloudfoundry/cloud_controller_ng/blob/1de8204421833fe3a8046b7b7b87165878972f03/lib/cloud_controller/uaa/uaa_client.rb#L29) method is used.
A workaround today is to restart the `cloud_controller_ng` process which will clear the caches, so it will fetch a new valid token.

## Possible Fix

It looks like another method [usernames_for_ids](https://github.com/cloudfoundry/cloud_controller_ng/blob/1de8204421833fe3a8046b7b7b87165878972f03/lib/cloud_controller/uaa/uaa_client.rb#L46) aims to resolve that issue, but it's not clear whether it actually does.
It's also worth checking for other methods that are part of this class which could potentially be affected from the same problem.

**Comment by tcdowney** [comment]
This was fixed in https://github.com/cloudfoundry/cloud_controller_ng/commit/a495ae14c34e4db2d779f440f9d4f721bd5ff706 which shipped in capi-release 1.83.0:

https://github.com/cloudfoundry/capi-release/releases/tag/1.83.0

Thanks for helping investigate!
