### ISSUE TITLE
Filtering service plans by service broker id results in CF-DatabaseError

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/cloud_controller_ng#1384]
## Issue

`/v2/service_plans?q=service_broker_guid:<guid>` fails with `CF-DatabaseError`.

## Context

cloud_controller_v2 version 2.136.0

## Steps to Reproduce

Run `cf curl /v2/service_plans?q=service_broker_guid:<guid>`.

## Expected result

List of service plans for a specific service broker.

## Current result

```
HTTP/1.1 500 Internal Server Error

{
   "description": "Database error",
   "error_code": "CF-DatabaseError",
   "code": 10011
}
```

## Root Cause

The following database query is executed...
```
SELECT count(*) AS "count" FROM "service_plans"
  LEFT JOIN "services" ON ("services"."id" = "service_plans"."service_id")
  LEFT JOIN "service_brokers" ON ("service_brokers"."id" = "services"."service_broker_id")
  WHERE ((("public" IS TRUE) OR ("id" IN (<long list of IDs>)))
    AND ("active" IS TRUE) AND ("service_brokers"."guid" = '<guid>'))
  LIMIT 1
```
... and fails with `PG::AmbiguousColumn: ERROR: column reference "id" is ambiguous`.

Changing the query in psql leads to another error: `column reference "active" is ambiguous`.

**Comment by blgm** [comment]
@philippthun, thank you for raising this issue.  We have managed to reproduce it, and are investigating the cause.

**Comment by williammartin** [comment]
Hi @philippthun this has been fixed in https://github.com/cloudfoundry/cloud_controller_ng/pull/1385 so it should be in the next Cloud Controller release.

You can @ssisil if this is something you want to us to release soon. Thanks!
