### ISSUE TITLE
Field `username` missing when getting `user_roles` with results-per-page > 100 

### ISSUE THREAD

**Issue by abiskop** [cloudfoundry/cloud_controller_ng#1428]
## Issue

When `cf curl`ing `/organizations/{guid}/user_roles` and `results-per-page` is >100, entities after the 100th are missing the `username` field.

## Context

We have an organization with 127 members. We fetch the org's members via `cf curl`, specifying `results-per-page=500` in order to return all members in one go. in the response, we get 127 entries in `resources` back. However, only the first 100 have the `username` field. The field is not present for the remaining entries.

## Steps to Reproduce

1. Create an org
2. Add more than 100 members
3. Use the CLI to login and perform `cf curl '/v2/organizations/{guid-of-the-org}/user_roles?results-per-page=110'`

## Expected result

110 entries are returned in `resources`, each with a `username` field.

## Current result

110 entries are returned in `resources`, out of which only 100 contain the `username` field; the field is missing for the remaining ones.
Example for one of those entries:

```
{
  "metadata": {
    "guid": "54ed86d9-ff0a-48c4-a827-ccc4642cd64a",
    "url": "/v2/users/54ed86d9-ff0a-48c4-a827-ccc4642cd64a",
    "created_at": "2019-09-04T13:59:04Z",
    "updated_at": "2019-09-04T13:59:04Z"
  },
  "entity": {
    "admin": false,
    "active": false,
    "default_space_guid": null,
    "organization_roles": [
      "org_user"
    ],
    "spaces_url": "/v2/users/54ed86d9-ff0a-48c4-a827-ccc4642cd64a/spaces",
    "organizations_url": "/v2/users/54ed86d9-ff0a-48c4-a827-ccc4642cd64a/organizations",
    "managed_organizations_url": "/v2/users/54ed86d9-ff0a-48c4-a827-ccc4642cd64a/managed_organizations",
    "billing_managed_organizations_url": "/v2/users/54ed86d9-ff0a-48c4-a827-ccc4642cd64a/billing_managed_organizations",
    "audited_organizations_url": "/v2/users/54ed86d9-ff0a-48c4-a827-ccc4642cd64a/audited_organizations",
    "managed_spaces_url": "/v2/users/54ed86d9-ff0a-48c4-a827-ccc4642cd64a/managed_spaces",
    "audited_spaces_url": "/v2/users/54ed86d9-ff0a-48c4-a827-ccc4642cd64a/audited_spaces"
  }
}
```

**Comment by sethboyles** [comment]
This is probably a bug in V3 as well.  I think we might have to supply the optional param `count` to UAA which defaults to 100: https://docs.cloudfoundry.org/api/uaa/version/74.17.0/index.html#list-3

**Comment by TobiasOetzel** [comment]
Hi @cwlbraa can you please remove the v2-only label?

i am able to reproduce this with 
```/v3/roles?organization_guids=<a guid>&page=1&per_page=300&include=user```
on an organization with more than 100 users (250 in our case).

**Comment by Gerg** [comment]
I believe this issue was address in #1574. I'm going to close this, but feel free to re-open this if you are still having trouble.

Thanks,
Greg

**Comment by weymanf** [comment]
We're going to lump this in with #1574 which is currently re-opened.
