### ISSUE TITLE
Fetching usage events after_guid when that guid has been pruned

### ISSUE THREAD

**Issue by lisamcho** [cloudfoundry/cloud_controller_ng#1429]
## Issue
As a usage service attempting to consume usage events and calculate durations that apps and services were running, we store the last fetched guid and then query the unfetched guids using the `after_guid` query parameter to the v2/app_usage_events and v2/service_usage_events endpoints.

When a CF deployment goes more than a month without pushing an app or creating a service event, then there are no new usage events.

This results in a BadQueryParameter error.

As a client, it's not clear what to do in this case, if we ignore the error and move on, then there's the risk that we missed events (because our app was down for some time and couldn't fetch events).

## Steps to Reproduce
cf curl v2/app_usage_events?after_guid=<pruned-event-guid>

## Expected result
We don't know what a good behavior would be in this case.

## Current result
This results in a BadQueryParameter error.

## Possible Fixes
1. The client (usage service) rescues and ignores the error and fetches the usage events with no query param. 
- Con: the badqueryparam error could be caused by something else on capi's side.
- Con: events can be missed if you fail to fetch events for >30 days. Currently this would result in an error, but it would be silently hidden with this fix, potentially resulting in corrupted data.

2. In Capi, when `after_guid` cannot be found, instead of returning BadQueryParameter error, return the first page of data as if the query param were not passed. 
- Con: events can be missed if you fail to fetch events for >30 days. Currently this would result in an error, but it would be silently hidden with this fix, potentially resulting in corrupted data.
- Con: you could query after_guid=<guid-with-typo> and it would return unexpected results.

3. Capi changes and always keeps at least one usage event for apps and services, even if it is older than the `cutoff_age_in_days`.
- Con: `cutoff_age_in_days` bosh properties are more complicated
^^ We like this option best. CC @jpalermo 

https://github.com/cloudfoundry/capi-release/blob/6059f17f7215919f0f9a23ffebea490002ab57e9/jobs/cloud_controller_clock/spec#L96-L101

4. Other ideas?

**Comment by sethboyles** [comment]
Closing as https://github.com/cloudfoundry/cloud_controller_ng/pull/1430 is in 1.87
