### ISSUE TITLE
Getting a 500 when assigning a new droplet after cancelling a deployment

### ISSUE THREAD

**Issue by ewrenn8** [cloudfoundry/cloud_controller_ng#1432]
## Issue

I am unable to set the current droplet for my app after cancelling a deployment.

## Steps to Reproduce

1. push an app with `cf push dora`
2. scale the app to 10 instances: `cf scale dora -i 10`
3. start a deployment that restarts the app: `cf curl -X POST /v3/deployments -d '{"relationships": {"app": {"data": {"guid": "'"$(cf app dora --guid)"'"}}}}'`
4. cancel the deployment and immediately start a new depoyment: `cf cancel-deployment dora`
5. try and push dora again `cf push dora`

## Expected result

A successful follow up push

## Current result

A 500

```
{\"errors\"=>[{\"title\"=>\"UnknownEr
ror\", \"detail\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"detail\"=>
\"undefined method `health_check_timeout' for nil:NilClass\", \"title\"=>\"CF-health_check_timeout\",
 \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/e938b29c6a2d46357cbceeed131bea2c404eee
2b/cloud_controller_ng/app/models/runtime/deployment_model.rb:67:in `failing?'\", \"/var/vcap/data/pa
ckages/cloud_controller_ng/e938b29c6a2d46357cbceeed131bea2c404eee2b/cloud_controller_ng/app/models/ru
ntime/app_model.rb:117:in `any?'\", \"/var/vcap/data/packages/cloud_controller_ng/e938b29c6a2d46357cb
ceeed131bea2c404eee2b/cloud_controller_ng/app/models/runtime/app_model.rb:117:in `failing?'\", \"/var
/vcap/data/packages/cloud_controller_ng/e938b29c6a2d46357cbceeed131bea2c404eee2b/cloud_controller_ng/
app/controllers/v3/apps_controller.rb:258:in `assign_current_droplet'\"...
```

Cancelling a deployment leaves deployments with `nil` as their `deploying_web_process`:
```
app.deployments.map(&:deploying_web_process)
=> [nil,
 #<VCAP::CloudController::ProcessModel @values={...}>]
```
When [assigning a new droplet](https://github.com/cloudfoundry/cloud_controller_ng/blob/b819ac602950ee834b71cebffa198d15e8c28549/app/controllers/v3/apps_controller.rb#L258) we check if the app [is failing](https://github.com/cloudfoundry/cloud_controller_ng/blob/b819ac602950ee834b71cebffa198d15e8c28549/app/models/runtime/app_model.rb#L116-L118) which inspects the deployment's [`deploying_web_process`'s health check](https://github.com/cloudfoundry/cloud_controller_ng/blob/b819ac602950ee834b71cebffa198d15e8c28549/app/models/runtime/deployment_model.rb#L67). Because the process is nil we get a 500.

**Comment by sethboyles** [comment]
Closing as the fix (https://github.com/cloudfoundry/cloud_controller_ng/commit/3cd2b9cd000ba7782634924601b12474c0c827ec) was in 1.87
