### ISSUE TITLE
Inefficient SQL query is causing API latency up to 60 sec

### ISSUE THREAD

**Issue by s-matyukevich** [cloudfoundry/cloud_controller_ng#1436]
## Issue

When processing [this](https://apidocs.cloudfoundry.org/11.2.0/spaces/retrieving_the_roles_of_all_users_in_the_space.html) API call, Cloud Controller uses eager loading to populate `spaces` `managed_spaces` and `audited_spaces` associated collections (this happens [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/65a75e6c97f49756df96e437e253f033415b2db1/app/fetchers/space_user_roles_fetcher.rb#L7)) This results in an SQL query similar to the following one

```
SELECT `spaces`.*, `spaces_auditors`.`user_id` AS `x_foreign_key_x` FROM `spaces` INNER JOIN `spaces_auditors` ON (`spaces_auditors`.`space_id` = `spaces`.`id`) WHERE (`spaces_auditors`.`user_id` IN (10606, 10612, 10615, 10618, 10621, 10624, 10627, 10630, 10633, 11005, 11011, 11317, 11320, 11323, 11326, 11329, 11332, 11452, 11494, 12067, 12172, 12184, 12373, 12382, 12400, 12820, 13000, 13129, 13132, 13537))
```

This query loads a lot of unnecessary information (We are populating the whole `user.audited_spaces` collection for each user, but for this particular API request we are only interested in answering a question whether a user is `space_auditor`, `space_developer` or `space_manager` for a single space). I made this conclusion based on the code that process the above query results [link](https://github.com/cloudfoundry/cloud_controller_ng/blob/65a75e6c97f49756df96e437e253f033415b2db1/app/collection_transformers/usernames_and_roles_populator.rb#L49)

## Context

I work in an organization that have a large PCF installation.  We have 10 Cloud Controllers and recently all of them started to process requests very slowly. (We observed latency up to 60 sec for some API requests) We are also seeing CPU spikes up to 100% on each cloud controller instance all the time.  Though, the overall load for a single cloud controller isn't very high (3-4 req/sec)

I run CC under [ruby-prof](https://github.com/ruby-prof/ruby-prof) and got some interesting results: it happens that method `Sequel::Database#synchronize` took on average about `60%` of the total execution time for each thread. Another interesting thing was that `Mysql2::Result#each` was the one that consumes the most CPU cycles.   From this I made the following conclusion: CC is doing some heavy mysql query processing, and in the meantime a lot of threads are waiting for available mysql connections from the connection pool, which is causing high latency.

Next I run some tcpdumps and identified what queries resulted in large result sets. I found a particular query that was much large that all other and that was executed very often (this is the same query that I copied above)

```
SELECT `spaces`.*, `spaces_auditors`.`user_id` AS `x_foreign_key_x` FROM `spaces` INNER JOIN `spaces_auditors` ON (`spaces_auditors`.`space_id` = `spaces`.`id`) WHERE (`spaces_auditors`.`user_id` IN (3859, 3862, 3865, 3898, 3901, 3904, 3907, 3910, 3913, 3916, 3994, 4450, 4456, 4462, 4468, 4471, 4639, 4708, 4711, 4714, 4717, 4729, 4816, 4822, 4957, 4963, 5110, 5119, 5122, 5701, 5704, 5707, 5764, 5767, 5779, 5830, 5899, 5953, 5959, 6571, 7129, 7435, 7792, 8311, 8401, 8503, 8590, 8602, 8689, 8692))
```

This particular query returns **51797** rows (this is because we have 256188 records in the `space_auditors` table) In addition this query was executed very often.

I searched through the CC source code and found the origin of this query [link](https://github.com/cloudfoundry/cloud_controller_ng/blob/65a75e6c97f49756df96e437e253f033415b2db1/app/fetchers/space_user_roles_fetcher.rb#L7) Here we are using [Sequel eager loading](https://sequel.jeremyevans.net/rdoc/classes/Sequel/Model/Associations/DatasetMethods.html#method-i-eager) to load `audited_spaces ` collection which results in `spaces_auditors.user_id IN ..` sql statement.
I also found the code that process the result of this query [link](https://github.com/cloudfoundry/cloud_controller_ng/blob/65a75e6c97f49756df96e437e253f033415b2db1/app/collection_transformers/usernames_and_roles_populator.rb#L49) From this code we can see that we don't need the whole `user.audited_spaces` collection - we only need to find out whether a user is a space auditor for a particular space, which can be done in SQL without loading the whole collection.

Finally I made an experiment: I modified the source code to look like this 

```
module VCAP::CloudController
  class SpaceUserRolesFetcher
    def fetch(space)
      space.developers_dataset.
        union(space.managers_dataset, from_self: false).
        union(space.auditors_dataset, from_self: false)
    end
  end
end
```

Here I removed `eager` method call from the query.

```
    def build_space_roles(user, space_id)
      return ['space_developer']
    end
```

Here I just hardcode the role, instead of getting if from the associated collections.

After I run this for a while on one of our cloud controllers CPU load drops from 100% to 3-4% and I didn't see a single high latency request.

## Steps to Reproduce

Create a large number of users and spaces, assign all users to all spaces as space auditors and execute `GET /v2/spaces/:guid/user_roles` API call for any space. The call should result in a huge SQL query similar to the one mentioned above.

## Expected result

The query should not load any unnecessary information (we should not populate `user. audited_spaces ` collection for each user)

## Current result

A huge SQL query is generated.

## Possible Fix

Fix SQL statement to use joins of subqueries to get user roles.

**Comment by selzoc** [comment]
Hi @s-matyukevich !

Thank you for such a detailed bug report!  We're taking a look at this now.

Your friendly CAPI team

**Comment by s-matyukevich** [comment]
Hi @cwlbraa, thanks for looking into that.

The first thing I would mention is that if you have a query that returns ~51797 rows, it is an issue by itself that in my opinion is worth fixing.

Now to your questions:

1. Here are some numbers:
```
spaces 1682
spaces_auditors 253613
spaces_developers 47870
spaces_managers 47
```
2. We are using internal mysql that comes with PCF 2.4.13
3. No we have perfomance issues without ruby-prof as well. When I did my experiment and modified ruby code I didn't run CC under ruby-prof
4. I think we have a couple of such services. The first one is prometheus which execute expensive `/v2/spaces/<guid>/summary` for each 1682 space every couple of minutes. The second one is Apps Manager (at least all requests for `/v2/spaces/:guid/user_roles` always come from browser) and all our developers uses Apps Manager a lot. Each of our CC receives a couple of `/v2/spaces/../user_roles` requests every second .(this is probably the most common request that I saw in the access log. When I did an experiment I had 739 requests in total and 103 `/v2/spaces/../user_roles`)

If you want to see both high latency and high CPU utilization I think you can try to make a simple load test. Here is my version

```
printf '%s\n' {1..400} | xargs -I % -P 10 cf curl /v2/spaces/e52c6716-b8c8-4aa2-ac61-4b0938af798e/user_roles
```

**Comment by cwlbraa** [comment]
> The first thing I would mention is that if you have a query that returns ~51797 rows, it is an issue by itself that in my opinion is worth fixing.

100% agree and we already have a fix for that locally here, I'm hoping to make sure we've nailed down the same issue as your slow queries.

Your info on point 4) gives us a good explanation as to the discrepancies in our numbers.

**Comment by cwlbraa** [comment]
we think we've fixed this, should be in the next release.
