### ISSUE TITLE
Wiki page on creating an app using v3 cc api has incorrect instructions for route mapping.

### ISSUE THREAD

**Issue by margocrawf** [cloudfoundry/cloud_controller_ng#1437]
## Issue

Wiki page on creating an app using v3 cc api has incorrect instructions for route mapping, possibly hitting an outdated endpoint.

## Context

In step 11 of [this](https://github.com/cloudfoundry/cloud_controller_ng/wiki/How-to-Create-an-App-Using-V3-of-the-CC-API) doc, it says to run:
 ```
ROUTE_MAPPING=$(printf '{"relationships": {"route": {"guid": "%s"}, "app": {"guid": "%s"} } }' "$ROUTE_GUID" "$APP_GUID")
cf curl /v3/route_mappings -X POST -d "$ROUTE_MAPPING"
```
This code returns an error. Also, the link to the docs is set to this dead link: http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html#create-a-route-mapping

## Possible Fix
We think step 11's code should be replaced with:
```
DESTINATION=$(printf '{"destinations" : [ {"app": {"guid": "%s"}  }  ]  } ' "$APP_GUID")
cf curl /v3/routes/$ROUTE_GUID/destinations -X POST -d "$DESTINATION"
```
and the doc link should be replaced with http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html#insert-destinations-for-a-route

**Comment by cwlbraa** [comment]
thanks! i think we fixed it.
