### ISSUE TITLE
v3-apply-manifest fails with unknown error when mapping apps.internal route

### ISSUE THREAD

**Issue by xyloman** [cloudfoundry/cloud_controller_ng#1445]
## Issue

Attempting to leverage v3-apply-manifest with a manifest that leverages an apps.internal route results in the following error in the terminal:

```
An unknown error occurred.
FAILED
```

## Context

Attempting to move applications over that leverage apps.internal to a new pipeline that leverage v3-apply-manifest cf cli command which lead to this discovery.

## Steps to Reproduce

manifest.yml
```
applications:
- name: test-app
  routes:
  - route: test-app.apps.internal
```

`cf v3-apply-manifest -f manifest.yml`

## Expected result

Should associate a route mapping to the application similar to `cf map-route`

## Current result

Results in the following error in the cloud controller logs:

```
<14>1 2019-09-16T20:31:44.767081Z 10.156.86.17 cloud_controller_worker rs2 - [instance@47450 director="" deployment="cf-52b8aeeeda6f562e05f9" group="cloud_controller_worker" az="us-west-2a" id="b9c6bfd1-00bb-4b0f-b5ad-8ce3bbc36b30"] {"timestamp":1568665904.582452,"message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"\\\"internal_route_vip_range\\\" is not a valid config key\", \"error_code\"=>\"CF-InvalidConfigPath\", \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/287d1000e3b52cfeeb10dda9c48e36bc1f9b4b10/cloud_controller_ng/lib/cloud_controller/config.rb:138:in `invalid_config_path!'\", \"/var/vcap/data/packages/cloud_controller_ng/287d1000e3b52cfeeb10dda9c48e36bc1f9b4b10/cloud_controller_ng/lib/cloud_controller/config.rb:130:in `block in valid_config_path?'\", \"/var/vcap/data/packages/cloud_controller_ng/287d1000e3b52cfeeb10dda9c48e36bc1f9b4b10/cloud_controller_ng/lib/cloud_controller/config.rb:126:in `each'\", \"/var/vcap/data/packages/cloud_controller_ng/287d1000e3b52cfeeb10dda9c48e36bc1f9b4b10/cloud_controller_ng/lib/cloud_controller/
```

## Possible Fix

Link to the conversation thread with the CAPI v3-acceleration team: https://cloudfoundry.slack.com/archives/CCRLX88DD/p1568666397020400

**Comment by cwlbraa** [comment]
This looks like a bug where the workers don't have as much config as the api job. Should be very easy to fix.

**Comment by xyloman** [comment]
@cwlbraa do you know what release a fix for this might be available?

**Comment by cwlbraa** [comment]
nope, but the story linked above is at the top of our backlog now. you can see that by clicking the down-to-the-left "expand" arrow at the top right of the story description. According to tracker it'll be in 1.87.0, but I'm not sure if that release will get pushed out early or not.

**Comment by reneighbor** [comment]
fixed here: https://github.com/cloudfoundry/capi-release/commit/3e12343aeb351416f360d4579bc6dd9eb247c768
