### ISSUE TITLE
Include app_guid in service_instance response 

### ISSUE THREAD

**Issue by Diwahars** [cloudfoundry/cloud_controller_ng#1448]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

service are binded to app and there is no easy way to get to know what service is bind to app in v3 API

## Context

Service_instance are binded to an app, so it would be great to have the app guid in API response

**Comment by cwlbraa** [comment]
Hi! I believe you're looking for https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#service-bindings. Service Instances are space-bound, but it's service bindings that describe the connection between service instances and apps.
