### ISSUE TITLE
restart-app-instance won't be recorded in `cf events" ?

### ISSUE THREAD

**Issue by cdlliuy** [cloudfoundry/cloud_controller_ng#1453]
On cf version ` "build": "v11.2.0",`,   I executed `cf restart-app-instance <app> <instance-number>` cmd,   the application instance was restarted as expected, but I can't find the audit log for this action in `cf events`

```
>>>cf restart-app-instance asmon 0
Restarting instance 0 of application asmon as xxxx
OK

>>> cf app asmon
Showing health and status for app asmon in xxxxx

name:              asmon
....

type:           web
instances:      1/1
memory usage:   1024M
     state     since                  cpu      memory         disk           details
#0   running   2019-09-30T05:28:07Z   162.8%   170.1M of 1G   259.4M of 1G

>>> cf events asmon
Getting events for app asmon in xxxx

time                          event                      actor                description
2019-09-25T10:13:44.00+0800   audit.app.ssh-authorized   xxxx   index: 0
....
```
I expected a `restart` record on  2019-09-30T05:xx:xxZ in `cf events` output.

**Comment by cwlbraa** [comment]
restarting an app instance is not the same as restarting an app. we don't have an audit event for restarting app instances and there's currently no plan to introduce one.
