### ISSUE TITLE
Default domain for organization 

### ISSUE THREAD

**Issue by boyan-velinov** [cloudfoundry/cloud_controller_ng#1454]
Hello,

I have found a proposal for default domain endpoint for v3:
https://docs.google.com/document/d/1HbJU3zYwiMVveIh_I4rJFDf-1zd9DxUiwRm9FsaWe_s/edit#heading=h.z0mpx7u4lmtz

Than I tried to call the endpoint and I received the expected result:
cf curl /v3/organizations/<xxx>/domains/default

That is great!

However, this is not documented here:
https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#list-domains-for-an-organization

Could you tell why this is not documented?
Option A: It is not official API
Option B: It is a gap in the documentation

Best Regards,
Boyan

**Comment by cwlbraa** [comment]
https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#get-default-domain

**Comment by boyan-velinov** [comment]
Thanks for pointing out the proper place
