### ISSUE TITLE
v3-apply-manifest fails with unknown error when mapping tcp routes

### ISSUE THREAD

**Issue by xyloman** [cloudfoundry/cloud_controller_ng#1460]
## Issue

Attempting to leverage v3-apply-manifest with a manifest with a tcp route results in picking the first port in the router group each time. 

## Context

Attempting to move applications over that leverage tcp routes to a new pipeline that leverage v3-apply-manifest cf cli command which lead to this discovery.

## Steps to Reproduce

manifest.yml
```
applications:
- name: test-app
  routes:
  - route: tcp.example.com:10073
```

`cf v3-apply-manifest -f manifest.yml`

This would result in mapping route to tcp.example.com:10063 instead of 10073 it also would result in collisions if an app in a different space already was using that route.

## Expected result

Should associate a route mapping to the application similar to `cf map-route` which still works as expected as well as the original `cf push`.

## Possible Fix

Might be similar to this issue: https://github.com/cloudfoundry/cloud_controller_ng/issues/1445

**Comment by cwlbraa** [comment]
So the problem here is that v3-apply-manifest seems to ignore the port? (10073 in your example?)

**Comment by cwlbraa** [comment]
@ssisil @ankitjain1988 this seems like a good, straightforward bug to prioritize.

**Comment by cwlbraa** [comment]
I'm not entirely sure the bug I fixed is the bug you were describing, so please feel free to reopen with more details if you test with the next release and still have the same problem!
