### ISSUE TITLE
Updating destinations for a route fails when using Eirini with CF-RunnerError

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cloud_controller_ng#1469]
## Issue

I tried using the [Replace All Destinations for a Route](https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#replace-all-destinations-for-a-route) endpoint on a Cloud Foundry that was using kubernetes (GKE) + Eirini as its container runtime. The destination seems to have been created correctly, but updating the LRP failed with a `CF-RunnerError`. I had to run `cf restart` to get the change to apply.

## Context
I encountered this in a dev environment that was running the following versions:
* `1.86.0` of capi-release
* `0.0.19` of eirini

## Steps to Reproduce

1. Push an app (I happened to be pushing a multi-process dora with a "worker" process listening on port 9090)
2. Create a route
```
cf create-route s -n dora-worker eirini-dev-1.routing.cf-app.com
```

3.  Add a destination for the worker process
```
cf curl -X PATCH /v3/routes/<ROUTE-GUID>/destinations -d '{
    "destinations": [
      {
        "app": {
          "guid": "<APP-GUID>",
          "process": {
            "type": "worker"
          }
        },
        "port": 9090,
        "weight": 100
      }
    ]
}'
```

## Expected result

The command does not fail.

## Current result

```
{
   "errors": [
      {
         "detail": "Runner error: failed to update: failed to get statefulset: statefulset not found",
         "title": "CF-RunnerError",
         "code": 170016
      }
   ]
}
```

Route destinations are updated in ccdb and can be applied by running `cf restart` on the app.

## Logs

[cc-stacktrace.txt](https://github.com/cloudfoundry/cloud_controller_ng/files/3713970/cc-stacktrace.txt)

## Possible Fix

Not sure, but I've seen similar errors when running the rolling app deployment commands when using Eirini. We're working on enhancing how routing works for CF on k8s (see https://github.com/cloudfoundry-incubator/eirini/issues/72) so this issue specifically is probably not that big of a deal, but there may be something underlying here around the concept of "updating an LRP" not working correctly.

cc @ndhanushkodi @rosenhouse

**Comment by cwlbraa** [comment]
@tcdowney so much has happened since this was reported, I imagine this is no longer an issue. Please reopen this if it still happens in networking load tests.
