### ISSUE TITLE
Add ability to include domains when listing routes

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cloud_controller_ng#1470]
## Issue

Currently to get the raw domain name for a route and whether or not it is `internal` requires a separate call to [/v3/domains/:guid](https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#get-a-domain). When listing all of the routes in a CF this ends up being a lot of API calls. It would be nice if we could `include` all of the domains referenced in `/v3/routes`.

This is similar in spirit to https://github.com/cloudfoundry/cloud_controller_ng/issues/1449. 

## Context

We're working on building a CC Route Syncer for CF on Kubernetes (see: https://github.com/cloudfoundry/cf-k8s-networking) that periodically polls all of the routes on Cloud Controller and creates Route CRs for them in the k8s API (see [this doc](https://docs.google.com/document/d/1EYRBVuQedU1r0zexgi8oMSOEFgaMNzM8JWBje3XuweU/edit#) for the proposed CRD). Since we're listing all routes this means, worst-case, we will be making 1 domain request for every route.

We need the domain and not just the `url` field because we want to construct FQDNs for each route without the path. We _could_ parse this out of the `url` field, but that feels cumbersome. We also will need to know whether or not the domain is `internal`, so we'd have to fetch the domains anyway for that.

## Possible Fix

Add an [include](https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#include) for domain to `/v3/routes`.

E.g.
```
cf curl /v3/routes?include=domain
```

**Comment by tcdowney** [comment]
I'm working on this during my flex time cause I miss writing Cloud Controller code. WIP is on the following branch and I plan to PR it eventually if that's ok: https://github.com/cloudfoundry/cloud_controller_ng/tree/issues/1470-include-domain-routes

**Comment by sethboyles** [comment]
@tcdowney can i close this now that https://github.com/cloudfoundry/cloud_controller_ng/pull/1503 is merged?

**Comment by sethboyles** [comment]
Closing. Feel free to reopen if this is still unresolved

**Comment by tcdowney** [comment]
Thanks!
