### ISSUE TITLE
Missing API endpoint for user_roles in V3

### ISSUE THREAD

**Issue by enchobelezirev** [cloudfoundry/cloud_controller_ng#1485]
#1064  Issue

With the current API V3 there is no clear possibility to retrieve a specific users by their roles. For instance, I could not find any way to get all the users with role 'SpaceDeveloper' in organization/space. There is implementation in the API V2 which is very useful  in some scenarios https://apidocs.cloudfoundry.org/12.5.0/spaces/list_all_developers_for_the_space.html

## Context

Retrieve users by their roles in organization/space.

## Expected result

A way to retrieve specific user by roles like in API V2.

## Current result

API V3 does not define a way to retrieve the users by roles. For instance, I would like to get the users in a given space which are with role 'SpaceDeveloper'.

**Comment by cwlbraa** [comment]
hello, the VAT team is working on this right now! you can find out more via the story:

https://www.pivotaltracker.com/story/show/168117402

for broader info and links to the other stories, check out this epic:

https://www.pivotaltracker.com/epic/show/4243301
