### ISSUE TITLE
/v3/routes with space_guids, organization_guids, or domain_guids 500s

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#1497]
The route_list_fetcher isn't correctly combining label_selector queries with the above three others.  When the pagination presenter tries to evaluate the dataset, it gets an error like:

```
Sequel::DatabaseError Exception: PG::UndefinedColumn: ERROR:  column routes.space does not exist
LINE 1: ...ute-in-other-org-guid', 'guid-1', 'guid-2')) AND ("routes"."...
```

where `dataset` looks like this:
```
(byebug) dataset
#<Sequel::Postgres::Dataset: "SELECT \"routes\".* FROM \"routes\" WHERE ((\"routes\".\"guid\" IN ('route-in-org-guid', 'route-in-other-org-guid', 'guid-1', 'guid-2')) AND (\"routes\".\"space\" IN (SELECT * FROM \"spaces\" WHERE (\"guid\" IN ('1326135d-3e40-48fb-b9c7-3f021d682867')))) AND (\"routes\".\"guid\" IN (SELECT \"resource_guid\" FROM \"route_labels\" WHERE ((\"key_prefix\" IS NULL) AND (\"key_name\" = 'animal') AND (\"value\" IN ('dog'))))))">
(byebug) dataset.all
```

## Context

This blocks the CLI implementation of `cf routes --labels SELECTOR`

## Steps to Reproduce
Run this:
```
cf curl /v3/routes?space_guids=3&label_selector=4
```

Same for org guids and domain guids

## Expected result
Some good JSON

## Current result
```
{
   "errors": [
      {
         "title": "UnknownError",
         "detail": "An unknown error occurred.",
         "code": 10001
      }
   ]
}
```

Part of the problem might be that routes don't have a `space_guid` field, they have `space_id` fields, so the fetcher might need to map `message.space_guids` to a set of IDs

**Comment by cwlbraa** [comment]
https://github.com/cloudfoundry/cloud_controller_ng/pull/1502

another route?

**Comment by cwlbraa** [comment]
fixed in https://www.pivotaltracker.com/story/show/170110304
