### ISSUE TITLE
Error granting role to a new UAA user (V3)

### ISSUE THREAD

**Issue by acrmp** [cloudfoundry/cloud_controller_ng#1506]
## Issue

We are unable to assign a role to a user unless that user exists already in the CAPI database.

## Context

We've recently seen a failure in the CLI team V7 pipeline related to integration tests that use the `/v3/roles` endpoint. We saw the failure after recreating a test foundation.

## Steps to Reproduce

```
$ cf --version
cf version 7.0.0-beta.28+53db7f0ab.2019-11-29
```
- Deploy a fresh bosh-lite with cf-deployment v12.14.0 deployed
- Deploy [CAPI 1.8.9.0-rc.51](https://s3.amazonaws.com/capi-releases/capi-1.89.0-rc.51-9f62a8cbde0a407d12a71c6cbb546bdbe50967de-350818b51d591bc07d68b860f2a27a9597da1f7c.tgz)
- Login to the UAA with UAAC and add a user:

```
$ uaac user add --emails fred@example.com fred@example.com
```

- Then login to the foundation as admin and attempt to assign a role to the new user:

```
$ cf login -u admin

$ cf set-org-role fred@example.com system OrgManager
Assigning role OrgManager to user fred@example.com in org system as admin...
Invalid user. Ensure that the user exists and you have access to it.
FAILED
```

## Expected result

I expected the new user to be assigned the org role.

## Current result

It errors with `Invalid user. Ensure that the user exists and you have access to it.`.

With `CF_TRACE` enabled we see the following:

```
REQUEST: [2019-11-29T15:23:50-08:00]
POST /v3/roles HTTP/1.1
Host: api.example.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/7.0.0-beta.28+53db7f0ab.2019-11-29 (go1.12.12; amd64 linux)
{
  "relationships": {
    "organization": {
      "data": {
        "guid": "9d90d8cc-8a30-4f3f-9685-25a0c1c3cdde"
      }
    },
    "user": {
      "data": {
        "origin": "uaa",
        "username": "fred@example.com"
      }
    }
  },
  "type": "organization_manager"
}


RESPONSE: [2019-11-29T15:23:50-08:00]
HTTP/1.1 422 Unprocessable Entity
Content-Length: 182
Content-Type: application/json; charset=utf-8
Date: Fri, 29 Nov 2019 23:23:50 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.153440
X-Vcap-Request-Id: 60b99396-b152-4be0-4c9e-38f2f023022c::2bd084dd-108d-4865-8247-0c03f6c1acd8
X-Xss-Protection: 1; mode=block
{
  "errors": [
    {
      "code": 10008,
      "detail": "Invalid user. Ensure that the user exists and you have access to it.",
      "title": "CF-UnprocessableEntity"
    }
  ]
}
```

We can force the user to be created in the CAPI database by logging in as that user and making a request

```
$ cf login -u fred@example.com
$ cf orgs
$ cf logout
```

When we then log back in as admin and assign the role it succeeds:

```
$ cf login -u admin
$ cf set-org-role fred@example.com system OrgManager
Assigning role OrgManager to user fred@example.com in org system as admin...
OK
```

## Possible Fix

CAPI could check for the existence of the user in the UAA and create it in the local database if it does not exist. We think that v2 always goes back to the UAA currently.

Andrew & @ericpromislow

**Comment by reid47** [comment]
Thanks for filing this. This was behavior that we intentionally omitted at first in our implementation of `POST /v3/roles`, but we realize that it was a workflow that was supported in V2, so we are working to support it in V3.

Here's a story to track this feature:
https://www.pivotaltracker.com/story/show/170061485

And here's a recent commit that hopefully addresses this problem:
https://github.com/cloudfoundry/cloud_controller_ng/commit/aa15abc9382143a7493b08c076757fcc51185d35
