### ISSUE TITLE
CAPI Docs referring to a not supported filter for apps `state`

### ISSUE THREAD

**Issue by vchrisb** [cloudfoundry/cloud_controller_ng#1547]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

The Page https://v3-apidocs.cloudfoundry.org/version/3.79.0/index.html#filters does show the example `GET /v3/apps?names=the_name&state=STARTED` how to use filters to filter on only started apps. The filter `state` is though not supported (yet?). 
The idocumented filters in `list apps` do not list the `state` filter: https://v3-apidocs.cloudfoundry.org/version/3.79.0/index.html#list-apps

**Comment by sethboyles** [comment]
Thanks for the issue!  Will be updated with https://www.pivotaltracker.com/story/show/170844278

**Comment by sethboyles** [comment]
this has been changed in the most recent release: https://v3-apidocs.cloudfoundry.org/version/3.80.0/#filters
