### ISSUE TITLE
Starting an app with a lot of env variables results in CF-DatabaseError

### ISSUE THREAD

**Issue by FloThinksPi** [cloudfoundry/cloud_controller_ng#1555]
## Issue

Starting an app with a lot of env variables results in CF-DatabaseError.

CC 2.145.0
CLI 6.49.0+d0dfa93bb.2020-01-07

## Context
A customer pushes an app and it fails with a database error. I could narrow it down to the DB Table but did not find how it is created or why it is limited to the length it currently has.
When there are many env variables or they are quite big (certs and stuff) it excedes the db varchar length limit and the sql query fails. This results in the user having a strange error message.
As the variables are encrypted to one varchar it can be quite easy having 16k characters or more.

The DB Table shows 16000 chars is the max at least for postgresql.
```
                                                 Table "public.revisions"
             Column              |            Type             | Collation | Nullable |                Default
---------------------------------+-----------------------------+-----------+----------+---------------------------------------
 id                              | integer                     |           | not null | nextval('revisions_id_seq'::regclass)
 guid                            | text                        |           | not null |
 created_at                      | timestamp without time zone |           | not null | now()
 updated_at                      | timestamp without time zone |           |          |
 app_guid                        | character varying(255)      |           |          |
 version                         | integer                     |           |          | 1
 droplet_guid                    | character varying(255)      |           |          |
 encrypted_environment_variables | character varying(16000)    |           |          |
 salt                            | character varying(255)      |           |          |
 encryption_key_label            | character varying(255)      |           |          |
 encryption_iterations           | integer                     |           | not null | 2048
 description                     | text                        |           | not null | 'N/A'::text
Indexes:
    "revisions_pkey" PRIMARY KEY, btree (id)
    "revisions_guid_index" UNIQUE, btree (guid)
    "fk_revision_app_guid_index" btree (app_guid)
    "revisions_created_at_index" btree (created_at)
    "revisions_updated_at_index" btree (updated_at)
Foreign-key constraints:
    "fk_revision_app_guid" FOREIGN KEY (app_guid) REFERENCES apps(guid)
Referenced by:
    TABLE "revision_annotations" CONSTRAINT "fk_revision_annotations_resource_guid" FOREIGN KEY (resource_guid) REFERENCES revisions(guid)
    TABLE "revision_labels" CONSTRAINT "fk_revision_labels_resource_guid" FOREIGN KEY (resource_guid) REFERENCES revisions(guid)
    TABLE "revision_sidecars" CONSTRAINT "fk_sidecar_revision_guid" FOREIGN KEY (revision_guid) REFERENCES revisions(guid)
    TABLE "revision_process_commands" CONSTRAINT "rev_commands_revision_guid_fkey" FOREIGN KEY (revision_guid) REFERENCES revisions(guid)
```

## Steps to Reproduce

1. Push a cf app
2. Add a huge env variable (20000 chars) to manifest (cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 20000 | head -n 1)
3. Push the app now again but with --no-start
4. cf start it, see it fail with a db error.

Interestingly pushing it normally does not output a db error however the app does not start at all and the push hangs.

## Expected result

App starts

## Current result

Client sees following error:
```
cf start test-app
Starting app test-app in org Test / space bugtest as someuser...Staging app and tracing logs...
Unexpected Response
Response code: 500
CC code:       0
CC error code:
Request ID:    blabla
Description:   {
  "description": "Database error",
  "error_code": "CF-DatabaseError",
  "code": 10011
}
```
In the CloudController logs once can see this(if db logging is on):
```
{"timestamp": 123,"message":"PG::StringDataRightTruncation: ERROR: value too long for type character varying(16000): INSERT INTO \"revisions\" (\"app_guid\", \"version\", \"droplet_guid\", \"salt\", \"encryption_key_label\", \"encryption_iterations\", \"encrypted_environment_variables\", \"description\", \"created_at\", \"updated_at\", \"guid\") VALUES (.....)"}
```

## Possible Fix

Increase DB field to an abitary higher value.
Return an exception inside CC that the amount/length of env variables is too large.

How do you think about that ? Trying digging trough the code but its difficult :).

**Comment by FloThinksPi** [comment]
Found this comment in the linter https://github.com/cloudfoundry/cloud_controller_ng/blob/4a0b5d4a70a6f54141f726a2086e080e50235415/spec/linters/migration/include_string_size.rb#L5-L9 so apparently no strings longer than 16k are possible otherwise one would break compatibility to mysql.

How about changing the type to a blob since i guess the encrypted env variables are anyway not searchable ?

**Comment by FloThinksPi** [comment]
See https://cloudfoundry.slack.com/archives/C07C04W4Q/p1581349934063000 for discussion of this.

**Comment by aashah** [comment]
Looks like this has already been addressed & released.

Closing.
