### ISSUE TITLE
`/v2/<space_guid>/services?q=label:[query]` always includes services from space-scoped brokers

### ISSUE THREAD

**Issue by x6j8x** [cloudfoundry/cloud_controller_ng#1559]
## Issue

Service label selector query returns results that don't match the label. 

## Context

While trying to create a service instance we get the error that 

> Service 'aws_ses_acceptance' is provided by multiple service brokers.

(which it isn't). 

Running the `cf create-service` with verbose mode enabled, we see that the label query returns two result resources (although only one actually matches the label). 

Example:
```
REQUEST: [2020-02-20T15:52:47+01:00]
GET /v2/spaces/1cf34cf6-1a50-4adb-a60f-ef416c8ecae7/services?q=label%3Aaws_ses_acceptance HTTP/1.1
Host: api...
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.49.0+d0dfa93bb.2020-01-07 (go1.13.4; amd64 darwin)

RESPONSE: [2020-02-20T15:52:47+01:00]
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 3668
Content-Type: application/json;charset=utf-8
Date: Thu, 20 Feb 2020 14:52:47 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 043605f0-3f55-44e1-477d-2a8fc04333f7::3c79638f-70fd-4e61-8179-35d1035135c0
{
  "next_url": null,
  "prev_url": null,
  "resources": [
    {
      "entity": {
        "active": 1,
        "allow_context_updates": 0,
        "bindable": 1,
        "bindings_retrievable": 0,
        "description": "Endpoint access control route services",
        "documentation_url": null,
        "extra": "",
        "info_url": null,
        "instances_retrievable": 0,
        "label": "protectr_acceptance",
        "long_description": null,
        "plan_updateable": 0,
        "provider": null,
        "requires": [
          "route_forwarding"
        ],
        "service_broker_guid": "ef3b2998-f803-4df0-a8d6-8e17432cc762",
        "service_broker_name": "protectr-broker-acceptance",
        "service_plans_url": "/v2/services/51a5a394-c6ba-40b0-b46a-2fbaf04ce47c/service_plans",
        "tags": null,
        "unique_id": "47AAD2AA-A4FD-453C-8DCD-7B5CE12DB1E1",
        "url": null,
        "version": null
      },
      "metadata": {
        "created_at": "2019-07-22T14:05:02Z",
        "guid": "51a5a394-c6ba-40b0-b46a-2fbaf04ce47c",
        "updated_at": "2020-02-20T13:25:20Z",
        "url": "/v2/services/51a5a394-c6ba-40b0-b46a-2fbaf04ce47c"
      }
    },
    {
      "entity": {
        "active": 1,
        "allow_context_updates": 0,
        "bindable": 1,
        "bindings_retrievable": 0,
        "description": "Send Emails from your app",
        "documentation_url": null,
        "extra": "",
        "info_url": null,
        "instances_retrievable": 0,
        "label": "aws_ses_acceptance",
        "long_description": null,
        "plan_updateable": 0,
        "provider": null,
        "requires": null,
        "service_broker_guid": "bdf97ab3-6692-440a-91dc-671e07da5884",
        "service_broker_name": "aws-ses-broker-acceptance",
        "service_plans_url": "/v2/services/14d3c156-b18d-49f0-a0a3-a81a637e1d30/service_plans",
        "tags": null,
        "unique_id": "9F152117-7125-46CA-9354-20D5DFBDDA5E",
        "url": null,
        "version": null
      },
      "metadata": {
        "created_at": "2020-02-20T14:50:04Z",
        "guid": "14d3c156-b18d-49f0-a0a3-a81a637e1d30",
        "updated_at": "2020-02-20T14:50:04Z",
        "url": "/v2/services/14d3c156-b18d-49f0-a0a3-a81a637e1d30"
      }
    }
  ],
  "total_pages": 1,
  "total_results": 2
}
```

Release: capi-release 1.91.0

**Comment by x6j8x** [comment]
Additional facts:
- both results are "space scoped" brokers
- both results are returned regardless of the value of the label parameters (so `/v2/spaces/1cf34cf6-1a50-4adb-a60f-ef416c8ecae7/services?q=label%3Aaws_ses_acceptance` returns exactly the same results

**Comment by FelisiaM** [comment]
Hi @x6j8x ! 

We agree that this is an issue in v2 API and we have already fixed it in v3 API (http://v3-apidocs.cloudfoundry.org/version/3.81.0/index.html#list-service-offerings) which is currently an experimental resource.

If you are interacting via the CLI, we suggest you specify the name of the broker in `cf create-service <service-offering> <plan> -b <broker-name>". This will disambiguate the offerings and works around the wrong API response since the filtering by broker name is done on the CLI side.

We will proceed to close this issue if you don't have any other questions.

Thanks
@FelisiaM & @pivotal-marcela-campo

**Comment by x6j8x** [comment]
@FelisiaM Just for the record... (as already written in Slack). 

I can't really agree here, as this would subject our users to applying workarounds to their pipelines that wouldn't be needed without this bug. 

We curate our marketplace very carefully and in general there's no need for the users to employ the `-b` flag when creating services. So they don't. 

I totally agree with migrating to v3 as fast as possible, but breaking v2 in the process simply can't be the way.

**Comment by blgm** [comment]
https://github.com/cloudfoundry/cloud_controller_ng/commit/7dc0c07ae342c3376ccb343a0dbd9841756260d1

**Comment by blgm** [comment]
Fixed by https://github.com/cloudfoundry/cloud_controller_ng/commit/7dc0c07ae342c3376ccb343a0dbd9841756260d1
