### ISSUE TITLE
Incorrectly presented links to entity relations

### ISSUE THREAD

**Issue by paroxp** [cloudfoundry/cloud_controller_ng#1565]
## Issue

Incorrectly presented links to entity relations in `/v2/apps/:guid` request.

## Context

One of our tenants, has discovered that making a curl request to `/v2/apps/:guid` produces a useful response containing the links to the relations of that entity. However in an attempt to hit these provided by the API links, the tenant ends up hitting 404 page instead...

## Steps to Reproduce

Run:

```
cf curl $(cf curl "/v2/apps/$(cf app myApp --guid)" | jq -r .entity.routes_url)
```

Or to give a better idea:

```
cf app myApp --guid # a000000a-000a-00a0-a000-aaa0a00000aa

cf curl /v2/apps/a000000a-000a-00a0-a000-aaa0a00000aa | jq -r .entity.routes_url # /v2/apps/z999999z-999z-99z9-z999-zzz9z99999zz/routes

cf curl /v2/apps/z999999z-999z-99z9-z999-zzz9z99999zz/routes # ... The app could not be found: z999999z-999z-99z9-z999-zzz9z99999zz
```

## Expected result

I would expect, the `.entity.routes_url` to have the same GUID as an app.

## Current result

Made up GUID as far as I can tell, producing 404s.

## Possible Fix

My ruby is somewhat limited, but my guess would be:

https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/presenters/v2/process_model_presenter.rb#L48

The merging function containing the wrong data.

Saying that, this test: 

https://github.com/cloudfoundry/cloud_controller_ng/blob/master/spec/request/v2/apps_spec.rb#L87

is also invalid in that case...

**Comment by aashah** [comment]
Hi @paroxp ,

Could you please test this on the latest CloudController? I tried to reproduce this (by pushing an app with a route and using the provided curl) and was unable to:

```
$ cf push --no-start dora
Pushing app dora to org org / space space as admin...
Getting app info...
Creating app with these attributes...
+ name:       dora
  path:       /Users/pivotal/go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/dora
  routes:
+   dora.stitch-foe.capi.land

Creating app dora...
Mapping routes...
.....

$ cf curl $(cf curl "/v2/apps/$(cf app dora --guid)" | jq -r .entity.routes_url)
{
   "total_results": 1,
   "total_pages": 1,
   "prev_url": null,
   "next_url": null,
   "resources": [
      {
         "metadata": {
            "guid": "d33802eb-5ff6-40e6-8740-9a05664ffa4a",
            "url": "/v2/routes/d33802eb-5ff6-40e6-8740-9a05664ffa4a",
            "created_at": "2020-04-24T22:04:06Z",
            "updated_at": "2020-04-24T22:04:06Z"
         },
         "entity": {
            "host": "dora",
            "path": "",
            "domain_guid": "646d2e63-60c3-4520-9ce5-3d21018deb01",
            "space_guid": "9115bb4c-62ef-471b-b745-3a671e1184cb",
            "service_instance_guid": null,
            "port": null,
            "domain_url": "/v2/shared_domains/646d2e63-60c3-4520-9ce5-3d21018deb01",
            "space_url": "/v2/spaces/9115bb4c-62ef-471b-b745-3a671e1184cb",
            "apps_url": "/v2/routes/d33802eb-5ff6-40e6-8740-9a05664ffa4a/apps",
            "route_mappings_url": "/v2/routes/d33802eb-5ff6-40e6-8740-9a05664ffa4a/route_mappings"
         }
      }
   ]
}
```

The links to the source code you provided are not stable as they reference a branch (master), so I'm not positive what revision you may have been looking at.

- Aakash

**Comment by paroxp** [comment]
Yup. Seems to have resolved.
