### ISSUE TITLE
[Feature Request]: Status in Revisions

### ISSUE THREAD

**Issue by JenGoldstrich** [cloudfoundry/cloud_controller_ng#1567]
Currently the Revisions object in CAPI does not return information about whether or not it is a deployable resource or not.  I think this is a good opportunity for the API to improve the Revision experience.  I would propose that when querying for an apps revision that each Revision include a status field, below are a few potential statuses.

- Deployed -> This revision is currently live 
- Not-Deployed -> This revision is not currently live but its droplet is still alive and we can roll back to this revision
- Expired -> This revision's droplet has expired and can no longer be rolled back to

This could also be bundled with a flag on /v3/apps/:guid/revisions to query for only non-expired revisions.

**Comment by sannidhi** [comment]
@JenGoldstrich We have made code changes here: https://github.com/cloudfoundry/cloud_controller_ng/pull/1611 

Is this enough to resolve the issue? What we have is the `deployable` boolean which indicates that it is staged but does not indicate if it is expired or not deployed. Seth has also made additional suggestions in the issue - feel free to give us feedback on it. 

Thanks!
Sannidhi & Jwal

**Comment by JenGoldstrich** [comment]
Hey @sannidhi !!

Yes this is fantastic, I will close this issue!

Thanks!
Jenna
