### ISSUE TITLE
Request to /v2/spaces/:guid/summary times out for spaces with many apps (when using eirini). 

### ISSUE THREAD

**Issue by piyalibanerjee** [cloudfoundry/cloud_controller_ng#1577]
## Issue
Request to /v2/spaces/:guid/summary times out for spaces with many apps (when using eirini). 

## Context

https://github.com/cloudfoundry/capi-k8s-release/issues/17

## Steps to Reproduce

**Given** I have deployed `cf-for-k8s` to a cluster of similarly substantial size as the GitHub issue's,
**And** I have pushed 1000 docker apps each with one route,
**When** I target that deployment and run `GET /v2/spaces/:targeted_space_guid/summary` (or run `cf6 apps -v`),
**Then** I receive a 504 Gateway Timeout response 

REQUEST: [2020-03-18T15:01:00-07:00]
GET /v2/spaces/b5f7b61a-19b8-4a88-a1d3-5c1ce77f92f6/summary HTTP/1.1
Host: api.hsamusk.capi.land
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.50.0+4f0c3a2ce.2020-03-03 / darwin

RESPONSE: [2020-03-18T15:02:05-07:00]
HTTP/1.1 504 Gateway Timeout
Connection: close
Content-Length: 160
Content-Type: text/html
Date: Wed, 18 Mar 2020 22:02:01 GMT
Server: istio-envoy
X-Envoy-Upstream-Service-Time: 60011

## Expected result

We expect no timeouts to occur, and to receive a 200 with a response including the paginated list of all apps in the targeted space in a reasonable amount of time.

**Comment by moleske** [comment]
k8s support was dropped, closing
