### ISSUE TITLE
[Feature Request] V3 Admin-only metadata

### ISSUE THREAD

**Issue by ChrisMtz** [cloudfoundry/cloud_controller_ng#1589]
## Proposal
V3 API Objects containing '**metadata.labels'** and '**metadata.annotations**' should also contain an Admin-only version that is inaccessible to the Users. 

## Context
As an Admin, there are multiple custom metrics that need to be linked to items hosted on Cloud Foundry. These metrics are currently store in an external database and accessed when needed, causing more overhead and slowing down API requests.

### Examples:
- **Lease Date** -- Calculated date of when an app should be EOL'd.
- **Team Identifier** -- Unique identifier attached to all hosted Orgs, Spaces, Apps, and Services to determine which User owns the object.
- **Monthly Usage** -- Calculated resource dollar amount each Org uses for billing purposes. 

Since metadata gives more flexibility to the Users, adding Admin-only labels/annotations would give more flexibility to the Admins for supporting the platform.

## Possible Solutions:
1. Have additional Metadata objects only admins can use.
2. Give Admins an option to make current Metadata objects completely inaccessible, read-only, or read-write permissions.

**Comment by cwlbraa** [comment]
We discussed this a lot when designing the metadata API. One thing that's interesting is that k8s doesn't have this feature afaik. Anybody who can modify an object can modify its labels. Implementing a feature like this in k8s might make it more difficult to give space developers k8s API access in some distant imagined future.

**Comment by ChrisMtz** [comment]
Understood, thank you for the information!
