### ISSUE TITLE
Not authorized error when fetching app usage events with global auditor role

### ISSUE THREAD

**Issue by mlin1001** [cloudfoundry/cloud_controller_ng#1590]
## Issue

We receive a not authorized error when fetching the app usage events of a cloud foundry foundation using an user account with the global auditor role assigned.
Basically this is the same issue as described and fixed with https://github.com/cloudfoundry/cloud_controller_ng/issues/1403 but on a different endpoint.

## Context

We did create a user with the global auditor role. We chose the role as described in the [docs](https://docs.cloudfoundry.org/concepts/roles.html)

The user has the correct scope when checking with uaac client.

## Steps to Reproduce

- Create user with role global auditor
- login via cf cli
- run cf curl `/v2/app_usage_events`

## Expected result

We expect to get a list of app usage events as described in [the docs](https://docs.cloudfoundry.org/running/managing-cf/usage-events.html).

## Current result

We receive a not authorized error.

## Possible Fix

We found that the request cycle ends up with an authorization check in https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/access/app_usage_event_access.rb#L68-L70

From our point of view the implementation is missing the global auditor part. As such the method should look like

```
def index?(*_)
  admin_user? || admin_read_only_user? || global_auditor?
end

```

**Comment by mhergerdt** [comment]
Unfortunately the link to pivotal tracker is not working for me (i get a 404). Is there any update on this?

**Comment by Gerg** [comment]
Hey @mlin1001 & @mhergerdt ,

The [v3 implementation of app usage events](https://v3-apidocs.cloudfoundry.org/version/release-candidate/#get-an-app-usage-event) should correctly allow global auditors to retrieve app usage events. Does this meet your needs?

Thanks,
Greg

**Comment by Gerg** [comment]
I'm going to close this issue, since it is fixed on the v3 implementation of usage events. Feel free to re-open if you continue to have issues.

**Comment by mlin1001** [comment]
> Hey @mlin1001 & @mhergerdt ,
> 
> The [v3 implementation of app usage events](https://v3-apidocs.cloudfoundry.org/version/release-candidate/#get-an-app-usage-event) should correctly allow global auditors to retrieve app usage events. Does this meet your needs?
> 
> Thanks,
> Greg

Hi @Gerg,

thanks for pointing that out - I will give it a try.
