### ISSUE TITLE
"cf service" slow when user is member of many orgs

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/cloud_controller_ng#1591]
## Issue

"cf service" slow when user is member of many orgs.

Users complain about really slow "cf service <myservice>" calls. Execution takes sometimes >5min.
Execution time seems to be related to the number of orgs that the user is member of. We have users with access to several thousand orgs.

## Context

CF 12.36
CF API 2.146.0
cf version 6.50.0+4f0c3a2ce.2020-03-03

Our CF foundation is really large: ~800 cells, 90 CC, 37k app instances.
CC VMs are well loaded but not overloaded according to our monitoring.
CC DB: AWS RDS db.m5.12xlarge, 20..40% CPU

## Steps to Reproduce

This is not exactly 'steps to reproduce' but more an analysis of a 'cf service postgres01' call.
The user in this example has access to 35 orgs.

## Expected result

Execution is fast (a few seconds).

## Current result

Execution took 52s.

I traced the CF API calls and the involved DB queries:

GET /v2/spaces/b79d0289-75dc-47bd-9460-7283508db450/service_instances?q=name%3Apostgres01&return_user_provided_service_instances=true HTTP/1.1
X-Vcap-Request-Id: 34b1ecb0-f22d-4ca8-473f-012d93d29f33::20e6abf8-4e51-4edc-8756-1c2e813812c9
- 13s
- results in 1 service instance (d1703063-df67-4952-ba09-8f615db92771)
- 51 DB queries
- 35x SELECT * FROM "service_plan_visibilities" WHERE ("service_plan_visibilities"."organization_id" = ?)
  - most time spent here (9s)
  - singly query took ~100ms

GET /v2/service_instances/d1703063-df67-4952-ba09-8f615db92771/shared_to HTTP/1.1
X-Vcap-Request-Id: 76563e6b-687b-4157-6671-17f584110e51::8af040ac-0009-441b-89c6-fc7b0a7b9102
- 2s
- 11 DB queries

GET /v2/service_plans/eefb5965-d893-4377-805d-876898887a28 HTTP/1.1
X-Vcap-Request-Id: 22465555-4ded-4f7b-4cb9-ad5ab695b931::a77c1b10-f7a1-4dec-b79a-9b3f3a79560f
- 15s
- 1178 DB queries
- 1117x SELECT * FROM "service_plans" WHERE "id" = ?
  - took ~4s
  - single queries are fast
  - no delay between queries (= processing CC was fast)
- 35x SELECT * FROM "service_plan_visibilities" WHERE ("service_plan_visibilities"."organization_id" = ?)
  - took 4s
- 7s for result rendering (time from last DB query until request completion)

GET /v2/services/c4ec80ae-5949-4a79-99ef-e42a894d73d3 HTTP/1.1
X-Vcap-Request-Id: 8c7e2d5a-0ea9-4263-6332-a970b3f640cd::e33f399f-a533-4180-a6e0-b030d839a761
- 7s
- 46 DB queries
- 35x SELECT * FROM "service_plan_visibilities" WHERE ("service_plan_visibilities"."organization_id" = ?)
  - took 5s

GET /v2/service_instances/d1703063-df67-4952-ba09-8f615db92771/service_bindings HTTP/1.1
X-Vcap-Request-Id: 6a9ddf12-e6db-48b5-6ebb-3c8ef2915c2a::631efc46-853c-4633-b8d5-c4bb5e4fa925
- 4s
- 18 DB queries, 5 of them with really long parameter lists

GET /v2/apps/d9652cff-5418-4442-9d60-37dc9e5f7685 HTTP/1.1
X-Vcap-Request-Id: 8bff6f9f-d881-4f22-4182-cb8b9b28421e::8afde353-3b2d-4a33-8800-a78afe8f589a
- fast, <1s

Summary:
- 3x35x SELECT * FROM "service_plan_visibilities" WHERE ("service_plan_visibilities"."organization_id" = ?)
  - this statement is invoked per org that the user has access
  - "cf service <myservice>" invokes CF API requests that lead to 3 times runnning this query per org (= in my example 3x35 queries)
  - a single query takes ~100ms
    - table service_plan_visibilities has ~92k entries, there is a btree (organization_id, service_plan_id) index
    - query time varies from 10ms up to 1s, I might ran into a load peak, overall 90% of queries take <= 10ms
  - it looks like there is a lot of additional CC processing between the queries. The 35 queries in /v2/spaces/b79d0289-75dc-47bd-9460-7283508db450/service_instances take 9s overall, each single query was ~120ms in average summing up to ~4s.
  - 18s are spent on this query including processing time in CC which is a good 1/3 of the execution time of this "cf service". This time increases with the # orgs that user has access to.
- 1117x SELECT * FROM "service_plans" WHERE "id" = ?
  - not sure why >1k plans have to be queried to find out the information about one service plan that is known by id (GET /v2/service_plans/eefb5965-d893-4377-805d-876898887a28)
  - maybe related to access rights/service enablements
  - this query is much faster compared to service_plan_visibilities (4s for ~1k queries)
- GET /v2/service_plans/eefb5965-d893-4377-805d-876898887a28 takes 7s from the last query until the request is completed

## Possible Fix

Unsure, just some ideas:
- Use joins instead of single queries that increase with e.g. number of orgs that the user is member of.
- Is the btree (organization_id, service_plan_id) index on service_plan_visibilities sufficient for the service_plan_visibilities queries? I guess so.
- Consider scalibility aspects in the v3 implementation.

**Comment by kirederik** [comment]
Hey @stephanme,

Thanks for opening this issue and for the detailed analysis of the v2 queries. Also sorry for the delay in getting you some response back.

Good news is that we **believe** we should have that fixed on v3. The team is finishing up the implementation of `cf services` on the CLI and we'll run some tests soon to make sure that that's the case.

We'll keep this issue open until then.

**Comment by blgm** [comment]
I have done some comparisons between `cf services` commands using V2 and V3 endpoints. The performance when a user is a member of a large number of organizations is broadly the same. I suspect the reason for this is that V3 does not change the permission model. The way it works is to get a list of readable space GUIDs (in this case a list of around 1000) and then use this list in a query of the service instances table. Because the list it too large for a single query, the query is split into various batches.

The way to progress this would be to get the service instances and readable space GUIDs in a single query, so that the DB can optimise it outside of the Sequel ORM layer. This isn't in the scope of the V3 migration. It may have fallen under the scope of the Perm project, which I understand is not currently active.

**Comment by stephanme** [comment]
I just received an error report about v2 vs v3 performance regression for service_plans:

v2:
```
 time  cf curl /v2/service_plans > /dev/null
cf curl /v2/service_plans > /dev/null  0.12s user 0.04s system 11% cpu 1.338 total
➜  ~ time  cf curl /v2/service_plans > /dev/null
cf curl /v2/service_plans > /dev/null  0.11s user 0.04s system 7% cpu 1.866 total
➜  ~ time  cf curl /v2/service_plans > /dev/null
cf curl /v2/service_plans > /dev/null  0.12s user 0.04s system 11% cpu 1.312 total
➜  ~ time  cf curl /v2/service_plans > /dev/null
cf curl /v2/service_plans > /dev/null  0.11s user 0.04s system 12% cpu 1.224 total
➜  ~ time  cf curl /v2/service_plans > /dev/null
cf curl /v2/service_plans > /dev/null  0.11s user 0.04s system 7% cpu 1.868 total
➜  ~ time  cf curl /v2/service_plans > /dev/null
cf curl /v2/service_plans > /dev/null  0.12s user 0.04s system 11% cpu 1.324 total
```

v3:
```
➜  ~ time  cf curl /v3/service_plans > /dev/null
cf curl /v3/service_plans > /dev/null  0.13s user 0.04s system 0% cpu 37.229 total
➜  ~ time  cf curl /v3/service_plans > /dev/null
cf curl /v3/service_plans > /dev/null  0.12s user 0.04s system 0% cpu 33.122 total
➜  ~ time  cf curl /v3/service_plans > /dev/null
cf curl /v3/service_plans > /dev/null  0.13s user 0.04s system 0% cpu 37.489 total
➜  ~ time  cf curl /v3/service_plans > /dev/null
cf curl /v3/service_plans > /dev/null  0.13s user 0.05s system 0% cpu 36.235 total
```

v3 is around factor 25 slower than v2 for this particular case. If it helps, I can provide more information and logs.
IIRC, the CF foundation was on capi-release 1.98 (cloud_controller_v2 = 2.153.0, cloud_controller_v3 = 3.88.0).

**Comment by blgm** [comment]
@stephanme, thank you - that's very helpful. We still have some optimisations to apply to `/v3/service_plans` and currently we see it being about 2 times slower than V2, so it's really interesting that you have a scenario where it's 25 times slower! Please do share some more details, such as the number of plans, and how their visibility is configured. Thanks!

**Comment by stephanme** [comment]
Some data about our CF foundation:

```
ccdb=> select count(*) from organizations;
-[ RECORD 1 ]
count | 22781

ccdb=> select count(*) from service_brokers;
-[ RECORD 1 ]
count | 289

ccdb=> select count(*) from service_plans;
-[ RECORD 1 ]
count | 1278

ccdb=> select count(*) from service_plan_visibilities;
-[ RECORD 1 ]-
count | 683194
```

The requests were invoked by a CF admin user.
/v2/service_plans returned "total_results": 1278 (i.e. all plans because admin sees them all).

/v2/service_plans costs 7 sql statements (include rate limit counting). All SQL stmts were fast (a few ms).

/v3/service_plans costs 251 sql statements. Most of them fast but service_plan_visibility queries seem to be a bit more costly (between 20 and 120ms).

I attach the log files for both requests (I have to redact some info). Unfortunately, the logs are not in correct order due to current bug in timestamp parsing in our logging system.

**Comment by stephanme** [comment]
[v3-service-plans-log.txt](https://github.com/cloudfoundry/cloud_controller_ng/files/5591145/v3-service-plans-log.txt)

**Comment by blgm** [comment]
@stephanme we have made some changes to the `/v3/service_plans` endpoint which will show up in the next release. We observe it being much faster as it makes fewer queries to get the data.

**Comment by bodymindarts** [comment]
Just want to document some differences between V2 and V3 code that might be the origins of the performance differences:

In the [v2 controller](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/services/service_plans_controller.rb#L21-L47) the ORM layer is called directly.

In the [v2 controller](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/v3/service_plans_controller.rb#L42-L60) an intermediate class [`ServicePlanListFetcher`](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/fetchers/service_plan_list_fetcher.rb) is called to handle the construction of the query (via the ORM layer).

**Comment by blgm** [comment]
Hi @stephanme, I have done some further investigation into this, specifically comparing `cf service <name>` v7 CLI with the future `cf service <name>` for v8 CLI which is under development. The principle difference is that v8 will use v3 API endpoints for services, while v7 uses v2 API endpoints for services.

Why is v7 CLI/v2 API so slow?
- you observed 35 queries to `service_plan_visibilities`. The Cloud Controller performs one of these queries per space that the user has access to.
- you observed 1178 queries to `service_plans`. The Cloud Controller performs one of these queries per managed service instance per plan that the user can see. So the total number of queries is `(visible plans) * (visible managed service instances)` which can result in a large number.
- you also observed that the 35 `service_plan_visibilities` queries happen for more than one endpoint (so they are repeated)

As @bodymindarts notes above, the V3 API uses fetchers which allows for more control over the database queries being used. In V2 there can sometime be an unexpectedly large number of queries as was observed. In this case V3 is better.

I created a test environment where a user is a space developer in 1000 spaces each in a separate org. There are also 100 service instances each in a different space.

v2 API running `cf service <name>`:
- median (n=3) time  was 6.57 seconds
- 4160 DB queries were performed

v3 API running `cf v3-service <name>`:
- median (n=3) time  was 1.09 seconds
- 69 DB queries were performed

As you can see there is a significant improvement on the way. Although current versions of the Cloud Controller support the API endpoints required, the CLI that uses these endpoints is planned to be V8.

I'm going to close this issue now as the work of improving the speed is complete from a development perspective. Please feel free to raise any further issues relating to performance. A lot of development work happens on much smaller CF foundations, so it's good to get data from large foundations to help drive performance improvements.

**Comment by stephanme** [comment]
Hi @blgm,

thanks for improving the perf of the service related v3 api endpoints and the usage in cf cli.
One question: is there a (rough) roadmap regarding cf cli v8?

Best regards, Stephan
