### ISSUE TITLE
v3 POST  org returns 422 instead of 400 for duplicate name

### ISSUE THREAD

**Issue by marius-munteanu-sc** [cloudfoundry/cloud_controller_ng#1597]
## Issue

cf curl -X POST /v3/organizations returns http 422 when organization name already exists.

## Context
```
cf curl /
{
   "links": {
  ... more lines here
      "cloud_controller_v2": {
         "href": "https://api.cloud.com/v2",
         "meta": {
            "version": "2.147.0"
         }
      },
      "cloud_controller_v3": {
         "href": "https://api.cloud.com/v3",
         "meta": {
            "version": "3.82.0"
         }
      },
... more lines here
   }
}
```

## Steps to Reproduce
```
cf curl -X POST /v3/organizations -d '{"name": "org name 110"}' -i
HTTP/1.1 422 Unprocessable Entity
... more lines here
{
   "errors": [
      {
         "detail": "Organization 'org name 110' already exists.",
         "title": "CF-UnprocessableEntity",
         "code": 10008
      }
   ]
}
```

## Expected result

http 400 

## Current result
http 422

**Comment by aashah** [comment]
Hey @marius-munteanu-sc,

It's true that in V2, trying to create an org that already exists would result in a 400.

In V3 however, we've chosen to use 422 instead. A little more about errors can be found here https://github.com/cloudfoundry/cc-api-v3-style-guide#client-errors. For this situation, the request payload is syntactically valid, but would result in an invalid state.

I hope this helps understand some of the team's thought processes behind that decision. Let me know if there's something more I can clarify too!
