### ISSUE TITLE
Labels for service instances available?

### ISSUE THREAD

**Issue by abh1kg** [cloudfoundry/cloud_controller_ng#1608]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

As per the docs at http://v3-apidocs.cloudfoundry.org/version/3.83.0/index.html#service-instances, labels and annotations are possible to be set for service instances (Albeit it's experimental). However, I don't seem to get them nor set them via APIs.

## Context

I would like to use labels and annotations for service instances in order to implement some advanced filtering capabilities

## Steps to Reproduce

`cf7 cli` does not contain a way to set labels and annotations on service instances yet

## Expected result

There should be a documented API to set labels and annotations for service instances

## Current result

No discernible API though documentation refers to it.

## Possible Fix

`N/A`

**Comment by cwlbraa** [comment]
Hi! 

The CC API documentation you're looking for is here: http://v3-apidocs.cloudfoundry.org/version/3.83.0/index.html#update-a-service-instance

If you'd like to track service instance label support being implemented in the CLI, there's a story here: https://www.pivotaltracker.com/story/show/169106275
