### ISSUE TITLE
[feature request] Include instance and binding IDs in VCAP_SERVICES

### ISSUE THREAD

**Issue by nictas** [cloudfoundry/cloud_controller_ng#1684]
## Issue

As an application, if you need a service instance or binding GUID, you need to make a request to the CC API, in order to retrieve them.

## Context

This is the current structure of `VCAP_SERVICES`:
```
"VCAP_SERVICES": {
  "postgresql": [
   {
    "binding_name": null,
    "credentials": {
     <CREDENTIALS>
    },
    "instance_name": "my-database",
    "label": "postgresql",
    "name": "my-database",
    "plan": "large",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "postgresql",
     "relational"
    ],
    "volume_mounts": []
   }
  ]
 }
```
It contains the names of the service instances and the names of the bindings, but it does not contain their respective GUIDs. Of course, if the application needs them, it can retrieve them by using the `space_id` and `cf_api` fields from VCAP_APPLICATION to make some calls to the CC API, but this leads to some extra complexity in the application. Is there some technical limitation why `VCAP_SERVICES` can't be modified to include the GUIDs? Was it an intentional design decision?

Something like this would be really helpful to us:
```
"VCAP_SERVICES": {
  "postgresql": [
   {
    "binding_name": null,
    "binding_id": "1911b7d9-061f-4bd8-babe-0e0ed09e3195",
    "credentials": {
     <CREDENTIALS>
    },
    "instance_name": "my-database",
    "instance_id": "b71fc53b-7518-4d2b-b8da-00aaed032e0c",
    "label": "postgresql",
    "name": "my-database",
    "plan": "large",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "postgresql",
     "relational"
    ],
    "volume_mounts": []
   }
  ]
 }
```

**Comment by FelisiaM** [comment]
Hi @nictas 

Thanks for the request. We have implemented this feature on v3 and it will be available on the next release.
You will be able to find `binding _guid` and `instance_guid` as part of `VCAP_SERVICES` data.

Thanks,
Felisia
