### ISSUE TITLE
Orphaned mitigation on service instance update failures

### ISSUE THREAD

**Issue by brunograz** [cloudfoundry/cloud_controller_ng#1690]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

CC issues an orphaned mitigation on service instances with failed updates resulting in the removal of the service instance.

## Context

Updating service instances may result in a failure and for such scenario the orphaned mitigation should not be triggered as described in the OSB specification.

- https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphan-mitigation
- https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#updating-a-service-instance

We assume that this commit has introduced this bug where it triggers the mitigation when a request to last_operation is issued by the CC and the service broker report its state is 'failed'. 

- https://github.com/cloudfoundry/cloud_controller_ng/commit/80176ff0068741088e19629516c0285b4cf57ef3#diff-6e29198ceec350cf6dfa0220146b0c61

From our point view it is incorrect to initiate a mitigation on a service instance based on the last_operation without checking the type of the operation that had been performed.

For additional information:
-  The service instance provisioning / deprovisioning / update is asynchronous. 
-  The service broker returns a `http 200, state = 'failed'` when last_operation is requested by CC.

## Steps to Reproduce

- Create any service in Cloud Foundry
- Update the service (change of a plan, configuration)
   - The service update must fail

## Expected result

- Update service instance fails but no orphaned mitigation is triggered.

## Current result

- Update service instance fails and orphaned mitigation is triggered.

**Comment by blgm** [comment]
Thank you for raising this @brunograz. This is clearly an incorrect behavior and we are working on a fix.
