### ISSUE TITLE
API to get app memory utilisation at a given point of time

### ISSUE THREAD

**Issue by bhanuReddy2695** [cloudfoundry/cloud_controller_ng#1805]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## API to get app memory utilisation at a given point of time

All i need is to know if there is an API in cloud foundary which gives the memory metrics of the application at a particular time like whats its memory, cpu uitlisation?

**Comment by cwlbraa** [comment]
http://v3-apidocs.cloudfoundry.org/version/3.83.0/index.html#get-stats-for-a-process

**Comment by Gerg** [comment]
Hey @bhanuReddy2695,

There is documentation [here](https://docs.cloudfoundry.org/loggregator/data-sources.html#viewing) on how to retrieve metrics. Historical data is not available from cloud controller, however you can warehouse container metrics from the firehose yourself.
