### ISSUE TITLE
Unable to push app with manifest.yml using a non-default stack

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/cloud_controller_ng#1819]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Using cf7 v7.0.2 I'm unable to push an app to the stack specified in the manifest.  For example:

    ---
    applications:
    - name: aspxtest01
      stack: windows2012R2
      buildpacks:
      - hwc_buildpack
      instances: 1
      health-check-type: port

**What happened**
App failed to push.

    cf push
    Pushing app aspxtest01 to org test / space test as admin...
    Applying manifest file C:\Development\aspxtest\manifest.yml...
    For application 'aspxtest01': Buildpack "hwc_buildpack" must be an existing admin buildpack or a valid git URI 

If I override the stack on the command line, it does work:

    cf push -s windows2012R2
    Pushing app aspxtest01 to org test / space test as admin...
    Applying manifest file C:\Development\aspxtest\manifest.yml...
    Manifest applied
    Packaging files to upload...
    Uploading files...
     1.28 KiB / 1.28 KiB [=================================================================================================================================================] 100.00% 1s
    
    Waiting for API to complete processing files...
    
    Staging app and tracing logs...
       Downloading hwc_buildpack...
       Downloaded hwc_buildpack
       <snip>

**Expected behavior**
App should be deployed successfully, manifest works with cf v6.

**To Reproduce**
1. Create manifest per above.
2. cf push
3. See error

**Provide more context**
- API version:    3.87.0

**Comment by JenGoldstrich** [comment]
We discovered this issue is actually in the cf CLI code base, we have submitted a PR to fix this https://github.com/cloudfoundry/cli/pull/2148 which should go out in the next cf CLI release.

Closing this now, please feel free to follow up further if you do not see this get resolved, thanks!

Jenna

**Comment by amhuber** [comment]
Thanks for following up on this, I'll monitor the CLI issue.
