### ISSUE TITLE
Cf push times out on azure

### ISSUE THREAD

**Issue by Peter-Sternberger** [cloudfoundry/cloud_controller_ng#1846]
## Issue

We are currently running into issues on pushing applications to our cf azure instance because of `cf push` timeouts.
The timeouts we are currently seeing are based on the usage of the fog library that is part of the cloud controller (also in the future cf-for-k8s product).

## Context

A deeper look shows that CF has a hard dependency to fog and in particular to fog-azure-rm.
However fog-azure-rm does not seem to be maintained anymore and it is using a preview-version of [azure-storage-ruby](https://github.com/Azure/azure-storage-ruby/releases/tag/v0.14.0).
Cloud controller even uses a dedicated branch of fog-azure-rm [fog-arm-cf](https://github.com/cloudfoundry/cloud_controller_ng/blob/34545f66dc072a03590cd34a2aef3ed6eeb14b90/Gemfile#L57), but master isn't maintained either.

## Steps to Reproduce

Cannot be reproduced, happens only sporadically.

## Expected result

A clear maintenance strategy for used dependencies, in particular for the `fog-azure-rm` project.

## Current result

We assume that all worker processes are hanging in the following stack trace:
```
| ./cloud_controller_ng/vendor/cache/fog-azure-rm-baaf3f4d684f/lib/fog/azurerm/requests/storage/multipart_save_block_blob.rb:82:in `join'                     +
| ./cloud_controller_ng/vendor/cache/fog-azure-rm-baaf3f4d684f/lib/fog/azurerm/requests/storage/multipart_save_block_blob.rb:82:in `each'                     +
| ./cloud_controller_ng/vendor/cache/fog-azure-rm-baaf3f4d684f/lib/fog/azurerm/requests/storage/multipart_save_block_blob.rb:82:in `multipart_save_block_blob'+
| ./cloud_controller_ng/vendor/cache/fog-azure-rm-baaf3f4d684f/lib/fog/azurerm/models/storage/file.rb:254:in `save_blob'                                      +
| ./cloud_controller_ng/vendor/cache/fog-azure-rm-baaf3f4d684f/lib/fog/azurerm/models/storage/file.rb:95:in `save'                                            +
| ./gem_home/ruby/2.5.0/gems/fog-core-1.45.0/lib/fog/core/collection.rb:50:in `create'                                                                        +
| ./cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:72:in `block in cp_to_blobstore'                                                     +
| ./cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:59:in `open'                                                                         +
| ./cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:59:in `cp_to_blobstore' 
   ... 
```

**Comment by Gerg** [comment]
We are [planning to revisit](https://www.pivotaltracker.com/story/show/174179944) how we use `fog-azure-rm` to see if we can get to a more recent version of `azure-storage`. That said, we occasionally see slow requests in our Azure environments because of performance degradations in the Azure service (regardless of client). Do you have anything that is leading you to believe that there is an issue with `fog-azure-rm` outside of general Azure slowness?

**Comment by Peter-Sternberger** [comment]
@Gerg not sure what you mean by general slowness.
In our case, we saw that all local workers are blocked (hanging forever) at this call:
https://github.com/fog/fog-azure-rm/blob/fog-arm-cf/lib/fog/azurerm/requests/storage/multipart_save_block_blob.rb#L82
which makes us believe that one of the threads is waiting at
https://github.com/fog/fog-azure-rm/blob/fog-arm-cf/lib/fog/azurerm/requests/storage/put_blob_block.rb#L12
The Azure Storage team suggested to add a timeout to the blob operation
https://docs.microsoft.com/rest/api/storageservices/setting-timeouts-for-blob-service-operations
to avoid waiting potentially forever on a single put blob operation.
But we are not sure that even if someone from the cloudfoundry community would open a PR against fog-azure-rm, if there would be someone accepting/reviewing the PR i.e. if there is still someone maintaining the project.

**Comment by Gerg** [comment]
I can't speak to the details of the `fog-azure-rm` project, but it looks like both fog maintainers and Microsoft employees contribute to it. It's definitely low traffic, but I don't have any reason to believe it is out of maintenance. 

I wasn't able to find documentation for this, but you can also configure a timeout using `cc.buildpacks.fog_connection. blobstore_timeout`: https://github.com/cloudfoundry/cloud_controller_ng/blob/56ba6bb2b55381bef0190bbb181ccb3de5ee24ed/lib/cloud_controller/blobstore/fog/fog_client.rb#L191.

**Comment by Peter-Sternberger** [comment]
I think the timeout you are referring to is a different timeout than https://docs.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations. As far as I could see, fog-azure-rm is not setting the blob timeout of the Azure Storage API. I assume the timeouts you are referring to are used to set HTTP/TCP read and write timeouts..?

**Comment by sethboyles** [comment]
@Peter-Sternberger since https://github.com/fog/fog-azure-rm/pull/432 has been merged, have you noticed an improvement?  Can we close this issue out?

**Comment by Peter-Sternberger** [comment]
@sethboyles, no, we didn't see the issue anymore since https://github.com/fog/fog-azure-rm/pull/432 was merged and used. I propose to close this issue, thanks!
