### ISSUE TITLE
[sapi] 1.93.0 regression. Unable to update meta-data to a service instance being async provisionned

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cloud_controller_ng#1848]
## Issue

As a cf user
* in order to attach metadata to a service instance that takes hours to create
* I need the `PATCH  /v3/service_instances/guid` endpoint to accept update to metadata although the service instance is still in progress

This behavior regressed with capi 1.93.0 

## Context

This scenario also affects tooling that provision service instances and need to attach metadata to them (this issue was detected through https://github.com/orange-cloudfoundry/osb-cmdb/issues/65 )

## Steps to Reproduce

```
cf cs service async-plan myservice
guid=$(cf s myservice --guid)
CF_TRACE=true cf curl -X PATH /v3/service_instances/${guid} -d '{
    "metadata": {
      "annotations": {
        "note": "detailed information"
      },
      "labels": {
        "key": "value"
      }
    }
  }'
```

## Expected result

`HTTP/1.1 200 OK`

## Current result

starting with 1.93.0 (and likely related support for async brokers at https://www.pivotaltracker.com/n/projects/2105761/stories/171649250 ) this fails with

`CF-AsyncServiceInstanceOperationInProgress(60016): An operation for service instance f0a8f886-76a2-49d8-80eb-5f7230e5f8fe is in progress.`

## Possible Fix

Allow metadata-only update to a service instance (or service binding) despite the status "in progress"

**Comment by kirederik** [comment]
Thanks @gberche-orange!

This issue is now fixed and will be included in the next capi-release. We'll close the issue once it's released

**Comment by gberche-orange** [comment]
Thanks a lot @kirederik for the prompt fix, I'll watch the capi release repo to test iit.

**Comment by kirederik** [comment]
CAPI 1.99.0 is released and should contain the fix for this!

I'll close it for now but please reopen it if you find any other issues!
