### ISSUE TITLE
Unable to see list of detected CNBs for apps built by kpack

### ISSUE THREAD

**Issue by piyalibanerjee** [cloudfoundry/cloud_controller_ng#1853]
## Issue

There's no way of viewing the list of CNBs used to build apps with a kpack lifecycle. 

## Context

For buildpack lifecycle apps, the buildpacks detected/used to build the app are observable via the `cf curl /v3/apps/:guid/droplets/current` endpoint. However, since kpack lifecycle apps are associated with docker lifecycle droplets containing the OCI image reference of the app image in the image registry, the `buildpacks` field is always returned as `null`. There needs to be a way to expose the CNBs used to build the apps by kpack.

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

**WHEN** I `cf push` an app (i.e.: Go app) with a paketo-buildpack (i.e.: paketo-buildpacks/go)
**AND** I `cf curl /v3/apps/:guid/droplets/current`
**THEN** I expect to see a response that includes an array of hashes containing info on each buildpack used to build the app
i.e.:
```
"buildpacks": [
    {
      "name": "paketo-buildpacks/go",
      "detect_output": "go 0.1.0",
      "version": "0.1.0.",
      "buildpack_name": "paketo-buildpacks/go"
    }
  ]
```
## Current result

**WHEN** I `cf push` an app 
**AND** I ` cf curl /v3/apps/821b06c1-b699-4cb6-8da6-28466b9fee31/droplets/current`
**THEN** I get this response with a null list of buildpacks:
```
{
   "guid": "b48e7860-ddce-490c-9539-b3cc5adf5d2e",
   "created_at": "2020-09-17T21:48:16Z",
   "updated_at": "2020-09-17T21:49:07Z",
   "state": "STAGED",
   "error": null,
   "lifecycle": {
      "type": "docker",
      "data": {}
   },
   "checksum": null,
   "buildpacks": null,
   "stack": null,
   "image": "gcr.io/cf-capi-arya/cf-workloads/821b06c1-b699-4cb6-8da6-28466b9fee31@sha256:0d293bb0f01a0091c890d473ad19b0289cc3bc49403e3e032eb92981841a08d8",
...
}
```
## Possible Fix

* Make a new `kpack` lifecycle type for droplets such that a staged `kpack` droplet would have a non-null `buildpacks` and `image` field.
* Have cf-api-controllers return list of CNBs used to build the kpack app back to CAPI

**Comment by cwlbraa** [comment]
I think this doesn't work regardless of whether you specify a buildpack, and it likely should work with no buildpack specified.

**Comment by piyalibanerjee** [comment]
@cwlbraa The only way specified buildpacks are viewable is through `GET /v3/apps/:guid` -- but those represent the requested, rather than the actual, state. So there's no way currently to see the list of buildpacks that were actually used to build kpack apps, regardless of whether they were specified by the user.

**Comment by sethboyles** [comment]
closing since cf-for-k8s is no longer under active development
