### ISSUE TITLE
Copying a package fails when using an OCI image registry to store packages

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cloud_controller_ng#1857]
## Issue

See: https://github.com/cloudfoundry/cf-for-k8s/issues/466

## Context

We have an endpoint that can copy a package from one app to another:
* `POST /v3/packages?source_guid=:guid`
* https://v3-apidocs.cloudfoundry.org/version/3.88.0/index.html#copy-a-package

The `PackageBitsCopier` relies on the blobstore supporting a copy operation which definitely doesn't work when our packages are sent to an image registry.

https://github.com/cloudfoundry/cloud_controller_ng/blob/aa19fd5c71af54be7b7fa228926161c563e8a26b/app/jobs/v3/package_bits_copier.rb#L20

## Steps to Reproduce

See: https://github.com/cloudfoundry/cf-for-k8s/issues/466

## Expected result
The package is successfully copied.

## Current result

An error occurs:
```
$ cf copy-source dora2 dora
Copying source from app dora2 to target app dora in org o / space s as admin...

Package failed to process correctly after upload
FAILED
```

```
failed to copy - CloudController::Blobstore::FileNotFound
```

**Comment by tcdowney** [comment]
Tracker Story was moved: https://www.pivotaltracker.com/story/show/175081123

**Comment by sethboyles** [comment]
closing since cf-for-k8s is no longer under active development
