### ISSUE TITLE
Package upload fails when client uses HTTP/2 with Istio Ingress Gateway

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cloud_controller_ng#1874]
**NOTE:** Logging this here to provide visibility into it as a "Known Issue". It is unclear at this time how much of the issue lies with the Istio Ingress Gateway Envoy proxy, how much lies with the Istio sidecar Envoy proxy, and how much lies with nginx/the nginx upload module. It is possible that a future Istio upgrade might fix this or that an alternative Ingress controller won't have this issue.

## Issue

This issue is a result of our investigation into [CAPI Story #174918523: Package upload fails intermittently](https://www.pivotaltracker.com/story/show/174918523).

When using `curl` to [upload a package](https://v3-apidocs.cloudfoundry.org/version/3.88.0/index.html#upload-package-bits), you will frequently receive 503 errors back from the API. The `cf-api-server/nginx` logs will include errors like this:

```
cf-api-server-749798466-w6tmt > nginx | 2020/09/21 21:37:09 [info] 10#0: *74674 started uploading file "dora.zip" to "/tmp/uploads/0000000011" (field "bits", content type "application/octet-stream"), client: 127.0.0.1, server: , request: "POST /v3/packages/d4d5232d-ed0f-47b7-bd1f-0fc5c968b8ad/upload HTTP/1.1", host: "api.nat.k8s.capi.land"
cf-api-server-749798466-w6tmt > nginx | 2020/09/21 21:38:10 [alert] 10#0: *74674 aborted uploading file "dora.zip" to "/tmp/uploads/0000000011", dest file removed, client: 127.0.0.1, server: , request: "POST /v3/packages/d4d5232d-ed0f-47b7-bd1f-0fc5c968b8ad/upload HTTP/1.1", host: "api.nat.k8s.capi.land"
```

The `cf` CLI does not appear to have this issue.

## Context

We did quite a bit of debugging in [#174918523](https://www.pivotaltracker.com/story/show/174918523). Things we've found:

1. `curl` gets its connection upgraded to use `HTTP/2` by the Ingress Gateway Envoy
1. This does not happen for the `cf` CLI for some reason. It continues to use `HTTP/1.1`.
1. The `nginx` we have configured and sidecar Envoy do not use `HTTP/2`. The Ingress Gateway uses `HTTP/2` with the client, but converts it to `HTTP/1.1` when delivering the request to the Pod.
1. The entire package file never makes it to the Sidecar Envoy/`nginx` and `nginx` will eventually timeout, resulting in a `408`.
1. The Sidecar Envoy returns this as a `503` which makes its way to the user.

## Steps to Reproduce

Deploy `cf-for-k8s` and use `curl` to upload some "app source" (I used this [Shakespeare txt file](https://ocw.mit.edu/ans7870/6/6.006/s08/lecturenotes/files/t8.shakespeare.txt)):

Example:
```
curl -k https://api.tim.k8s.capi.land/v3/packages/some-package-guid/upload -X PUT -f -F bits=@/tmp/shakespeare.txt -v -H "Authorization: $(cf oauth-token)"
```

## Expected result

For a valid package guid I would expect a successful 200 level response. For testing purposes you can use a bogus package guid and expect to get a `404` back from the API after the file is uploaded.

## Current result

The `curl` will output something like this and hang at "We are completely uploaded and fine" for 60 seconds:

```
*   Trying 34.82.158.28...
* TCP_NODELAY set
* Connected to api.tim.k8s.capi.land (34.82.158.28) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=USA; O=Cloud Foundry; CN=*.tim.k8s.capi.land
*  start date: Sep 28 17:11:13 2020 GMT
*  expire date: Sep 28 17:11:13 2021 GMT
*  issuer: C=USA; O=Cloud Foundry; CN=ca
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fc23680fe00)
> PUT /v3/packages/some-package-guid/upload HTTP/2
> Host: api.tim.k8s.capi.land
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: bearer <bearer-token-removed>
> Content-Length: 5458392
> Content-Type: multipart/form-data; boundary=------------------------d0063abea4df3cad
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
* We are completely uploaded and fine
```

Eventually it will fail with:

```
* The requested URL returned error: 503
* stopped the pause stream!
* Connection #0 to host api.tim.k8s.capi.land left intact
curl: (22) The requested URL returned error: 503
* Closing connection 0
```

When we did `tcpdumps` at various places[0] we found that `curl` was successfully sending the whole file to the Ingress Gateway Envoy, but it was not making it to the sidecar Envoy. Cloud Controller's `nginx` was waiting for the complete file (looking for the `------------------------d0063abea4df3cad` boundary) and eventually timed out returning a `408`. The sidecar Envoy considered this a bad response and bubbled it up as a `503` to the user.

---

[0] I took the `tcpdump` from the `cf-api-server` Pod's `nginx` container by including `tcpdump` in its Dockerfile and rebuilding the image. You may also try a tool like [ksniff](https://github.com/eldadru/ksniff).

For example, this one shows traffic between the Ingress Gateway and the Pod's Sidecar Envoy on `eth0`:
```
kubectl exec -n cf-system cf-api-server-6b5895c557-scr95 -c nginx -- tcpdump -i eth0 -w - | wireshark -k -i -
```

This one shows traffic between the Sidecar Envoy and nginx on `lo`:
```
kubectl exec -n cf-system cf-api-server-6b5895c557-scr95 -c nginx -- tcpdump -i lo -w - | wireshark -k -i -
```

## Possible Fix

A mitigation for `curl` is to force HTTP/1.1 with the `--http1.1` flag.

## Screenshots

![Screen Shot 2020-09-25 at 12 22 51 PM](https://user-images.githubusercontent.com/2096955/94486663-9914d900-0194-11eb-8044-f456e91ba596.png)
![Screen Shot 2020-09-25 at 12 34 13 PM](https://user-images.githubusercontent.com/2096955/94486668-9ade9c80-0194-11eb-87fa-080a6eda7cda.png)

## Version Information
* `curl` version:

```
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

* CF API version: `3.89.0`
* cf-for-k8s SHA: `c03c38f03495fc5afc4d108799149419678514c8` ([vendir.yml](https://github.com/cloudfoundry/cf-for-k8s/blob/c03c38f03495fc5afc4d108799149419678514c8/vendir.yml))
* Istio version: `1.6.4`

**Comment by sethboyles** [comment]
closing since cf-for-k8s is no longer under active development
