### ISSUE TITLE
Staging fails with "failed to create container", can't set cgroup config, (bosh-lite environment)

### ISSUE THREAD

**Issue by ipa-bak** [cloudfoundry/cloud_controller_ng#1882]
## Issue

`cf push` fails for most simple apps (here: "cf-ex-php-info" example app) pushing to a fresh deployed "cloud foundry" running on a local "bosh-lite" installation built with the docker CPI.

Problem seems to be, that the cf runner(?) tries to configure control group properties that can't be set when already running in a container.

## Context

I created for testing a local, docker-based bosh-lite environment.  I used initially the "bucc" instructions from here: https://github.com/starkandwayne/bucc with the "docker" CPI. (The VirtualBox CPI is currently broken, see here: https://github.com/cppforlife/bosh-virtualbox-cpi-release/issues/18.)  I then followed the instruction here: "https://github.com/cloudfoundry/cf-deployment/blob/master/texts/deployment-guide.md" to deploy the cloud foundry from "https://github.com/cloudfoundry/cf-deployment".

I retried with a plain bosh-lite from "https://github.com/cloudfoundry/bosh-deployment".

Both deployments went without problems I know of.

## Steps to Reproduce

1. Create a local bosh-lite environment using the "docker" CPI
   * either using the repository from here https://github.com/starkandwayne/bucc
   * or using the instruction here https://bosh.io/docs/bosh-lite/ 
   * I tried both ways with identical result
2. Deploy cf against the director from step 1
3. Configure an initial org and space and login
4. Run git clone https://github.com/cloudfoundry-samples/cf-ex-php-info and enter the work tree
5. Execute `cf push`

I created a gist with my deployment steps, you can run that script to exactly redo the steps I used: https://gist.github.com/ipa-bak/732310132381c65b6636f9ce8f79ac54#file-make-bosh-cf-simple-sh . Save as "make-bosh-cf-simple.sh" and then adapt to your local system at the top of the script, then run with `./make-bosh-cf-simple.sh bosh`

I attached below the manifest used to create the director and the one used to deploy cf:
- Director manifest: [director-manifest.yaml.txt](https://github.com/cloudfoundry/cloud_controller_ng/files/5322389/director-manifest.yaml.txt)
- cf-deployment manifest: [cf-manifest.yaml.txt](https://github.com/cloudfoundry/cloud_controller_ng/files/5322390/cf-manifest.yaml.txt)

## Expected result

The app gets staged and eventually started.

## Current result

The `cf push` returns with error `StagingError - Staging error: staging failed`

It produces the following error messages:
``` 
Pushing app cf-ex-php-info to org cf-ex / space cf-ex-space as admin...
Applying manifest file /home/cf-test/workspace_2020-10-03-223039/cf-ex-php-info/manifest.yml...
Manifest applied
Packaging files to upload...
Uploading files...
 3.21 KiB / 3.21 KiB [==============================================================================================] 100.00% 1s

Waiting for API to complete processing files...   

Staging app and tracing logs...
   Downloading php_buildpack...
   Downloaded php_buildpack
   Cell b150fae6-354c-4217-b1fb-8b91c63f8d34 creating container for instance afec48b7-5b88-49f4-88d5-9fe66bb29e04
   Cell b150fae6-354c-4217-b1fb-8b91c63f8d34 failed to create container for instance afec48b7-5b88-49f4-88d5-9fe66bb29e04:
      OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:459: container init
      caused: process_linux.go:422: setting cgroup config for procHooks process caused: failed to write "1073741824" to
      "/sys/fs/cgroup/memory/docker/4e78cd5bc062e646907456357396a0f6c9715e46fa8bca62b0159f765d77f736/
      19de8c8c-3b71-448c-7b56-de1dc5baef61/garden/afec48b7-5b88-49f4-88d5-9fe66bb29e04/memory.memsw.limit_in_bytes":
      open /sys/fs/cgroup/memory/docker/4e78cd5bc062e646907456357396a0f6c9715e46fa8bca62b0159f765d77f736/
      19de8c8c-3b71-448c-7b56-de1dc5baef61/garden/afec48b7-5b88-49f4-88d5-9fe66bb29e04/memory.memsw.limit_in_bytes:
      permission denied: unknown
   Cell b150fae6-354c-4217-b1fb-8b91c63f8d34 destroying container for instance afec48b7-5b88-49f4-88d5-9fe66bb29e04
   Cell b150fae6-354c-4217-b1fb-8b91c63f8d34 successfully destroyed container for instance afec48b7-5b88-49f4-88d5-9fe66bb29e04
 ```
The lines from `Downloading php_buildpack...` to `successfully destroyed container` repeat four times.

I am not aware of other relevant logs, please let me know if I should look for a specific log file.

## Possible Fix

No specific suggestion, but a concourse installation (coming with the "bucc" installation method) running in the same director environment does work and can run its build containers inside the docker container.

**Comment by mnitchev** [comment]
Hello,
It looks like you don't have swap enabled on the diego-cell (which is probably expected with the docker cpi). Because of this garden can't write the swap memory limit in the cgroups file. We have a property in Garden for exactly this case [here](https://github.com/cloudfoundry/garden-runc-release/blob/bd0297dab8ebb0320862e33c296827338cdf1f2c/jobs/garden/spec#L167-L169). You can enable it with the following ops file, that you can [pass when deploying cf](https://gist.github.com/ipa-bak/732310132381c65b6636f9ce8f79ac54#file-make-bosh-cf-simple-sh-L254-L260): 
```yaml
---
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/disable_swap_limit?
  value: true
```
After redeploying it should work.

@cloudfoundry/cf-garden cc

**Comment by ipa-bak** [comment]
Hello @mnitchev , thanks for the suggestion.  I can confirm it now works for me.

It would be nice if links to such documentation could be included in the main ReadMe.md (here or in cf-deployment).

Anyway, fell free to close this issue as solved.
