### ISSUE TITLE
Frequent error in worker logs: "copilot.enabled" is not a valid config key

### ISSUE THREAD

**Issue by reidmit** [cloudfoundry/cloud_controller_ng#1883]
> Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

You're welcome!

## Issue

Poking through the worker logs, I see a bunch of lines like this:

```
{"timestamp":"2020-10-05T18:44:47.099211218Z","message":"failed communicating with copilot backend: \"copilot.enabled\" is not a valid config key","log_level":"error","source":"copilot_adapter","data":{"request_guid":"64b95f14-e5ad-4ae5-b7c5-b39bf4e8cffd::16cf40eb-3d25-4c87-94db-4f71c6e3288b"},"thread_id":47356977710560,"fiber_id":47357041155080,"process_id":1,"file":"/workspace/lib/cloud_controller/copilot/adapter.rb","lineno":87,"method":"rescue in with_guardrails"}
```

## Context

I wouldn't expect to see errors like this in the logs. It seems like a developer error (referring to an invalid config key). Can we make the logs less noisy?

## Steps to Reproduce

I think we just did some `cf push`es.

## Expected result

No errors like this logged.

## Current result

See logs above.

## Possible Fix

Not sure. Is copilot not a thing anymore?

cc @belinda-liu

**Comment by AP-Hunt** [comment]
Is there a known fix for this issue? We're seeing it in our logs more than 3800 times a day per production foundry, and causing us some alert blindness.

**Comment by sethboyles** [comment]
fixed by https://github.com/cloudfoundry/cloud_controller_ng/pull/2940
