### ISSUE TITLE
Service broker client does not handle redirects

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cloud_controller_ng#1893]
## Issue

The [service broker client](https://github.com/cloudfoundry/cloud_controller_ng/blob/51cd33a48fe2bd85c057b13dd69e05aa9380b342/lib/services/service_brokers/v2/http_client.rb#L11) in Cloud Controller does not appear to follow redirects (e.g. `301`).

We've observed this in environments where `http` is redirected to `https`, as is the case for service brokers that are deployed as apps on cf-for-k8s where this [redirection is configured by default](https://github.com/cloudfoundry/cf-for-k8s/blob/8e1ae38b4126f8d629f28015d21c015f19b7e512/config/istio/gateway.lib.yml#L19).

## Context

Brought to us via Slack by @reneighbor, this is resulting in failing CATS :
https://cloudfoundry.slack.com/archives/C017LDM6KTQ/p1602280933144500

## Steps to Reproduce

The test makes a request like this:
```
POST /v3/service_brokers HTTP/1.1
Host: api.approachable-mimicker.k8s-dev.relint.rocks
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/7.1.0+4c3168f9a.2020-09-09 (go1.13.8; amd64 darwin)
{
  "authentication": {
    "credentials": {
      "password": "[PRIVATE DATA HIDDEN]",
      "username": "username"
    },
    "type": "basic"
  },
  "name": "CATS-1-BRKR-9fff84a541fc6c28",
  "url": "http://CATS-1-BRKR-9fff84a541fc6c28.approachable-mimicker.k8s-dev.relint.rocks"
}
```

And the asynchronous job eventually fails with an error like this:
```
The service broker returned an invalid response. Status Code: 301 Moved Permanently, Body
```

## Expected result

I would expect the service broker client to follow the redirect.

## Current result

The service broker client does not follow the redirect and considers the `301` to be the final response.

## Possible Fix

Figure out why the client isn't following the redirect and see if you can make it do so. If this is impossible we can probably have the code check for redirect level status codes and manually remake the request to the correct endpoint as specified by the `Location` response header.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301

**Comment by blgm** [comment]
Fixed by #1896
