### ISSUE TITLE
Question: Case of instance_id of ServiceInstance

### ISSUE THREAD

**Issue by vivekzhere** [cloudfoundry/cloud_controller_ng#1894]
Our service is provisioned on k8s and is exposed on cloud foundry using OSB. [OSB spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#url-properties) does not place much restrictions on `instance_id`. I am using the `instance_id` as name for kubernetes resource created as part of instance provisioning. [Kubernetes Names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/) must contain only lowercase alphanumeric characters, `-` or `.`. Our broker have always received instance_id in this format only and never faced any issue with this (both from service catalog and cloud foundry).

I want to confirm that cloud foundry is not using mixed case for the `instance_id` . We are planning to just add a toLowerCase conversion on the `instance_id` and use it as kubernetes resource names. Here my concern is, if cloud foundry uses mixed case, it could possibly result in uniqueness conflict for the Kubernetes resource created.

https://github.com/kubernetes-sigs/service-catalog/issues/2845

**Comment by kirederik** [comment]
Hi @vivekzhere,

The `instance_id` generated by CAPI is a `UUID` and is case insensitive (and we only generate lower case UUIDs anyways).

I'll close this issue for now but feel free to reopen/comment if you have further questions.

We are also on [slack](https://slack.cloudfoundry.org/) at #capi :)

Thanks!
