### ISSUE TITLE
Create an alias for `diego_docker` feature flag

### ISSUE THREAD

**Issue by mike1808** [cloudfoundry/cloud_controller_ng#1912]
## Issue

Since Cloud Controller NG now runs for both cf-for-k8s and cf-for-vms the `diego_docker` feature flag name makes no sense for cf-for-k8s. I suggest to make an alias for this flag called something like `docker` or `container` and also rewrite documentation for it so it becomes platform agnostic.

I'm happy to help to contribute this change.

**Comment by sethboyles** [comment]
closing, as cf-for-k8s is deprecated
