### ISSUE TITLE
`/v3/droplets` should return the buildpacks used to stage a kpack lifecycle app

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#1916]
## Issue

In cf-for-k8s, Apps manager would like to display which buildpacks were used to produce app images via the kpack lifecycle type on the droplet.

## Context

Since user provided buildpacks are getting converted into docker images by kpack - at the droplet level lifecycle type is shown as docker. 

## Steps to Reproduce

1. Push an app to cf-for-k8s, specifying a buildpack to use in the manifest.
1. Inspect the current droplet for the app with `GET /v3/apps/:app-guid/droplets/current`

## Expected result
```
...
"lifecycle": {
      "type": "kpack",
      "data": {
         "buildpacks": [
            "tanzu-buildpacks/nodejs"
         ]
     }
 }
```

## Current result
```
...
 "lifecycle": {
      "type": "docker",
      "data": {}
  },
```

cc @reid47

**Comment by tcdowney** [comment]
Apparently the `lifecycle.data` key in the response has been hardcoded to be `{}` for a long time:
https://github.com/cloudfoundry/cloud_controller_ng/blob/a0402f489186c436781247c6433c3f80d59cc15d/app/presenters/v3/droplet_presenter.rb#L19

I think you actually might want this to be in the `buildpacks` array on a [Droplet](https://v3-apidocs.cloudfoundry.org/version/3.89.0/index.html#the-droplet-object)?

That is also missing on a `kpack` droplet, so this issue is still relevant. Just want to clarify the ask.

Example kpack droplet:
```json
{
   "guid": "3ad8f43d-cae9-4720-9a15-9a88d3fbac23",
   "created_at": "2020-10-19T23:35:42Z",
   "updated_at": "2020-10-19T23:37:03Z",
   "state": "STAGED",
   "error": null,
   "lifecycle": {
      "type": "kpack",
      "data": {}
   },
   "checksum": null,
   "buildpacks": null,
   "stack": null,
   "image": "gcr.io/cf-capi-arya/cf-workloads/aa1edbd2-3b82-493b-aa41-6d421c33959f@sha256:d37551c225ce80c54a2380806e13c9ff0d8199a707fb9879ba9b14fba3f95485",
   "execution_metadata": null,
   "process_types": {
      "web": "bundle",
      "worker": "bundle"
   },
   "relationships": {
      "app": {
         "data": {
            "guid": "aa1edbd2-3b82-493b-aa41-6d421c33959f"
         }
      }
   },
   "metadata": {
      "labels": {},
      "annotations": {}
   },
   "links": {
      "self": {
         "href": "https://api.tim.k8s.capi.land/v3/droplets/3ad8f43d-cae9-4720-9a15-9a88d3fbac23"
      },
      "app": {
         "href": "https://api.tim.k8s.capi.land/v3/apps/aa1edbd2-3b82-493b-aa41-6d421c33959f"
      },
      "assign_current_droplet": {
         "href": "https://api.tim.k8s.capi.land/v3/apps/aa1edbd2-3b82-493b-aa41-6d421c33959f/relationships/current_droplet",
         "method": "PATCH"
      },
      "package": {
         "href": "https://api.tim.k8s.capi.land/v3/packages/dcdfddbb-daa4-48c3-9cd7-784480ef3613"
      },
      "download": {
         "href": "https://api.tim.k8s.capi.land/v3/droplets/3ad8f43d-cae9-4720-9a15-9a88d3fbac23/download"
      }
   }
}
```

**Comment by reid47** [comment]
Oh, yeah that works too! (And is consistent with how buildpacks are listed on other droplets, rather than apps.) I think the main thing is we want to be able to read a list of buildpacks off of a kpack-produced droplet. I don't think we feel strongly about where exactly it appears in the JSON.

**Comment by sethboyles** [comment]
closing since cf-for-k8s is no longer under active development
