### ISSUE TITLE
push with "--strategy rolling" never completes [kubecf]

### ISSUE THREAD

**Issue by jimmykarily** [cloudfoundry/cloud_controller_ng#1952]
## Issue

Original issue: https://github.com/cloudfoundry-incubator/kubecf/issues/1354

In kubecf (see the lined issue above for specific versions), when pushing an app with `cf push dora --strategy rolling`, the old process doesn't get deleted, neither in the Cloud Controller database nor the Eirini side. After debugging (see the linked issue for logs), it turns out, the cloud controller never sends an app-stop request to Eirini so it doesn't seem to be an issue in the Eirini code.

The same steps (linked issue again), when run on a cf-for-k8s cluster, work fine. A request for deletion in that case is indeed sent and things on the Eirini side work as expected.

We tried to see if this is fixed in some later cloud_controller_ng commit than the one consumed by the kubecf version but we found no relevant changes. Maybe this rings some bells to someone more familiar with the cc code.

## Context

_See_ also linked issue above_

Kubecf versions:
- kubecf: 2.6.1
- cf-deployment: v13.17.0
- capi-release: 1.98.0
- cloud_controller_ng: ee7d6a6fb3232948cf7f7bff54c6b853822efa9c

cf-for-k8s:
- cf-for-k8s: v1.0.0
- capi-k8s-release: 29b77b94183a26cefdc98eff5825f22ae6c75090
- cloud_controller_ng: ? (can't find what version the above cf-for-k8s tag is using)

## Steps to Reproduce

- Deploy kubecf 2.6.1 with Eirini
- `cf push dora`
- wait for the deployment to finish
- `cf push dora --strategy rolling`

## Expected result

The old instance (pod) of the dora app should disappear from the k8s cluster and the `cf push` command should exit with success.

## Current result

`cf push` times out and both pods keep running.

_See linked issue on kubecf for logs_

## Possible Fix

Bump cloud controller to a version that fixed the problem? (if any)

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by sethboyles** [comment]
Hi @jimmykarily,

Unfortunately we are not too familiar with kubecf, but to me this sounds like it might be an issue with the configuration of the deployment updater in kubecf.  

Is there anything in the deployment updater logs that indicates an error?

**Comment by jimmykarily** [comment]
@sethboyles thank you for your answer. I think the deployment_updater is completely missing from kubecf. I updated the issue on the kubecf project: https://github.com/cloudfoundry-incubator/kubecf/issues/1354. I think we can close this issue. If there are problems after enabling the deployment_updater we can either re-open this issue or create another. Thanks.

**Comment by jimmykarily** [comment]
While debugging this issue, I realized that CC is handling the rolling deployments on it's own without leveraging any built-in kubernetes functionality (e.g. Statefulset's rolling updates). Wouldn't it be possible (and maybe better?) to let kubernetes handle the rolling deployments so CC has less to care about? I wonder if this has been thoroughly discussed already that's why I didn't open a new issue. I can open one if a discussion needs to happen.

**Comment by sethboyles** [comment]
I believe we discussed this at length earlier this year, and we ultimately decided that supporting deployments as they are currently implemented for k8s was lower risk for the time being, with the intention of eventually utilizing kubernetes's rolling updates (as well as many other features of k8s).  

I'm no longer on the cf-for-k8s team, however, so not sure what the status of the plan is today. I wouldn't object to a new issue either here or in https://github.com/cloudfoundry/capi-k8s-release so that the topic is more visible to those who have the same question.
