### ISSUE TITLE
`/v2/domains` doesn't check if subdomain is already owned by another org

### ISSUE THREAD

**Issue by dueckminor** [cloudfoundry/cloud_controller_ng#1962]
## Issue

`/v2/domains` doesn't check if subdomain is already owned by another org

## Context

Assuming you have a domain aaa.bbb.ccc.ddd in one CF org, it should not be possible to use `cf create-domain other_org bbb.ccc.ddd` or to use a REST-API call which does the same.

Using cf version 6.x and 7.x works as expected.
The REST-API endpoints `/v2/private_domains` and `/v3/domains` work as expected and reject the creation of the `bbb.ccc.ddd` domain.
But the `/v2/domains` endpoint allows to create the domain.

## Steps to Reproduce

Try to create the domain using `cf create-domain`
```
> cf create-domain evil-org bbb.ccc.ddd
Creating private domain bbb.ccc.ddd for org evil-org as provisioned_user_cf_admin...
The domain name "bbb.ccc.ddd" cannot be created because "aaa.bbb.ccc.ddd" is already reserved by another domain
FAILED
```

Try it using `/v2/domain`:
```
cf curl -X POST /v2/domains -d '{"name":"bbb.ccc.ddd","wildcard":true,"owning_organization_guid":"..."}'
```

## Expected result

I would expect that `/v2/domains` does the same checks as `/v2/private_domains` and `/v3/domains` and returns an error like this:
```
The domain name "bbb.ccc.ddd" cannot be created because "aaa.bbb.ccc.ddd" is already reserved by another domain
```

## Current result

`/v2/domains` allows to create domains which you can't create using the CF-CLI 

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by Gerg** [comment]
This endpoint has been deprecated as far back as the API docs go: https://apidocs.cloudfoundry.org/192/domains_(deprecated)/creates_a_domain_owned_by_the_given_organization_(deprecated).html. I think it's unlikely that we will prioritize fixing this behavior, though we would probably merge a PR.

We could also consider removing the endpoint, though that will likely break some client. Also, we are close (🤞) to deprecating and then disabling the entire v2 API, so this issue will resolve itself at that point.

**Comment by sethboyles** [comment]
Closing this as we are unlikely to prioritize this.  If you would like to create a PR, feel free to do so and we will reopen the issue.
