### ISSUE TITLE
GET v3 user space roles is slow

### ISSUE THREAD

**Issue by cloudmarius** [cloudfoundry/cloud_controller_ng#1974]
## Issue

Querying user v3 roles is slow.

## Context

```
      "cloud_controller_v2": {
         "href": "...",
         "meta": {
            "version": "2.156.0"
         }
      },
      "cloud_controller_v3": {
         "href": "...",
         "meta": {
            "version": "3.91.0"
         }
      }
```

## Steps to Reproduce

Given that user Anne is Space Auditor in space Dev
And given this amount of data in ccdb  
```
ccdb> select count(*) from users;
+----------+
| count(*) |
+----------+
| 2000     |
+----------+
ccdb> select count(*) from spaces_developers;
+----------+
| count(*) |
+----------+
| 10000    |
+----------+
ccdb> select count(*) from spaces_auditors;
+----------+
| count(*) |
+----------+
| 20000    |
+----------+
ccdb> select count(*) from spaces_managers;
+----------+
| count(*) |
+----------+
| 10000    |
+----------+
```
When querying 'cf curl "v3/roles?space_guids=space-dev-id&user_guids=user-anne-id" 
Then it takes an average of 3.5 seconds to retrive this 1 role

Given that user Anne is Space Auditor in space Dev
And given this amount of data in ccdb  
```
ccdb> select count(*) from users;
+----------+
| count(*) |
+----------+
| 5000     |
+----------+
ccdb> select count(*) from spaces_developers;
+----------+
| count(*) |
+----------+
| 3000     |
+----------+
ccdb> select count(*) from spaces_auditors;
+----------+
| count(*) |
+----------+
| 500      |
+----------+
ccdb> select count(*) from spaces_managers;
+----------+
| count(*) |
+----------+
| 2000     |
+----------+
```
When querying `cf curl "v3/roles?space_guids=space-dev-id&user_guids=user-anne-id" `
Then it takes an average of 0.6 seconds to retrieve this 1 role

## Expected result

Querying takes no more than 1 second with such (moderately large) amounts of data.

## Current result

Querying takes 4 seconds.

**Comment by philippthun** [comment]
There have been several performance improvements for v3 endpoints over the last months. For the `/v3/roles` endpoint especially [this PR](#3068) improved response times significantly. Thus I'm closing the issue.

**Comment by cloudmarius** [comment]
I confirm the improvements.
