### ISSUE TITLE
Race condition when a buildpack is deleted

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cloud_controller_ng#2010]
## Issue

Race condition when a buildpack is being deleted.

## Context

When you delete a buildpack, the blob is deleted first and then (to our understanding) the record in the database:
https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/actions/buildpack_delete.rb

If an app is pushed at the same time and uses buildpack auto-detection, the push can fail with:
```
Staging app and tracing logs...
Staging error: Missing blob for <buildpack being deleted>. Specify a different buildpack with the -b flag or contact your operator.
```
Note that the app uses a different buildpack. Workaround is to specify a fixed buildpack so that auto-detection does not try to use the buildpack being deleted.

## Steps to Reproduce

Could be reproduced by inserting a wait/sleep after blobstore deletion and before database deletion:
https://github.com/cloudfoundry/cloud_controller_ng/blob/76cb268b88909a0e07e60c3c3b82f1ce52fbe1be/app/actions/buildpack_delete.rb#L12

## Expected result

The push should not fail.

## Current result

The push can fail with the error shown above.

## Possible Fix

The database record should be deleted first so that the buildpack is not referenced in the auto-detect process. The buildpack blob should be deleted afterwards.

**Comment by philippthun** [comment]
Fixed with #2133.
