### ISSUE TITLE
V3 CAPI equivalents for /v2/spaces/<guid>/summary and  /v2/services

### ISSUE THREAD

**Issue by mvadu** [cloudfoundry/cloud_controller_ng#2016]
## Issue

Is there any document which maps V2->V3 equivalent CAPI entry points? I am looking for V3 CAPI equivalents for `/v2/spaces/<guid>/summary` and  `/v2/services`. 

## Context
I am trying to get a single page view which shows all the service instances across orgs and spaces. Kind of iterative execution of `cf target` followed by `cf services`, but using CAPI with dotnet core instead of CLI. When you try `cf services` internally it runs 
1. [GET /v2/spaces/<guid>/summary](https://apidocs.cloudfoundry.org/15.3.0/spaces/get_space_summary.html) - Gets the service instances in the space
2. [GET /v2/services](https://apidocs.cloudfoundry.org/15.3.0/services/list_all_services.html) - Gets the available services for te foundation, and probably uses it to reverse look with the first response to determine if update is available. 

But in V3 API both of these are not available. What is the recommended way of getting this data in V3 API? I don't want to spend time on V2 which is already marked "**deprecated**".

**Comment by FelisiaM** [comment]
Hi @mvadu 

In V3 you can use different [query filters](http://v3-apidocs.cloudfoundry.org/version/3.94.0/index.html#list-service-instances) and [fields](http://v3-apidocs.cloudfoundry.org/version/3.94.0/index.html#fields-parameter) to achieve a similar result to what a V2 summary endpoint was doing. 

For example the combination of target and services command will be something like `/v3/service_instances?fields[service_plan.service_offering.service_broker]=guid,name&fields[service_plan.service_offering]=guid,name,relationships.service_broker&fields[service_plan]=guid,name,relationships.service_offering&space_guids=<target_space_guid>` 

Given your feedback, I will add a [task](https://www.pivotaltracker.com/story/show/176339636) in the backlog to make sure that the replacements for the summary endpoints are documented in the [upgrade guide](http://v3-apidocs.cloudfoundry.org/version/3.94.0/index.html#upgrade-guide).

Thanks,
Felisia

**Comment by FelisiaM** [comment]
Hi @mvadu 

We have added more details on the upgrade guide on how to get similar fields as the summary endpoints used to expose. You can find it [here](http://v3-apidocs.cloudfoundry.org/version/release-candidate/#resource-summaries).

I am now closing this issue.

Thanks,
Felisia

**Comment by mvadu** [comment]
@FelisiaM I finally got a chance to go through the new documentation. Makes much more sense. One followup question:
[documentation you updated](http://v3-apidocs.cloudfoundry.org/version/release-candidate/#resource-summaries) says "To fetch all apps in a space, use `GET /v3/apps?space_guids=<space-guid>`", but the old Apps section of space summary gave us few key health points e.g. `instances`, `running_instances`, `memory` etc. But [the app object](http://v3-apidocs.cloudfoundry.org/version/release-candidate/#the-app-object) in V3 does not have those. Could you please help me how to get app side view similar to app object in V2 space/summary end point?
