### ISSUE TITLE
Issue with unauthenticated rate limits for CF API clients sharing IP addresses

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/cloud_controller_ng#2040]
Follow-up of discussion on [capi slack](https://cloudfoundry.slack.com/archives/C07C04W4Q/p1609946417352600).

CF API implements two kinds of [rate limiting](https://docs.cloudfoundry.org/running/setting-rate-limit-cloud-api.html): 
- rate limits for authenticated requests (counted per user)
- rate limits for unauthenticated requests (counted per IP address)

Unauthenticated rate limits based on IP address can become a problem when many CF API clients share the same IP address. This happens e.g. when the CF API clients are CF applications. CF foundations usually have just a very few outgoing IP addresses due to NAT. This means that the unauthenticated rate limit becomes a shared resource for such CF API clients and if one of these clients consumes all unauthenticated requests (e.g. due to bug), other CF API clients sharing the same IPs can get impacted.

One could assume that a well-behaving client never calls the CF API unauthenticated. Unfortunately, this is not the case when using the typical CF API client libs (e.g. https://github.com/cloudfoundry/cf-java-client). These libraries use the access token until the CF API responds with a 401 on an expired token, then refresh the access token and retry the request. Works well ... until unauthenticated rate limiting kicks in and responds 429 instead of 401. 429 is not handled by the CF java client lib.

The current CF API behavior on an expired access token is:
- 401 if the unauthenticated rate limit for the IP is not yet reached, unauthenticated rate limit counter is incremented
- 429 if the unauthenticated rate limit for the IP was already reached

This is not necessarily wrong from CC point of view but it is unexpected from CF API clients/libs that rely on a working access token refresh. As explained above a refresh is not properly implemented in many CF API client libs in case the (shared) unauthenticated rate limit was reached.

Possible solutions:

**CC prefers 401 over 429**

CC responds always 401 on an expired access token so that CF API client libs handle the refresh. The request can still be counted on unauthenticated rate limits.

CC responds 429 on requests without access token or if the access token is invalid for other reasons (e.g. can't be parsed, invalid signature etc.).

This fixes the described issue without having to adapt all CF API client libs and/or apps.

**CF API client libs implement 429 handling**

CF API client libs could implement token refresh on 429 (when hitting the unauthenticated limit only).
This was proposed for cf-java-client in https://github.com/cloudfoundry/cf-java-client/issues/960 nearly 2 years ago but not implemented so far. 

Alternatively, a CF API client could ensure that it never calls the CF API with an expired or soon to expire access token. This solution was applied to cf cli: https://github.com/cloudfoundry/cli/issues/1582

Drawback is that the 429 handling has to be implemented in every CF API client lib. Refresh on 401 is usually implemented in contrast to 429 handling.

**Disable unauthenticated rate limits**

A final solution could be to disable CF API rate limiting for unauthenticated access. There might be a higher risk of overloading the CC because unauthenticated requests get recognized later in CC coding. DoS attacks via /v3/service_offerings would be possible if the feature flag hide_marketplace_from_unauthenticated_users is not set to true.

**Comment by Gerg** [comment]
I think the "CC prefers 401 over 429" solution makes sense. One nuance that there are some intentionally unauthenticated endpoints, and we would still want to return `429` when the user is rate-limited.

**Comment by sethboyles** [comment]
I think this approach is reasonable and I would be OK with you all moving forward with this solution.  

When writing tests, can you include one that ensures that when calling an Unauthenticated request with an Expired but Otherwise Valid token, that rate limiting is still being applied?

**Comment by elenasharma** [comment]
Thanks for raising this issue with us! Since this issue has been addressed with https://github.com/cloudfoundry/cloud_controller_ng/pull/2079, I am going to close out this issue. The change is planned for our next release, capi-release `1.108.0`.
