### ISSUE TITLE
Revisions support

### ISSUE THREAD

**Issue by MTudorrrr** [cloudfoundry/cloud_controller_ng#2044]
Hello cloud_controller_ng team.
I found 2 sources of documentation for revisions functionality:
1. https://docs.cloudfoundry.org/devguide/revisions.html
2. https://v3-apidocs.cloudfoundry.org/version/3.94.0/index.html#revisions
On second one revisions are mentioned under "Experimental Resources".
Is it a kind of Beta feature?  Is it safe to use it?

Regards,
Tudor

**Comment by Gerg** [comment]
The revisions APIs are currently experimental and my have breaking changes in future releases. That said, they are currently functional, so you can use them if you don't mind potentially having to make some changes in a future release.

I've submitted a PR (https://github.com/cloudfoundry/docs-dev-guide/pull/421) to update the docs.
