### ISSUE TITLE
Create new CC role for an application troubleshooter/support persona

### ISSUE THREAD

**Issue by piyalibanerjee** [cloudfoundry/cloud_controller_ng#2178]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

This issue will be used for tracking purposes only. See tasks for issues capturing granular work.

## Context

As a CF space manager, I want to have fine-grained control on the authorizations of my space users, so that I can grant only the actually required authorizations and thus avoid issues like leakage of credentials, unauthorized access to critical data, corruption of data by mistake (e.g. deletion of service instances). 

One such granular space-level persona would be an application support persona who would have the following capabilities/restrictions:
- Can display action logs
- Can start, stop, restage and restart applications
- Can view lifecycle events for application
- Can read, bind and unbind service instances
- Can scale applications
- Cannot display application environment (=> reveals technical credentials)
- Cannot create, update or delete service instances
- Cannot create new packages or update source code. As a result, wouldn't be authorized to cf push 

A `401 unauthorized` error should be returned with a helpful error message for the unauthorized actions. Authorized actions should behave as normal.

**Comment by piyalibanerjee** [comment]
- [ ] blah test

**Comment by philippthun** [comment]
The `Space Supporter` role has been implemented: https://github.com/orgs/cloudfoundry/projects/6
