### ISSUE TITLE
numbers with commas in space manifests get parsed as an integer, not a string

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/cloud_controller_ng#2193]
## Issue

When pushing an application with the following manifest file: 

```
applications:
- name: dora

env:
INTEGER: 1234,567,89
```

When they run cf env the variable INTEGER is not handled correctly and is returned as follows: 

```
INTEGER: 123456789
```

The commas are removed and the field is parsed as an integer instead of a string.  This is different than CF CLI v6's behavior and contrary to the YAML spec definition of an integer (and float): https://yaml.org/spec/1.2/spec.html#id2803828

## Context

This is caused by an issue with Ruby's included YAML parsing library, Psych.  There is an [old issue from 2016](https://github.com/ruby/psych/issues/273) where they note it is not fixed due to backwards compatibility concerns.  

## Expected result

`INTEGER: 1234,567,89` should be parsed as a string (EDIT: actually maybe it should be an array?)

## Current result

`INTEGER: 1234,567,89` is parsed as an integer `1234,567,89`

## Possible Fix

We could make a PR into https://github.com/ruby/psych, or we could switch libraries (if there even are others to choose from).  

We could try pre-parsing the YAML before we pass it to Psych, however I would expect that to be difficult and fraught with other issues.

- @sethboyles & @MarcPaquette

**Comment by thelangley** [comment]
hey it looks like a potential fix was merged into psych. https://github.com/ruby/psych/issues/273

do we need an official release of psych to be cut before testing this new strict_integer functionality?
