### ISSUE TITLE
Help **fog-azure-rm** upgrade (or pin) **azure-storage**

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/cloud_controller_ng#2197]
In response to the Azure regression introduced in https://github.com/cloudfoundry/capi-release/releases/tag/1.97.0

**The Situation**
1. CC uses [fog-azure-rm](https://github.com/fog/fog-azure-rm) for communicating with Azure blobstores
2. fog-azure-rm uses [azure-storage](https://github.com/Azure/azure-storage-ruby) under the hood
3. azure-storage has [a bug](https://github.com/Azure/azure-storage-ruby/issues/122) between `0.15.0.preview` and `1.1.0` that breaks resource matching
4. We use a [cf-specific branch](https://github.com/fog/fog-azure-rm/tree/fog-arm-cf) of fog-azure-rm
5. That branch [depends on azure-storage < 1.0](https://github.com/fog/fog-azure-rm/blob/baaf3f4d684f82561aa8695412fec98f363bdd7f/fog-azure-rm.gemspec#L35), so Bundler keeps trying to upgrade azure-storage to `0.15.0.preview` (which has the bug)
6. Master of fog-azure-rm is pinned to [an even older version of azure-storage](https://github.com/fog/fog-azure-rm/blob/master/fog-azure-rm.gemspec#L35)

**To Do**
Ideally bundler (and dependabot) shouldn't try to upgrade us to a broken version of fog-azure-rm. It would also be cool if in the future we could move to newer versions of fog-azure-rm and azure-storage for new features and security fixes.

Some possible paths forward:
1. Move to the mainline releases of fog-azure-rm, assuming it has the features we need from our special branch
2. Convince the fog-azure-rm maintainers to pin fog-storage on our special branch to a version < `0.15.0.preview`
3. Convince the fog-azure-rm maintainers to bump fog-storage on our special branch to a version >= `1.1.0`
4. Some other, even better, plan

**Deliverable:** One or more of the following:
1. A github issue against fog-azure-rm
2. A github PR against fog-azure-rm
3. A change to the version of the fog-azure-rm that CC uses

**Notes:**
1. If relevant, you can deliver this story when the issue or PR is submitted. No need to wait for the issue/PR to be resolved.
2. There is currently [a PR](https://github.com/fog/fog-azure-rm/pull/418) for bumping azure-storage in fog-azure-rm
3. Related issue: https://github.com/cloudfoundry/cloud_controller_ng/issues/1846

**Comment by sethboyles** [comment]
this issue has been migrated from this Tracker story: https://www.pivotaltracker.com/story/show/174179944

Please refer to that story for additional context

**Comment by JenGoldstrich** [comment]
### Current status of this track and next steps forward

@tstannard and I tried to update the fog-azure-rm gem by updating to the newest version of all the sub-dependancies for azure-storage, this resulted in a lot of failing tests and general Chaos®.  

[Link to fork](github.com/tstannard/fog-azure-rm),

After talking with @jenspinney we have decided that we should is do the minimum bump we can to get the bugfix above.

This should minimize the complexity of the change.  The CAPI team will reach out afterwards to the maintainers of this repo again and see if we can get traction on their side.

[GitHub issue link](https://github.com/fog/fog-azure-rm/issues/436)

**Comment by sethboyles** [comment]
@JenGoldstrich @tstannard It seems that fork is private, can you add me and @MarcPaquette as contributors?

**Comment by MarcPaquette** [comment]
Just a bad link: https://github.com/tstannard/fog-azure-rm

**Comment by JenGoldstrich** [comment]
Seth and I submitted a PR to fog-azure-rm [here](https://github.com/fog/fog-azure-rm/pull/438) to bump to the deps to 1.1, @jenspinney's idea to go from fog-arm-cf .15.preview => 1.1 was the right call!

**Comment by sethboyles** [comment]
resolved by #2690
