### ISSUE TITLE
**API** client can see **memory** used for **builds**

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/cloud_controller_ng#2204]
**Context**

** This should be done alongside https://www.pivotaltracker.com/story/show/177103073**

Follow up to https://www.pivotaltracker.com/story/show/174473957. 

Builds currently support `staging_memory_in_mb` and `staging_disk_in_mb` fields which override the memory and disk used to stage the application. These are useful in some cases where an app requires more resources to stage than it needs to run. However, these fields are currently write-only, so API clients can't tell how much memory/disk was used and it is difficult to discover these fields in the first place (especially since we didn't have documentation for them).

Our objective is to always display how much memory/disk a build will use/has used on the build object.

---

**Acceptance Criteria**

### Default Memory

**Given** an app with a web process
**And** the web process is scaled to `1024` `memory_in_mb`
**When** I create a build for the app
**Then** that build's `staging_memory_in_mb` should display `1024`

---

### Override Memory

**Given** an app with a web process
**And** the web process is scaled to `1024` `memory_in_mb`
**When** I create a build for the app
**And** I specify `staging_memory_in_mb` is `2048` on the build
**Then** that build's `staging_memory_in_mb` should display `2048`

---

### Minimum Memory

**Given** an app with a web process
**And** the web process is scaled to `1024` `memory_in_mb`
**And** the system [minimum staging memory](https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/capi-release&version=1.99.0#p%3ddea_next.staging_memory_limit_mb) is `2048`
**When** I create a build for the app
**And** I specify `staging_memory_in_mb` is `1024` on the build
**Then** that build's `staging_memory_in_mb` should display `2048`

---

### ✍️Document Staging Memory  📝

**Given** browsing the v3 API docs
**When** I view the builds resource
**Then** there is documentation for the `staging_memory_in_mb` field
**And** it appears in the examples

---

Notes:
- No need to backfill data for old builds. Happy to chat about any other migration concerns.

**Comment by sethboyles** [comment]
migrated from https://www.pivotaltracker.com/story/show/175148968

**Comment by sweinstein22** [comment]
Docs addressed in https://github.com/cloudfoundry/cloud_controller_ng/commit/83913d297f2aca8941070133441c2b23fb705f03
