### ISSUE TITLE
Allow space application supporter to access specific process endpoints. 

### ISSUE THREAD

**Issue by MerricdeLauney** [cloudfoundry/cloud_controller_ng#2211]
## Issue

Allow space application supporter to access specific process endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

GET /v3/processes/:guid
GET /v3/processes/:guid/stats
GET /v3/apps/:guid/processes/:type
GET /v3/apps/:guid/processes/:type/stats
GET /v3/processes
GET /v3/apps/:guid/processes
PATCH /v3/processes/:guid
POST /v3/processes/:guid/actions/scale
POST /v3/apps/:guid/processes/:type/actions/scale
DELETE /v3/processes/:guid/instances/:index
DELETE /v3/apps/:guid/processes/:type/instances/:index

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these process endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

**Comment by belinda-liu** [comment]
There's an existing pattern to redact the start command in process endpoint responses when the user is an auditor. For example, querying a process as a space auditor yields:
```
{                                                                                                                                                                                                                                                                            "guid": "01c2ec0c-dbbe-486c-8472-24668fe9397e",
         "created_at": "2021-06-08T00:02:57Z",                                                                                                                                                                                                                                      "updated_at": "2021-06-08T00:02:57Z",
         "type": "web",
         "command": "[PRIVATE DATA HIDDEN]",
         "instances": 2,
         "memory_in_mb": 1024,
         "disk_in_mb": 1024,
...
}
```
Should a space application support be able to see the start command, or should the response for that role also redact this information?

cc: @monamohebbi @MerricdeLauney
