### ISSUE TITLE
Allow space application supporter to access specific build endpoints. 

### ISSUE THREAD

**Issue by MerricdeLauney** [cloudfoundry/cloud_controller_ng#2212]
## Issue

Allow space application supporter to access specific **build** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

POST /v3/builds
GET /v3/builds/:guid
GET /v3/builds
GET /v3/apps/:guid/builds
PATCH /v3/builds/:guid

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these build endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

**Comment by monamohebbi** [comment]
We are not sure this role will need to restage. Putting this down unless we receive feedback in favor of restaging.
