### ISSUE TITLE
Allow space application supporter to access specific droplet endpoints.

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2220]
## Issue

Allow space application supporter to access specific **droplet** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

GET /v3/droplets/:guid 
GET /v3/droplets
GET /v3/packages/:guid/droplets 
GET /v3/apps/:guid/droplets

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these droplet endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

**Comment by ctlong** [comment]
@monamohebbi @sweinstein22 Should `GET /v3/droplets/:guid` for Space Application Supporters be redacted in a similar way to the org and space managers, and all auditors? Only admin roles and developers are able to access the non-redacted list at present.

Specifically, this redaction replaces the contents of the `execution_metadata` and `process_types` keys with messages like `[PRIVATE DATA HIDDEN]`.
