### ISSUE TITLE
Allow space application supporter to access specific job endpoints.

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2224]
## Issue

Allow space application supporter to access specific **job** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

GET /v3/jobs/:guid

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these job endpoints.

**Comment by philippthun** [comment]
@monamohebbi @sweinstein22 - There is a deviation between the documentation of the `GET /v3/jobs/:guid` endpoint and its implementation. As there is no permissions check in the coding ([jobs_controller.rb](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/v3/jobs_controller.rb)), all authenticated users can access this endpoint (i.e. including Org Auditor, Org Billing Manager and users with no role at all). Shall the documentation be fixed or the implementation?

If we decide to simply adapt the documentation, I would also think that we don't even need tests and can simply move this issue to the Acceptance column.

**Comment by sweinstein22** [comment]
Hi @philippthun , I think the behavior should be that jobs are visible to everyone who has an assigned role, which means a slight change on both sides. On the implementation side, users with no role at all should not be able to hit `GET /v3/jobs/:guid`. On the documentation side we can change the permissions to say "All Roles". Thanks for catching that!

**Comment by philippthun** [comment]
@sweinstein22 I've now adjusted the documentation (e.g. "All Roles" are permitted) and added some tests. I did not adjust the implementation as the code seems to be in line with other endpoints (e.g. `/v3/stacks/:guid`) that also claim to be accessible for "All Roles". So even a user with [no_role](https://github.com/cloudfoundry/cloud_controller_ng/blob/4b770eb2587c7841e9f591172c96b4f1233a6f99/spec/request_spec_shared_examples.rb#L14) has access; as long as the `cloud_controller.read` scope is set.
