### ISSUE TITLE
Allow space application supporter to access specific packages endpoints.

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2225]
## Issue

Allow space application supporter to access specific **packages** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

GET /v3/packages/:guid
GET /v3/apps/:guid/packages

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these packages endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

**Comment by philippthun** [comment]
@will-gant and I are working on this one.
