### ISSUE TITLE
Allow space application supporter to access specific service offering endpoints.

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2240]
## Issue

Allow space application supporter to access specific **service offering** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

GET /v3/service_offering
GET /v3/service_offerings/:guid

A space supporter should get a 403 unauthorized when attempting to curl the following endpoints:

PATCH /v3/service_offerings/:guid
DELETE /v3/service_offerings/:guid

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these service offering endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

**Comment by will-gant** [comment]
Starting this now.

**Comment by will-gant** [comment]
Could I please just query the access that we want the space application supporter to have to the `/v3/service_offerings/:guid` endpoint? That isn't mentioned in this story, but [the docs](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#visibility-of-service-offerings) indicate that all roles can get _public_ service offerings, and also any that are scoped to either the org or the space that that role is a member of.

If it's desired that `/v3/service_offerings/:guid` is in fact completely off limits to the space application supporter (which would be more restrictive than is the case for, say, space auditors) then that will require further changes.

**Comment by monamohebbi** [comment]
Hi @will-gant,

Sorry for the delayed response. This is another oversight. I will update the issue and leave a comment on the PR as well. Thanks!
