### ISSUE TITLE
Allow space application supporter to access specific service binding endpoints.

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2241]
## Issue

Allow space supporter to access specific **service binding** endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space supporter should be able access the following endpoints:

POST /v3/service_credential_bindings
DELETE /v3/service_credential_bindings
GET /v3/service_credential_bindings
GET /v3/service_credential_bindings/:guid
GET /v3/service_credential_bindings/:guid/parameters

A space supporter should get a 403 unauthorized when attempting to curl the following endpoints:

PATCH /v3/service_credential_bindings/:guid

A space supporter should get a 404 when attempting to curl the following endpoints:

GET /v3/service_credential_bindings/:guid/details 

## Acceptance
A space supporter would see the same info as a space developer assigned to the same space for these and only these service binding endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

**Comment by iaftab-alam** [comment]
Hey @monamohebbi,

I have checked the [V3 documentations](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#the-service-credential-binding-object) and there are some other service binding endpoints that I guess are missing. Please nudge me in the right direction If my understanding is wrong and such endpoints are not left out on purpose, i.e., I can see in the above comment that you have mentioned **"...only these service binding endpoints."**) (for instance, to be tested in next round or in other backlog).

So the other endpoints which are not mentioned here(above) are for example,

- GET, PATCH and DELETE  /v3/service_credential_bindings/:guid
- GET /v3/service_credential_bindings/:guid/parameters (space application supporter role should have access to this one but not to the details ).

Regards,
Aftab

**Comment by monamohebbi** [comment]
Hi @iaftab-alam,

Sorry for the delayed response. 

DELETE v3/service_credential_bindings/:guid is the full path for the delete endpoint I can clarify and update the issue.
GET v3/service_credential_bindings/:guid should be included, so thank you for bringing this to my attention!
PATCH v3/service_credential_bindings/:guid only allows for metadata updates which we have decided to skip for this role across the resources for now

We were not familiar with use cases around the /v3/service_credential_bindings/:guid/parameters endpoint and didn't receive much feedback around it so decided not to unblock it. However, we can still change this if you can bring up any examples on how this endpoint could be used in a support role or can guarantee that no app secrets can live here.

Thanks,
Mona

**Comment by stephanme** [comment]
SpaceSupporters shall be able to manage service bindings for existing service instances. Therefore I would include/allow:

PATCH v3/service_credential_bindings/:guid - Update meta data, SpaceSupporter can also set meta data on binding creation.
GET /v3/service_credential_bindings/:guid/parameters - same argumentation. SpaceSupporter can set parameters on binding creation so read should be possible as well.

I think that we have to forbid:
GET /v3/service_credential_bindings/:guid/details
because according to the example response show in https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#get-a-service-credential-binding-details it delivers the credentials - and they shall never be visible for SpaceSupporters.

I haven't checked the implementation but I wonder if this endpoint is a possible bypass for SpaceDevelopers on foundations with disabled  space_developer_env_var_visibility feature flag.

**Comment by iaftab-alam** [comment]
already working on it.

**Comment by monamohebbi** [comment]
I think `GET /v3/service_credential_bindings/:guid/details` is too risky to expose, flag or not. However it is useful to hear use cases for the parameters endpoints, we can make that allowed. As a first pass implementation we have blocked metadata and label updates across all endpoints and I think it would be a bit awkward to allow it for just this endpoint. If this is something we receive a lot of requests for, we can always start a new feature story to allow metadata updates in future releases.

**Comment by iaftab-alam** [comment]
hey @monamohebbi,

One question related to 404 code error for the the following endpoints:

- GET /v3/service_credential_bindings/:guid/details
- PATCH /v3/service_credential_bindings/:guid

As per issue description, you explicitly mentioned it that the space supporter should get 403 for the above two endpoints. However, for other roles, we are expecting to have 404 and for me it does not make sense to have 403 (though it should be 403 not 404 for all other roles) for these two endpoints only. You can check the 404 codes for other roles:

https://github.com/cloudfoundry/cloud_controller_ng/blob/a3d28a08dc6c052b963c075e4995d1a8edf3814f/spec/request/service_credential_bindings_spec.rb#L614

Can you please share your thoughts on this. Thanks

Regards,
Aftab

**Comment by monamohebbi** [comment]
Hi @iaftab-alam,

Thanks for catching this! We want to get the 404 for  `GET /v3/service_credential_bindings/:guid/details`. However a 403 is still desired behavior for `PATCH /v3/service_credential_bindings/:guid` because we are allowing `GET /v3/service_credential_bindings/:guid`

**Comment by iaftab-alam** [comment]
hey @monamohebbi,

Thank you for the feedback. As per suggestions, changes are made and as a result the PR is ready.

Regards,
Aftab
