### ISSUE TITLE
manifest_diff showing diff where top-level app fields incorrectly are being compared to web process-level fields

### ISSUE THREAD

**Issue by elenasharma** [cloudfoundry/cloud_controller_ng#2243]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

The manifest_diff endpoint shows an incorrect diff when top-level application fields conflict with web process fields.

## Context

When I create a [manifest diff](https://v3-apidocs.cloudfoundry.org/version/release-candidate/#create-a-manifest-diff-for-a-space-experimental) with a manifest like the following:

```
---
applications:
- name: test-app
  memory: 1024M
  processes:
  - type: web
    instances: 2
    memory: '256M'
```

I get an incorrect diff result:

```
{
   "diff": [
      {
         "op": "replace",
         "path": "/applications/0/memory",
         "was": "256M",
         "value": "1024M"
      }
   ]
}
```

The resulting diff has the top-level application `memory` value of "1024M" replacing the web process' `memory` value of "256M", even though the process memory has not been replaced.

## Steps to Reproduce

1. Push an application with a manifest in which there's a top-level application field (e.g. `memory`) that is the same as a web process field.
1. Without altering the manifest file, use the space guid of the space that the above app is in to create a manifest diff e.g. `cf curl /v3/spaces/<SPACE_GUID>/manifest_diff -X POST -H "Content-Type: application/x-yaml" -d @<PATH_TO_MANIFEST_FILE>`
1. Observe that in the resulting diff, the web process value appears to be replaced by the top-level application value.

## Expected result

I would expect to see no diff, e.g.

```
{
   "diff": []
}
```

## Current result

The current result is a diff with a "replace":

```
{
   "diff": [
      {
         "op": "replace",
         "path": "/applications/<PROCESS_INDEX>/<FIELD>",
         "was": "<PROCESS_VALUE>",
         "value": "<TOP_LEVEL_APPLICATION_VALUE"
      }
   ]
}
```

**Comment by sweinstein22** [comment]
After further discussion we've decided to ignore top-level `memory` and `disk-quota` keys, as they're not part of the supported, documented [v3 manifest schema](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#the-manifest-schema). Those keys will still have an impact when applying manifests or pushing applications in order to preserve backwards compatibility, however they will be ignored in visual app manifest diffs ([the `GET /v3/apps/:guid/manifest` endpoint](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#generate-a-manifest-for-an-app))

**Comment by bepotts** [comment]
This issue has been addressed and move into main. The merge can be viewed [here](https://github.com/cloudfoundry/cloud_controller_ng/commit/2e5b0f7245fa09272b1ee71fac3a81fcb3fa5a78)

**Comment by sethboyles** [comment]
closing as this was fixed a while ago
