### ISSUE TITLE
Allow sparse instance indexes

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cloud_controller_ng#2247]
## Issue

The Eirini team is planning to support Kubernetes [`Deployment`s](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) in addition to [`StatefulSet`s](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) for workloads. In order to do so, some assumptions about instance indexes would have to be removed from the Cloud Controller.

## Context

This change would lead to relaxing our guarantees on instance indexes: instead of forming a `0..n` sequence, indexes would be sparse in a quite wide range (from 1 to 60,466,177 😅 ). Instances would still be uniquely identifiable but indexes wouldn't be stable (they would change every time an instance is recreated for any reason), ordered or contiguous.

While [investigating this](https://github.com/cloudfoundry-incubator/eirini-release/issues/207), we could only find one place where this assumption is made, in [`app/actions/process_terminate.rb`](https://github.com/cloudfoundry/cloud_controller_ng/blob/637fe7d6449a593e89fc344d0745aadfad221f5c/app/actions/process_terminate.rb#L12):
```ruby
raise InstanceNotFound unless @index < @process.instances && @index >= 0
```
* What do you think about removing this check  and letting Cloud Controller fail only for instance that don't actually exist?
* Can you think of other places in CC where our change could cause problems?

For more context, see cloudfoundry-incubator/eirini-release#207.

Thanks!
/cc @cloudfoundry/eirini

**Comment by tcdowney** [comment]
Here's at least one other place where this kind of check is done:
https://github.com/cloudfoundry/cloud_controller_ng/blob/24a27be681db02035d48dcdb119827d2e3df5230/lib/cloud_controller/diego/reporters/instances_stats_reporter.rb#L42

**Comment by sethboyles** [comment]
What would these checks be replaced with?

**Comment by gcapizzi** [comment]
> What would these checks be replaced with?

@sethboyles We would have to actually assess that the index exists instead of just checking that the index is in range, potentially storing the indexes explicitly. This is an issue we would have to solve for alphanumeric indexes too.
