### ISSUE TITLE
Space Application Supporter can access specific app POST endpoints

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2280]
## Issue

Allow space application supporter to access specific app endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoints:

- [x] POST /v3/apps/:guid/actions/start
- [x] POST /v3/apps/:guid/actions/stop
- [x] POST /v3/apps/:guid/actions/restart
- [ ] PATCH /v3/apps/:guid/features/revisions
- [ ] PATCH /v3/apps/:guid/relationships/current_droplet

## Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these endpoints.

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing.

**Comment by sweinstein22** [comment]
Still some pieces of this that haven't been addressed quite yet. First PR has been merged, going to work on acceptance for the second one, will close this issue when all endpoints mentioned are addressed
