### ISSUE TITLE
/v3/apps does not offer app.version

### ISSUE THREAD

**Issue by h0nIg** [cloudfoundry/cloud_controller_ng#2296]
## Issue
/v3/apps does not offer app.version

## Context
We use this to get into the application instance container, as we need to form the process id. The version attribute is no longer offered via /v3/processes nor /v3/apps. https://community.pivotal.io/s/article/How-to-get-into-an-App-Container-Manually-with-Garden-RunC-Backend?language=en_US, see point 1 "1. Establish the process-guid for the app:"

## Steps to Reproduce
cf curl

## Expected result

containing version attribute

## Current result
missing version attribute

## Possible Fix
add version attribute to /v3/apps

**Comment by MarcPaquette** [comment]
Hi @h0nIg,

Can you go into a bit more detail on how you are using this information? I'd like to understand your use case a bit more before choosing a path forward.

In addition, have you taken a look at the [revisions](https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#revisions) endpoint?

Thanks,
Marc

**Comment by h0nIg** [comment]
@MarcPaquette, we are required to use this version attribute in order to get into the garden runc container. Please checkout https://community.pivotal.io/s/article/How-to-get-into-an-App-Container-Manually-with-Garden-RunC-Backend?language=en_US

![grafik](https://user-images.githubusercontent.com/2757302/120080757-ac2ccf80-c0ba-11eb-9f1c-6574c04c5374.png)


yes, the revisions endpoint does not offer this information, just cross checked this:
```
∆ cf app --guid XXX
2be241c3-4816-482c-8d7d-28ea0b053c3e
∆ cf curl /v2/apps/2be241c3-4816-482c-8d7d-28ea0b053c3e | grep version
      "version": "60a6c47e-3ed1-4565-9a21-86247f42b630",
∆ CF_TRACE=true cf revisions XXX | grep 60a6c47e-3ed1-4565-9a21-86247f42b630
This command is in EXPERIMENTAL stage and may change without notice
```

**Comment by tjvman** [comment]
You don't actually need the `app.version` field to get the container guid; the app guid alone is sufficient. Replace the command in step 3 with:
```
cfdot actual-lrps | jq -r 'select(.process_guid | startswith("<app guid>")) | .instance_guid' | head -n1
```

We don't have plans to add the `version` field to /v3.

**Comment by elenasharma** [comment]
Closing this issue, as there's another route for getting the container guid.
