### ISSUE TITLE
Audit Events filter now working- GET /v3/audit_events?created_ats[lt]=2020-01-02T00:00:00Z&created_ats[gt]=2019-12-31T23:59:59Z

### ISSUE THREAD

**Issue by rchalapaka** [cloudfoundry/cloud_controller_ng#2298]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue
Audit Events time interval not working. Need this to retrieve all the events for a time interval thru our scheduler.
GET /v3/audit_events?created_ats[lt]=2020-01-02T00:00:00Z&created_ats[gt]=2019-12-31T23:59:59Z

## Context

Should be able to get a list of events for a certain time interval.

## Steps to Reproduce

GET /v3/audit_events?created_ats[lt]=2020-01-02T00:00:00Z&created_ats[gt]=2019-12-31T23:59:59Z

## Expected result

with list of resources in the response.

## Current result

{
  "errors": [
    {
      "detail": "The query parameter is invalid: Unknown query parameter(s): 'created_ats'",
      "title": "CF-BadQueryParameter",
      "code": 10005
    }
  ]
}

[include relevant logs]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

Audit Events issue

**Comment by sweinstein22** [comment]
Hi @rchalapaka , 

I've run the curl command you listed, `GET /v3/audit_events?created_ats[lt]=2020-01-02T00:00:00Z&created_ats[gt]=2019-12-31T23:59:59Z`, and was able to successfully curl the endpoint against the most recent `capi-release` version.

Could you check the cloud controller version you are using? Audit event filtering by `created_ats` was [introduced in `capi-release 1.97.0`](https://github.com/cloudfoundry/capi-release/releases/tag/1.97.0), which corresponds to [Cloud Controller v3 API version 3.87.0](http://v3-apidocs.cloudfoundry.org/version/3.87.0/#list-audit-events), so earlier versions will not be able to successfully complete the request.

You can check your Cloud Controller API version by curling the API root url, e.g. `api.system_domain`, and looking for the `cloud_controller_v3.meta.version` field.

**Comment by rchalapaka** [comment]
Thanks for the response. We are using the v3.80 and that could be the reason why it didn't work.

**Comment by sweinstein22** [comment]
Sounds like that's the issue. I'm going to close this out, feel free to reopen it if you continue to have trouble once you're on a version where filtering audit events by `created_ats` is supported.
