### ISSUE TITLE
Log evacuation events in app event logs

### ISSUE THREAD

**Issue by FloThinksPi** [cloudfoundry/cloud_controller_ng#2327]
## Issue

Log evacuation events in app event logs. 
Currently customers see only app crashes and manual actions like restart/restage and so on. 

## Context

Currently customers see only app crashes and manual actions like restart/restage and so on. However in their own monitoring, they see their instances are being restarted(due to Diego evacuations). When they investigate why this happens, they cannot correlate the restart to any event logged in CF. They then think it was a system error and ask the foundation owners what happened with their apps and if its normal.

We should also log evacuations as this is confusing for a customer.

## Steps to Reproduce

Restart a Diego cell with an app on it.

## Expected result

There is an Event called e.g. App Evacuation which signals the customer that a normal restart of their app on a different vm was done.

## Current result

The Stop of this app and start on a different cell is not visible in the CC Events.

## Possible Fix

We would need to create a new internal endpoint for Diego to make calls agains. Also introduce a new Event type.
Simmilar to: https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/internal/app_crashed_controller.rb
Then raise this on the Diego side so they provide information when a evacuation occurs.

**Comment by 46bit** [comment]
I've made a set of WIP commits to implement this:

- https://github.com/46bit/cloud_controller_ng/tree/emit-audit-events-when-app-instance-get-evacuated
- https://github.com/46bit/runtimeschema/tree/add-struct-to-send-app-evacuation-events-to-cc
- https://github.com/46bit/bbs/tree/emit-events-when-actual-lrps-get-evacuated
- https://github.com/46bit/tps/tree/forward-bbs-events-to-cc-when-apps-get-evacuated

Adding tests and getting it shippable would take a bit longer than I have right now, but it's a start.

**Comment by 46bit** [comment]
This got finished off and submitted. See https://github.com/cloudfoundry/cloud_controller_ng/pull/2447 for the main PR.
