### ISSUE TITLE
Space Application Supporter can access specific app env details

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2386]
## Issue

Allow space application supporter to access specific app environment variable endpoints. 

## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result
A space application support should be able access the following endpoint:

- [ ] GET /v3/apps/:guid/env

with a redacted view.

## Acceptance
A space application supporter would see the following formatted output when trying to view their apps environment details:

```
{
  "staging_env_json": {
    "key":"value"
  },
  "running_env_json": {
        "key":"value"
  },
  "environment_variables": {
        "key":"value"
  },
  "system_env_json": {},
  "application_env_json": {
    "key":"value"
  }
}
```

## Documentation
When I browse to any of these endpoints on [v3 docs](https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html) I can see the Space Application Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing, and that this role will only be able to see a redacted view.

**Comment by will-gant** [comment]
Starting this now

**Comment by will-gant** [comment]
There's still a little more to do on this to get the unit tests to pass, and unfortunately I'm now going on vacation - returning on Monday 26 July. Will sort these out when I get back.

**Comment by sweinstein22** [comment]
This was taken care of as part of https://github.com/cloudfoundry/cloud_controller_ng/pull/2388, going to close it out. Thanks for the PR!
