### ISSUE TITLE
Ensure space supporter receives proper error code for specific droplet endpoints

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2403]
## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result

A space should get a 403 unauthorized error when trying to curl the following endpoints:

PATCH /v3/droplets/:guid
DELETE /v3/droplets/:guid
POST /v3/droplets
POST /v3/droplets?source_guid=:guid
GET /v3/droplets/:guid/download
POST /v3/droplets/:guid/upload

## Acceptance
As a space supporter, if I curl the above endpoints for a droplet that exists, I receive a 403 error telling me I am not authorized to perform this action.

## Documentation
No changes required. We are just aligning with our style guide.

**Comment by ctlong** [comment]
@sweinstein22 @monamohebbi should this issue include `POST /v3/droplets`? Currently we only see `POST /v3/droplets?source_guid=:guid`, which translates to copying a droplet. What about creating a droplet, is that something a space supporter can do?

**Comment by sweinstein22** [comment]
I believe that was an oversight, according to [the spreadsheet of endpoints](https://docs.google.com/spreadsheets/d/1w07-1nlEXYzeDseT_BEKaT2T-QC-wZhNXrX4JPRrAYM/edit#gid=0&range=39:39) they shouldn't be able to hit `POST /v3/droplets`. I'll add it to the description of the issue, thanks for checking in!

**Comment by ctlong** [comment]
@sweinstein22 `GET /v3/droplets/:guid/download` seems like read-only permissions (ie. something that the space supporter should be able to do). In addition, we see that in the spreadsheet of endpoints, in the cf cli tab, `download-droplet` is listed as an allowed command.

❓ Why should `GET /v3/droplets/:guid/download` return 403 rather than succeed with a 302?

**Comment by piyalibanerjee** [comment]
I believe this was mainly because we couldn't think of a use case where a space supporter persona would need to download a droplet. Thanks for sharing that it's read-only for all roles -- perhaps it would be fine to allow it even if it likely won't be used.

**Comment by ctlong** [comment]
@piyalibanerjee @monamohebbi it seems possible (albeit bad practice) to store staging env vars in a droplet. Additionally, the droplet download would include the start command of an app which again could contain env vars (also bad practice).

🤔 Are those potential deal-breakers for allowing space supporters to download droplets?

**Comment by monamohebbi** [comment]
Sorry for the delayed response.

It seems like the problem with returning a 302 is that for Cloud Foundry deployments with internal blobstores CC will return the the actual source code. Preventing the user from seeing source code is one of the main goals of the space supporter, so even though it is a small edge case I think we want to continue to return 403s for the download droplet endpoint.

**Comment by mariash** [comment]
@monamohebbi we updated the PR with 403 status for download droplet endpoint returned to space supported.
