### ISSUE TITLE
Ensure space supporter receives proper error code for specific environment variable endpoints

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2404]
## Context

We are introducing a [new role](https://github.com/cloudfoundry/cfar-proposals/issues/22) and we want to make sure it has the right access.

## Expected result

A space should get a 403 unauthorized error when trying to curl the following endpoints:

GET /v3/apps/:guid/environment_variables
PATCH /v3/apps/:guid/environment_variables

## Acceptance
As a space supporter, if I curl the above endpoints for an app that exists, I receive a 403 error telling me I am not authorized to perform this action.

## Documentation
No changes required. We are just aligning with our style guide.

**Comment by ctlong** [comment]
I wasn't sure if there was a reason that this wasn't on the project board... so I just added it.

**Comment by monamohebbi** [comment]
Oh no! I think this story got duplicated because it wasn't on the project board. I think the behavior we are looking for is covered by #2388. Thank you still for your contributions!

**Comment by moleske** [comment]
@monamohebbi I'll close the PR I opened then.  Should this issue be closed then also?

**Comment by monamohebbi** [comment]
@moleske hold off for one second, I'd like to test and confirm against a bosh lite that these changes really have made it through.

**Comment by monamohebbi** [comment]
Closing out this issue. I think this was made on accident as we have updated other issues to allow for both of these endpoints to be used by the space supporter.
