### ISSUE TITLE
Allow space supporter to access any endpoints we might have missed

### ISSUE THREAD

**Issue by monamohebbi** [cloudfoundry/cloud_controller_ng#2410]
Issue
Allow space supporter to access specific app environment variable endpoints.

Context
We are introducing a new role and we want to make sure it has the right access.

Expected result
A space supporter should be able access the following endpoints:

GET /v3/apps/:guid/ssh_enabled
GET v3/stacks/:guid/apps

Acceptance
A space application supporter would see the same info as a space developer assigned to the same space for these and only these endpoints.

Documentation
When I browse to any of these endpoints on v3 docs I can see the Space Supporter role in the list of permitted roles with an indication that this role is not fully implemented and the permissions will be changing, and that this role will only be able to see a redacted view.

**Comment by mariash** [comment]
MIssed endpoints:

| CLI Command | Endpoint | Handler |
| -------------- | --------- | -------- |
| services | /v3/service_instances | service_instances_v3#index |

**Comment by galenhammond** [comment]
A few more endpoints that were missed:

GET /v3/apps/:guid/environment_variables
PATCH /v3/apps/:guid/environment_variables
PATCH /v3/deployments/:guid 
PATCH /v3/environment_variable_groups/:name

I would also be interested in reviewing the following endpoint specs:

GET v3/buildpacks -> not sure about permissions test setup as user is defined as a member of space by default/using single object endpoint test
GET v3/deployments -> no permissions test

**Comment by monamohebbi** [comment]
Thank you for looking over these endpoints! 

Due to some CI issues some of these endpoints are already complete and just waiting on being merged in, some are still waiting on acceptance testing, and some are currently in flight:

I believe these: 
https://github.com/cloudfoundry/cloud_controller_ng/pull/2388
https://github.com/cloudfoundry/cloud_controller_ng/pull/2378
https://github.com/cloudfoundry/cloud_controller_ng/issues/2241
should cover environment variable and services endpoints you all had listed.

As for `PATCH /v3/deployments/:guid` I believe we are blocking `PATCH` updates that only allow for metadata updates for now due to a lack of user data on metadata. I can update the spreadsheet accordingly.

I'll look into backfilling the tests!
