### ISSUE TITLE
Documentation on service instances list is unclear or has contradictions in managed and user-defined types

### ISSUE THREAD

**Issue by devconcept** [cloudfoundry/cloud_controller_ng#2470]
## Issue

The documentation on the service instances list states the following:

_This endpoint retrieves the service instances the user has access to. At the moment, this endpoint only returns managed service instances. This may change in the future._

But immediately it states that you can filter by type with the following query parameters

**type** _string_  Filter by type; valid values are managed and user-provided

Which suggest that this endpoint **does** return user-defined service instances

## Context

Applies only to the service instances list endpoint

## Steps to Reproduce

Check the documentation on service instances list

https://v3-apidocs.cloudfoundry.org/version/3.99.0/index.html#list-service-instances

## Expected result

It should be clear if the endpoint does in fact return user-defined service instances or not and if true in which conditions it does. The current statement is misleading.

- If the endpoint does indeed return user-defined service instances but only when querying them it should state that **by default** it does not return user-defined instances instead of stating that it never does.
- If the endpoint does not return user-defined instances in any circumstance it should state that the type filter has no effect.
- If the endpoint does return user-defined instances by default the statement should be removed.

## Current result

It is impossible to know just by reading the docs which will be the output of this endpoint

**Comment by sethboyles** [comment]
You are linking to an old version of the docs.  Please check that you are referencing the latest version of the docs before submitting an issue (this was fixed in 3.102):

https://v3-apidocs.cloudfoundry.org/version/3.103.0/#list-service-instances
https://v3-apidocs.cloudfoundry.org/version/3.102.0/#list-service-instances
