### ISSUE TITLE
No pageable way to gets users by space or org

### ISSUE THREAD

**Issue by moleske** [cloudfoundry/cloud_controller_ng#2489]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

We would like to be able to get users by space or org and the v3 endpoints do not allow that specification in a pageable format.  We could page through the roles endpoints, then process all of the roles to group by users.  But the problem with going through the roles endpoint is that we get inconsistent page sizes when it comes to displaying users and their roles in a table.

Ideally we would have a consistent way to get a page of unique users for a space or org, and then pull all their associated roles

## Context

We are updating an app to use v3 endpoints from v2 and while upgrading `GET /v2/spaces/:guid/user_roles` and `GET /v2/organizations/:guid/user_roles` endpoints we could not find a comparable way in v3 to construct a consistently sized table of users and roles via pagination.  We expect to have lots of users, so we would like to be able to paginate these requests in order to retrieve the information in a performant way.

## Possible Fix

1. Replicate the `user_roles` endpoints
2. Create a `v3/space/:guid/users` and `v3/organizations/:guid/users`
3. Add a `group_by` filter to the roles endpoint

We think 2 is the most feasible and reasonable based on the 1. being a composite endpoint and 3. might be computationally hard

**Comment by sweinstein22** [comment]
Reopening as the org level endpoint has not been completed

**Comment by JenGoldstrich** [comment]
This was released as part of CAPI 1.117.0
