### ISSUE TITLE
Confusing response from `POST /v3/apps/:guid/processes/:type/actions/scale`

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cloud_controller_ng#2526]
## Issue

`POST /v3/apps/:guid/processes/:type/actions/scale` returns a `202` status code but no Location header.

## Context

The [v3 Asynchronous Operations docs](https://v3-apidocs.cloudfoundry.org/version/3.107.0/index.html#asynchronous-operations) state that "endpoints that require asynchronous processing will return `202 Accepted` with a Location header pointing to the job resource to poll. Endpoints that do not require asynchronous processing will respond synchronously."

By returning `202 Accepted` with no Location header, CAPI leaves `POST /v3/apps/:guid/processes/:type/actions/scale` ambiguous to parse for clients using the API. If it is asynchronous then what endpoint should a client poll to judge when it is complete? And if it isn't asynchronous then why does it return a `202 Accepted` instead of a `200 OK`.

## Steps to Reproduce

* Push an app with a web process with 1 instance
* `cf curl -X POST v3/apps/:guid/processes/web/actions/scale -d '{"instances": 2}' -i`
* See that the status code is `202 Accepted` and that there is no Location header

## Expected result

Either a `200 OK` with the desired state of the process (as with `GET /v3/processes/:guid`), or a `202 Accepted` with a Location header to poll for the status of the scale request.

## Current result

The status code is `202 Accepted`, there is no Location header, and the desired state of the process is returned (as with `GET /v3/processes/:guid`; which in this instance seems to indicate that the scale command succeeded synchronously).

```
$ cf curl -X POST v3/apps/be2d3415-d0df-4e3e-a7f3-163d59aedbb7/processes/web/actions/scale -d '{"instances": 1}' -i

HTTP/1.1 202 Accepted
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 30 Sep 2021 19:04:05 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-B3-Spanid: 505537cb68836ab1
X-B3-Traceid: 505537cb68836ab1
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.113671
X-Vcap-Request-Id: 9696ed2d-2235-4c94-72a6-584c902b86b5::2ad69c6b-4ff9-4694-8761-a49ca5b9f500
X-Xss-Protection: 1; mode=block


{
   "guid": "be2d3415-d0df-4e3e-a7f3-163d59aedbb7",
   "created_at": "2021-09-30T18:51:01Z",
   "updated_at": "2021-09-30T19:04:05Z",
   "type": "web",
   "command": "bundle exec rackup config.ru -p $PORT -o 0.0.0.0",
   "instances": 1,
   "memory_in_mb": 256,
   "disk_in_mb": 1024,
   "health_check": {
      "type": "port",
      "data": {
         "timeout": null,
         "invocation_timeout": null
      }
   },
   "relationships": {
      "app": {
         "data": {
            "guid": "be2d3415-d0df-4e3e-a7f3-163d59aedbb7"
         }
      },
      "revision": {
         "data": {
            "guid": "e09e83fc-30a2-4a82-8470-e97aad9be995"
         }
      }
   },
   "metadata": {
      "labels": {},
      "annotations": {}
   },
   "links": {
      "self": {
         "href": "https://api.weed-centaur.capi.land/v3/processes/be2d3415-d0df-4e3e-a7f3-163d59aedbb7"
      },
      "scale": {
         "href": "https://api.weed-centaur.capi.land/v3/processes/be2d3415-d0df-4e3e-a7f3-163d59aedbb7/actions/scale",
         "method": "POST"
      },
      "app": {
         "href": "https://api.weed-centaur.capi.land/v3/apps/be2d3415-d0df-4e3e-a7f3-163d59aedbb7"
      },
      "space": {
         "href": "https://api.weed-centaur.capi.land/v3/spaces/b2d11e3f-fe3a-412f-b3af-1818a83bb9d9"
      },
      "stats": {
         "href": "https://api.weed-centaur.capi.land/v3/processes/be2d3415-d0df-4e3e-a7f3-163d59aedbb7/stats"
      }
   }
}
```

## Possible Fix

* Return `200 OK` instead and add a note in the docs that this is just for the desired state of the process, and that Diego may take some extra time to actually implement the scaling up / that an app restart may be required.
* Add a note to the docs explaining why `202 Accepted` is returned with no Location header
* Find some clever way to setup a job that a client could poll to find out when Diego has actually applied their scale

**Comment by ctlong** [comment]
It's my opinion from a brief scan of the code that all `POST /v3/apps/:guid/processes/:type/actions/scale` does is update the desired state of the process. In that case, it would seem to me that it should be returning `200 OK` for a job well done.

**Comment by sethboyles** [comment]
Duplicate of https://github.com/cloudfoundry/cloud_controller_ng/issues/2464
