### ISSUE TITLE
Blobstore error messages when pushing CF Docker apps

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cloud_controller_ng#2582]
## Issue

If a CF Docker application is restaged multiple times (> max_staged_droplets_stored), the droplets will be marked as EXPIRED. Then the delete_expired_droplet_blob coding will attempt to delete the droplet. As the droplet has no "droplet_hash" in the database, the jobs fails with the error "Attempting delete of '' from blobstore 'droplet_blobstore'" which will result in multiple "Failed to perform blobstore operation after three retries." errors.

## Context

We are running CF v17.0.0.

## Steps to Reproduce

1. Push a Docker test app 7 times.

2. Check the "droplets" database table. You should see that the oldest droplet is marked as "EXPIRED":
```
  id  |                 guid                 |         created_at         |         updated_at         |               droplet_hash               |  state  |                        docker_receipt_image                        |               app_guid
------+--------------------------------------+----------------------------+----------------------------+------------------------------------------+---------+--------------------------------------------------------------------+--------------------------------------
 1479 | ef5b189a-eff7-4927-93a0-eb3b18fc866b | 2021-12-06 16:30:44.612357 | 2021-12-06 16:30:44.652223 |                                          | STAGED  | <repository>/cloudfoundry/test-app:latest | 82a95a4d-0c95-4daf-b106-73b6748f5662
 1478 | 03de52d9-d2e3-4049-8240-3ac80e4a22e4 | 2021-12-06 16:29:14.482917 | 2021-12-06 16:29:14.521709 |                                          | STAGED  | <repository>/cloudfoundry/test-app:latest | 82a95a4d-0c95-4daf-b106-73b6748f5662
 1476 | 541b7be2-2c34-47c9-aae4-37e10ee96132 | 2021-12-06 16:28:19.65487  | 2021-12-06 16:28:19.684666 |                                          | STAGED  | <repository>/cloudfoundry/test-app:latest | 82a95a4d-0c95-4daf-b106-73b6748f5662
 1475 | db5d4b1b-de42-45a2-bf27-c1fedc9c4da0 | 2021-12-06 16:25:39.21491  | 2021-12-06 16:25:39.243884 |                                          | STAGED  | <repository>/cloudfoundry/test-app:latest | 82a95a4d-0c95-4daf-b106-73b6748f5662
 1361 | dba11389-7cd3-4a79-b077-b7cc7eac96ff | 2021-12-06 12:46:34.50551  | 2021-12-06 12:46:34.54427  |                                          | STAGED  | <repository>/cloudfoundry/test-app:latest | 82a95a4d-0c95-4daf-b106-73b6748f5662
 1350 | 70ceea40-52cd-45d7-8613-9040c31f87ae | 2021-12-06 12:29:48.105372 | 2021-12-06 12:29:48.137734 |                                          | STAGED  | <repository>/cloudfoundry/test-app:latest | 82a95a4d-0c95-4daf-b106-73b6748f5662
 1348 | 2b47add2-9832-4cac-9955-58d0a8bab657 | 2021-12-06 12:27:33.437929 | 2021-12-06 16:30:44.701828 |                                          | EXPIRED | <repository>/cloudfoundry/test-app:latest | 82a95a4d-0c95-4daf-b106-73b6748f5662
```

3. Search for the expired droplet guid in the "cc.background" logs. You should find these error messages:
```
"Deleting expired droplet blob for droplet: 2b47add2-9832-4cac-9955-58d0a8bab657"
"Attempting delete of '' from blobstore 'droplet_blobstore'".
```

4. You will also find this error message from the Fog client:
```
"Error with blobstore: TypeError - no implicit conversion of nil into String","log_level":"error","source":"cc.error_handling_client","data":{"request_guid":"<guid>"},"thread_id":67040,"fiber_id":67100,"process_id":6,"file":"/var/vcap/data/packages/cloud_controller_ng/bc1298c3641dc46ccd4fd65c1419c501b91ee5f6/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb"
```

## Expected result

As there is no blobstore operation involved at all for Docker images, there is no need for a cleanup action. Expired droplets without a droplet_hash (or, alternatively, with a set "docker_receipt_image") could simply be deleted from the database. No blobstore error messages should be produced.

## Current result

We see blobstore error messages as described above.

## Possible Fix

We could check here if the droplet has a valid "droplet_key" (which is composed of the "droplet_hash") and only if yes, continue with the deletion:
https://github.com/cloudfoundry/cloud_controller_ng/blob/4a23a419862ef9b7272f411a4435e33fc7305f30/app/jobs/runtime/delete_expired_droplet_blob.rb#L17

**Comment by philippthun** [comment]
I would filter out these entries already one level above. `DeleteExpiredDropletBlob` jobs are created at two different places:

1. According to [this](https://github.com/cloudfoundry/cloud_controller_ng/blob/27c7239b422a27d4c3136ffc938887bdb7eabdde/app/jobs/runtime/expired_blob_cleanup.rb#L8) `exclude(droplet_hash: nil)` there shouldn't be a delete job for these "docker droplets".

2. But [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/27c7239b422a27d4c3136ffc938887bdb7eabdde/lib/cloud_controller/bits_expiration.rb#L23) no such exclusion was added. So my proposal is to add a `if droplet.droplet_hash` to this line - then both places are consistent.

**Comment by tjvman** [comment]
@philippthun That approach sounds reasonable to us.

**Comment by jochenehret** [comment]
Ok we are preparing a PR.

**Comment by jochenehret** [comment]
Proposed fix: https://github.com/cloudfoundry/cloud_controller_ng/pull/2588
