### ISSUE TITLE
support AWS IMDSv2 with AWS instance profiles

### ISSUE THREAD

**Issue by metskem** [cloudfoundry/cloud_controller_ng#2597]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Run a BOSH director with properties/aws?/metadata_options/http_tokens: required (which is IMDSv2), while at the same time have an AWS Instance Profile that provides the permissions to get to an S3 blobstore.
This results in an error message:

Error with blobstore: ArgumentError - Missing required arguments: aws_access_key_id, aws_secret_access_key

## Context

It has been detailed in the slack channel: https://cloudfoundry.slack.com/archives/C07C04W4Q/p1639565419043400 

## Steps to Reproduce

When running with the above mentioned BOSH director setup, try to recreate an api server (bosh -d cf recreate api/0). This will result in the cloud_controller_ng to not come up and show the above message in the log.

## Expected result

I expect the cloud_controller_ng to just initialize and work.

## Current result

See the error message above, the cloud_controller_ng doesn't initialize.

## Possible Fix

It as stated in the slack channel, it is a known issue that still needs to picked up

**Comment by sethboyles** [comment]
fixed with 1.127
