### ISSUE TITLE
Is there any API that can get quota usage of an organization?

### ISSUE THREAD

**Issue by hezhijun** [cloudfoundry/cloud_controller_ng#261]
Hello, I know that we can get quota_definition of an organization, but how can we know resource usage of an organization? 
We can get overall limits and usage as below, but have no idea how to get usage of a specific organization.
GET https://api.run.pivotal.io/info
"limits":
   {
       "memory": 2048,
       "app_uris": 4,
       "services": 16,
       "apps": 20
   },
   "usage":
   {
       "memory": 768,
       "apps": 2,
       "services": 3
   }

**Comment by pburkholder** [comment]
```
cf install-plugin -r CF-Community "Usage Report"
```

**Comment by asherbar** [comment]
@pburkholder where can I find information on how to use the "Usage Report" plugin?

**Comment by pburkholder** [comment]
@asherbar https://github.com/krujos/usagereport-plugin
