### ISSUE TITLE
Evaluate if CC runs Ruby 3.X

### ISSUE THREAD

**Issue by FloThinksPi** [cloudfoundry/cloud_controller_ng#2619]
## Issue

Different sources claim alternative ruby implementations as well as CRuby 3.x do have a positive performance impact on rails applications that can be quite substantial. 

## Context

See https://eregon.me/blog/2022/01/06/benchmarking-cruby-mjit-yjit-jruby-truffleruby.html for reference to a benchmark comparing multiple ruby interpreters also with a rails application benchmark.

We should try out some of them firstly if they work and also if they improve overall performance in a mensurabel way.
Especially as CRuby 3.1 includes https://github.com/Shopify/yjit which promises improvements without loosing compatibility at all.

## Acceptance Criteria

- [ ] Have a branch of CC_NG that runs with CRuby 3.x and preferably yjit

**Comment by sethboyles** [comment]
Thanks for linking that blog post.  Would be very interesting to see if we can get comparable perf improvements from Truffleruby.

**Comment by sethboyles** [comment]
see #2623 for a WIP on the Ruby 3 upgrade

**Comment by sethboyles** [comment]
yjit available with config flag here: https://github.com/cloudfoundry/capi-release/pull/270
