### ISSUE TITLE
Test in which way the "sequel_pg gem" improves performance and throughput

### ISSUE THREAD

**Issue by FloThinksPi** [cloudfoundry/cloud_controller_ng#2625]
## Summary

With #2595  we have added a Gem that enables sequel to use C libraries for certain functions and thus promising more performance. It is even mentioned in Sequel docs that when using Sequel with PSQL it is recommended to do so.
We have merged it yet we cannot tell if it improves performance.

## Acceptance Criteria

- [x] Test if this really benefits performance 
- [x] Test if this really benefits troughput 
- [x] Document findings

**Comment by philippthun** [comment]
I think [this comment](https://cloudfoundry.slack.com/archives/C07C04W4Q/p1647860043541169) provides enough evidence that the `sequel_pg` gem reduced CPU consumption and thus improved performance/throughput.
