### ISSUE TITLE
`POST /v3/droplets/:guid/upload` doesn't take tgz files

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cloud_controller_ng#2655]
## Issue

In testing `POST /v3/droplets/:guid/upload`, I've noticed that a consistent error is returned when anything other than a `.zip` file is uploaded: `The app upload is invalid: Invalid zip archive.`

## Context

I've been investigating some failures in CATs in https://github.com/cloudfoundry/cf-acceptance-tests/blob/develop/v3/buildpacks.go. In the process of trying to fix those failures I tried changing the zip file that is uploaded and found that CAPI doesn't appear to accept any `.tar`, `.tar.gz`, or `.tgz` files.

## Steps to Reproduce

```
git clone git@github.com:cloudfoundry/ruby-buildpack.git
cd ruby-buildpack/fixtures
tar -cvzf /tmp/ruby_calls_go.tgz --directory=ruby_calls_go .
```
Use that tar file in a request to `POST /v3/droplets/:guid/upload`.

## Expected result

Right now you might see a different failure, which is what I'm trying to fix. However, the [current docs](https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#upload-droplet-bits) lead me to believe that `.tgz` file would be preferred to a `.zip`.

## Current result

Anything not generated by `zip -r...` (eg. `zip -r /tmp/ruby_calls_go.zip ruby_calls_go`) fails with the error `The app upload is invalid: Invalid zip archive.`

## Possible Fix

N/A

## `name of issue` screenshot

N/A

**Comment by sethboyles** [comment]
We weren't able to reproduce this issue.  Can you post what request you are making in trying to upload the tgz file?

**Comment by ctlong** [comment]
@sethboyles sorry, turned out this was user error 😅.

🤦 I was tar-ing the folder instead of the individual files.
