### ISSUE TITLE
cannot add orgRole to valid user for org I own

### ISSUE THREAD

**Issue by christo4ferris** [cloudfoundry/cloud_controller_ng#277]
@ematpl - we discussed this earlier today.

From Brian Martin
---
I can recreate the org membership problem on run.pivotal.io, so not sure if this is by design or not.  I think it is a bug in the token obtained by cf CLI not obtaining the correct resource id (scim) to access the UAA users query endpoint.   See here where I try to add OrgAuditor role for org I own and valid user that already exists.

cf set-org-role bkmartin@us.ibm.com "Brian's Org" OrgAuditor

VERSION:
6.3.2-217929b

REQUEST: [2014-08-08T10:15:29-04:00]
GET /Users?attributes=id,userName&filter=userName+Eq+%22bkmartin%40us.ibm.com%22 HTTP/1.1
Host: uaa.run.pivotal.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.3.2-217929b / darwin

RESPONSE: [2014-08-08T10:15:29-04:00]
HTTP/1.1 403 Forbidden
Content-Length: 97
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Fri, 08 Aug 2014 14:15:29 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
Www-Authenticate: Bearer realm="UAA/oauth"
X-Cf-Requestid: 4b92a9a4-eb50-416e-6600-f4d3c6f37cb7

{"error":"access_denied","error_description":"Invalid token does not contain resource id (scim)"}
FAILED
User bkmartin@us.ibm.com not found
FAILED
User bkmartin@us.ibm.com not found

**Comment by dieucao** [comment]
@christo4ferris This was addressed as part of cf-release 219 with the new management by username endpoints.
