### ISSUE TITLE
After introducing new state "initial" in cf service, our applications are failing

### ISSUE THREAD

**Issue by VedaReddivari** [cloudfoundry/cloud_controller_ng#2862]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

After introducing new state "initial" in cf service, our applications are failing

## Context

some of the functionality, our application flow is dependent on the 3 states of the (in-progress , succeeded, Failed) , Now with this new state (initial) , functionality is failing.

This was not mentioned in CAPI Release notes or CF V3 documentation,

## Steps to Reproduce

Create the CF service and verify the states

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you are currently experiencing from this process, and thereby explain the bug]

[include relevant logs]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

![image](https://user-images.githubusercontent.com/86948965/178187204-fb123b2b-04fa-4d5c-90d0-3abfe348ffd8.png)
![image](https://user-images.githubusercontent.com/86948965/178187240-51d4be33-5fc9-4d02-bb3b-c689822664b9.png)

**Comment by philippthun** [comment]
Sorry for causing trouble; the documentation has been adapted in the meantime.

**Comment by philippthun** [comment]
I've added a note to [CAPI release 1.129.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.129.0) containing the change.
