### ISSUE TITLE
v3/service_instance/:guid/permissions endpoint missing ?

### ISSUE THREAD

**Issue by FloThinksPi** [cloudfoundry/cloud_controller_ng#2872]
## Issue

Deprecating the V2 api there is following workflow that imho is not covered by V3 API

https://docs.cloudfoundry.org/services/dashboard-sso.html#checking-user-permissions

The `v3/service_instance/:guid/permissions` endpoint is not implemented and afaik no way to check permissions of a dashboard client exist. 

This was noticed as there are failing cats tests that fail when disabling v2 as they check permissions for dashboard clients via v2:

https://github.com/cloudfoundry/cf-acceptance-tests/blob/develop/helpers/services/sso.go#L154

## Steps to Reproduce

Run latest CATS with v2 disabled via experimental ops file

## Expected result

CATS finish successfully

## Current result

They fail on `v2/service_instance/:guid/permissions` calls since this is disabled.
No alternative in v3 is obvious

## Possible Fix

Implement such functionality endpoint in v3 ?
Is this workflow covered by api calls i have overlooked ?

**Comment by will-gant** [comment]
Opened the following PRs to tackle this:
1. https://github.com/cloudfoundry/cloud_controller_ng/pull/2946
1. https://github.com/cloudfoundry/cf-acceptance-tests/pull/593
1. https://github.com/cloudfoundry/cf-deployment/pull/986
