### ISSUE TITLE
Enhancement: Include[processes] into GET Apps/{guid} 

### ISSUE THREAD

**Issue by KevinJCross** [cloudfoundry/cloud_controller_ng#2879]
## Request
We in the [Cf autoscaler team](https://github.com/cloudfoundry/app-autoscaler-release) are migrating to only using the V3 api. Currently there is no direct replacement for the apps/summary endpoint (possibly for valid reasons). The new V3 api allows us to include related resources into the result of the call. 
To reduce our fan out of calls to the cloud controller we would like to include the `apps/{guid}/processes` and `processes/{guid}/stats` as relationships we can include using the V3 `include[relationship]` directives. This would go a long way to replicate the items we require from the summary page namely. 
app state from the `/apps/{guid}`
app instances from `/apps/{guid}/processes`  

the one call is now costing us minimum 2 calls for 2 distictively related items

**Comment by Gerg** [comment]
We have been thinking about including *-to-many relationships for a while, but we never came up with a design we were super happy with. I think the closest we got was [this proposal](https://docs.google.com/document/d/1KxRRGAvE9FXPOA6GFRX5K17lwo5BTHmYzogOUJDrdBw/edit).

**Comment by philippthun** [comment]
@KevinJCross We are in the process of extending this endpoint. See [this issue/comment](https://github.com/cloudfoundry/cloud_controller_ng/issues/1990#issuecomment-1183335580) for more details.

**Comment by KevinJCross** [comment]
@philippthun Great this looks like it is being thought about and looked. I just added a comment to the document too.
Thanks ... ill consider this duplicated then

**Comment by KevinJCross** [comment]
Im happy that this issue is already seen and currently under discussion.
