### ISSUE TITLE
There's need for configurable public host address of CC.

### ISSUE THREAD

**Issue by resouer** [cloudfoundry/cloud_controller_ng#295]
Here is the use case:

1. We runs CF inside Docker
2. We all know that CC need to report its external ip and port to Gorouter, and DEA also need that to download bits. 

Here is the issue:

But the existing CC code use vcap common local_ip method to get real ip from local_route, this works well in most cases, but when there's a "private IP" & "public IP" network, it fails: CC gets its private IP and report it to Gorouter or DEA, but it is actually unreachable.

So here is a need for a configurable public host like external port here: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/config/cloud_controller.yml#L3

As "private IP" & "public IP" network is common in Docker world, my team has fixed this by a small patch and we'd like to send a PR to CC. But first of all, do Pivotal guys have other suggestions about this issue?

**Comment by aashah** [comment]
There has not been any recent activity on this issue. We are closing the issue.

Please feel free to re-open.

CAPI Community Pair - @aashah @rizwanreza
