### ISSUE TITLE
Wrong table `asg_timestamps` definition

### ISSUE THREAD

**Issue by kinjelom** [cloudfoundry/cloud_controller_ng#2994]
## Issue

The endpoint `internal/v4/asg_latest_update` always returns `{ "last_update": "1970-01-01T00:00:00Z" }` so changes to security groups do not propagate

Restart / restage an app does not help, only restarting the `cf/api/policy-server-asg-syncer` job helps because then it does full-sync on the start: https://github.com/cloudfoundry/cf-networking-release/issues/168

## Context

Wrong table `asg_timestamps` definition, wrong the field name `{:name=>:id}`: https://github.com/cloudfoundry/cloud_controller_ng/blob/main/db/migrations/20220601183937_create_asg_lastest_updates.rb#L4

```
describe asg_timestamps;
+--------------+-----------+------+-----+-------------------+-----------------------------+
| Field        | Type      | Null | Key | Default           | Extra                       |
+--------------+-----------+------+-----+-------------------+-----------------------------+
| {:name=>:id} | int(11)   | NO   | PRI | NULL              | auto_increment              |
| last_update  | timestamp | NO   |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |
+--------------+-----------+------+-----+-------------------+-----------------------------+
2 rows in set (0.00 sec)

select * from asg_timestamps;
Empty set (0.00 sec)

show create table asg_timestamps;
CREATE TABLE `asg_timestamps` (
  `{:name=>:id}` int(11) NOT NULL AUTO_INCREMENT,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`{:name=>:id}`)
)
```

@MerricdeLauney @dalvarado @moleske https://github.com/cloudfoundry/cloud_controller_ng/commit/7cb7e88b54dc046de79851345c839cfbfe780c46
> would be nice to keep the database constraint, but we couldn't figure out why the sequel migration didn't like the CREATE UNIQUE INDEX line for mysql (it was fine with postgres)

maybe that is why...

**Comment by MerricdeLauney** [comment]
Thank you for pointing out the error in the table field, thats clearly not correct as you say. However, we were unable to reproduce the bug that causes `internal/v4/asg_latest_update` to always return { "last_update": "1970-01-01T00:00:00Z" }

based on the how the [class works](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/models/runtime/asg_last_updated.rb) and our own testing we don't think the poorly named field affects the output of internal/v4/asg_latest_update:

We did the following steps: 
curl  https://cloud-controller-ng.service.cf.internal:9023/internal/v4/asg_latest_update
{"last_update": "1970-01-01T00:00:00Z"}
cf curl -X POST /v3/security_groups -d '{"name": "blah"}'
{201 ...}
curl  https://cloud-controller-ng.service.cf.internal:9023/internal/v4/asg_latest_update
{"last_update": "2022-10-03T22:58:00Z"}

Could you list your reproduction steps so we can test further? The only thing we could can think of is if you might be using v2 endpoints to update security groups.

CC: @dalvarado

**Comment by kinjelom** [comment]
@MerricdeLauney What database do you use? I think there is a problem in MySQL/PXC (I have this one), there is no problem (probably) if you use PostgreSQL: https://github.com/cloudfoundry/cloud_controller_ng/commit/7cb7e88b54dc046de79851345c839cfbfe780c46

**Comment by MerricdeLauney** [comment]
HI We tested it manually on mysql 5.7.39. Can you list your reproduction steps?

**Comment by kinjelom** [comment]
It is working now (CAPI 1.140.0 / ng_cloud_controller with changed column name https://github.com/cloudfoundry/cloud_controller_ng/pull/3013)
