### ISSUE TITLE
Health endpoint logging too much

### ISSUE THREAD

**Issue by KevinJCross** [cloudfoundry/cloud_controller_ng#3029]
The health check endpoint is logging a large amount of entries for no real reason. When have you every thought there is the health check log or ever needed a health check lof ?

```
{"timestamp":"2022-10-20T14:59:05.991061958Z","message":"Started GET \"/healthz\" for user: , ip: 127.0.0.1 with vcap-request-id: 7efc7d0c-674b-4096-9e83-fa07db3270a3 at 2022-10-20 14:59:05 UTC","log_level":"info","source":"cc.api","data":{"request_guid":"7efc7d0c-674b-4096-9e83-fa07db3270a3"},"thread_id":90500,"fiber_id":90520,"process_id":7,"file":"/var/vcap/data/packages/cloud_controller_ng/fba084f53dc0776a44238fed554af441032b6fcb/cloud_controller_ng/lib/cloud_controller/logs/request_logs.rb","lineno":14,"method":"start_request"}
{"timestamp":"2022-10-20T14:59:05.991612144Z","message":"Completed 200 vcap-request-id: 7efc7d0c-674b-4096-9e83-fa07db3270a3","log_level":"info","source":"cc.api","data":{"request_guid":"7efc7d0c-674b-4096-9e83-fa07db3270a3"},"thread_id":90500,"fiber_id":90520,"process_id":7,"file":"/var/vcap/data/packages/cloud_controller_ng/fba084f53dc0776a44238fed554af441032b6fcb/cloud_controller_ng/lib/cloud_controller/logs/request_logs.rb","lineno":28,"method":"complete_request"}
```
This is logged every health check which is in effect pointless logging and noise.

We should really only log if there is an error in the health check not 2 logs for every health check.

Looking at my current log of 45MB (only been running for a day 84% of the log is just health check 
looking at my log file for 1 day !
that means that only 14 % of the log is actually useful to anyone!
Logging is also not for free ... this will be causing cpu and memory waiste on each node.

```
➜  cloud_controller_ng git:(main) ✗ cat cloud_controller_ng.log |  wc -l
   78852
➜  cloud_controller_ng git:(main) ✗ cat cloud_controller_ng.log | grep -v "/healthz" | wc -l
   53398
➜  cloud_controller_ng git:(main) ✗ cat cloud_controller_ng.log | grep -v "/healthz" | grep -v "request_logs.rb" | wc -l
    5572
```

**Comment by philippthun** [comment]
I agree; the logs for requests to `/healthz` do not contain any useful data. The user is always empty, the IP address is 127.0.0.1 and for the VCAP request ID no additinal information can be found as this endpoint does nothing.

We also have the nginx access logs which contain the exact same information (including the upstream HTTP status code).

So I created a PR to omit request logging for this endpoint: #3032
