### ISSUE TITLE
deleting an app shows "Deleted app with guid" log message for v2, but not for v3 

### ISSUE THREAD

**Issue by metskem** [cloudfoundry/cloud_controller_ng#3047]
## Issue

When creating, updating, deleting apps, we see these kind of log/audit messages in the cf logs:
"Created app with guid <guid>"
"Updated app with guid <guid>"
"Deleted app with guid <guid>"

When using the v2 api the above 3 messages are emitted, however, when using the v3 api only the first 2 are emitted and the Deleted message does not show.

## Context

We try to have an audit trail of what happens with apps, and therefore use these kind of message, however, we discovered that the "Deleted app..." message does not show up when using api v3. 
I think cf cli v7 and v8 use this api v3, so at least there you have the issue.

## Steps to Reproduce

Have any simple app and cf push it.
Tail the cf logs (I used the log-stream cf cli plugin and issue the following command): 
```
cf log-stream -t log| egrep "(Deleted app with guid )|(Created app with guid )|(Updated app with guid )"
```
While that is running issue this command:
```
cf curl -X DELETE /v2/apps/<app-guid>
```
Then push the app once more, and delete it again using the api v3:
```
cf curl -X DELETE /v3/apps/<app-guid>
```

## Expected result

I would expect in both cases (v2 and v3 api) that the "Deleted app with guid <guid>" message would show in the log.

## Current result

You currently see the log message only when using the api v2 to delete the app.

## Possible Fix

I did some quick finds through the source, but I am not competent enough to really spot the issue.

**Comment by philippthun** [comment]
This log message is emitted through the `AppLogEmitter` (https://github.com/cloudfoundry/cloud_controller_ng/blob/44d07caaedbf2d2f76a0f4352b2f79168427bdd5/app/repositories/app_event_repository.rb#L85). In my local development environment I've set a breakpoint at this specific line and when deleting the app with **v3**, the debugger stopped there - not for the `api` process, but the `generic worker` process.

The `generic worker` corresponds to `cc-worker` VMs which have the corresponding endpoint [configured by default](https://github.com/cloudfoundry/capi-release/blob/77ef13998a1a3ca6fd05e178974a364de54c14ad/jobs/cloud_controller_worker/spec#L395-L400), but the `loggr-udp-forwarder` job seems to be missing on these VMs which should listen on the configured port.

So the explanation could be that all the actions for which you are seeing log messages are synchronous and thus run on `api` VMs, whereas the **v3** delete request runs asynchronously on `cc-worker` VMs and thus the logs are not forwarded. If that is true, the missing job needs to be added in [cf-deployment](https://github.com/cloudfoundry/cf-deployment).

**Comment by philippthun** [comment]
@metskem - Do you see the log message "Enqueued job to delete app with guid ..."? This one should be emitted synchronously by the api process ([here](https://github.com/cloudfoundry/cloud_controller_ng/blob/44d07caaedbf2d2f76a0f4352b2f79168427bdd5/app/controllers/v3/apps_controller.rb#L156)).

**Comment by metskem** [comment]
Hi @philippthun - Yes, I do see that "Enqueued job to delete app with guid ..." message.
And after adding the loggr-udp-forwarder job to the cc-worker instance_group I also see the "Deleted app with guid " message now.

So, thanks for that.

Do you think the loggr-udp-forwarder should run on the cc-worker by default (meaning a PR for cf-deployment) ?

**Comment by metskem** [comment]
Will do that, I think we can close this issue now then, right?

**Comment by metskem** [comment]
I filed https://github.com/cloudfoundry/cf-deployment/pull/1007

**Comment by philippthun** [comment]
Thanks, @metskem!
