### ISSUE TITLE
Retry to delete service, where are these codes in cc_ng?

### ISSUE THREAD

**Issue by kinghw** [cloudfoundry/cloud_controller_ng#309]
in doc http://docs.cloudfoundry.org/services/api.html#orphans end, there are such description 

Orphans
The Cloud Controller database and a Broker are expected to store identical copies of existing instances and bindings. These two lists may potentially become inconsistent. For example, if a broker times out during a delete request, the Cloud Controller will be unsure whether that resource still exists on the broker. Cloud Controller will implement the following orphan prevention techniques:

If a broker fails to provision or bind an instance, the Cloud Controller will immediately issue a deprovision or unbind request.

If a broker fails to unbind or deprovision an instance, the Cloud Controller will periodically retry that DELETE request until it succeeds (or generates a 410). Eventually it will give up, but this technique will help clean up resources that remain when a broker fails to delete.

but i can not find these codes in cc_ng? where are they? how does cc_ng retry to delete?

**Comment by dieucao** [comment]
Closing this issue. It's been a long time without a response. Please feel free to open a new issue if needed.
