### ISSUE TITLE
/v2/spaces/<spaceguid>/summary produces "-1" running_instances for all apps, instead of actual # instances

### ISSUE THREAD

**Issue by metskem** [cloudfoundry/cloud_controller_ng#3112]
## Issue

We upgraded to cf-deployment v24.1.0, which brings CAPI v1.142.0.
After the upgrade it appears that  _/v2/spaces/\<spaceguid\>/summary | jq .apps[].running_instances_ shows mostly “-1”.  
Other calls that show the process states (like /v3/apps/\<appguid\>/processes/web/stats) do show the correct state "RUNNING".

## Context

The issue is prominently shown when using the [prometheus boshrelease](https://github.com/bosh-prometheus/prometheus-boshrelease), a [CFAppUnHealthy](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/090ecffed02b12dbb451b29dcb7b8c5f41015b3b/jobs/cloudfoundry_alerts/templates/cf_apps.alerts.yml#L14) alert fires for each app, since [cf_exporter](https://github.com/bosh-prometheus/cf_exporter) uses the /v2/spaces/\<spaceguid\>/summary a lot.

## Steps to Reproduce

* Target any space that has one or more running apps.
* Find the space guid (cf space \<spacename\> --guid)
* Issue:  cf curl /v2/spaces/\<spaceguid\>/summary | jq '.apps[].running_instances'

## Expected result

The number of running instances for each app.

## Current result

The result will be a "-1" for each app.

## Possible Fix

I have no idea

**Comment by moleske** [comment]
cross referencing https://github.com/cloudfoundry/cloud_controller_ng/issues/3109 since seems like root cause is similar

**Comment by thelangley** [comment]
hey, just noticed that capi-release 1.143.0 was released yesterday which reverts the code which introduced this feature.

just tested in my env and we don't get `-1` anymore

**Comment by metskem** [comment]
yup, same here, problem fixed.
Thanks!
