### ISSUE TITLE
The VCAP::RestAPI::Query#clean_up_boolean method fails with postgres

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#314]
Commit a512767f7769f3ff151275bbaca6e417886fe5de maps "t" to true, with a comment that
this is for Sequel/MySQL. But it causes some CC API queries with x=true to fail, treating x as false.

**Comment by dieucao** [comment]
@ericpromislow The fix for this should be available in the next cf-release.
The commit with the fix https://github.com/cloudfoundry/cloud_controller_ng/commit/b009554572ddfbb296d475bcbb02436433c5f4c3
This will allow query parameters of t or true to be valid and all else to be treated as false.
