### ISSUE TITLE
Unmatching results compare the btp-cockpit using the command: cf curl "v3/service_instances"

### ISSUE THREAD

**Issue by daoshihaideba** [cloudfoundry/cloud_controller_ng#3165]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Hi all, 
Recently I am using the CAPI to collect some data in our orgnization, When i am trying to caculate the number of the service-instances. I find the result does not match with the data shown in BTP-cockpit.

## Context
For example : 
When i type the command in cmd: cf curl "v3/service_instances/da281fea-2705-44f8-b1a9-abac59ec6a1b"
This will return the detail data of this service instance 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/92013799/215415544-9d469cee-0535-41d1-859a-2360524e1827.png">
But when I loggin to the btp-cockpik. There is no service-instance in that space 
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/92013799/215415794-485693b6-e86f-446b-99c9-db0c93d53bed.png">

## Steps to Reproduce

1. open the command line
2. cf login -a  https://api.cf.eu10.hana.ondemand.com
3. cf curl "v3/service_instances/da281fea-2705-44f8-b1a9-abac59ec6a1b"      there you can find the deleted instance still exists
4. Go to the btpcockpit and you will find not instance exist in this space [https://cockpit.eu10.hana.ondemand.com/cockpit/#/globalaccount/SA0101044080/subaccount/bb4f5af2-639a-48aa-a0ec-8449ef4e912d/org/8decc1b6-6591-4a21-97db-517b199c722c/space/26e175b8-0f76-4541-8c72-636207433309/service-instances](url)

## Expected result

make the result of the cpi matching the result shown in btp-cpckpit

## Current result

the result in cpi does not match the data in btp-cockpit

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by moleske** [comment]
Hi @daoshihaideba,

btp-cockpit seems to be an SAP proprietary product, not a cloud foundry feature.  As such we don't know what it is doing and can't help here.  If you find a bug with cloud controller that results in the incorrect listing, please open an issue.  Otherwise I recommend reaching out directly to SAP support.

tagging @philippthun and @johha just in case

**Comment by daoshihaideba** [comment]
Hi moleske, 
Thanks for your reply. Have found the cause: missing space developer role in btp cockpit. Thank you for your reply
