### ISSUE TITLE
`updated_at` field of apps is updated during encryption key rotation

### ISSUE THREAD

**Issue by johha** [cloudfoundry/cloud_controller_ng#3196]
## Issue

During a ccdb encryption key rotation the field `updated_at` of an app is changed to a current timestamp (via [Sequel timestamps plugin](http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/Timestamps.html)) although the app resource / metadata didn't change semantically.
For customers this could be confusing  as they might notice changes of `updated_at` without any actual changes and without any traceability (e.g. `cf events`) . 

#### Unit test to reproduce issue

```Ruby
it 'rotates an app' do
  expect(app.encryption_key_label).to eq('old')

  puts("updated_at before rotation and 10 sec sleep: #{app.values[:updated_at]}")
  sleep(10)
  RotateDatabaseKey.perform(batch_size: 1)

  expect(app.reload.encryption_key_label).to eq('new')
  puts("updated_at after rotation: #{app.values[:updated_at]}")
end
```

#### Output
```
updated_at before rotation and 10 sec sleep: 2023-02-20 13:08:15 UTC
updated_at after rotation: 2023-02-20 13:08:25 UTC
```

## Expected result

`updated_at` should not change during a ccdb encryption key rotation

## Current result

`updated_at` is updated during a ccdb encryption key rotation

**Comment by sethboyles** [comment]
Makes sense that if we display `updated_at` to users there should be some discernible reason it changed. Sequel recommends overriding the `before_update` for use cases like this: https://github.com/jeremyevans/sequel/blob/master/doc/model_hooks.rdoc#conditional-hooks-

**Comment by sethboyles** [comment]
Of course right now most of our models probably have similar issues, where the timestamp may be updated for unclear reasons.  We might at least want to skip it for all the models that store encrypted fields to being with.

**Comment by philippthun** [comment]
The [Sequel timestamp plugin](http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/Timestamps.html) has a config option `allow_manual_update` which we [don't set](https://github.com/cloudfoundry/cloud_controller_ng/blob/cb05e88ad79c9ed6c1c98e5cbb60401508fde459/lib/cloud_controller/db.rb#L93).

One option would be to set this by default, another option is to override it during the database key rotation for those model classes that we are actually updating. This can be done by setting [`@allow_manual_timestamp_update`](https://github.com/jeremyevans/sequel/blob/e86e1ee72a52937b810d9c0b5de767e5b0a1b81d/lib/sequel/plugins/timestamps.rb#L34) in an `instance_exec` block.

To skip the automatic update of the `updated_at` field, it is then sufficient to mark the field as already modified (`modified!(:updated_at)`).

[This commit](https://github.com/sap-contributions/cloud_controller_ng/commit/92e42a2757d97893d8216e3d9f7c5fc0087e562b) contains the necessary changes, but misses a unit test as well as an overall integration/system test (i.e. full run of a database key rotation).
