### ISSUE TITLE
Misspelled attribute : plan_updatable in Broker API specification vs plan_updateable in code vs 

### ISSUE THREAD

**Issue by tomaszpancho** [cloudfoundry/cloud_controller_ng#321]
There is a new attribute in service broker API Catalog, called **plan_updatable** :  [spec v2.4 Catalog management](http://docs.cloudfoundry.org/services/api.html#catalog-mgmt). But throughout the code **plan_updateable** is used, for instance here : app/models/services/service.rb

Broker written according to spec, will be unable to set **plan_updateable** to true, and in consequence to change plans. Cloud foundry will respond to cli cf update-service command with "The service does not support changing plans."

**Comment by shalako** [comment]
We have updated the docs, rather than change the broker and CC API.
