### ISSUE TITLE
PUT /v2/organizations/:id - returns 201 Created; perhaps 200 is better status

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cloud_controller_ng#326]
```
cf curl /v2/organizations/9bb42328-706e-489b-a969-cbd4ab728ab3 -X PUT -v -d '{"billing_enabled": true}'

...

RESPONSE: [2015-01-22T18:36:12Z]
HTTP/1.1 201 Created
...
```

201 means "created resource" I think the status might be better as 200.

**Comment by dieucao** [comment]
@drnic We agree that 200 would be better but changing it at this point would be backwards incompatible for /v2 end points.  Also, this is actually hard to change due to the meta programming magic.  We're trying to be more thoughtful about this as we work on /v3 endpoints.
