### ISSUE TITLE
Add a tracking tag to "Unknown Error" messages intended for users

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#329]
When emitting an "Unknown Error" message to the client, include a tracking ID
in both the message and the full error written to the log file. If the user needs
more info, someone with access to the VM can help find more details, if 
authorized.

**Comment by jfmyers9** [comment]
Hi @ericpromislow,

Thanks for bringing this to our attention. We are going to revisit how we log UnknownErrors. You can see the state of this work by following the story [here](https://www.pivotaltracker.com/story/show/87833758).

Thanks,

@jfmyers9 && @sergueif, CF Runtime Team

**Comment by aashah** [comment]
There has not been any recent activity on this issue. We are closing the issue.

Please feel free to re-open.

CAPI Community Pair - @aashah @rizwanreza
