### ISSUE TITLE
Docker's registry password

### ISSUE THREAD

**Issue by krismarc** [cloudfoundry/cloud_controller_ng#3304]
Dear Community,

just today, I've learnt the docker image is pulled each time the app is getting restarted. Somehow I though it works like with droplets and those are internally stored within CF until the next app deployment.

It means, if the password is changed the app can't be successfully restarted anymore.

I've also learnt about your recommendation about using 2 passwords. I can imagine this while using registry protected by secrets like in Azure or so. https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#private-repo

However, our internal registry is AD protected and there's no option to configure secondary password for the same user.

Imagine, we have hundreds of applications deployed this way and all of them are using the same user to access the registry. If the password would be changed we are in trouble.

Is there any option to address this? A magic way to update the password on existing app without re-pushing it? I couldn't find such an option using cf cli nor v3 api. I assume it's somehow internally stored within CF because initial password is passed only once when pushing the app as a variable CF_DOCKER_PASSWORD=YOUR-PASSWORD

eg. a direct update on the database level?

Looking forward for your support. Thank you.

Best regards,
K.M.

**Comment by johha** [comment]
Just a quick thought on this, have you tried updating the package? The [package object](https://v3-apidocs.cloudfoundry.org/version/3.138.0/index.html#the-package-object) has a field `data.password` for docker images. If you [update the password of the corresponding app package](https://v3-apidocs.cloudfoundry.org/version/3.138.0/index.html#update-a-package) the new password should be used during the next restart. The endpoint can be called e.g. with `cf curl`.

**Comment by krismarc** [comment]
Unfortunately, seems to be not supported.
```
{
   "errors": [
      {
         "detail": "Unknown field(s): 'data'",
         "title": "CF-UnprocessableEntity",
         "code": 10008
      }
   ]
}
```
even in api documentation optional parameters are just about metadata keys

> Optional parameters
> Name 	Type 	Description
> metadata.labels 	[label object](https://v3-apidocs.cloudfoundry.org/version/3.138.0/index.html#labels) 	Labels applied to the package
> metadata.annotations 	[annotation object](https://v3-apidocs.cloudfoundry.org/version/3.138.0/index.html#annotations) 	Annotations applied to the package

**Comment by krismarc** [comment]
I'm not Ruby expert but I assume having this supported shouldn't be a big deal if there are no 'conceptional' blockers.

https://github.com/cloudfoundry/cloud_controller_ng/blob/4019d2c697693244c2ec8dbb47e2793c1c8a2b14/app/actions/package_create.rb#L20

https://github.com/cloudfoundry/cloud_controller_ng/blob/4019d2c697693244c2ec8dbb47e2793c1c8a2b14/app/actions/package_update.rb#L10

I assume, more or less the same is done if it comes to eg. app rename
https://github.com/cloudfoundry/cloud_controller_ng/blob/4019d2c697693244c2ec8dbb47e2793c1c8a2b14/app/actions/app_update.rb#L17

Is here anyone who could comment on this?

**Comment by johha** [comment]
Looks like you could update docker credentials in the v2 API with a [`PUT /v2/apps/<guid>`](https://apidocs.cloudfoundry.org/16.22.0/apps/updating_an_app.html) request. Implementation: https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/actions/v2/app_update.rb#L102-L110
@sethboyles @Gerg @moleske Any thoughts on this?

**Comment by krismarc** [comment]
@johha it worked! you're my hero :)
I assume this should be re-implemented in v3 as well, no?

**Comment by johha** [comment]
Lets see what some other contributors think. Maybe there was a reason for removing it in v3.

**Comment by Gerg** [comment]
I'm guessing this was just an oversight when implementing v3.  It seems reasonable that we could support this on v3.

**Comment by sethboyles** [comment]
We'd be happy to review a PR that updates v3 to support this.

**Comment by kathap** [comment]
PR to support updating docker registry credentials can be found here: #3467
