### ISSUE TITLE
Why is space_guid required to create apps?

### ISSUE THREAD

**Issue by kevinSuttle** [cloudfoundry/cloud_controller_ng#337]
I'm hoping this is the right repo to ask this API-level question, but I'm wondering why the `create-app` command _requires_ a `space_guid`. What if you don't know it ahead of time? 

Doc: http://apidocs.cloudfoundry.org/195/apps/creating_an_app.html

**Comment by dieucao** [comment]
Currently it's not possible to create an app that exists outside of a space. Therefore we need to know what space to associate it to.  The org/space controls who has permissions to the app and what restrictions are relevant for the app.
The cf cli hides this away by allowing you to target an org/space and not worry about the space guid when dealing with the app.
