### ISSUE TITLE
Add support for RethinkDB

### ISSUE THREAD

**Issue by kevinSuttle** [cloudfoundry/cloud_controller_ng#340]
http://rethinkdb.com/

Realtime API would be amazing. 
http://rethinkdb.com/blog/realtime-web/

Go driver https://github.com/dancannon/gorethink

**Comment by dieucao** [comment]
@kevinSuttle This is not something we're interested in doing at this time.
What use case do you see this solving for cloud controller?

**Comment by kevinSuttle** [comment]
Performance.

**Comment by dieucao** [comment]
Based on the faq it does not seem a good fit for what cloud controller needs.
We do require ACID support for cloud controller.
http://rethinkdb.com/faq/#when-is-rethinkdb-not-a-good-choice
