### ISSUE TITLE
Is it possible to create a brand new user using the CF API?

### ISSUE THREAD

**Issue by kevinSuttle** [cloudfoundry/cloud_controller_ng#342]
https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#id26 Not sure if this validates or invalidates the answer.

**Comment by dieucao** [comment]
You can find more information here:
http://docs.cloudfoundry.org/adminguide/uaa-user-management.html

**Comment by kevinSuttle** [comment]
Thanks. I've been through that doc, but this first line makes me question: 
> "an administrator can create users and manage organization and space roles."

I've also been through this one as well.
http://docs.pivotal.io/pivotalcf/adminguide/cli-user-management.html
> "an administrator can create users and manage user roles."

These elude to the fact that it's not possible create a brand new user.

**Comment by dieucao** [comment]
@kevinSuttle I'm not sure what you mean by that.
When we say administrator, that means a certain user that has appropriate UAA scopes granted to them.
That user can use the CF API, and the cf CLI for that matter, to create new users.
See step 9 of the "creating an admin user" topic for the specific scopes required.

**Comment by kevinSuttle** [comment]
In other words, the application creating the new user can be/is an admin user, because the UAA client has auth tokens on the app's behalf?

**Comment by dieucao** [comment]
Some applications do this on behalf of users that do not have the required privileges.

**Comment by allomov** [comment]
@dieucao I am wondering what kind of applications are you talking about. Are there any of them in open source? What about a case when I want to grant user privileges to create users with limited scope (for instance he can creates a users for particular space or org)?

**Comment by dieucao** [comment]
@allomov Not sure of any open source applications that do that.  Pivotal's Apps Manager has done this in some instances.  It could create users and set roles for new users using a client provisioned for the application that has the cloud_controller.admin scope. It is then up to that application to be responsible for managing the appropriate business logic.

**Comment by allomov** [comment]
@dieucao yes, this makes sense. Thank you for answer.

As an example I remembered [admin-ui boshrelease errand](https://github.com/cloudfoundry-community/admin-ui-boshrelease/blob/master/jobs/register_admin_ui/templates/bin/register_admin_ui) that used `uaac` to register admin-ui as a client.

I had a talk with manager of dev department, who potentially could need such feature, but he is ok with delegating whole user management to BOSH/CF operators.
