### ISSUE TITLE
Upload bits docs are self-contradictory

### ISSUE THREAD

**Issue by kevinSuttle** [cloudfoundry/cloud_controller_ng#343]
The [upload-bits API doc](http://apidocs.cloudfoundry.org/197/apps/uploads_the_bits_for_an_app.html) contradicts itself. 
`resources` is a required parameter, 

>Fingerprints of the application bits that have previously been pushed to Cloud Foundry. Each fingerprint must include the file path, sha1 hash, and file size in bytes. Fingerprinted bits MUST exist in the Cloud Foundry resource cache or the request (or job, if async) will fail.

but the high-level description says: 
> 'Bits that have not already been uploaded to Cloud Foundry must be included as a zipped binary file named "application".'

**Comment by jfmyers9** [comment]
Hi @kevinSuttle,

We don't see how this is contradictory. `resources` is a list of all bits already uploaded (and retained through resource matching) while the application bits are bits that do not exist in the CloudController's resource cache. We're not sure where you see the contradiction in these two statements. The description of `application` (`A binary zip file containing the application bits.`) could be clearer in that it specifies that it includes only bits that haven't been uploaded; this would match the high level description.

Please let us know if we're misunderstanding this issue or if you have any suggestions for improvement!

@jfmyers9 && @zaksoup, CF Runtime Team

**Comment by kevinSuttle** [comment]
@jfmyers9 So, the application bits have not yet been uploaded, yet `resources` are a required parameter to the `upload_bits` call. Resources, according to the docs, are "Fingerprints of the application bits that have previously been pushed to Cloud Foundry" and "Fingerprinted bits [...] will fail" if they don't already "exist in the Cloud Foundry resource cache".

Is it just a wording issue, or am I just flat our misunderstanding this? Can you upload a brand new application.zip + create a new app in one call, and if so, is this that call?

**Comment by DanLavine** [comment]
Hi @kevinSuttle,

I think we understand the confusion now. `resources` is a required parameter in the body of your PUT, however this does not mean that it needs to contain any values (it can be an empty array). Our standard workflow (as implemented by the cli, `cf push`) will call out to `/v2/resource_match` and then send the result in the PUT to `/v2/apps/:guid/bits`.

Sorry for the confusion,

@jfmyers9 && @DanLavine, CF Runtime Team

**Comment by kevinSuttle** [comment]
Oh I see. Thanks @DanLavine. That makes sense now.
