### ISSUE TITLE
Does cf attempt auto-detection of runtime/buildpack on first push?

### ISSUE THREAD

**Issue by kevinSuttle** [cloudfoundry/cloud_controller_ng#344]
Are buildpacks auto-detected at all? For example, if I just push up a brand new folder or zip file without specifying a runtime, will cf attempt to match a buildpack/runtime?

**Comment by drnic** [comment]
Yes it will auto-detect.




Each build pack in your CF will be asked "do you support this app src?" via it's bin/detect script.




The first buildpack (run "cf buildpacks" for ordered list) to say yes wins.

**Comment by kevinSuttle** [comment]
Thanks. Just saw the `detected_buildpack` property as well. Can you share the source where this happens? Is it known to be reliable and accurate?  http://apidocs.cloudfoundry.org/195/apps/get_app_summary.html

**Comment by kevinSuttle** [comment]
Found these as well. Thanks. 
http://docs.cloudfoundry.org/buildpacks/detection.html

https://github.com/cloudfoundry/nodejs-buildpack/blob/master/bin/detect
