### ISSUE TITLE
Storing bound service VCAP env. vars in manifest.yml?

### ISSUE THREAD

**Issue by kevinSuttle** [cloudfoundry/cloud_controller_ng#345]
As far as I see, there is no way to specify env. vars for a bound service in a manifest. 
Right now, all you can do is list the service name. 
The docs say to use VCAP_Services, but there is no YAML equivalent (maybe there shouldn't be, could be by design and there's a way to reference this). 

Hopefully that makes sense. I can provide further examples if need be.

**Comment by jfmyers9** [comment]
Hi @kevinSuttle,

Can you help us understand your question? From what we can tell, you are asking that in an application manifest you can specify environment variables that will contain credentials of the services specified? 

If so, this feature is not currently supported in CloudFoundry. Currently we use `VCAP_SERVICES` as a generic location for service information. It allows us to prevent environment variable pollution and provides a consistent pattern for apps to access service credentials. Therefore I do not believe there is a plan to change this currently.

Thanks,

@jfmyers9 && @zaksoup, CF Runtime Team

**Comment by kevinSuttle** [comment]
Thanks @jfmyers9. That makes sense. I was referencing this: http://12factor.net/config, and was wondering how a team would share VCAP_Services + environment variables, in both their local environment and their PAAS. I guess that just happens on a per-app basis in the space/org by default?

**Comment by DanLavine** [comment]
Hi @kevinSuttle,

Cloud Foundry has no notion of sharing service information in a manifest for a couple of reasons. The manifest serves as a request to Cloud Foundry of the state you would like your app to be in with information specific to Cloud Foundry. A service is any 3rd party add-on and so some deployments might share the same service while others will not. This makes it impossible to add add service specific details in the manifest.

After starting your application, you can retrieve the `VCAP_SERVICES` from `cf env APP_NAME`.

Hope this helps,
@jfmyers9 && @DanLavine, The Runtime Team
