### ISSUE TITLE
Rubocop reports some violations in the code

### ISSUE THREAD

**Issue by xingzhou** [cloudfoundry/cloud_controller_ng#363]
when doing the `bundle exec rake` test, the rubocop reported some code issues.
![2015-04-16 3 03 08](https://cloud.githubusercontent.com/assets/5344440/7175669/c59a205c-e449-11e4-9332-0ed3f4db03dd.png)

**Comment by xingzhou** [comment]
fix submitted: https://github.com/cloudfoundry/cloud_controller_ng/pull/364

**Comment by zaksoup** [comment]
Thanks for checking this out for us! We caught it pretty quickly but we appreciate you looking out!
