### ISSUE TITLE
Cannot reset the command if set on the initial create/push of an application

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/cloud_controller_ng#371]
Easiest way to reproduce it.

1. cf push myapp -c abc --no-start
2. cf push myapp -c null --no-start

cf curl /v2/apps/GUID will show that the command is still abc.

The problem is during the app creation, console touches metadata which populates the metadata with the command. The command is then stored in the metadata as part of the app creation.

Any further attempt to reset/remove the command will pick it up from the metadata.

**Comment by dieucao** [comment]
This was addressed by #373
