### ISSUE TITLE
Invalid parameter in quota documentation example

### ISSUE THREAD

**Issue by sleungcy** [cloudfoundry/cloud_controller_ng#3762]
Hi,

The example provided in the documentation seems to be invalid. The documentation uses `domains.total_domains` rather than `domains.total_private_domains`. 

Could you help clarify in the docs which is the correct parameter to use?

https://github.com/cloudfoundry/cloud_controller_ng/blob/337bf712bd83583958b8c28e8d60f1f5ccb41490/docs/v3/source/includes/resources/organization_quotas/_update.md.erb#L31

Thanks,
Sam

**Comment by tcdowney** [comment]
Thank you for pointing out this issue @sleungcy! The correct parameter to use in V3 is `domains.total_domains`. I just submitted PR #3786 to correct it.
