### ISSUE TITLE
Large number of db migrations can cause bosh job to fail to start

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/cloud_controller_ng#379]
On new CF deployments (currently deploying v201) we see intermittent failures of the CC when trying to start for the first time. It would appear that the bosh timeout is hit before all the db migrations are run.

When I login to the server and restart the job via monit, it starts quickly because there are no db migrations to run.

Is there an optimization of the db schema scripts to reduce the number of migrations need to be run. Can we flatten some when we move to v3?

**Comment by dieucao** [comment]
@johnmcteague We have this story [1] to increase the time allowed for ccdb migrations to run.  
[1] https://www.pivotaltracker.com/story/show/92724718
Currently it's killed after 30 seconds.
We are definitely concerned about the migration times involved with moving to v3 so we'll be looking at that closely before we start adding those to cf-release.
