### ISSUE TITLE
"add_delete_cascade_to_foreign_keys.rb" Can fail due to missing Builds

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/cloud_controller_ng#3803]
## Issue

In this commit: https://github.com/cloudfoundry/cloud_controller_ng/commit/ad9b5a1f29526df1307edf4644a0e733bbbb8bcb#diff-214a865c0b7fb0f3d7d40880ce1e6b38ebf38dd2cb104703663844da306dddc3R11, when adding a foreign key constraint to `build_guid` on`buildpack_lifecycle_data`, the migration also attempts to delete all `buildpack_lifecycle_data` that has a `build_guid` no longer present in the `builds` table.

They query it runs is this:

```
SELECT * FROM `buildpack_lifecycle_data` WHERE (`build_guid` NOT IN (SELECT `guid` FROM `builds`))
```

The issue is that when trying to delete orphaned `buildpack_lifecycle_data`, there are still `buildpack_lifecycle_buildpacks` with `buildpack_lifecycle_data_guids`.  These `buildpack_lifecycle_buildpacks` have their own foreign key constraint, and this causes the following error:

```
Sequel::ForeignKeyConstraintViolation: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`ccdb`.`buildpack_lifecycle_buildpacks`, CONSTRAINT `fk_blbuildpack_bldata_guid` FOREIGN KEY (`buildpack_lifecycle_data_guid`) REFERENCES `buildpack_lifecycle_data` (`guid`) ON DELETE RESTRICT) (Sequel::ForeignKeyConstraintViolation)
```
 
## Steps to Reproduce

1. Spin up an environment that predates the migration ([CAPI 1.172.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.172.0)) or otherwise revert the migration.
1. Push an app.  This should create a `build`, `buildpack_lifecycle_data`, and `buildpack_lifecycle_buildpack`
1. Manually delete the build from the DB <--it's unclear yet how this happens in real envs
1. Run the migration (or execute `SELECT * FROM buildpack_lifecycle_data WHERE (build_guid NOT IN (SELECT guid FROM builds))`
1. Observe the error

## Expected result

The migration successfully deletes the orphaned `buildpack_lifecycle_data` AND `buildpack_lifecycle_buildpack(s)`

## Current result

error as described above

## Possible Fix

I'm not sure, but I think possibly swapping Lines 11 and 12 of the migration would fix the migration.

https://github.com/cloudfoundry/cloud_controller_ng/blob/ad9b5a1f29526df1307edf4644a0e733bbbb8bcb/db/migrations/20240115163000_add_delete_cascade_to_foreign_keys.rb#L11-L12

This way the delete cascade is applied to the `buildpack_lifecycle_data_guid` on `buildpack_lifecycle_buildpacks` BEFORE attempting to delete orphaned `buildpack_lifecycle_data`
https://github.com/cloudfoundry/cloud_controller_ng/blob/ad9b5a1f29526df1307edf4644a0e733bbbb8bcb/db/migrations/20240115163000_add_delete_cascade_to_foreign_keys.rb#L29

@philippthun

**Comment by philippthun** [comment]
@sethboyles - I was able to reproduce the issue by enhancing the (already existing) unit test for this migration. Changing the order of migration statements (as you suggested) fixes the problem (e.g. makes the unit test pass).
