### ISSUE TITLE
Cloud controller logs have too much low-information entries

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#384]
The logs for parse_params, cc.read, and cc.enumerate.related should be downgraded to DEBUG2.  They fill up the logs and rotate more useful messages to secondary files, and quickly to oblivion.

**Comment by zaksoup** [comment]
Hi @ericpromislow, thanks for submitting this issue!

We appreciate your input when describing this issue, however we find the information in these log messages useful when debugging. As such we will not be changing log levels at this time.

Best,
@zaksoup + @wendorf, CF Runtime Team

**Comment by ericpromislow** [comment]
We just reopened discussion on this issue, and fail to see how any of the affected messages are useful. Place log.debug messages in two broad categories: 1: log potentially anomalous, and infrequent, conditions in the field that could be useful to support teams, and (2): emit messages that help the developers better understand their code. I would say we have no business pushing type-2 log.debug messages into production, especially when they cause logs to turn over in less than a minute on busy clusters.  @zaksoup and @wendorf, could you explain some specific benefits of retaining these statements?
