### ISSUE TITLE
Deleting the only OrgManager in an org yields too vague err message - The request is invalid

### ISSUE THREAD

**Issue by michaljemala** [cloudfoundry/cloud_controller_ng#385]
Can you please improve the error message returned when trying to unset the only OrgManager in an org as the `Server error, status code: 400, error code: 10004, message: The request is invalid` is not very helpful.

To replicate just run:

```
cf create-org test-org
cf create-user user1 user1
cf set-org-role user1 test-org OrgManager
cf unset-org-role user1 test-org OrgManager ------> Will yield the the 400 - The request is invalid.
```

**Comment by zaksoup** [comment]
Thanks for letting us know about this, @michaljemala 

I've created a [bug in our backlog](https://www.pivotaltracker.com/story/show/96249276) that our PM will prioritize. As always, we will also welcome any pull request adding this functionality to the Cloud Controller!

Thanks again,
@zaksoup CF Runtime Team

**Comment by zaksoup** [comment]
Hi @michaljemala,

We have added the ability for an admin to remove only OrgManager as well as improved the error returned.

Please see https://github.com/cloudfoundry/cloud_controller_ng/commit/9d9911e676ce5171fab29cf0595e8c6da2b59bf8
