### ISSUE TITLE
Admin cannot delete only OrgManager

### ISSUE THREAD

**Issue by EngineerBetter** [cloudfoundry/cloud_controller_ng#386]
As an admin, I'd like to be able to delete the only OrgManager for an Organisation.

I'm working on an automation tool to declaratively configure entities in Cloud Foundry (orgs, spaces, services, users, and so on). As I can create an Org without an OrgManager, I should also be able to revert back to that state. As it stands, one cannot, which makes testing harder and also means some operations are irreversible.

Either Orgs should require an OrgManager on creation, or admins should be able to delete the last remaining OrgManager.

**Comment by dieucao** [comment]
@EngineerBetter This was fixed in cf-release 213. (Currently recommending to not upgrade to 213 due to some possible cloud controller down time during the deploy)

**Comment by EngineerBetter** [comment]
Cool, thanks!
