### ISSUE TITLE
Assign permissions to LDAP users before first login

### ISSUE THREAD

**Issue by palonsoro** [cloudfoundry/cloud_controller_ng#390]
Good morning.

While I have been using CF integrated with LDAP. I noticed that you cannot grant permissions at organizations/spaces to a LDAP user until that user has already logged in at least once. This may not be a big problem for a small team, but for a bigger amount of users (600-700 people), this makes CF administration much more complicated.

Would there be any solution for this?

**Comment by dieucao** [comment]
Yes, there's a couple of stories further down in the backlog that helps to address this problem.
https://www.pivotaltracker.com/story/show/88838792
https://www.pivotaltracker.com/story/show/90565766

**Comment by palonsoro** [comment]
Thank you for pointing that
