### ISSUE TITLE
Missing validations for application fields

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/cloud_controller_ng#392]
If someone requests -512M of disk, there is no check if disk is less than 0. There is a check if memory is less than 0. I didn't look if there are other fields that are also missing basic validation checks.

The odd thing is that a push with -512 M appears to stage, and attempt to start, but doesn't actually ever run.

**Comment by dieucao** [comment]
Fixed this back in June with this commit.
https://github.com/cloudfoundry/cloud_controller_ng/commit/d2aeb2fef506f78255d392e91af1acd601c9c37d

Okay to close @fraenkel ?

**Comment by fraenkel** [comment]
Yes.  Closed
