### ISSUE TITLE
Normal users are not authorized to perform the requested action get /v2/users .

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry/cloud_controller_ng#393]
My uaa config oauth user authorities are:
    - openid
    - scim.read
    - scim.userids
    - scim.me
    - cloud_controller.read
    - cloud_controller.write
    - cloud_controller_service_permissions.read
    - password.write
    - uaa.user
    - approvals.me
    - oauth.approvals
    - notification_preferences.read
    - notification_preferences.write

I have the cloud_controller.read authority, but when i use /v2/users api , not admin user,they tell me 403 , I want to know, this is my configuration problem? or any other problems caused by.If only the cloud_controller.admin can get users , i think this setting is not very reasonable.

**Comment by utako** [comment]
Hi @wdxxs2z,

This is intended behavior. We currently do not allow non-admins to access /v2/users, as we consider it a security risk. We do, however, plan on allowing org/space managers to set roles by username within the next couple of weeks. The story can be tracked [here](https://www.pivotaltracker.com/story/show/88838792) if you're interested.

Hope this helps,
@utako && @DanLavine, CF Runtime Team

**Comment by wdxxs2z** [comment]
Thank you utako ,closed.
