### ISSUE TITLE
Nginx conf line prevents me from seeing files for my app

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/cloud_controller_ng#400]
The nginx conf line here prevents me from seeing my files in an app container: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh-templates/nginx.conf.erb#L94

I have an app that I push onto the platform that contains source in a directory called "application". I then run `cf files my-app app/application` and I get a 405 back. The greedy regexp here seems to cause the issue as the path for that request is the following:
/v2/apps/<app-guid>/instances/0/files/app/application

This means that anyone with a directory called application will not be able to see the files in that directory. Looking at the regex, this also probably applies to a directory called "bits".

**Comment by utako** [comment]
Good morning @ryanmoran,

We have a [bug](https://www.pivotaltracker.com/story/show/85564044) in tracker that would fix this issue. We'll talk to @dieucao about possibly prioritizing this higher. 

Thanks!
@wendorf && @utako, CF Runtime Team
