### ISSUE TITLE
API docs for resource_match endpoint lack detailed description

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cloud_controller_ng#410]
These [docs](http://apidocs.cloudfoundry.org/214/resource_match/list_all_matching_resources.html) generated by this [spec](https://github.com/cloudfoundry/cloud_controller_ng/blob/be46952c8648d61cfe016f0f684e31e8c89649c8/spec/api/documentation/resource_matches_api_spec.rb) lack sufficient description about what the endpoint actually does.  The docs could better explain:

* What is it for?
* Exactly what resources is it matching?
* What are the semantics of the request and response bodies?

**Comment by dieucao** [comment]
@Amit-PivotalLabs 
Updated description here:
http://apidocs.cloudfoundry.org/runtime-passed/resource_match/list_all_matching_resources.html

Do you think that sufficiently explains it?

**Comment by Amit-PivotalLabs** [comment]
@dieucao yes, asked a fresh pair of eyes to look, it made sense.
