### ISSUE TITLE
what the "v3" directory for?

### ISSUE THREAD

**Issue by jassonSQ** [cloudfoundry/cloud_controller_ng#413]
I am a new comer, I am reading CC code, and I am confused that what the "v3" directory for? Does it means "version 3"?

**Comment by wendorf** [comment]
Hi @jassonSQ ,

You're absolutely right. We're currently working on creating a version 3 of the Cloud Controller API, which has the goal of reducing the coupling between concepts (e.g. apps and droplets) to allow users of the API to have finer control over their applications.

I encourage you to watch [this talk](https://www.youtube.com/watch?v=Cz3rKCHicf4&list=PLhuMOCWn4P9g-UMN5nzDiw78zgf5rJ4gR&index=33) from the Cloud Foundry Summit 2015 about the motivations behind v3, and to look at the in progress [API documentation](http://apidocs.cloudfoundry.org/release-candidate/) (v3 APIs are currently marked as "experimental").


Cheers,
Dan Wendorf
Cloud Foundry CAPI team
