### ISSUE TITLE
Documentation for VCAP_APPLICATION environment variable

### ISSUE THREAD

**Issue by abhikco** [cloudfoundry/cloud_controller_ng#414]
In the documentation for application environment variables, the details of a few VCAP_APPLICATION  attributes are misleading and wrong (http://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#VCAP-APPLICATION ):

1. application_id: With commit https://github.com/cloudfoundry/dea_ng/commit/3e1c2be17ca5dcd4073fdccbbb36620aba70d233  , this attribute is also added to the VCAP_APPLICATION variable. However, this is not documented at all.

2. instance_id: This represents the GUID of the application instance and not the "GUID that identifies the application". Instead, it is the 'application_id' field which identifies the application.

Requesting an update of the docs to clear these issues.

**Comment by abhikco** [comment]
In a related note, for the fields "application_version" and "version", the docs state that it is a "GUID that identifies a version of the application that was pushed. Each time an application is pushed, this value is updated". However, I found that even upon restarting an app (cf restart APP_NAME), the application version is updated. 
Can the documentation be updated to reflect this as well? I hope this is the intended behavior

**Comment by jberkhahn** [comment]
Hello there @abhikco,

This has been updated in the Cloud Foundry docs. Take a look [here.](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html)

If you think anything else needs to be updated, please let us know.

Thanks,
@jberkhahn & @wendorf 
CF CAPI Team

**Comment by abhikco** [comment]
@jberkhahn : Thanks ! This looks fine
