### ISSUE TITLE
Broken cc.runner logger

### ISSUE THREAD

**Issue by vlerenc** [cloudfoundry/cloud_controller_ng#417]
Hi guys,

@mandelsoft and I accidentally made a mistake when configuring our CF system. What we saw during analysis was that cc.runner wasn't logging anything (especially not during seeding). Line 87 in https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/runner.rb#L87 initializes the cc.runner logger implicitly while initializing the message bus. However, the actual configuration for the logger is not read until line 89 when the cloud controller initialization is triggered. So no cc.runner log gets written, especially not the logs made during CC seeding in line 91.

We could validate this by switching the initialization order. If the logging is initialized (call of setup_logging) before the message bus is initialized that implicitly initializes the logger, the cc.runner logger logs properly.

You can reproduce this by inserting logs after the CC initialization. They won't appear until you call setup_logging before the message bus implicitly initializes the logger:
```ruby
setup_logging
message_bus = MessageBus::Configurer.new(servers: @config[:message_bus_servers], logger: logger).go
logger.info("TEST INFO LOG")
logger.error("TEST ERROR LOG")
start_cloud_controller(message_bus)
```

Cheers, Uwe and Vedran

**Comment by wendorf** [comment]
Hi @vlerenc ,

Thank you for bringing this to our attention. We made [a commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/1aae2c31b5e24c7476893bcd3269fe74355fe18c) that should address this. Please let us know if there are any outstanding concerns.


Thank you,
@wendorf and @jeffpak93 , Cloud Foundry CAPI team

**Comment by vlerenc** [comment]
Great, thanks!
