### ISSUE TITLE
Need a way to configure how many stagers to select across

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/cloud_controller_ng#419]
In larger environments, selecting one from the top 5 isn't always ideal. In the case of freshly rolled DEAs (although this is a more serious issue) or imbalanced DEAs, the selection will tend to select the same 5 DEAs for all future staging requests until they have more running applications.

During this window which can be days, users experience frequent staging failures because they are all competing for the disk and network.

Ideally we would want to be smarter, however, in the interim, it might prove better to at least spread the pain to more DEAs. Whether its a "fixed" number or a percentage of known DEAs doesn't really matter. The goal is to improve the end user perception.

**Comment by dieucao** [comment]
The PR has been merged and should be available in the next cf-release.
