### ISSUE TITLE
Cloud controller logs have developer-oriented debug information

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#427]
Another attempt at contributing our fixes for reported/rejected bug https://github.com/cloudfoundry/cloud_controller_ng/issues/384. Sometimes we needed Stackato customers to run in debug mode when running into problems, but the cloud-controller logs would fill up with messages that are more useful during development (this rest call is getting these parameters, we're copying to the blobstore, we're about to request info across nats), and not about potentially anomalous situations.  We've applied this fix to solve our pain point.  Pull request to follow.

**Comment by jeffpak93** [comment]
Hi @ericpromislow ,

We've addressed this issue through the [PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/428) you sent. We'll be closing this issue now, but if you have any other concerns, feel free to open a new issue. Thanks!

Best,
@jeffpak93, CF CAPI Team

**Comment by ericpromislow** [comment]
Sounds good. I'm now working on a fork much closer to upstream CF, so will have a more appropriate PR in the future.
