### ISSUE TITLE
Apps Manager on Prod hitting users/summary

### ISSUE THREAD

**Issue by weymanf** [cloudfoundry/cloud_controller_ng#429]
On production we see a spike on newrelic. When we investigated it, it seems there is a very slow query made on the ccdb. 

This was somebody calling the /v2/users/summary. We know this endpoint is terribly slow, but maybe there can be an investigation to make it faster.

Slow Query:
```
SELECT `users`.* FROM `users` INNER JOIN `organizations_managers` ON (`organizations_managers`.`user_id` = `users`.`id`) WHERE (`organizations_managers`.`organization_id` = ?)	

Time: 41.7 s on 09/11 09:20
```

**Comment by dieucao** [comment]
@weymanf We spent some time investigating. Details in the tracker story.   Could you take a look?

**Comment by dieucao** [comment]
Closing this issue.
Suggest to use individual end points for now instead of the summary end point.
