### ISSUE TITLE
CCNG .rspec file has a typo, and --profile output isn't needed

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#430]
Running `rake spec` with --profile off speeds up the run negligibly, but
produces output that is almost always uninformative.

However, "--color" is misspelled as "--colour" in the .rspec file.

I would also recommend adding 
config.backtrace_exclusion_patterns to hide lines from sinatra and other
ignorable gems in the backtrace.

**Comment by zrob** [comment]
PR merged
