### ISSUE TITLE
cf apps command in one spaces errors out - v211

### ISSUE THREAD

**Issue by balajeen** [cloudfoundry/cloud_controller_ng#439]
This command works for other spaces - just fails for this one.

cf curl /v2/apps works fine - 13 apps are running, 

Any ideas?
From cloud_controller_ng logs see this

{"timestamp":1443040260.7873325,"message":"Request failed: 500: {\"code\"=>10001, \"description\"=>\"HTTPClient::KeepAliveDisconnected: \", \"error_code\"=>\"CF-KeepAliveDisconnected\", \"backtrace\"=>[\"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:895:in `block in parse_header'\", \"/var/vcap/packages/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'\", \"/var/vcap/packages/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:101:in `call'\", \"/var/vcap/packages/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:101:in `timeout'\", \"/var/vcap/packages/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:127:in `timeout'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:888:in `parse_header'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:871:in `read_header'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:678:in `get_header'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:1215:in `do_get_header'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:1164:in `do_get_block'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:962:in `block in do_request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:1064:in `rescue in protect_keep_alive_disconnected'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:1058:in `protect_keep_alive_disconnected'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:961:in `do_request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:823:in `request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:726:in `post'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/hm9000/client.rb:76:in `post_bulk_app_state'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/hm9000/client.rb:96:in `make_request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/hm9000/client.rb:90:in `app_state_bulk_request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/hm9000/client.rb:23:in `healthy_instances_bulk'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/instances_reporter.rb:38:in `healthy_instances_bulk'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/dea/instances_reporter.rb:21:in `number_of_starting_and_running_instances_for_apps'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/backends/instances_reporters.rb:32:in `number_of_starting_and_running_instances_for_apps'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/controllers/runtime/space_summaries_controller.rb:39:in `app_summary'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/controllers/runtime/space_summaries_controller.rb:33:in `space_summary'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/controllers/runtime/space_summaries_controller.rb:15:in `summary'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/app/controllers/base/base_controller.rb:76:in `dispatch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1602:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1602:in `block in compile!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'\", \

**Comment by dieucao** [comment]
Could you try 
`CF_TRACE=true cf apps`

**Comment by balajeen** [comment]
$ CF_TRACE=true cf a

VERSION:
6.11.2-2a26d55

Getting apps in org predix-release / space predix-acs as admin...

REQUEST: [2015-09-23T16:25:23-07:00]
GET /v2/spaces/458b857b-fe1f-4646-94fc-c8b28461bf4e/summary HTTP/1.1
Host: api.system.aws-usw02-pr.ice.predix.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.11.2-2a26d55 / darwin



RESPONSE: [2015-09-23T16:25:24-07:00]
HTTP/1.1 401 Unauthorized
Content-Length: 97
Content-Type: application/json;charset=utf-8
Date: Wed, 23 Sep 2015 23:25:25 GMT
Server: nginx
X-Cf-Requestid: 16764787-cb50-4178-5fba-02bc4bd771ca
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 3daaf178-7520-495e-7a7c-9d50633c9d28::98bf2012-2533-46a9-942f-565bf7b06434

{
  "code": 1000,
  "description": "Invalid Auth Token",
  "error_code": "CF-InvalidAuthToken"
}


REQUEST: [2015-09-23T16:25:24-07:00]
POST /oauth/token HTTP/1.1
Host: login.system.aws-usw02-pr.ice.predix.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.11.2-2a26d55 / darwin

grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJjZDY5NmI1Yy0zOGI0LTRjNTYtYmU4MS0wNGYxY2U3NDJiYzkiLCJzdWIiOiI2Y2ZkYzI4OC1jNTBiLTQ5MjQtYWU1ZS1hN2RkN2U0OTRlNjIiLCJzY29wZSI6WyJzY2ltLnJlYWQiLCJjbG91ZF9jb250cm9sbGVyLmFkbWluIiwic2NpbS53cml0ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJwYXNzd29yZC53cml0ZSIsIm9wZW5pZCIsImNsb3VkX2NvbnRyb2xsZXIucmVhZCIsImRvcHBsZXIuZmlyZWhvc2UiXSwiaWF0IjoxNDQzMDQwODAzLCJleHAiOjE0NDU2MzI4MDMsImNpZCI6ImNmIiwiaXNzIjoiaHR0cHM6Ly91YWEuc3lzdGVtLmF3cy11c3cwMi1wci5pY2UucHJlZGl4LmlvL29hdXRoL3Rva2VuIiwiemlkIjoidWFhIiwiZ3JhbnRfdHlwZSI6InBhc3N3b3JkIiwidXNlcl9uYW1lIjoiYWRtaW4iLCJ1c2VyX2lkIjoiNmNmZGMyODgtYzUwYi00OTI0LWFlNWUtYTdkZDdlNDk0ZTYyIiwiYXVkIjpbImNmIiwic2NpbSIsImNsb3VkX2NvbnRyb2xsZXIiLCJwYXNzd29yZCIsIm9wZW5pZCIsImRvcHBsZXIiXX0.I4VrKKYYW_qmjoNUsr02xYMhDIr_SXbqazvObS_tyIQRMGHSGP-FRqcI9ZNMYk7m6dbolHyEKSBAwd99_49V_Pl9ipJBgJRSEqJhrx4potbESi2gH8DJf2qbwkgzpX6wv04W1fCN0yDwioxCT0NhbrHbKbw01f1H074zO6yEk0UvKWM1EzFDnHWbp7WhyKp7fxnjBmj7AOjkN9yqFwQx36LEgQLhUCeA1VGzpgRj7AcK8ADUuRk3E3qtFMhSHO3jH1GntSGTaeYwwDy466XM5FWs7jc1iEq3ZEFR6KOYxhlzbGBYfYpvPwwPzeMUgIZPUXozj6u9ok3Vldi52mYw2g&scope=

RESPONSE: [2015-09-23T16:25:25-07:00]
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-store
Content-Type: application/json;charset=UTF-8
Date: Wed, 23 Sep 2015 23:25:05 GMT
Expires: 0
Pragma: no-cache
Pragma: no-cache
Server: Apache-Coyote/1.1
X-Cf-Requestid: 0d84712b-931d-4cdf-704f-2f27e5cfa464
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

99d
{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"bearer","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":599,"scope":"scim.read cloud_controller.admin password.write scim.write openid cloud_controller.write cloud_controller.read doppler.firehose","jti":"a2608fc4-a1ad-4e1e-b905-958de3197f59"}
0



REQUEST: [2015-09-23T16:25:25-07:00]
GET /v2/spaces/458b857b-fe1f-4646-94fc-c8b28461bf4e/summary HTTP/1.1
Host: api.system.aws-usw02-pr.ice.predix.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.11.2-2a26d55 / darwin





FAILED
Error performing request: Get https://api.system.aws-usw02-pr.ice.predix.io/v2/spaces/458b857b-fe1f-4646-94fc-c8b28461bf4e/summary: EOF
FAILED
Error performing request: Get https://api.system.aws-usw02-pr.ice.predix.io/v2/spaces/458b857b-fe1f-4646-94fc-c8b28461bf4e/summary: EOF

**Comment by zrob** [comment]
@balajeen 

Hi, could you try making the same request that the CC is making manually and see if you get the same issue?

You will first need to look in your deployment manifest for the following fields and note their values:
- internal_api_password
- internal_api_user

Then you need to ssh onto on of your cloud controller vms.   They look like api_zx on a bosh deployment.

Then you can run `curl -vvv https://[internal-user]:[internal-pass]@[hm9000-ip-address]/bulk_app_state -X POST`

Also we are going to go ahead and bump the version on our http client because we noticed it was a little older.  We did not see anything specific in the updates for this issue, but it's possible it could help.

Thanks,
@zrob & @swetharepakula

**Comment by justalisteningman** [comment]
Hey @balajeen 

Did you have any luck with this?  

Thanks, 
 Ben Watts

**Comment by rmasand** [comment]
Hi @balajeen,

Going to close this issue since we haven't heard back in well over a month. Feel free to reopen it if you'd like to continue discussing.

Thanks,
Raina Masand
CAPI Team
