### ISSUE TITLE
app.rb: has_stop_event_for_latest_run? definition removed, but one use remains

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#444]
In commit 7cf51e3329647370efffcd315087e37776c3e178 there's still code using this reference, and from my running `spec/actions/app_stop_spec.rb` there's no test exercising the `generate_stop_event?` method with the dangling reference.

**Comment by justalisteningman** [comment]
Hi @ericpromislow,

Nice catch; it looks like this should've been removed with its calls during that commit. This issue raised underlying logical cruft from the era where billing events existed.  Specifically,  the method that calls `has_stop_event_for_latest_run?`, `generate_stop_event?` wasn't used anywhere - so we plan on deleting it.  But we also noticed the `generate_start_event?` method IS being used (once), outside the billing events context. 

At any rate - thanks for bringing it up, we'll be addressing it soon. 

Ben Watts

**Comment by dieucao** [comment]
The fix for this will be included in the next cf-release.
