### ISSUE TITLE
security_groups.rules column too small

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#445]
We are trying to create a security group to cover all AWS subnets.  This creates a rule too large for a single security_group.  Thoughts in changing security_groups.rules from VARCHAR(2048) to mediumtext?  Would this change create a problem?

We can work around the issue by creating multiple security_groups but that is messy.

**Comment by dieucao** [comment]
@youngm 
Thanks for pointing this out.
We have a bug [1] currently prioritized in our backlog that's likely to land in the next month.
We were thinking of upping the size to 16384 chars.
That's not quite as large as mediumtext though.
I understand that rules can be very specific and add up to quite a bit of characters
Would the suggested 16384 be sufficient for your use cases that you foresee?
Or significantly more than that?

[1] https://www.pivotaltracker.com/story/show/102449084

**Comment by youngm** [comment]
We are attempting to create security groups for popular large cloud providers.  For AWS we're using the source [0].  For Azure we're using [1].

Currently it takes 16 security groups to contain all of AWS and 34 to contain all of Azure.  Just in the last month azure has grown by 4 security groups and aws grown by 1 security group.

16K definitely wouldn't be big enough.  64K (Text) would work for now.  16M (mediumtext) would work for a lot longer. :)


[0] https://ip-ranges.amazonaws.com/ip-ranges.json
[1] http://www.microsoft.com/en-us/download/details.aspx?id=41653

**Comment by youngm** [comment]
Actually I guess 64K would be tight to fit azure in today if it could fit.

**Comment by dieucao** [comment]
@youngm Thanks for the links.
I think its okay to up the size of the column to mediumtext on mysql and the equivalent size on postgres.
As a side note, there's a separate configuration that controls the max body size that cloud controller will accept
`cc.client_max_body_size` that currently defaults to 15M but could be adjusted if that's actually required.

https://github.com/cloudfoundry/cf-release/blob/master/jobs/cloud_controller_ng/spec#L407-L408

I'll update the other story and link to this issue.

**Comment by youngm** [comment]
Excellent.  Thanks @dieucao !

**Comment by dieucao** [comment]
@youngm This should be addressed in the next cf-release that includes the above linked commits.
Thanks!

**Comment by youngm** [comment]
Thanks @dieucao you rock! :)
