### ISSUE TITLE
Custom nginx.conf file

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry/cloud_controller_ng#447]
Hi,

Is there a possibility for customizing CC's nginx.conf?

**Comment by dieucao** [comment]
@charyorde Could you clarify what customization you're looking to do?  What problems are you looking to solve by being able to customize CC's nginx.conf?
We currently expose a few properties:
https://github.com/cloudfoundry/cf-release/blob/master/jobs/cloud_controller_ng/spec

**Comment by charyorde** [comment]
Considering that the route services is still a work in progress, we have a reverse proxy requirement for all our apps. Using the staticfile-buildpack works like a charm, but we want to add other features such as metrics, rate limiting, auth etc, but we can't achieve that with the staticfile-buildpack.

Having the reverse proxy configs directly in CC's nginx.conf would solve this for us breezily.

**Comment by dieucao** [comment]
@charyorde I believe the route services work is actually very nearly complete.
https://www.pivotaltracker.com/epic/show/1884060

I don't think using CC's nginx.conf to configure proxy's for other apps is the right approach.

/cc @shalako

**Comment by charyorde** [comment]
Never knew the route services is the same as [routing api](https://github.com/cloudfoundry-incubator/routing-api). 

While I can't wait any longer to try this out, is [this](http://apidocs.cloudfoundry.org/220/routes/creating_a_route.html) the starting point?

CC's nginx.conf can be more flexible.

**Comment by shalako** [comment]
I agree with @dieucao. CC's nginx should not be used for routing app traffic. 

This design doc lays out the user-facing APIs and CLI commands for Route Services: https://docs.google.com/document/d/1SfwaQ1hnngfopXC_Q24cT6lbo0yFwvbAbPcCPEHeNPY/edit?usp=sharing

You can follow our progress on Route Services here: https://www.pivotaltracker.com/epic/show/2031344

We will publish real documentation for both broker authors and CF end users soon.

**Comment by charyorde** [comment]
@shalako Thanks for docs. Makes things clearer.

One question though. From the above docs, does it mean "rateLimiting" feature is built-in or this is just an example - the broker developer is meant to implement the feature within the broker itself, during service instance provisioning? Likewise metering. Is this builtin just like reverse proxy is?

**Comment by shalako** [comment]
Nothing is built-in. Service brokers are a powerful extension point in CF, enabling service authors to offer developers any kind of transformation, API management, or analytics that may be useful. 

Typically, the service isn't implemented in the broker itself but this is an implementation detail. As brokers may offer multiple marketplace services, they are typically used as a translation layer between CF and the actual services.

Rate limiting is one example of a service that could be offered through the marketplace through the broker and route services integrations.

I don't know what you mean by you mean by "just like reverse proxy is" [built in].

**Comment by charyorde** [comment]
From the doc above:
>The broker may respond with an optional route_service_url. If a valid route_service_url is returned, >GoRouter will be configured to forward requests for the route to the route_service_url

**Comment by shalako** [comment]
The broker must declare `"requires":["route_forwarding"]` in the catalog, or CC will not allow the service instance to be bound to the route.

If a broker returns a `route_service_url` in the create binding response, but has not declared `"requires":["route_forwarding"]` in the catalog, the response is considered invalid, the user receives an error, and CC will attempt to delete the binding.

**Comment by jeffpak93** [comment]
Hi @charyorde ,

We noticed there hasn't been much activity regarding this issue. We hope all your questions about routing app traffic have been answered.

We'll be closing this issue in the meantime. Please feel free to send in another issue should you desire.

Best,
@jeffpak93 & @jberkhahn , CF CAPI Team
