### ISSUE TITLE
Wrong endpoint for experimental packages operations

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#448]
The two operations [Copy a Package](http://apidocs.cloudfoundry.org/220/packages_%28experimental%29/copy_a_package.html) and [Create a Package](http://apidocs.cloudfoundry.org/220/packages_%28experimental%29/create_a_package.html) are using the `/v3/apps/....` endpoint but should be using `/v3/packages/....`. Logically they are packages operations and they are listed under the Packages section of the API docs. All the other packages operations are using the `/v3/packages/....` endpoint, please update these to be the same. This inconsistency is causing issues in the design of the Java Client for the API.

**Comment by simonleung8** [comment]
Thanks for reporting the issue.

It is now being tracked in the [tracker](https://www.pivotaltracker.com/story/show/113296905)

**Comment by adowns01** [comment]
We chose this url scheme to illustrate the underlying relationships between packages and apps. A package requires an app to be created, so we use an endpoint nested under the app `/v3/apps/:app_guid/packages/:package_guid`. However, once the package is created, it can be accessed directly without referencing its app.

Please let us know if this is still an issue and we can look into it further.

Thanks, 
Amelia && Kara @karafelix, CF CAPI Team Members

**Comment by SocalNick** [comment]
We actually have a story to fix this: https://www.pivotaltracker.com/story/show/114742243
