### ISSUE TITLE
Wrong return type for delete operation

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#449]
See: http://apidocs.cloudfoundry.org/214/users/remove_audited_organization_from_the_user.html

A delete operation should not return `201 created`.

**Comment by dieucao** [comment]
@cgfrost 
Thanks for the report.
It's apparently extremely hard to fix this on the v2 end points because of some of the meta-programming magic in cloud controller.
We'll address this when we move the users resource over to /v3.
I'll mark this with the wontfix label though and leave it open

**Comment by fraenkel** [comment]
@dieucao It's actually quite easy to fix. I thought the original reason was to prevent breakage even though I believe most folks would rather it be fixed.

**Comment by dieucao** [comment]
@fraenkel I'll follow up with @zrob . I could have sworn it was because it was hard to change.  I get how it could be considered a backwards breaking change, but it seems silly.

**Comment by cgfrost** [comment]
Possibly related to https://github.com/cloudfoundry/cloud_controller_ng/issues/450

There may be others, we will continue to raise issues as we find them. We're working through the API endpoint one by one to implement a new CF Java Client.

**Comment by dieucao** [comment]
This was addressed as part of the above linked PR from @fraenkel .
http://apidocs.cloudfoundry.org/225/users/remove_audited_organization_from_the_user.html

Closing this issue.
