### ISSUE TITLE
Wrong return type for delete operation and duplicate param

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#450]
See: http://apidocs.cloudfoundry.org/220/security_groups/remove_space_from_the_security_group.html

A delete operation should not return `201 created`, also the parameters list shows `space_guid` twice.

**Comment by justalisteningman** [comment]
Hey @cgfrost, 

Thanks for bringing this to our attention!  

The `201` return code for this endpoint is a known issue in V2.  We're not planning on fixing it in v2, rather, we'll be addressing the issue in v3 of cloud controller. 

As for the the duplicated space_guid field - I'm fixing that as we speak. 

I'm marking this as closed.  Feel free to reopen it if you feel it's necessary.  

Best, 
Ben Watts

**Comment by cgfrost** [comment]
Thanks.

**Comment by dieucao** [comment]
Reopening.  I am thinking about taking in @fraenkel 's PR.  No one has objected on cf-dev to this change.
Leaving this open until then.

**Comment by dieucao** [comment]
Api doc updated.
http://apidocs.cloudfoundry.org/release-candidate/security_groups/remove_space_from_the_security_group.html

As for the return code, please track that as part of this PR https://github.com/cloudfoundry/cloud_controller_ng/pull/453

I'm waiting to hear back from the cf cli if this change would cause an issue for them.

**Comment by dieucao** [comment]
@cgfrost We merged that PR. This change will be available in the next cf-release v223.

**Comment by cgfrost** [comment]
That's great. Thanks.
