### ISSUE TITLE
staging_failed_reason and staging_failed_description type information missing

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/cloud_controller_ng#454]
In (e.g.) https://apidocs.cloudfoundry.org/214/apps/list_all_apps.html and in other v2 REST API responses, the examples show null for these fields. Presumably they are Strings. Can you document this, please?

**Comment by jeffpak93** [comment]
Hi @Zteve ,

Thanks for bringing this up! This is a known issue for these API docs that will be addressed when we update and revamp the docs in the near future. Until then, we would suggest that you interact with any field that you feel unsure of directly to guarantee its type.  It is safe to presume that those fields are strings.

If this addresses your concerns, feel free to close this issue.

Best,
@jeffpak93, CF CAPI Team

**Comment by youreddy** [comment]
Hi @Zteve ,

Apologies for the long response time. We've just made [a commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/66ea954641235ec503aa9e55359e481466137e90) that addresses your issue, and it will be available in the next release of the documentation.

If this does correctly address your concern, please feel free to close this issue.


Cheers,
@youreddy and @wendorf, CF CAPI Team

**Comment by Zteve** [comment]
Great, thanks. There is a small typo in the description of the `staging_failure_description` field. Not important.

**Comment by youreddy** [comment]
@Zteve, 

Just fixed the typo! 44e4e9480469915b06a303a6755b7d0b92bef0a9

Thanks, 
@youreddy, CF CAPI Team
