### ISSUE TITLE
Updates to user provided services do not propagate to bindings

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/cloud_controller_ng#456]
Given the following scenario:
```
cf push dora -b ruby_buildpack --no-start
cf cups drain -l syslog://logs.example.com
cf bs dora drain
cf uups drain -l syslog-tls://logs.example.com
cf start dora
```
The update to the syslog drain is not reflected in the service binding so restarting or re-staging the application does not pick up the changes (which is what the CLI suggests). The only way to get the syslog drain URL updated is to explicitly unbind the service from the affected apps and then bind the service instance again.

This appears to be a side effect of how syslog drains and credentials are copied from a service instance when a binding is created. While this makes (some) sense in the managed service space where this information comes from the bind operation but it seems awkward and confusing in the user provided service space.

Should changes to user provided services have a mechanism to propagate them up through the bindings?

**Comment by dieucao** [comment]
@sykesm It seems like it should.  This is likely one of the many reasons why Shannon would like to get rid of user provided services and replace it with something that uses the same code paths as regular service brokers without requiring users to deploy an actual service broker app.  We can take a look at what it would take to fix this with user provided services though.  Do you have pointers to the relevant pieces of code?

**Comment by sykesm** [comment]
@dieucao The best pointers I can give you are to the [user provided service broker client][client] and the [service instance binding manager][manager]. The client simply adheres to the service broker contract and copies a few pieces of information from the service instance into the binding when the bind operation is called. Since bind isn't called when the user provided service is updated, the binding never gets updated.

There are definitely some assumptions in there that may make this a little more difficult than adding a before_update hook.

[client]: https://github.com/cloudfoundry/cloud_controller_ng/blob/be4a72310d5e30d36883f2dd9fd5ca9f54608bfb/lib/services/service_brokers/user_provided/client.rb#L7-L15
[manager]: https://github.com/cloudfoundry/cloud_controller_ng/blob/be4a72310d5e30d36883f2dd9fd5ca9f54608bfb/app/controllers/services/lifecycle/service_instance_binding_manager.rb#L78-L79

**Comment by SocalNick** [comment]
@sykesm I've verified this is fixed on https://github.com/cloudfoundry/cf-release/tree/acceptance-deployed and will be included in CF-237.

Would you like to verify or shall I close this?

**Comment by sykesm** [comment]
Happy to close. Thanks for looking into solutions and addressing the most common instance.
