### ISSUE TITLE
Too many params on Delete Application

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#458]
For this one http://apidocs.cloudfoundry.org/224/apps/delete_a_particular_app.html

I don't understand why there are so many request parameters just to select an app for deletion, are they there in error.

**Comment by dieucao** [comment]
Yes.  I think they're all there in error. I'll see if we can fix it up.

**Comment by youreddy** [comment]
Hello @cgfrost, 

We've created a fix for this. Look for it in the next cf-release. If there aren't any more concerns, please close the issue. 

Thanks, 
@youreddy and @jberkhahn

**Comment by cgfrost** [comment]
Thanks.
