### ISSUE TITLE
User provided service instances should handle errors when renaming

### ISSUE THREAD

**Issue by d-reinhold** [cloudfoundry/cloud_controller_ng#459]
Steps to reproduce:
```
cf cups foo
cf cups bar
cf rename-service foo bar
```

Expected output: 
```
Server error, status code: 400, error code: 60002, message: The service instance name is taken: bar
```

Actual output:
```
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
```

It's important for products building on top of Cloud Controller to get semantic, useful error messages in these situations.

**Comment by dieucao** [comment]
This has been fixed in https://github.com/cloudfoundry/cloud_controller_ng/commit/bfc76f147a1429d275474762b0e3f28e974e447d

This should be available in the next cf-release, tentatively v226
