### ISSUE TITLE
Create V3 droplets via POST /v3/droplets instead of POST /v3/packages/:guid/droplets

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cloud_controller_ng#460]
Looking at the current API docs, I see that droplets are created by posting to /v3/packages/:guid/droplets with optional lifecycle information. This is confusing to me, because it implies there is a "belongs to" relationship between the droplet and the package (i.e. the droplet belongs to the package), but once the droplet is created, its relationship to the package is more incidental.

It would make more sense to me if droplets were created with POST /v3/droplets, including package_guid as a parameter. The package does seem more like a parameter to the droplet, and less like an owner, so this API feels more natural. It also helps make clear the difference between a package type (e.g. bits, docker, or some day git) versus the lifecycle type of a droplet (e.g. droplet or docker). When creating a droplet that _belongs_ to the package, seeing "type" in both makes me feel like the type will inherit, which is incorrect.

Thanks,
@wendorf

**Comment by michaelxupiv** [comment]
Hi @wendorf,

You make a good point, and this is certainly something we can take into consideration. @SocalNick, thoughts?

@michaelxupiv & @utako, CF CAPI Team

**Comment by SocalNick** [comment]
We create tasks and packages in the context of an app, what do you all think about this?

```
POST /v3/apps/:guid/droplets
{
  "relationships": {
    "package": {
      "guid": "[package-guid]"
    },
  }
}
```

**Comment by michaelxupiv** [comment]
Hey @wendorf ,

Thanks for submitting this issue. It seems like our direction forward is to use a `POST` to `/v3/droplets`, as seen in these upcoming stories: [story1](https://www.pivotaltracker.com/story/show/135883263), [story2](https://www.pivotaltracker.com/story/show/136378233), [story3](https://www.pivotaltracker.com/story/show/137379857). We will update our docs accordingly to the work being delivered as well. Closing this issue for now, feel free to reopen if you are still concerned.

Thanks,
CAPI Community - @michaelxupiv
