### ISSUE TITLE
User can't read private domains related to routes if user doesn't have Space Developer role

### ISSUE THREAD

**Issue by dweber019** [cloudfoundry/cloud_controller_ng#464]
Dear Cloud Foundry Team

I have the following issue at the moment with CF API version 2.25.0.

*Given:* User A has Manager Role on Space A
*Given:* User A hasn't any role on parent Organization B of Space A
*Given:* User A hasn't any Space Developer role on any Space in Organization B
*Given:* User A is able to see all routes related to Space A
*Given:* Organization B has some private domains attached
*Given:* Space A has some routes which are using a private domain from Organization B

If user A list all routes for Space A (for example with /v2/routes?inline-relations-depth=1&q=organization_guid:<org_guid>) he can't see the related domains if the domain is a private domain from parent Organization B.

As user A can see routes, he should also be able to see the directly related private domain else the route information is unless as a route is only fully valid/unique if user A sees the full Url (host + domain).

I expect that if user A has role Auditor or Manager he can also *read* private domains.

Thanks
David Weber

**Comment by dweber019** [comment]
This bug has been fixed with Cloud Controller API version 2.43 or at least the version 2.43 is working fixing my problem.

**Comment by dieucao** [comment]
@dweber019 I believe that was fixed as part of https://www.pivotaltracker.com/story/show/102294544
in cf-release v219.  If this addresses your issue, are you okay to close this issue?

**Comment by wendorf** [comment]
A while has passed since the last activity on this issue, so it appears to be solved and we will close it. @dweber019 , if you have any further questions, please feel free to open another issue.


Thanks,
Cloud Foundry CAPI Team, @wendorf & @fkotsian
