### ISSUE TITLE
No mechanism exists to update the encryption key in the CC

### ISSUE THREAD

**Issue by ScarletTanager** [cloudfoundry/cloud_controller_ng#465]
In Encryptor.rb, a passphrase is used to generate a randomized key used in the CCDB field encryptor.  Unfortunately, once the database has been populated, it is difficult (to the point of being nearly impossible for all practical purposes) to change this key.  Changing encryption keys (and credentials generally) periodically is sound security practice used in most enterprises, and I think it's something CF should support across the board, but maybe we start here?

I think that a feature to implement this would need to handle the entire transaction of decrypting existing fields and reencrypting them using the new key, meaning there would be a window during which both keys would need to be available to the CC (or to whatever component, could be something new, was handling the data reencryption).  I think there needs as well to be some kind of integrity check (a checksum over the entire DB, for all practical purposes?) to ensure that all the data has been migrated before finalizing the Tx (at which point in time only the new key would be available/used).

I think this is likely to be tricky, but I think it's necessary both from an operational perspective and from one of incorporating additional/better security features moving forward (e.g. FIPS enablement of CF will require this as a prereq).

**Comment by dieucao** [comment]
@ScarletTanager I would be interested to learn more about what approaches other projects have taken with this.
Of particular concern is that any approach that we take needs to consider rolling deploys where some CC's will have new code/configuration before other CC's and migrations ideally performed in a way that could be backwards compatible, perhaps introduced over several releases.
@ematpl mentioned for Diego they had padded the fields to indicate which key was used.
They could then decrypt with the correct key and encrypt with the new active key.
From there it likely makes sense to consider a slower, asynchronous job, combing through the db and decrypting/re-encrypting fields to ensure all fields are eventually encrypted with the new active key, at which point the older key could be removed.

**Comment by ScarletTanager** [comment]
I agree with the general idea of an asynchronous job acting in much the manner you describe.  But I also think that you need to have some very careful synchronization between that job and the CC itself - how does the CC know that it's time to switch to using the new key (and new DB/tablespace/whatever is being used to store the fields encrypted with the new key), e.g.?  One might go the route of giving the CC enough intelligence to say, "inserts use the new key and $NEWCONTAINER, but updates to existing rows use the old key and $OLDCONTAINER," but I worry about how you manage that decision logic.  So I definitely agree with a KISS approach as much as humanly possible.  Thoughts?

**Comment by fraenkel** [comment]
Let us not over complicate things. The goal should be to minimize locking as much as possible and allow normal processing to occur.

We all agree you need the "current" encryption key, and potentially a set of decryption keys.
There is a table which would mark the current encryption key for each table. This mapping can be dynamically deduced by walking the models. It shouldn't have to be said but do not store the actual value of the encryption key.

Any read activity will attempt to decrypt with the encryption key and on failure go through the list of decrypt keys. Any update will use the encryption key.

To convert a table, each row is update individually. One can easily determine the set of rows that need to updated prior to conversion. Once all the rows have been updated, the encryption key table is updated.

**Comment by ScarletTanager** [comment]
@fraenkel Thanks for the head-shaping, I like that approach.  I don't think anyone had brought forth the idea of storing the actual key itself, or at least I hope noone had.

I'm not sure I fully grok your last paragraph, and I hope I'm not being overly obtuse.  I interpret your approach to mean that both the CC itself and the async converter would be doing encryption with `$CURRENTKEY`, and decryption would be done in the manner you describe.  I do think that simplifies things - at the moment you mark a new key as current, any inserts/updates will be encrypted with that key, and if the async converter simply figures out the current last row in each table, then yes, it can simply walk each table up to that point and do the conversion, and as long as we know that the CC is doing any new inserts with `$CURRENTKEY`, we should be good.  I think in this scenario you actually mark the new key as current at the beginning, not the end of the job.  Am I wildly offbase?

**Comment by fraenkel** [comment]
I realize that there is a slight issue on how to flip to say current key is in use.

Having a mapping table is somewhat optional and potentially confusing. Let's drop it for now.
To make this work without any issues, one would need to do something like the following:
1. Deploy with new key in decryption list
2. Deploy with new key as encryption key and removed from decryption list
3. Run a re-encrypt job after the second deploy completes.

The mapping table is just an optimization for step 3 but should never be used for runtime purposes.

**Comment by dieucao** [comment]
@justinjsmith @johnpfield @zrob @onsi 
Any thoughts on @fraenkel 's suggestion?
It sounds reasonable to me.
I'm hopeful that this change can be done in a backwards compatible way.

**Comment by zrob** [comment]
the approach @fraenkel defines seems solid

as he mentions we should be leery with any mapping table approaches that would require us to do something special when new tables/columns that need encryption come up

**Comment by fraenkel** [comment]
Creating or destroying tables shouldn't matter.
All models should be scanned to determine encrypted columns. The table should have no entry if its new and should be deleted if there are no encrypted columns for the table. Its just there as book keeping to know that the columns have been updated.

**Comment by dieucao** [comment]
@ScarletTanager synced up with @justinsmith and we think this approach sounds good.
If you're still up for it, happy to take a PR with this approach.

**Comment by ScarletTanager** [comment]
@dieucao I'm working on it with a team member.  Talked the key rotation over with @fraenkel and @sykesm , will likely try to make that work in a manner similar to how Diego handles it to keep things consistent across components.  Will update as we progress.

**Comment by johnpfield** [comment]
+1 to consistency. On two levels.

In general, we should always try to maintain a consistent approach to common security patterns / use cases, such as key rotation.  In addition, IIRC, the Diego approach does not require a separate crypto housekeeping task, but rather the logic for dealing with key rotation is just part of the runtime. I would encourage this model, as it ensures that rotating the key does not constitute a special operational task/event.  It should just be business as usual.

**Comment by dieucao** [comment]
@ScarletTanager Do you have an update on this PR? Do you still intend to submit a PR for this?

**Comment by ScarletTanager** [comment]
@dieucao Yes, I have one half-finished, but I got sidetracked by RuntimeOG work.  I will try to polish it and have Michael review by next week.

**Comment by aashah** [comment]
@ScarletTanager Has there been any activity on this front?

**Comment by ScarletTanager** [comment]
@aashah Wow, I'm surprised this is still open.  Honestly, no, and I'd probably have to start from scratch (although it's not a hard change, IIRC).  I'm not hearing a huge hue and cry on our side for this (although I personally think it's kind of important).  I'm going to close this for now - I can reopen it if it becomes a priority.

**Comment by cnelson** [comment]
So it's impossible to rotate db_encryption_key?  We have compliance requirements that mandate all secrets are rotated when staff members change.  How can we change this?

**Comment by rogeruiz** [comment]
Pinging again, @ScarletTanager. Will it every be possible to rotate `db_encryption_key: ccdb_encryption_key`?

**Comment by ScarletTanager** [comment]
@rogeruiz I am sure it will be at some point.  I will see if my side wants me to reopen this, in which case I may have the time to PR the work (it isn't huge) in the next couple of weeks.
