### ISSUE TITLE
List services bindings for an App API documents incorrect filters

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/cloud_controller_ng#466]
Documentation for [List all Service Bindings for the App](http://apidocs.cloudfoundry.org/214/apps/list_all_service_bindings_for_the_app.html) puts the app guid in the URI, and then offers an `app_guid` query-filter.  Why should we filter on the `app_guid` when it is already fixed in the URI?

Furthermore it documents a query filter called `service_instance_guid`, but the example uses a simple query parameter called `service_binding_guid`. The correct name and filter type should be documented.

Finally, the response documented doesn't refer at all to the query parameter guid value. It appears to be ignored.

**Comment by Gerg** [comment]
The `app_guid` filter should be addressed by our fix for #496

The `service_instance_guid` filter should be addressed by our fix for #467

Can you clarify what you mean by "the response documented doesn't refer at all to the query parameter guid value. It appears to be ignored."

**Comment by Zteve** [comment]
Only that the guid specified in the example Request URI/payload doesn't appear anywhere in the example Response uri/payload. If the query parameter `service_binding_guid` is removed then this is now consistent. Thanks.

**Comment by utako** [comment]
@Zteve,

Great, we believe this issue has been resolved. You can see the changes applied [here](http://apidocs.cloudfoundry.org/230/apps/list_all_service_bindings_for_the_app.html#). Please feel free to reopen this issue.

Thanks,
@utako & @simonleung8, CF Capi Team
