### ISSUE TITLE
Several List endpoint have erroneous query paramerers

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#467]
The list endpoints concerned document a query parameter to specify one of the thing being listed. This is not correct, please update the documentation. 

e.g.
List all the developers in a space.
GET /v2/spaces/3cc21402-8370-4d52-a4b4-4f7eb02cd4a6/developers~~?developer_guid=uaa-id-237~~

I suspect there are quite a few endpoints with this problem, after a minute of clicking around I found at least four of them.

http://apidocs.cloudfoundry.org/225/spaces/list_all_auditors_for_the_space.html
http://apidocs.cloudfoundry.org/225/apps/list_all_routes_for_the_app.html
http://apidocs.cloudfoundry.org/225/spaces/list_all_developers_for_the_space.html
http://apidocs.cloudfoundry.org/225/spaces/list_all_managers_for_the_space.html

**Comment by cgfrost** [comment]
Also:
http://apidocs.cloudfoundry.org/214/users/list_all_audited_organizations_for_the_user.html
http://apidocs.cloudfoundry.org/214/users/list_all_audited_spaces_for_the_user.html
http://apidocs.cloudfoundry.org/214/users/list_all_billing_managed_organizations_for_the_user.html
http://apidocs.cloudfoundry.org/214/users/list_all_managed_organizations_for_the_user.html
http://apidocs.cloudfoundry.org/214/users/list_all_managed_spaces_for_the_user.html
http://apidocs.cloudfoundry.org/214/users/list_all_organizations_for_the_user.html
http://apidocs.cloudfoundry.org/214/users/list_all_spaces_for_the_user.html

**Comment by zrob** [comment]
Fix pushed.

Also updated these docs:

List all Service Bindings for the App
List all Audited Organizations for the User
List all Audited Spaces for the User
List all Billing Managed Organizations for the User
List all Managed Organizations for the User
List all Managed Spaces for the User
List all Organizations for the User
List all Security Groups for the Space

Thanks!

**Comment by cgfrost** [comment]
Thanks.
