### ISSUE TITLE
Empty request body documented

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#469]
See:

http://apidocs.cloudfoundry.org/225/space_quota_definitions/updating_a_space_quota_definition.html

If the request/response body is empty it shouldn't be shown in the documentation.

**Comment by dieucao** [comment]
It now shows name being changed.
http://apidocs.cloudfoundry.org/release-candidate/space_quota_definitions/updating_a_space_quota_definition.html
