### ISSUE TITLE
Delete endpoint returns 201 created

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#471]
Delete endpoints should not return 201 Created.

http://apidocs.cloudfoundry.org/225/blobstores/delete_all_blobs_in_the_buildpack_cache_blobstore.html

**Comment by zrob** [comment]
Fix pushed.  Please re-open if you have any further issues.

Thanks!

**Comment by cgfrost** [comment]
Thanks.
