### ISSUE TITLE
Incorrect filter field documented for the query string.

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#472]
The two issues below include a filter query for the field `space_guid`. This is a duplicate of the `guid` field in the path and should be removed.

http://apidocs.cloudfoundry.org/226/spaces/list_all_service_instances_for_the_space.html
http://apidocs.cloudfoundry.org/226/spaces/list_all_managers_for_the_space.html

**Comment by Gerg** [comment]
This should be addressed by our fix for issue #496

**Comment by dieucao** [comment]
http://apidocs.cloudfoundry.org/230/spaces/list_all_service_instances_for_the_space.html
http://apidocs.cloudfoundry.org/230/spaces/list_all_managers_for_the_space.html

Looks good. Closing.
