### ISSUE TITLE
Delayed jobs can cause system hangs when the jobs queue is full with a many failed jobs

### ISSUE THREAD

**Issue by smoser-ibm** [cloudfoundry/cloud_controller_ng#474]
In the following cases

https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/jobs/services/delete_orphaned_binding.rb#L45
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/jobs/services/delete_orphaned_instance.rb#L28
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/jobs/services/delete_orphaned_key.rb#L29

the "max_attempts” property of the jobs is 11. We had a scenario where the API worker established a connection to the service broker successfully, but the service broker was hung and didn’t respond. In consequence, the job re-attempted 11 times (since the request continued to fail), resulting in many failed jobs being scheduled on the api workers. With a timeout set to 60s, you very quickly have any failed attempt re-scheduled almost immediately since only 1 job is processed per worker. 

Obviously, the main issue was the service broker being hung and unresponsive, but we believe the API worker should be more resilient and handle this situation properly.

**Comment by smoser-ibm** [comment]
@dieucao, could anyone from the CAPI team comment on that  ? I might have ideas on how to solve this, but we'd like to get the CAPIs team point of view on it first.

**Comment by dieucao** [comment]
@smoser-ibm The team has made some changes.  You can see the commits on the tracker story.  The changes will be in the next cf-release.  Okay to close this issue and if you continue to see problems could you open a new issue?

**Comment by smoser-ibm** [comment]
sure, lets do ti like that
