### ISSUE TITLE
Extra param for Create a Route

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#478]
The API endpoint for creating a Route is wrong.
http://apidocs.cloudfoundry.org/226/routes/creating_a_route.html

When creating a route the guid of the route is not known and should not be specified in the request.

**Comment by dieucao** [comment]
@cgfrost Thanks. Removed it from the api doc.  Will be available in the next cf-release.
http://apidocs.cloudfoundry.org/release-candidate/routes/creating_a_route.html
