### ISSUE TITLE
GET Route Exists returns no content

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#479]
This endpoint should return some content, anything to indicate if the route exists. If that information is coming back in a header, it's not documented. If that information is in the response code, please document the response code used for `false`.

http://apidocs.cloudfoundry.org/226/routes/check_a_route_exists.html

**Comment by dieucao** [comment]
Added a description section to describe the expected response codes.
http://apidocs.cloudfoundry.org/release-candidate/routes/check_a_route_exists.html
