### ISSUE TITLE
Delete Organization Auditor should return 204 No Content

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#483]
This is also to be consistent with the Remove operations

See: http://apidocs.cloudfoundry.org/226/organizations/disassociate_billing_manager_with_the_organization_by_username.html

**Comment by dieucao** [comment]
Should be addressed in the next cf-release https://github.com/cloudfoundry/cloud_controller_ng/commit/49ecead930a2aff53242554bbb0b2fa18b103d4e
