### ISSUE TITLE
Delete Organization Manager should return 204 No Content

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#484]
This is to be consistent with the matching remove operation, ideally these operations should be merged in to a single endpoint.

See:
http://apidocs.cloudfoundry.org/226/organizations/disassociate_manager_with_the_organization_by_username.html

**Comment by dieucao** [comment]
Addressed in next cf-release https://github.com/cloudfoundry/cloud_controller_ng/commit/49ecead930a2aff53242554bbb0b2fa18b103d4e
