### ISSUE TITLE
Delete Organization User should return 204 No Content

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#485]
This is to be consistent with the matching remover operation, ideally they should be merged in to a single endpoint.

See:
http://apidocs.cloudfoundry.org/226/organizations/disassociate_user_with_the_organization_by_username.html

**Comment by dieucao** [comment]
Fixed in cf-release 229
http://apidocs.cloudfoundry.org/229/organizations/disassociate_user_with_the_organization_by_username.html
