### ISSUE TITLE
Delete Organization Billing Manager should return 204 No Content

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#486]
This is to be consistent with the matching remove operation, ideally they should be merged in to a single endpoint.

See:
http://apidocs.cloudfoundry.org/226/organizations/disassociate_billing_manager_with_the_organization_by_username.html

**Comment by dieucao** [comment]
Addressed in https://github.com/cloudfoundry/cloud_controller_ng/commit/49ecead930a2aff53242554bbb0b2fa18b103d4e

Should be available in cf-release 229.
