### ISSUE TITLE
List Domains documents invalid query parameter

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#487]
The API documentation for [List all Domains (deprecated)](http://apidocs.cloudfoundry.org/226/domains_(deprecated)/list_all_domains_(deprecated).html) describes a `space_guid` filter.  This filter is invalid as `GET https://api.local.micropcf.io/v2/domains?q=space_guid%20IN%206cf8ccaf-c3f4-4267-a73b-92ed96e0b477` results in `CF-BadQueryParameter(10005): The query parameter is invalid: space_guid`.

**Comment by dieucao** [comment]
Fixed in cf-release 229
http://apidocs.cloudfoundry.org/229/domains_(deprecated)/list_all_domains_(deprecated).html
