### ISSUE TITLE
Better exposure of property for monit memory limit

### ISSUE THREAD

**Issue by tushar-dadlani** [cloudfoundry/cloud_controller_ng#488]
We noticed that the monit memory limit on the cloud controller in CF Release is configured as 'number megabytes'.  https://github.com/cloudfoundry/cf-release/blob/master/jobs/cloud_controller_ng/monit#L27-L29

This forces the operator to think of memory as a part of the bosh deployment, but ideally an operator would prefer to configure a percentage or how much memory can be used by everything besides the cloud controller, since the cloud controller is the main job running on the vm. 

The benefit of this approach is that if the operator changes instance types and has more memory, monit will not restart based on the default hard limit configured for the job , rather would be flexible about using more memory as provided by the system. Also it wouldn't force the operator to update an extra property when updating instance types. 

Tushar && Gary
Cloudops (CF)

**Comment by dieucao** [comment]
@tushar-dadlani I think it makes sense for this value to not be percentage.  We want to be able to understand if there are memory leaks or just differences in usage or other things causing memory increases or spikes.  If it was changed to percentages, depending on the vm size, the memory leaks and other issues would be masked.  Let me know if you have any questions about this.

**Comment by tushar-dadlani** [comment]
@dieucao It does make sense.
