### ISSUE TITLE
document that Files API only supports Diego deployed apps

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cloud_controller_ng#490]
Files API (http://apidocs.cloudfoundry.org/226/files/retrieve_file.html) does not document that it does not work for DIEGO deployed apps, and what API endpoint to use as alternative.

When called with the guid of an app deployed to DIEGO, this API returns:

```json
{
  "code": 190001,
  "description": "File error: Request failed for app: cf-cli-ref-guide, instance: 0 and path:  as the instance is not found.",
  "error_code": "CF-FileError"
}
```

**Comment by simonleung8** [comment]
Dies, thanks for reporting this, we have documented that Files API is for non-Diego app only. 

Docs will be updated once changes flow through our pipeline.

Thanks
