### ISSUE TITLE
"Push-based" API for monitoring Events API

### ISSUE THREAD

**Issue by jthomas** [cloudfoundry/cloud_controller_ng#491]
The [CF Events API](https://apidocs.cloudfoundry.org/226/events/list_all_events.html) is a great integration point for monitoring applications and services on the platform. 

If you are trying to monitor this event stream in real-time, you have to repeatedly poll the REST API to retrieve all events, regardless of whether any new events have occurred. 

It would be ideal to have an additional "push-based" API for endpoint, whether through a websocket, long-polling or webhooks. This feature would be to enormously reduce unnecessary HTTP requests for this use-case.

**Comment by dieucao** [comment]
@jthomas Thanks for the feedback. I agree this is something that would be useful and has actually been requested several times.  The CAPI team is currently focused on a few other feature initiatives currently so we would not be working on this type of enhancement in the near term.

I am interested in hearing more about your specific use cases though.
What types of events are you looking to monitor?
Are you monitoring from an operators point of view or from an app developer's point of view?
What type of action would you want to take based on receiving a push?
How often do you currently poll for the events?

**Comment by jthomas** [comment]
I've been working on a project to surface the "events" stream from the CF API into Slack.
https://github.com/jthomas/cfbot
http://jamesthom.as/blog/2016/01/05/cfbot/

Monitoring is from an application developer's perspective. I'm currently polling every 30 seconds.

**Comment by SocalNick** [comment]
Hi @jthomas,

I'm Nick, the new PM on the CAPI team. As Dieu mentioned, this is definitely a useful feature, we just have a lot of high priority features to work on in the near future. I'm going to close this in favor of a [feature story in our tracker](https://www.pivotaltracker.com/story/show/116265655). I'd like to explore the possibility of sending these events via the loggregator firehose which is much better suited for push-based workloads.

**Comment by ngehani** [comment]
Hi @jthomas 

I was reading your blog post on sending CF logs to ELK. We currently use web hooks to get Github events like commits into ELK. We would like to similarly get cf events via web hooks. If we get all events into ELK, then we can potentially correlate different events. Is there a something that exposes cf events via web hooks so we can select the events we want?

**Comment by jthomas** [comment]
@ngehani I don't believe so. You can access CF events over HTTP but not via webhooks I'm afraid.

**Comment by ngehani** [comment]
@jthomas - Anyone working on making these events available via web hooks? Is that a viable request?

**Comment by jthomas** [comment]
@ngehani I'm not a CF developer :) @SocalNick might be able to answer.

**Comment by SocalNick** [comment]
See above: https://github.com/cloudfoundry/cloud_controller_ng/issues/491#issuecomment-200601697

**Comment by ronvenna** [comment]
@ngehani any traction on this?

**Comment by SocalNick** [comment]
@ronvenna I'm no longer on that team, maybe @zrob can help.
