### ISSUE TITLE
Users in role OrgManager and no other role don't get service instances or bindings (but get apps with empty service bindings)

### ISSUE THREAD

**Issue by vlerenc** [cloudfoundry/cloud_controller_ng#494]
We noticed an odd behavior that seems to violate the description in http://docs.pivotal.io/pivotalcf/concepts/roles.html that states that org managers should be able to see e.g. service bindings for an app.

When we have a user that is *only* an org manager but has no other roles assigned (especially no space roles), that user nicely gets all apps via curl, but the ```"service_bindings_url"``` yields an empty list response ```"resources": []```. Also when this user curl's the service instances or bindings, that user gets no results.

Expected behavior would be to also get the service instances and bindings or get a response code like 403 indicating there is an issue, but an empty list seems to be an incorrect response.

**Comment by vlerenc** [comment]
We also noticed that the CLI shows the services and bindings, e.g. ```cf s```, but this seems related to the summary request that is being made, e.g. ```/v2/spaces/xxx/summary``` that yields applications and services and that the CLI then correlates. That seems to indicate as well that above/reported behavior is a bug.

**Comment by dieucao** [comment]
@vlerenc Thanks for the report.  I believe the intended functionality was that an Org Manager should be able to see the service instances, service bindings and service keys objects but with credentials redacted.  We'll take a look.

**Comment by youreddy** [comment]
Hello @vlerenc, 

We pushed a fix for this https://github.com/cloudfoundry/cloud_controller_ng/commit/3e21703f2ac82cdd3e148a159efa79342b5b1baa

Let us know if you have any questions. Please close the issue if you feel that your issue has been addressed. 

Thanks!
@youreddy & @karafelix 
CF Capi Team

**Comment by vlerenc** [comment]
Thank you @youreddy & @karafelix. I haven't tested your fix yet, but we will when we adopt the CF release that includes your fix. Closing ticket now.
