### ISSUE TITLE
return_user_provided_service_instances param not preserved in next/prev urls

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#495]
Recently ran into an issue using the cf-java-client: https://github.com/cloudfoundry/cf-java-client/blob/1.x/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClientImpl.java#L900

The space had more than 50 services and since the next_url didn't include `return_user_provided_service_instances` it caused all kinds of problems.

As a side note user provided services are a pain in the butt.  Is there a story to consider converting user provided services into a more standard v2 service?  Perhaps a CC provided broker so tools that consume services don't need all the hacks user provided services require?  The `null` service plan gets me all the time.

Mike

**Comment by youngm** [comment]
Simple test case:  Find a space with more than 1 service instance in it and execute:

`cf curl "/v2/spaces/$(cf space test-space --guid)/service_instances?return_user_provided_service_instances=true&results-per-page=1"`

Note that the next_url doesn't include a `return_user_provided_service_instances` param.

**Comment by youngm** [comment]
We're running cf-release 225

**Comment by dieucao** [comment]
@youngm Thanks for the report. We'll take a look.

We would like to eventually deprecate the existing user provided services with something more standard and fully featured.  @shalako has called it an Echo Broker because you could define what the responses would be and it would be echoed back to users binding services.

We're not planning on working on that in the near term but I'll add your plus one to it.

**Comment by youngm** [comment]
Thanks @dieucao

**Comment by youreddy** [comment]
Hello @youngm,

The above commit should resolve this issue. Let us know if you have any questions. Please close the issue if you feel that your issue has been addressed. 

Thanks!
@youreddy & @karafelix 
CF Capi Team

**Comment by youngm** [comment]
Thank you @youreddy
