### ISSUE TITLE
details field not documented in response of GET /v2/apps/:guid/instances

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cloud_controller_ng#497]
The [Get instance information for a STARTED app](http://apidocs.cloudfoundry.org/227/apps/get_the_instance_information_for_a_started_app.html) REST interface does not document a `details` response field, but the CLI [refers to such a field](https://github.com/cloudfoundry/cli/blob/master/cf/api/app_instances/app_instances.go#L71).

If the field is supported, it should be documented.

**Comment by dieucao** [comment]
I'm not sure what details refers to on the cli side.
For an app running on Diego the endpoint currently returns this:
```
$ cf curl /v2/apps/b5ec1f75-34f9-4ef1-bcd4-e5345595eecc/instances
{
   "0": {
      "state": "RUNNING",
      "uptime": 9135,
      "since": 1452678744
   }
}
```

For an app running on DEAS it returns this:
```
$ cf curl /v2/apps/ef01a7da-9569-437b-bbf4-3f2dd01635ef/instances
{
   "0": {
      "state": "RUNNING",
      "since": 1452688078.8228042,
      "debug_ip": null,
      "debug_port": null,
      "console_ip": null,
      "console_port": null
   }
}
```

We'll see if we can clarify on the doc the fields better.  I should also not that debug_ip, debug_port, console_ip, and console_port are deprecated and weren't carried forward for Diego apps.

**Comment by nebhale** [comment]
@dieucao Do you believe that this is a bug against the CLI then?

/cc @dkoper

**Comment by wendorf** [comment]
@nebhale ,

Yes, it looks like the CLI is doing something a little strange there. There's definitely no details field on an instance. Is it okay if we close this issue?

Thanks,
@wendorf and @fkotsian

**Comment by nebhale** [comment]
@wendorf Yes, that's fine.  We'll remove it from our payloads.

**Comment by dkoper** [comment]
Thanks guys. I have created https://www.pivotaltracker.com/story/show/114051135 for the CLI team to take a look at this.

**Comment by kkellner** [comment]
Sorry to comment on a closed / old issue, but "details" is a field that Diego cell and /v2/apps/<GUID>/instances does return if the state of container is DOWN.  This field is used on the cf cli.  Its very helpful field when trying to debug why a container is not starting.

Example:
...
"348": {
    "details": "insufficient resources: disk",
    "since": 1501296280,
    "state": "DOWN",
    "uptime": 0
  },
  "349": {
    "details": "waiting to start instance: reached in-flight start limit",
    "since": 1501296280,
    "state": "DOWN",
    "uptime": 0
  },
  "35": {
    "since": 1501296277,
    "state": "STARTING",
    "uptime": 2
  },
  "350": {
    "details": "waiting to start instance: reached in-flight start limit",
    "since": 1501296280,
    "state": "DOWN",
    "uptime": 0
  },
