### ISSUE TITLE
List all Service Instances: organization_guid query parameter not combinable 

### ISSUE THREAD

**Issue by pmlanger** [cloudfoundry/cloud_controller_ng#498]
When filtering `GET v2/service_instances` by `organization_guid`, the same request can't be filtered by any other filter (e.g., `space_guid`, `service_plan_guid`, ...). Combining other filters works fine, though.
In particular,
(1) this restriction is not documented (afaik)
(2) other parameters are silently ignored, when `organization_guid` filter is used. A 400 response could be more suitable.

**Comment by dieucao** [comment]
@pmlanger This will be fixed in the next cf-release that includes the above commit.
