### ISSUE TITLE
Get Space Summary does not document last_operation parameter type

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#499]
The API documentation for [Get Space Summary](http://apidocs.cloudfoundry.org/227/spaces/get_space_summary.html) describes a `services.last_operation` payload element.  The type of this payload element is undocumented as the example only shows `null`.

See: cloudfoundry/cf-java-client#354

**Comment by wendorf** [comment]
Hi @nebhale,

 We've added documentation of this field to the docs. Please reopen if you find any further issues.

@wendorf and @fkotsian 
CF CAPI Team

**Comment by nebhale** [comment]
@wendorf Is the `last_operation` payload a hash with keys `created_at`, `description`, `state`, `type`, and `updated_at` (since I can't yet see the docs)?

**Comment by wendorf** [comment]
Hi @nebhale,

Yes indeed. The payload appears as follows:

```
"last_operation": {
  "type": "create",
  "state": "succeeded",
  "description": "description goes here",
  "updated_at": "2016-02-18T22:12:11Z",
  "created_at": "2016-02-18T22:12:11Z"
}
```

This should show up in the [release candidate](http://apidocs.cloudfoundry.org/release-candidate/spaces/get_space_summary.html) docs relatively soon.

**Comment by nebhale** [comment]
Thanks much.
