### ISSUE TITLE
update ups API does not document route_service_url field

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cloud_controller_ng#500]
CLI now allows the user to update the route service url field, but it seems this field (route_service_url) is not documented as being allowed in the request body?

http://apidocs.cloudfoundry.org/227/user_provided_service_instances/updating_a_user_provided_service_instance.html

Also, setting an illegal url for it (i.e. not starting with https), returns a create message instead of update:

```
{
  "code": 60019,
  "description": "The service instance could not be created: Scheme for route_service_url must be https.",
  "error_code": "CF-ServiceInstanceRouteServiceURLInvalid"
}
```

**Comment by karafelix** [comment]
I have pushed a fix to both the documentation and the error message.

Please close the issue if you feel that it has been adequately addressed.

Thanks,
Kara Felix
CF CAPI Team

**Comment by dieucao** [comment]
You can see the updated api doc here and available officially in the next cf-release.
http://apidocs.cloudfoundry.org/release-candidate/user_provided_service_instances/updating_a_user_provided_service_instance.html

Updated error message
```
cf uups mycup -r www.google.com
Updating user provided service mycup in org dcao@pivotal.io / space dev as dcao+spacedeveloper@pivotal.io...
FAILED
Server error, status code: 400, error code: 60019, message: The route service URL is invalid: Scheme for route_service_url must be https.
```
