### ISSUE TITLE
Returned field defined at wrong level and not documented

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#505]
The [http://apidocs.cloudfoundry.org/228/apps/get_detailed_stats_for_a_started_app.html](http://apidocs.cloudfoundry.org/228/apps/get_detailed_stats_for_a_started_app.html) operation defines `upTime` in the returned JSON under the `stats` field, but it is _also_ being returned at the top level of an instance's statistics.

**Comment by wendorf** [comment]
Hi @twoseat ,

We investigated your issue but can't seem to get the same output you're seeing. When we get the stats for an app, the response looks like this:

```
{
   "0": {
      "state": "RUNNING",
      "stats": {
         "name": "dora",
         "uris": [
            "dora.bosh-lite.com"
         ],
         "host": "10.244.16.10",
         "port": 60002,
         "uptime": 19,
         "mem_quota": 268435456,
         "disk_quota": 1073741824,
         "fds_quota": 16384,
         "usage": {
            "time": "2016-02-18T22:22:57.849895561Z",
            "cpu": 0,
            "mem": 22917120,
            "disk": 72499200
         }
      }
   }
}
```

We only see `uptime` in the `stats` field. Can you show us the HTTP request and response you're doing to see the behavior?


Thanks,
@wendorf and @fkotsian , Cloud Foundry CAPI team

**Comment by wendorf** [comment]
Hi @twoseat ,

I'm going to close this issue, since it looks like everything is working appropriately. If you are still having issues, please feel free to open another issue.


Thanks,
@wendorf, Cloud Foundry CAPI team

**Comment by twoseat** [comment]
Sorry for the delay, I was in mid-release. While I'm sure this was happening at one point, I agree it's not any more, so thanks for closing this.
