### ISSUE TITLE
List Service Instance for a Service Plan documents invalid query parameter

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#508]
The API documentation for [List Service Instance for a Service Plan](http://apidocs.cloudfoundry.org/214/service_plans/list_all_service_instances_for_the_service_plan.html) describes an `organization_guid` filter. This filter is invalid, as `GET https://api.local.micropcf.io/v2/service_plans/755fb089-5a5f-49b2-a646-96f72e4491de/service_instances?q=organization_guid:ebf76526-270a-4ccc-99a6-0c6981fb81a7` results in `CF-BadQueryParameter(10005): The query parameter is invalid: organization_guid`.

**Comment by dieucao** [comment]
Fixed as part of an upcoming cf-release.
http://apidocs.cloudfoundry.org/release-candidate/service_plans/list_all_service_instances_for_the_service_plan.html

**Comment by dieucao** [comment]
Oops wrong link.
http://s3.amazonaws.com/cc-api-docs/110284023/service_plans/list_all_service_instances_for_the_service_plan.html

It's not yet on release-candidate.
We've removed the org_guid filter.
