### ISSUE TITLE
List Service Instance for a Service Plan documents invalid query parameter (2)

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#509]
The API documentation for [List Service Instance for a Service Plan](http://apidocs.cloudfoundry.org/228/service_plans/list_all_service_instances_for_the_service_plan.html) describes a `service_instance_guid` filter.  This filter is invalid as the `service_plan_guid ` is included in URI instead.

**Comment by wendorf** [comment]
Hi @nebhale @antechrestos, 

 We've removed this filter from the List Service Instance for a Service Plan endpoint. Please reopen if you find any further issues.

Best,

@wendorf and @fkotsian 
CF CAPI Team
