### ISSUE TITLE
Get the instance information for a STARTED App does not document field

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#511]
The API documentation for [Get the instance information for a STARTED App](http://apidocs.cloudfoundry.org/228/apps/get_the_instance_information_for_a_started_app.html) does not described an `uptime` payload property that exists in the implementation.

**Comment by wendorf** [comment]
Hi @nebhale,

This was an interesting one - a difference between what was returned by the instances reporter for DEAs and the reporter for Diego. We've added documentation of both the response bodies, reproduced below. Please reopen if you find any further issues.

DEA response (no "uptime" property):

```
{
          "0": {
            "state": "RUNNING",
            "since": 1403140717.984577,
            "debug_ip": null,
            "debug_port": null,
            "console_ip": null,
            "console_port": null
          }
}
```

Diego response: 

```
{
  "0": {
    "state": "RUNNING",
    "since": 1403140717.984577,
    "uptime": 2405
  },
  "1": {
    "state": "STARTING",
    "since": 3625363939.984577,
    "uptime": 1394
  },
  "2": {
    "state": "CRASHED",
    "since": 2514251828.984577,
    "uptime": 283
  },
  "3": {
    "state": "DOWN",
    "uptime": 9172
  }
}
```

@wendorf and @fkotsian 
CF CAPI Team
