### ISSUE TITLE
List all Spaces for the Organization documents invalid query parameter

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#515]
The API documentation for [List all Spaces for the Organization](http://apidocs.cloudfoundry.org/228/organizations/list_all_spaces_for_the_organization.html) describes a `organization_guid` filter. This filter is invalid as the `organization_guid` is included in URI instead.

**Comment by dieucao** [comment]
Will be addressed once https://github.com/cloudfoundry/cloud_controller_ng/commit/ebbae0ab4bad7d1ce8fec3402812c45e352d4210 makes it into a cf-release.
You can find docs that include this change at
http://s3.amazonaws.com/cc-api-docs/104228398/index.html
