### ISSUE TITLE
Global readonly scope for CC API

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/cloud_controller_ng#517]
We need the ability to query application state in readonly form from administrative tooling without adding a user to every org/space. Currently, the only way to do this would give that user full admin permissions through the api (cloud_controller.admin scope).

For reference, this was discussed in https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/W6NO5POMASFTTJS5MRHFS6B3QTHPBHFD/

**Comment by dieucao** [comment]
@johnmcteague Thanks for filing the issue.  I've asked the team to think about what the effort would be to implement this.

**Comment by SocalNick** [comment]
@johnmcteague - I've added https://www.pivotaltracker.com/story/show/117558887 to address this. It's likely going to be considerable work, but it keeps coming up so we should prioritize.

**Comment by flavorjones** [comment]
Looks like this tracker story was completed and accepted! :woot:
