### ISSUE TITLE
List all Domains for the Space (deprecated) documents invalid query parameter

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#521]
The API documentation for [List all Domains for the Space (deprecated)](http://apidocs.cloudfoundry.org/228/spaces/list_all_domains_for_the_space_(deprecated).html) describes a `space_guid` filter. This filter is invalid as the `space_guid` is included in URI instead.

**Comment by dieucao** [comment]
Fixed in 229
http://apidocs.cloudfoundry.org/229/spaces/list_all_domains_for_the_space_(deprecated).html
