### ISSUE TITLE
"/v2/apps/:guid/summary" will return duplicated "name" keys in JSON response

### ISSUE THREAD

**Issue by archerzz** [cloudfoundry/cloud_controller_ng#524]
## Problem
If you invoke "/v2/apps/:guid/summary" API, you will find that in the response JSON object, there are two "name" properties on top level. Please inspect the raw HTTP content.
Some JSON parsing tools will report error due to duplicated keys, which will break the work flow to get application summary.
## Why
After some investigation, the problem seems located in [app_summaries_controller.rb, line 22](https://github.com/cloudfoundry/cloud_controller_ng/blob/965dbc4bdf65df89f382329aef39f86a916b3f05/app/controllers/runtime/app_summaries_controller.rb#L22)
"app_info" does a merge with "app.to_hash". So if "app.to_hash" contains "name":"foo" pair, the merge will create two "name" keys. Below are the sample codes.
```ruby
require "json"
a = {name: "foo"}
b = {"name" => "bar"}
puts a.merge(b).to_json
```
The result will be
```
{"name":"foo","name":"bar"}
```

**Comment by dieucao** [comment]
This should be fixed in the next cf-release that contains the above commit.
