### ISSUE TITLE
Wildcard parameter not documented on Create Private Domain

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cloud_controller_ng#526]
The endpoint to create a new private domain doesn't document the boolean json parameter `wildcard`. The parameter is used by the CLI. Please include if it is required and if not what the default value is.

http://apidocs.cloudfoundry.org/230/private_domains/create_a_private_domain_owned_by_the_given_organization.html

**Comment by zrob** [comment]
@cgfrost 

That is not a field that has any meaning or is used in any way by private domains.  

The cli probably sends it because of some legacy endpoints that are not longer responsible for domain management.

Thanks,
@zrob & @fkotsian
