### ISSUE TITLE
Provide atomic way to delete an orphaned route

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cloud_controller_ng#527]
The CLI operation `cf delete-orphaned-routes` attempts to delete orphaned routes by querying all routes for the targeted space, checking which of them have no associated application, and then deleting those routes. So there is a problem if a route is associated with an application (e.g. by someone else) just before the route is deleted. This does not appear to be soluble in the CLI without a CC operation which will delete a route atomically if and only if there is no application associated with the route.

**Comment by dieucao** [comment]
Hey @glyn I think this is a reasonable request.  It's not something we can take on immediately though.
Do you have any suggestions on what a reasonable request param might be to include on the route delete
@shalako Thoughts?

**Comment by glyn** [comment]
@dieucao thanks. This is important but not urgent, so please just keep it on the books. :-)

**Comment by shalako** [comment]
I'm assuming that we already return an error to a delete route request if it is mapped to an app? So the issue with the CLI command is you might get an error that a route couldn't be deleted? 

I would suggest that either the CLI expose errors when something couldn't be deleted, or the CLI always returns a success, deletes whatever it can, and masks any errors from the user.

**Comment by glyn** [comment]
@shalako I'm not sure your assumption is valid. For example, the reproduction steps in https://github.com/cloudfoundry/cli/issues/751 demonstrate a way of deleting a route which is in use by an application, although admittedly this may be a different code path. It would be good to validate the assumption.

**Comment by dkoper** [comment]
@SocalNick Can you please reopen the cli issue (https://github.com/cloudfoundry/cli/issues/746) when you have a solution for us? Then we'll do what we need to do on our end.

**Comment by zrob** [comment]
Reopened the referenced issue for cli and pointed to our fix for this issue
