### ISSUE TITLE
Apps in space summary do not contain route paths

### ISSUE THREAD

**Issue by MrWolfZ** [cloudfoundry/cloud_controller_ng#528]
When querying for a space summary, it contains a list of all apps in the space. The apps will also contain all their routes (i.e. see https://apidocs.cloudfoundry.org/230/spaces/get_space_summary.html).

However, the routes do not contain the recently introduced `path` field, and the `urls` field also does not contain the `path` in the listed URLs.

Here is an example of what I get and what I expect:

**Actual:**

```
  "apps": [
    {
      "guid": "34a994d9-4c34-402a-975a-6ebf7680ce63",
      "urls": [ "host-1.domain-1.example.com" ],
      "routes": [
        {
          "guid": "f5f4bdf9-9616-4f2b-902c-81115a15584d",
          "host": "host-1",
          "domain": {
            "guid": "ac6abb36-f28f-4aa6-ac5b-5e50a1107dc4",
            "name": "domain-1.example.com"
          }
        }
      ],
      ...
    }
  ]
```

**Expected:**

```
  "apps": [
    {
      "guid": "34a994d9-4c34-402a-975a-6ebf7680ce63",
      "urls": [ "host-1.domain-1.example.com/some/path" ],
      "routes": [
        {
          "guid": "f5f4bdf9-9616-4f2b-902c-81115a15584d",
          "host": "host-1",
          "path": "/some/path",
          "domain": {
            "guid": "ac6abb36-f28f-4aa6-ac5b-5e50a1107dc4",
            "name": "domain-1.example.com"
          }
        }
      ],
      ...
    }
  ]
```

**Comment by dieucao** [comment]
@MrWolfZ This should be addressed in the next cf-release that includes https://github.com/cloudfoundry/cloud_controller_ng/commit/09afe2453ddbee8f2b76e1c5dd25db07e4adfe74
