### ISSUE TITLE
Not found service "...v2/org/:orgID/quota_usage" in v212 [migrated from cf-release]

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cloud_controller_ng#532]
> Original issue: https://github.com/cloudfoundry/cf-release/issues/899
> Original poster: @SolutionBTO

----

Hi

Not exists service "v2/organizations/:orgID/quota_usage" in
http://apidocs.cloudfoundry.org/212/

Only in before version
http://apidocs.cloudfoundry.org/211/organizations/retrieving_quota_usage_for_the_organization.html

Will add or remove definitely?

Roberto Silva
Best Regard's

**Comment by dieucao** [comment]
@SolutionBTO These end points were reverted because we did not get requested changes on the PR.
You can see that here:
https://github.com/cloudfoundry/cloud_controller_ng/pull/383
I think these end points could be useful and would be happy to take another PR for it with the suggested changes.
Does that answer your question?

**Comment by SolutionBTO** [comment]
Hi @dieucao 

Yes, I understand the current situation had to be reversed this end point "quota_usage", according to the forum link:
https://github.com/cloudfoundry/cloud_controller_ng/pull/383#issuecomment-110946289


I'm will able to solve my problem with this end point:
http://apidocs.cloudfoundry.org/212/organizations/retrieving_organization_memory_usage.html

Once you have a position like to be informed.

Thanks for attention!

Roberto Silva,
Best Regards

**Comment by dieucao** [comment]
@SolutionBTO I don't have current plans to introduce a better quota usage end point but should someone take that up, we'll be sure to include that in the release notes and api docs.
Thanks!
