### ISSUE TITLE
Get Detailed Stats for an App's Process does not document request payload

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#534]
The API Documentation for [Get Detailed Stats for an App's Process](http://apidocs.cloudfoundry.org/230/apps_(experimental)/get_detailed_stats_for_an_app's_process.html) does not describe the paginated request parameters in its request payload.  The response payload indicates that it is paginated indicating that they should be there.

**Comment by SocalNick** [comment]
http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html#get-stats-for-a-process-for-an-app
