### ISSUE TITLE
Delete Service does not document response payload

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#536]
Since the [Delete a Particular Service](http://apidocs.cloudfoundry.org/214/services/delete_a_particular_service.html) API exposes an `async` parameter, it should also return a response payload consisting of a Job entity.  This response payload is not currently documented.

**Comment by wendorf** [comment]
Hi @nebhale ,

The documentation will be update shortly. When deleting asynchronously, the response code is 202 and the body is:

```
{
  "metadata": {
    "guid": "cd9ca5c0-62f6-40e2-b663-f9f6213d3f21",
    "created_at": "2016-02-19T01:00:03Z",
    "url": "/v2/jobs/cd9ca5c0-62f6-40e2-b663-f9f6213d3f21"
  },
  "entity": {
    "guid": "cd9ca5c0-62f6-40e2-b663-f9f6213d3f21",
    "status": "queued"
  }
}
```


Best,
@wendorf and @fkotsian
