### ISSUE TITLE
Updating an application does not document enable_ssh request payload

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#537]
The API documentation for [Updating an App](http://apidocs.cloudfoundry.org/230/apps/updating_an_app.html) does not described an `enable_ssh` request payload property that exists in the implementation.

**Comment by wendorf** [comment]
Hi @nebhale ,

The documentation will be updated on the release-candidate docs relatively soon. The enable_ssh boolean field is documented as "Enable SSHing into the app. Supported for Diego only.", and the default value is false if SSH is disabled globally or on the space, true if enabled for both.


Cheers,
@wendorf
