### ISSUE TITLE
Staging error: failed to stage application: another staging request was initiated

### ISSUE THREAD

**Issue by djvdorp** [cloudfoundry/cloud_controller_ng#539]
I am currently having some issues with Cloud Foundry, which might be due to the way we interact with our Cloud Foundry instance. I initially thought that it was related to (and to be solved within) the `cf-java-client v1.x` (see [this issue](https://github.com/cloudfoundry/cf-java-client/issues/392)), but it is not, hence I'm referred to open an issue here.

The issue seems to occur when we send a `start request` to an app, while the app is still `staging`.
The logging output makes it look like we actually send `staging requests` to the same application multiple times, eg. before the first `staging request` is completed we have already sent 1 (or more) `start requests` towards the same app, in which case it will end up in (some kind of) an infinite (re)staging loop.

This currently seems to result in this line in the app's (staging) log, which is not very detailed:
`encountered error: Staging error: failed to stage application: another staging request was initiated`

And this when you request the app's status from the `cf cli`, you will get:
`Server error, status code: 400, error code: 170002, message: App has not finished staging`

At this point, I am unsure if this is a bug in Cloud Foundry or a buildpack we're using.
However, I would expect Cloud Foundry to handle it in either 1 of these 2 ways:
1. Cancel the current `staging request`, and continue with the new `staging request` instead. (I think this is what the current implementation is trying to do, however, if `start requests` keep coming in, you will end up in this infinite (re)staging loop like we do)
or
2. Finish the current `staging request`, and wait with processing the new `staging request` until the current one is finished. (effectively blocking new `staging requests` from coming in while you are staging, to prevent this infinite (re)staging loop)

I am unable to resolve this matter myself at this point, and I would like some input on how to prevent this condition from happening in the future, and learn if what I am describing is maybe just a feature as intended (with this side effect as an result) or that I might have found an actual bug or issue here.

Currently, in our specific situation, it seems like this infinite (re)staging loop is able to bring at least an or some runners to it's knees, if this would happen to all runners then this would mean that sending `start requests` to an app that is still `staging` could effectively bring a whole Cloud Foundry cluster to it's knees.

**Comment by dieucao** [comment]
@djvdorp I'm curious why your implementation is sending additional start requests while the app is staging?  I believe the cf CLI does not do that and would recommend clients using the v2 api to do that but perhaps I'm misunderstanding the use case?

The current behavior is option 1 that you've listed above.

I would like to mention that the v3 cloud controller api has separated staging from starting so that these are discrete actions and will not interfere with each other.

**Comment by djvdorp** [comment]
@dieucao The additional `start requests` (while the app is `staging`) are sent by a custom functionality which allows apps that are `stopped` to be `started` upon receiving an http(s) request. This custom functionality will send `start request(s)` to the app to ensure it will be `started`, and this works fine if the `staging request` is relatively fast, but if the `staging request` is relatively slow, it will cause multiple `start requests` to be sent. 

Thanks to your information, I now know that the current behavior (option 1) combined with our custom functionality sending multiple `start requests` will result in an infinite (re)staging loop, which explains the behavior we are currently seeing and trying to avoid in this case.

We would also like to thank you about the information regarding the `v3 cloud controller api`. 
However, as far as my understanding goes, the `v3 cloud controller api` is still under development at the time of writing (the latest `cf-release v230` has api version `2.48.0`), or can we already use it (I can see a lot of `/v3/` traces in the `cloud_controller_ng` codebase)?

Also, am I correct to notice that `cf-java-client v1.x` maps to the `v2 cloud controller api` and the new `cf-java-client v2.x` will map to the `v3 cloud controller api` ?

**Comment by dieucao** [comment]
@djvdorp Yes, the v3 cloud controller api is still under development.  The plan is to introduce it in a way that it can live side by side with the v2 api and start with app related end points.
You can see many of the v3 end points documented on apidocs.cloudfoundry.org and a few in a new set of docs that we've started work on at v3-apidocs.cloudfoundry.org.
I mentioned it as an FYI for consideration in future.

I'm not sure about the java client library mapping and versions.

**Comment by djvdorp** [comment]
@dieucao Thanks again for your help and information. I have spoken with @cgfrost on the [Cloud Foundry (Open Source) Slack](https://cloudfoundry.slack.com/) and received some more information regarding the `cf-java-client` library mapping and versions, which I will share below for my (and others) reference.

Key points that @cgfrost informed me about:
- The `cf-java-client v1.x` maps to the `v2 cloud controller API` and the new `cf-java-client v2.x` will map to `both the v3 and v2 cloud controller APIs`.
- With regard to using the `v3 cloud controller API`, you should follow the docs. Both the current V3 and V2 APIs are valid to use as long as they are in the most recent documentation. Endpoints that are going to be removed will be marked as `deprecated` and endpoints that are new and likely to change are marked `experimental`.
- We should be releasing the first milestone soon (M1). It's a Milestone so you shouldn't use it in production, we reserve the right to change everything until we get to an RC release. You are correct, we still have a lot of the underlying APIs to implement.
- It's worth noting that work on the `cf-java-client V1.x` is essentially frozen apart from serious bugs. All our effort is going towards the `cf-java-client V2.x` line.

Other (re)sources of information I stumbled upon regarding the `v3 cloud controller API`, please let me know if these are not (supposed) to be used for information about this:
- https://github.com/cloudfoundry/cc-api-v3-style-guide
- https://github.com/cloudfoundry/cloud_controller_ng/blob/master/config/routes.rb

**Comment by nebhale** [comment]
@dieucao This can actually be reproduced using the CLI.  All you need to do is start a `push` and `^C` as staging starts.  Then you can start another `push` and the CLI will return you the exception described above (assuming staging takes a little while).  This isn't a typical use-case but it is possible (a CI pipeline without proper serialization could conceivably do the same thing) and I think that the Cloud Controller does the right thing here.  The pattern of rejecting subsequent requests to a critical section (in concurrency terms) is a valid one.  I think it's reasonable to expect the caller to handle the error, poll for a state when it's safe to stage again and then reattempt.

**Comment by SocalNick** [comment]
Closing as behavior is expected
