### ISSUE TITLE
Black list of private domains

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/cloud_controller_ng#540]
Private domains are allowed to be any non-overlapping shared domain or private domain registered by another organization. However, there are cases where one needs to reserve domains to prevent users from registering common or well-known domains, e.g., co.jp, and many others. A complete list can be found here, https://publicsuffix.org/.

Allowing an operation is specify a list of reserved private domains is necessary. It would be nice to just allow the deployment manifest to enumerate the list of domains that are reserved, alas, the current list is approximately 11k items which would seem a bit prohibitive to specify in a manifest. The alternative is to provide a file via a package which could be referenced (similar to how buildpacks are specified). This would allow large lists to be provided.

Thoughts?

**Comment by dieucao** [comment]
Associated PRs for this https://github.com/cloudfoundry/cf-release/pull/922 and https://github.com/cloudfoundry/cloud_controller_ng/pull/554
Close this issue if/when those PRs have been merged
