### ISSUE TITLE
Mapping an App and a Route documents invalid payload parameter

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#541]
The API documentation for [Mapping an App and a Route](http://apidocs.cloudfoundry.org/229/routes_mapping/mapping_an_app_and_a_route.html) describes a `guid` parameter. This parameter is invalid as it doesn't relate to either an application (`app_guid`) or route (`route_guid`).

**Comment by youreddy** [comment]
Hello @nebhale, 

The `guid` parameter was removed in version [231](http://apidocs.cloudfoundry.org/231/routes_mapping/mapping_an_app_and_a_route.html) of the api docs. If you feel as if your issue has been addressed, please close the issue. 

Thank you for bringing this to our attention, 
@youreddy, CF CAPI Team

**Comment by nebhale** [comment]
Looks good.
