### ISSUE TITLE
List all Service Bindings for the User Provided Service Instance documents invalid query parameter

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#543]
The API documentation for [List all Service Bindings for the User Provided Service Instance](http://apidocs.cloudfoundry.org/214/user_provided_service_instances/list_all_service_bindings_for_the_user_provided_service_instance.html) describes a `service_instance_guid` filter. This filter is invalid as the `guid` is included in URI instead.

**Comment by fkotsian** [comment]
docs updated
