### ISSUE TITLE
Update User Provided Service Instance misdocuments payload parameter

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#545]
The API documentation for [Update User Provided Service Instance](http://apidocs.cloudfoundry.org/231/user_provided_service_instances/updating_a_user_provided_service_instance.html) describes a `name` key that is listed as _required_. This parameter is not required as indicated by the example in the documentation.

**Comment by wendorf** [comment]
Hi @nebhale ,

Thanks for another good catch! I just commited the change, and it will make its way to the docs in the normal timeframe.


Cheers,
@wendorf
