### ISSUE TITLE
Add app_guid to unbind call?

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#546]
We have app_guid on bind which is great!  However unbind does not currently pass along the app_guid.

I'd like app_guid added to unbind requests.  When discussions were originally underway about adding app_guid to bind I had assumed that on unbind my broker could simply query the binding from the CC to get the app guid.  However, if unbind fails the binding is deleted making it impossible to know the app_guid for unbind requests invoked by the worker.  For this reason app_guid of the original binding on unbind would be nice to have.

Thoughts?

Mike

**Comment by SocalNick** [comment]
Hi Mike,

1) When you say, "if unbind fails" are you saying the broker failed to delete the binding and returned an error to the Cloud Controller? Please clarify.
2) When you say "the binding is deleted", does that mean the binding resource in the Cloud Controller is deleted even when the broker returns an error response from unbind?

In general, we aren't clear why your service brokers need the app_guid and why they need to call back to the Cloud Controller. It seems as though your unbind operation needs the app_guid and is currently calling CC for it within the unbind operation; we would like to know why.

Thanks,

Nick

**Comment by youngm** [comment]
@SocalNick Hi nick.  I thought I was seeing behavior at one point where a failed unbind would result in the binding being removed from the database.

I assumed that was normal behavior but looking at the api docs http://docs.cloudfoundry.org/services/api.html#unbinding it states that a failed unbind will keep the binding in the database.

I'll take a closer look at my code and reopen the issue or create an new issue if necessary.
