### ISSUE TITLE
Cannot purge private service broker

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cloud_controller_ng#549]
I have a private service broker registered that I want to purge, but I get auth error:

```
$ cf purge-service-offering haash-broker
...
Server error, status code: 403, error code: 10003, message: You are not authorized to perform the requested action
```

**Comment by dieucao** [comment]
Thanks @drnic .  Looks like we missed that.  I'll see if we can queue this up to be fixed "soon"

**Comment by dieucao** [comment]
@drnic This will be fixed with https://www.pivotaltracker.com/story/show/114649983
Should be available as part cf-release v232/v233
