### ISSUE TITLE
link to GH issues and/or source on apidocs pages

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cloud_controller_ng#550]
Please consider adding on the apidocs pages a link to the GH issue tracker where users can report omissions/questions about these docs, or even to the source in GitHub so we can easily edit them online and raise PRs.

**Comment by dkoper** [comment]
Can't seem to attach my test app. It's a JSP with:

```
<%@ page session="false" %>

File write<HR>
<%
try{
	long length = 0;
	
	try{
		length = Long.parseLong(request.getParameter("length")) * 1024 * 1024;
	}catch(Exception ex){
		out.println(ex);
		out.println("<HR>");
		out.println("USAGE: " + request.getRequestURL() + "?length=[Mbytes]");
		out.println("<HR>");
		out.println("and... check following.<HR>");
		out.println("cf app [application name] <BR>");
		out.println("cf files [application name] app");
	}

	java.io.FileOutputStream fo = new java.io.FileOutputStream("FileOutputStream.txt", false);
	java.io.BufferedOutputStream bo = new java.io.BufferedOutputStream(fo);	
	byte b = (byte)'b';
	byte bytes[] = new byte[]{b};

	for (long i=0 ; i<length; i++){
		bo.write(bytes, 0, 1);
	}
	bo.close();
} catch (Exception ex){
	ex.printStackTrace();
	out.println(ex);
}
%>
```

Invoke with app-url/file.jsp?length=2400

**Comment by thausler786** [comment]
Hey @dkoper,

Thanks for the suggestion. We added a "Getting Help" section to the v3 docs with a link to the repo in this commit: `a2a02cadace0cb3521dc7954da3965903f8ab2cb`. Let us how we can improve our docs further.

CAPI Community Pair: @thausler786 && @aashah
