### ISSUE TITLE
Missing service/plan id for async last_operation call

### ISSUE THREAD

**Issue by vlerenc** [cloudfoundry/cloud_controller_ng#551]
The documentation at http://docs.cloudfoundry.org/services/api.html describes nicely all API calls a broker needs to implement. Provision, deprovision, bind, and unbind all transport the service and the plan id with each call. That is great and extremely useful. However, when the async feature was added, last_operation misses that information in http://docs.cloudfoundry.org/services/api.html#polling.

That is a problem for us as our broker has no chance to find out to which service/plan the service instance GUID belongs. Maybe most brokers have no issue with this, but the generic https://github.com/cloudfoundry-community/cf-containers-broker can't be migrated to async calls, unfortunately. Our container manager abstraction has multiple implementations and depend on the plan, but without the service/plan ID we don't know which backend to contact (https://github.com/cloudfoundry-community/cf-containers-broker/blob/master/config/settings.yml#L47) to find out the right backend to contact for a given service instance GUID.

Would it be possible to resolve this issue? Maybe add additional query parameters like there are for deprovision (http://docs.cloudfoundry.org/services/api.html#deprovisioning) and unbind (http://docs.cloudfoundry.org/services/api.html#unbinding).

**Comment by vlerenc** [comment]
Did anybody check the issue already? Does it make sense to add the seemingly missing information?

**Comment by SocalNick** [comment]
Hi @vlerenc,

This makes sense. I'll prioritize. cc @avade 

Thanks,

Nick

**Comment by sax** [comment]
@vlerenc we're hoping to clarify the problem that you are facing, so we can understand the best approach for solving it.

Do you have the `service_id` or `plan_id` of the related services? Or do you only have the `guid` of the service instance?

Are you expecting to hit the `last_operation` endpoint for each `service_id`, or were you expecting to hit it only for the `guid`, and then see a `service_id` in the response? Couldn't you hit `GET /v2/service_instances/:guid` to look up the `service_plan_guid` when the asynchronous operation is complete?

**Comment by vlerenc** [comment]
Hi,

> Do you have the service_id or plan_id of the related services?

Yes, but since I don't have/generate the guid, I don't know how they relate.

> Are you expecting to hit the last_operation endpoint for each service_id, or were you expecting to hit it only for the guid, and then see a service_id in the response?

Not sure how you mean that. I am not hitting anything (CC calls the broker), but I am hit (by CC). What I would expect is that I then see service_id AND plan_id (both) with the last_operation call.

> Couldn't you hit GET /v2/service_instances/:guid to look up the service_plan_guid when the asynchronous operation is complete?

Again, I don't understand. I have a broker, I am called by the CC only with the guid. All other calls deliver service_id AND plan_id, but last_operation doesn't. That looks to me like someone forgot to add that to that call.

Yes, for now I call back to the CC to resolve the service_id AND plan_id for a guid whenever last_operation hits the broker, but a.) this is adding complexity, b.) introducing a dependency you tried to remove (CC should call the broker; only in this direction), c.) forces me to insert the CC credentials into the broker, d.) adds load unnecessarily.

**Comment by SocalNick** [comment]
@vlerenc I think there was a misunderstanding regarding your ask. We will add query params similar to the broker delete request.

**Comment by michaelxupiv** [comment]
Hey @vlerenc,

Thanks for submitting this issue. Seems like the query params have been added as part of this [story](https://www.pivotaltracker.com/story/show/114769745). We're closing this issue for now, feel free to reopen this if you feel like your issue hasn't been addressed.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
