### ISSUE TITLE
Mis-leading error when wrong service broker response [migrated from diego-release]

### ISSUE THREAD

**Issue by ematpl** [cloudfoundry/cloud_controller_ng#555]
> Original issue: https://github.com/cloudfoundry-incubator/diego-release/issues/139
> Original poster: @LaynePeng

---

Hi, I'd like to report a bug, but not sure which project I should raise to. 

How to reproduce the bug: 
In own service broker, binding the service with a wrong return: without "credentials" field. (The API should be: PUT /v2/service_instances/:instance_id/service_bindings/:binding_id)
Create a service with this broker, than bind to a app. Then restage the app. 
You will get the error as following:

```
Starting app env-test in org emc / space elc as admin...
FAILED
Server error, status code: 500, error code: 170011, message: Stager error: undefined method `[]' for nil:NilClass
```

The problem should be caused by setting VCAP_SERVICES enviroment variable in container, but cannot find the credentials information. 
But this error is quite mis-leading, and make people think there is some error happened in stager.

---

Updates from comment thread:
- This error occurs on CF v230 + Diego v0.1454.0.
- In the App model's `database_uri` method, https://github.com/cloudfoundry/cloud_controller_ng/blob/39da42fe661cc87b3be0b8ef5c47bea7987b04db/app/models/runtime/app.rb#L377 extracts a `uri` field from the service binding credentials, and that `database_uri` method does get called when building the staging message to send to the Diego backend. Since the credentials were omitted in the service-binding request, it's plausible that those credentials are `nil` in memory in CC, and the `undefined method '[]' for nil:NilClass` error message in those logs corresponds to applying `['uri']` to that `nil` object.

Thanks,
Eric

**Comment by michaelxupiv** [comment]
Hey @ematpl ,

Thanks for reporting this issue. It looks like this bug was fixed in this other [story](https://www.pivotaltracker.com/story/show/133604735). Closing the issue for now.

Thanks,
CAPI Community - @michaelxupiv
