### ISSUE TITLE
V3 Task Object does not document CANCELING state

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#556]
The V3 API Documentation of the [Task Object](http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html#the-task-object) does not document the [`CANCELING` state](http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html#cancel-a-task).

**Comment by SocalNick** [comment]
@nebhale we chose to document the various states in a single location: http://v3-apidocs.cloudfoundry.org/version/release-candidate/#the-task-object
