### ISSUE TITLE
App Start Events are not recorded in some cases.

### ISSUE THREAD

**Issue by NAGAI-Tsuyoshi** [cloudfoundry/cloud_controller_ng#558]
When hm9000 resurrects(creates) an application instance, App Start Events of the instance are not recorded. I tried to start application by cf push command. cf push command failed because of insufficient resources, and afterwards, the application was started by hm9000. However, App Start Events of the instance is not shown in the result of cf events. I think that it is necessary to record the App Start Events in this case.

**Comment by SocalNick** [comment]
Hi @NAGAI-Tsuyoshi,

`cf events` calls `/v2/events` which is an audit of changes requested by users. In this case, it's an internal component trying to achieve consistency.

@ematpl - I have a note to check with you about this and whether it's something we want to record in Diego world.

**Comment by aashah** [comment]
There has not been any recent activity on this issue. We are closing the issue.

Please feel free to re-open.

CAPI Community Pair - @aashah @rizwanreza
