### ISSUE TITLE
Add a parameter `service_id` in Polling Last Operation of service broker APIs [migrated from cf-release]

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cloud_controller_ng#559]
> Original issue: https://github.com/cloudfoundry/cf-release/issues/925
> Original poster: @bingosummer

---

This is a feature request.

```
curl http://username:password@broker-url/v2/service_instances/:instance_id/last_operation?service_id=service-id-here
```

If the broker provides multiple services, with the service id, the broker can determine which service the instance is, and get the state of the last operation. In such a scenario, the broker does not need to store the map between the instance id and the service id.

**Comment by utako** [comment]
Hi @bingosummer,

To clarify, is your feature request to add a new endpoint specifically to get last_operations, and to add a query parameter to filter by service ids? 

@utako and @thausler786, CF CAPI Team

**Comment by michaelxupiv** [comment]
Hi @Amit-PivotalLabs ,

Thanks for submitting this. We are closing this issue now due to inactivity, but feel free to reopen this issue if you feel like we need to further address it.

Thanks,
CAPI Community Pair - @ericpromislow & @michaelxupiv
