### ISSUE TITLE
SSO clients should have uaa.resource authority

### ISSUE THREAD

**Issue by william-tran** [cloudfoundry/cloud_controller_ng#560]
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/services/sso/uaa/uaa_client_manager.rb#L93

scope is present but there are no authorities for the client. As a result, SSO clients cannot use UAA's /check_token endpoint to verify the token.

**Comment by johnmcteague** [comment]
+1, was about to raise the exact same issue.

**Comment by utako** [comment]
Hi @william-tran,

We agree that SSO clients should be able to use the check_token endpoint to verify their tokens. Would you be interested in [submitting a PR](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/PULL_REQUEST_TEMPLATE.md)? 

Thanks,
@utako and @thausler786, CF CAPI Team

**Comment by william-tran** [comment]
I'm a total ruby noob. But it doesn't seem like a huge change so what the heck.

**Comment by luan** [comment]
Hey @william-tran,

Following up on this PR. Is this still something you're interested in doing? 

Thanks,
@utako and @luan, CF CAPI Team

**Comment by utako** [comment]
@william-tran and @johnmcteague,

We've gone ahead and [made this change](https://github.com/cloudfoundry/cloud_controller_ng/commit/2747f354f16399b705e1ff3f9ed243b1e28541d8) for you. We're going to close this issue now, feel free to comment and we'll reopen if you have more concerns.

@thausler786 and @utako, CF CAPI Team

**Comment by william-tran** [comment]
Thanks a bunch team! The changes look good and far simpler than I thought.  Looks like I'm up next for whisky club, I'll bring Toronto's finest next time I'm over.
