### ISSUE TITLE
loggregator endpoint wrong

### ISSUE THREAD

**Issue by Koizumi85** [cloudfoundry/cloud_controller_ng#564]
Hello,

I've deployed cloudfoundry v232 today and had trouble with the loggregator.
If I push an app, I get an error, that the loggregator request failed.

After investigation I found out the following:
loggregator registers route "loggregator.[domain]", but cloud_controller uses the following config:
loggregator:
  router: <%= host %>:<%= port %>
  url: ws<%= "s" if p("logger_endpoint.use_ssl") %>://loggregator.<%= p("system_domain") %>:<%= p("logger_endpoint.port") %> 

So the cf cli gets the loggregator.[system_domain] from the cloud_controller which fails.

I don't know which of both is the correct configuration, but the current doesn't work I think.

**Comment by youreddy** [comment]
Hello @Koizumi85, 

Can you check if your manifest file has `system_domain` and `domain` set to the same value? By default we have `system_domain` pointing to domain in the templates used to generate the manifest. 

Best,
@ureddy & @rizwanreza 
CF CAPI Team

**Comment by Koizumi85** [comment]
@youreddy yes, we have different domains there at the moment.
But in fact the definitions are definitely wrong:
Cloudcontroller looks for loggregator.system_domain
Loggregator registers as loggregator.domain

so if everyone defines different values for domain and system_domain, the loggregator would fail.

Best Regards

**Comment by simonleung8** [comment]
@Koizumi85 As of now, you are right. `system_domain` and `domain` properties must match for the internal services to work properly. There is a backwards incompatibility issue here, as some services rely on one properties and others on the second. We will keep this issue in mind and try to refactor in due time.

**Comment by SocalNick** [comment]
Closing in favor of https://www.pivotaltracker.com/story/show/117401791
