### ISSUE TITLE
Database migration for total_service_keys in space quotas failure

### ISSUE THREAD

**Issue by LinuxBozo** [cloudfoundry/cloud_controller_ng#570]
In the migrations for `total_service_keys`, the [Space quota migration](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/db/migrations/20160221153023_add_total_service_keys_to_space_quota_definitions.rb) specifies `null: false` with no `default:` value. If you have any existing space quotas, this causes the migration to fail:
```
PG::NotNullViolation: ERROR: column "total_service_keys" contains null values: ALTER TABLE "space_quota_definitions" ADD COLUMN "total_service_keys" integer NOT NULL
```

/cc @dlapiduz

**Comment by cholick** [comment]
This is also a problem for us trying to update to a newer version.

**Comment by omazhary** [comment]
Yes. I can confirm this issue exists. It also occurs when downgrading from v233 to v231 due to the same bug.

**Comment by adowns01** [comment]
Hi @LinuxBozo, 

We were unable to reproduce this locally, but clearly there is an issue. Can you please give us steps to reproduce? I don't understand if you are getting this error while migrating (in which case it is a new column, so nothing can be set yet) or rolling back (in which case, it should just delete the column). 

Thanks, 
Amelia @adowns01 & Riz @rizwanreza, CAPI Team Members

**Comment by LinuxBozo** [comment]
@adowns01 Yes, you get this error during migration. The steps to reproduce are simple, as I mentioned, you have created one or more space quota definitions, and then run the migration. If you can't repeat, I'm guessing you are working with an empty `space_quota_definitions` table before you are running the migration.

**Comment by cholick** [comment]
Our solution to get past this was to run different sql to modify the table:
```
ALTER TABLE "space_quota_definitions" ADD COLUMN "total_service_keys" integer NOT NULL DEFAULT -1
```
and manually insert a record into the `schema_migrations` table so it didn't try to run the problematic sql.

@adowns01 You're adding a not null restriction; this also requires a default value when there are existing rows.

**Comment by karafelix** [comment]
Hello @LinuxBozo and @cholick,
I have pushed a fix to this, adding `DEFAULT -1` to the migration; however, for some reason the commit does not appear to be showing up on github yet. The commit does seem to show up when I pull.
Hopefully this will resolve itself in time.

Please feel free to close the issue if the issue has been adequately resolved, or let us know if there are any further problems.

Thanks,
Kara, CF CAPI team member

**Comment by fraenkel** [comment]
This highlighted the fact that migrations aren't tested with existing data. And this hasn't added any test. The problem isn't limited to this but highlights the omission that can occur with any migration and the fact that most of the test environments do not have at least one of every type of object.

**Comment by karafelix** [comment]
@fraenkel,
you are correct that this is a problem.
I have added [a chore](https://www.pivotaltracker.com/story/show/117023765) to take a look at this.

Thanks,
Kara, CF CAPI team member

**Comment by LinuxBozo** [comment]
Like @fraenkel I was figuring there would be some added test here, but glad that's now on your radar @karafelix. Commit 06ec4c9 does indeed close out this issue..
