### ISSUE TITLE
SpaceManager / SpaceAuditor could not see private domain

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry/cloud_controller_ng#573]
## Issue
 Not really an issue, but more a question.
SpaceManager /  SpaceAuditor can be use to see the status of the space.
Application and so on but they could NOT see the private domain, only the SpaceDeveloper can see that.

As an SpaceManager / SpaceAuditor  I would like to verify domain that my SpaceDeveloper can use or not.

## Steps to Reproduce

Create a private domain within your org
```bash
cf create-domain ORG-TEST space-test.local.pcfdev.io
```
Login with your SpaceManager / SpaceAuditor users
```bash
cf login 
```
List domain
```bash
cf domains
```
## Expected result

```bash
cf domains                                                                                            
Getting domains in org SPACE-TEST as gwenn...
name                         status
local.pcfdev.io              shared
space-test.local.pcfdev.io   owned
```

## Current result
```bash
cf domains                                                                                                                 
Getting domains in org SPACE-TEST as gwenn...
name              status
local.pcfdev.io   shared
```

## Possible Fix
Permit domain enumaration for SpaceAuditor / SpaceManager

**Comment by adowns01** [comment]
Hi @shinji62, 

We were not able to reproduce this error on API version 2.55.0. Which version are you using? 

Can you run `cf org-users ORG-TEST` and `cf space-users ORG-TEST SPACE-TEST` to double check that your user is an org manager and a space manager?

Thanks, 
@adowns01 && @simonleung8, CAPI Team Members

**Comment by shinji62** [comment]
If my user have OrgManager it works but I don't understand why my user should be OrgManager.
SpaceManager normally can manage the space right ? So why he could not see the domain that his space can use.

**Comment by zrob** [comment]
@shinji62 the reason only OrgManager can see the private domain is because private domains are managed at an organization level.  This means that SpaceManagers cannot add or remove domains.  SpaceDevelopers are able to see them because they need to know the domains in order to create routes.

I can't think of a specific reason that it is valuable to prevent SpaceAuditors/SpaceManagers from also being able to at least view private domains.

@SocalNick would you like to comment from a product perspective?

thanks,
@zrob

**Comment by SocalNick** [comment]
@zrob I agree, I think we want to move towards auditors being able to _See everything except for potentially sensitive data. Change nothing._ Space Managers should be able to _See everything. Change only user access._

Feel free to make this so in regards to Private Domains.

**Comment by shinji62** [comment]
@zrob @SocalNick I am agree, auditor are well defined name, that's mean be able to audit the space / organization so to See everything.

**Comment by adowns01** [comment]
Hi @shinji62, 

Currently space auditors can view the private domains. @rizwanreza and I have just made a commit that will allow space managers to view private domains.

https://github.com/cloudfoundry/cloud_controller_ng/commit/f9465f4e0d99e702cab95f98e61bcdd9c6c19920

This commit should be available in the next release.

If this solves your problem, please close this issue.

Best, 
@adowns01 && @rizwanreza, CAPI Team Members

**Comment by shinji62** [comment]
Thanks.
Will check that.
