### ISSUE TITLE
CF PUSH via CF CLI doesn't time out for hours

### ISSUE THREAD

**Issue by AndreasJHeix** [cloudfoundry/cloud_controller_ng#574]
Thanks for submitting an issue to `cloud_controller-ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

CF PUSH (for both java and ruby apps) fails to finish and doesn't time out for hours

## Context

We have scheduled jobs which regularly push sample apps into several CF landscapes. We see in way less than 1% of these pushes a non-termination. Some other pushes also fail with a clear error message - this issue is about the non-termination

## Steps to Reproduce

Also seen with a CF version > 229.
Regular pushing of java or ruby apps.
Patience.

## Expected result

The CF CLI should have ended, telling me what went wrong during the process, just like it does for other issues

## Current result

The CF CLI is patiently waiting for the CC to send either an ok or a failure.

## Possible Fix

Maybe this https://github.com/cloudfoundry/cli/issues/260 discussion with the timeout config of the CC helps.

I'd like to have a reliable termination signal from the CC. Watching the duration of the CF CLI process on the client side and terminating this after a given time seems like a workaround

## `name of issue` screenshot
Here's a snippet from the CF CLI

[…]
API endpoint: https://api...
Authenticating...
OK
 
Targeted org <myOrg>
 
Targeted space <mySpace>
                   
API endpoint:   https://api.... (API version: 2.41.0)   
User:           <myUser>
Org:            <myOrg> 
Space:          <mySpace>
Using manifest file /var/lib/jenkins/jobs/mon_PushAppInternet/workspace/manifest.yml
 
Updating app cf_push_app in org <myOrg> / space <mySpace> as monitoring_pushapp...
OK
 
Using route cf_push_app.cfapps....
Uploading cf_push_app...
Uploading app files from: /var/lib/jenkins/jobs/mon_PushAppInternet/workspace
Uploading 30.7K, 10 files
 
                             
Done uploading
OK
 
Stopping app cf_push_app in org <myOrg> / space <mySpace> as monitoring_pushapp...
OK
 
timeout connecting to log server, no log will be shown
Starting app cf_push_app in org <myOrg> / space <mySpace> as monitoring_pushapp...
[…]

**Comment by adowns01** [comment]
Hi @AndreasJHeix, 

This reminds us of an [old bug that we fixed awhile ago](https://github.com/cloudfoundry/cli/commit/831be3f13df41238d68e0cf5842006f9aaaf3a0b). The fix should be on v 6.11.1 of the CLI and onward. What version of the CLI are you using?


Thanks, 
@simonleung8 && @adowns01, CAPI Team Members

**Comment by AndreasJHeix** [comment]
Hi,

version is  6.14.0

Kind regards
Andreas

**Comment by youreddy** [comment]
Hello @AndreasJHeix, 

We're trying to narrow down where this is happening in the code. Can you please provide us with a CF_TRACE of the cf push? Are you using diego or DEAs?

Thanks,
@youreddy & @thausler786
CF CAPI Team

**Comment by AndreasJHeix** [comment]
Hi Urvashi,
I am using DEA. However we just stumbled across another issue so we don't want to clog our logs with additional output. So it may take some days until we can turn the CF_TRACE on. 

Short heads-up: We are using 6.18.0+b22884b-2016-05-10 and haven't had the issue for the last ~ 3 weeks (around 10000 pushes) anymore. 

Cheers
Andreas

**Comment by michaelxupiv** [comment]
Hi @AndreasJHeix,

If you haven't ran into this issue again or think it has been fixed, please close this issue. Thanks for your submission!

Best,
@jberkhahn & @michaelxupiv

**Comment by aashah** [comment]
We are going to close this issue due to inactivity. Please feel free to reopen the issue if the issue persists.

Thanks,
@aashah & @rizwanreza 
The CAPI Team
