### ISSUE TITLE
Create a Private Domain doc error for owning organization

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#576]
## Issue

Doc for Create Private Domain claims owning_organization_guid is not required, but CF errors if it isn't.

## Context

The documentation for Create Private Domain describes `owning_organization_guid` by saying "The organization that owns the domain. If not specified, the domain is shared." In practice if the field is not specified CF returns an error:
"CF-MessageParseError(1001): Request invalid due to parse error: Field: owning_organization_guid, Error: Missing field owning_organization_guid"

## Steps to Reproduce

Make a call to the private_domains endpoint without specifying an owning_organization_guid

## Expected result

Based on the documentation, a shared domain should be created.

## Current result

An error is thrown as detailed above

## Possible Fix

I believe the functionality is correct, and the documentation should be brought into line.

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by sax** [comment]
@twoseat thanks for calling our attention to this! I've pushed a fix to the documentation, so it will be updated as the change works its way through our CI pipeline.
