### ISSUE TITLE
Undocumented API

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#582]
## Issue

The CF CLI makes a request for `GET /v2/service_instances/<SERVICE_INSTANCE_ID>/service_keys` which is an undocumented API.
## Context

While tracing the `cf service-keys` command against PWS (`2.53.0`), I noticed the following request sequence:

```
GET /v2/spaces/<SPACE_ID>/service_instances?return_user_provided_service_instances=true&q=name%3A<SERVICE-INSTANCE-NAME>&inline-relations-depth=1
GET /v2/services/<SERVICE_ID>
GET /v2/service_instances/<SERVICE_INSTANCE_ID>/service_keys
```

The final request is not [documented](http://apidocs.cloudfoundry.org/235/).
## Steps to Reproduce

`CF_TRACE=true cf set-keys <SERVICE-INSTANCE-NAME>`

**Comment by adowns01** [comment]
Hi @nebhale, 

Thanks, nice catch. We added docs in [this commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/8a79066f156ac1a4ad617f9f61eb6887af4fdc02). The docs should be updated soon. 

-- @adowns01 && @simonleung8, CAPI Team Members

**Comment by nebhale** [comment]
@SocalNick I'm not sure this quite complete.  Reviewing the `release-candidate` docs, [it does not appear](http://apidocs.cloudfoundry.org/release-candidate/service_instances/retrieving_service_keys_associated_with_a_service_instance.html) that the `name` filter parameter is documented.

**Comment by SocalNick** [comment]
Re-opened tracker issue

**Comment by SocalNick** [comment]
Verified: http://apidocs.cloudfoundry.org/release-candidate/service_instances/list_all_service_keys_for_the_service_instance.html

**Comment by michaelxupiv** [comment]
Hey @nebhale,

This seems to be documented now. Thanks for bringing up this issue. We are closing this now, feel free to reopen if you experience any other problems.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
