### ISSUE TITLE
Create a Task does not document droplet_guid request payload

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#586]
The API Documentation for [Create a Task](http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html#create-a-task) does not describe the `droplet_guid` parameter in its request payload. This parameter appears to be legal based on the [source code](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/messages/task_create_message.rb#L5) and it's absence in the documentation makes the API less useful.

**Comment by michaelxupiv** [comment]
Hey @nebhale,

Thanks for the issue. This seems to have been added now in our [docs](http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html#create-a-task). Closing this issue now, feel free to reopen if you feel like we haven't addressed your issue.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
