### ISSUE TITLE
Task command database column is too small

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#589]
Thanks for submitting an issue to `cloud_controller-ng`. We are always trying to improve! To help us, please fill out the following template.
## Issue

Currently, the task `command` column in the database is too small.
## Context

Currently, the task `command` column in the database is too small.  As it is [not specified](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/db/migrations/20160114182148_create_tasks.rb#L7), it's likely to be 255 characters wide.  Processes on the other hand, get [4096 characters for a command](https://github.com/cloudfoundry/cloud_controller_ng/blob/7d15cfb01cf602fdfe9aa4d67c33a98217661fdc/db/migrations/20150202222600_add_command_to_processes.rb#L3).
## Steps to Reproduce

Create a task with a command longer than 255 characters.
## Expected result

A command length equal to the command lengths in the rest of the system.  For the simplest possible Java application, you're looking at 613 characters.
## Current result

From the client side we get:

```
org.cloudfoundry.client.v2.CloudFoundryException: UnknownError(10001): An unknown error occurred.
```

On the server we get:

```
Sequel::DatabaseError (Mysql2::Error: Data too long for column 'command' at row 1):
```
## Possible Fix

Database migration to at least 4096 characters to match V3 processes.  All command lengths, detected or specified, v2 and v3 should be consistent as a more robust solution.

**Comment by michaelxupiv** [comment]
Hey @nebhale,

Thanks for submitting this issue. It seems like this [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/56931056a94895137f20f58d38c9b5a83173354b) fixed it. We're closing this issue for now, feel free to reopen this issue if you see any other problems.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
