### ISSUE TITLE
List endpoints have unexplained space_guid filter

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/cloud_controller_ng#594]
## List endpoints have unexplained `space_guid` filter

The [List all Users][1] and [List all Auditors for the Organization][2] endpoints (and similar ones) document a `space_guid` filter. There is no explanation about how this filter is interpreted. How is the space guid supposed to be related to the users being listed?

## Steps to Reproduce

Read the docs pages [list all users][1] and [list auditors for the organization][2] and try to use them.

## Expected result

By reading the docs, the user would expect to understand how to use the filter.

## Current result

Confusion.

## Possible Fix

Rename the filter, or explain the filter explicitly.  Check all other List endpoints which list users filtering on space_guid, for example, in the `organizations` endpoint path there are [list billing managers for the organization][3], [list managers for the organization][4] and [list users for the organization][5].

There is a similar (though greater) confusion is in the `spaces` endpoint path where the description of the `space_guid` filter on [list auditors for the space][6], for example, implies it means something else!

[1]: http://apidocs.cloudfoundry.org/236/users/list_all_users.html
[2]: http://apidocs.cloudfoundry.org/236/organizations/list_all_auditors_for_the_organization.html
[3]: http://apidocs.cloudfoundry.org/236/organizations/list_all_billing_managers_for_the_organization.html
[4]: http://apidocs.cloudfoundry.org/236/organizations/list_all_managers_for_the_organization.html
[5]: http://apidocs.cloudfoundry.org/236/organizations/list_all_users_for_the_organization.html
[6]: http://apidocs.cloudfoundry.org/236/spaces/list_all_auditors_for_the_space.html

**Comment by adowns01** [comment]
Hi @Zteve, 

When you filter a users list endpoint by `space_guid`, it will return users who belong to that space. 

At this time, we are focusing on creating [new docs for v3](http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html) where it is much easier to explain each filter and query parameter. The v2 docs are auto generated in a way where it is difficult to add such explanations. 

I hope this gives you enough context. If this resolves your problem, please close this issue. 

Thanks, 
@adowns01 & @rizwanreza, CAPI Team Members

**Comment by Zteve** [comment]
Hi Amelia,
If I understood what "users who belong to that space" meant, I could proceed, but I'm not at all sure. It is not possible to associate a user with a space; but it is possible to associate a space with a user.  As far as I can see, we can associate a user with a specific role with a space (auditor, manager, developer). Would any of these count as 'belonging' to the space?

Also, please can you explain what the [list auditors for the space][1] endpoint means by the `space_guid` filter in that case?

[1]: http://apidocs.cloudfoundry.org/236/spaces/list_all_auditors_for_the_space.html

**Comment by adowns01** [comment]
Hi @Zteve, 

1. Yes, by "belonging to a space" I mean users who are associated with a space through roles. 

2. According to the docs on the page that you linked to:

> Note that filtering on space_guid will return an empty list if you specify anything other than the guid included in the path.

I hope this gives you enough context. If this resolves your problem, please close this issue.

Thanks, 
@adowns01

**Comment by Zteve** [comment]
Hi Amelia,

I believe a single user can be associated with multiple spaces (in many roles).  And vice-versa.  Therefore when [listing auditors for a space][1] it is quite reasonable to filter on spaces it should _also_ be associated with. These need not be the space in the URL.

This implies that the comment in that API endpoint documentation is incorrect and calls into question the resolution of issues 512, 513, 514, 516, 519, and 520 also.

[1]: http://apidocs.cloudfoundry.org/236/spaces/list_all_auditors_for_the_space.html

**Comment by SocalNick** [comment]
Hi @Zteve,

I agree, the note added for all the issues you mentioned doesn't really help much. Listing auditors for a space is already fairly tightly scoped: **Users that have the SpaceAuditor role on the Space**. The filters are being inherited from `/v2/auditors` and don't really make sense when nested under a specific space.

We could consider deprecating some of these filters that don't really make sense, would you be opposed? Would like to hear from @dieucao and @nebhale on this as well.

As much as we appreciate the attention you are giving the docs, we are spending a lot of developer cycles on various issues filed against the V2 API documentation. The rigidity of the V2 API and documentation is exactly why we desperately want to replace it. Please consider that any time we spend ~~fighting with~~ _working on_ the V2 API prolongs the replacement of it.

**Comment by SocalNick** [comment]
We will consider the following two stories:

Make the docs better: [#119754443](https://www.pivotaltracker.com/story/show/119754443)
Remove the filters from these sort of nested endpoints: [#120020209](https://www.pivotaltracker.com/story/show/120020209)

**Comment by Zteve** [comment]
Hi Nicholas (@SocalNick),

I really appreciate the work you are all putting into these APIs and, like you, look forward eagerly to the replacement of the V2 API with something better. Rather than simple deprecation, I would prefer a 'deprecation with prejudice', whereby the API remains, but issues a warning or error which cannot be suppressed.  This would encourage people to move, and allow client implementors like us to _legitimately_ avoid them altogether.

Until the design criteria for our project change (@nebhale?) we are committed to providing an interface to all the available APIs, deprecated or not, _especially_ if other higher-level operations, for example in the CLI, use them.

Here is a more general observation: the relationships within CF (exposed on the REST API, and represented by the `guid`s which appear as key fields and foreign keys in the db) are _opaque_ to the API user.

If these were made clearer in the doc, it would be much more obvious if a particular operation (or feature on an API) were necessary, or could be reconstructed from other operations.  Then, when something is deprecated, it would be clear how to replicate the (old) function by other means. Essentially, API completeness would be a testable criterion.

Is it too much to hope that you might eventually provide a relationship diagram for end-users to read?

**Comment by SocalNick** [comment]
@Zteve sorry for never responding. I did make a follow on story to remove filters that don't make sense: https://www.pivotaltracker.com/story/show/120020209
