### ISSUE TITLE
Associated Private Domain does not appear in List Domains for Org

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/cloud_controller_ng#595]
## A Private Domain _associated_ with an Organization (but not owned by it) is not listed by List All Domains endpoint

The api endpoint [list domains for an organization](http://apidocs.cloudfoundry.org/236/organizations/list_all_domains_for_the_organization_%28deprecated%29.html) does not include private domains that are associated with the organization but not owned by  it.

This also implies that the filter `owning_organization_guid` has no function.
## Context

Latest version (236 2.55.0). Tested using PcfDev.
## Steps to Reproduce
1. Create two organizations, `o1` and `o2`.
2. Create a private domain, `pd`, with `owning_organization_guid` set to `o2`.
3. Associate `pd` with organization `o1`.
4. [List All Domains for Organization](http://apidocs.cloudfoundry.org/236/organizations/list_all_domains_for_the_organization_%28deprecated%29.html) specifying organization `o1`.
## Expected result

The list produced from step 4 should include the private domain `pd`.
## Current result

It does not.
## Possible Fix

Implement the join correctly?
## Here is a testcase (taken from `cf-java-client` development version)

``` java
@Test
public void listDomainsWithAssociatedPrivateDomain() {
    String organizationName1 = getOrganizationName();
    String organizationName2 = getOrganizationName();
    String privateDomainName = getDomainName();
    Mono
        .when(
            createOrganizationId(this.cloudFoundryClient, organizationName1),
            createOrganizationId(this.cloudFoundryClient, organizationName2)
        )
        .then(function((organizationId1, organizationId2) -> Mono
            .when(
                Mono.just(organizationId1),
                createPrivateDomainId(this.cloudFoundryClient, organizationId2, privateDomainName)
            )))
        .as(thenKeep(function((organizationId, privateDomainId) -> requestAssociatePrivateDomain(this.cloudFoundryClient, organizationId, privateDomainId))))
        .then(function((organizationId, privateDomainId) -> Mono
            .when(
                Mono.just(privateDomainId),
                requestListOrganizationDomains(this.cloudFoundryClient, organizationId)
                    .log("stream.domains.list")
                    .filter(resource -> privateDomainName.equals(ResourceUtils.getEntity(resource).getName()))
                    .single()
                    .map(ResourceUtils::getId)))
        )
        .subscribe(this.<Tuple2<String, String>>testSubscriber()
            .assertThat(this::assertTupleEquality));
}
```

and here is the log I see from it:

```
main               cloudfoundry-client.test            >> OrganizationsTest.listDomainsWithAssociatedPrivateDomain <<
cloud-foundry-4    cloudfoundry-client.request         POST   /v2/organizations
cloud-foundry-2    cloudfoundry-client.request         POST   /v2/organizations
cloud-foundry-3    cloudfoundry-client.request         POST   /v2/private_domains
cloud-foundry-6    cloudfoundry-client.request         PUT    /v2/organizations/47f6baa2-b485-4922-9099-d4aaee67df97/private_domains/b66dc7c7-b761-4223-8de7-42f77a8d1b28
cloud-foundry-6    stream.domains.list                  onSubscribe(reactor.core.publisher.FluxFlatMap$FlatMapMain@7606e8c9)
cloud-foundry-6    stream.domains.list                  request(unbounded)
cloud-foundry-7    cloudfoundry-client.request         GET    /v2/organizations/47f6baa2-b485-4922-9099-d4aaee67df97/domains?page=1
cloud-foundry-7    stream.domains.list                  onNext(DomainResource(super=Resource(entity=DomainEntity(name=local.pcfdev.io, owningOrganizationId=null, owningOrganizationUrl=null, routerGroupId=null, routerGroupType=null, sharedOrganizations=null, spacesUrl=null), metadata=Resource.Metadata(createdAt=2016-05-06T08:42:20Z, id=c73229ba-21a1-4976-896e-0b1e62005b89, updatedAt=2016-05-06T08:42:20Z, url=/v2/domains/c73229ba-21a1-4976-896e-0b1e62005b89))))
cloud-foundry-7    stream.domains.list                  request(1)
cloud-foundry-7    stream.domains.list                  onComplete()
cloud-foundry-7    stream.domains.list                  cancel()

java.lang.AssertionError: Unexpected error
...
Caused by: java.util.NoSuchElementException: Source was empty
```

**Comment by adowns01** [comment]
Hi @Zteve, 

Any endpoint for listing domains, including 
- `/v2/organizations/:guid/domains`
- `/v2/domains`
- etc

will *not* show private domains. To get the private domains for an organization, you can use [this](http://apidocs.cloudfoundry.org/236/organizations/list_all_private_domains_for_the_organization.html) endpoint.

We went through your steps, but instead of listing all domains for `o1`, we listed all private domains for `o1` and private domain `pd` was returned. 

If this fixes your problem, please close this issue. 

Thanks, 
@adowns01 & @rizwanreza, CAPI Team Members

**Comment by sax** [comment]
We're closing this issue, since there is already a way to get the private domains you're looking for.

Please feel free to re-open it if you have any concerns!

**Comment by Zteve** [comment]
Please can you at least update the documentation to say this (it currently says it lists all domains), and explain what the `owning_organization_guid` filter is for?

**Comment by SocalNick** [comment]
@Zteve the documentation says it is deprecated, I don't think we should update the documentation on deprecated endpoints. Please use [/v2/organizations/:guid/private_domains](http://apidocs.cloudfoundry.org/236/organizations/list_all_private_domains_for_the_organization.html).

**Comment by Zteve** [comment]
Hi Nicholas,
Although the endpoint is marked deprecated, it is still used in the CLI and possibly in applications. My feeling is that, until it is removed, it should be documented correctly.

I am implementing a client which exposes (and therefore tests) all of the API—deprecated or not—and I have not the luxury of "using another endpoint", since I have to use this one.  Updating the documentation (or fixing bugs—whichever way you look at it) on deprecated parts of the API should still be undertaken until those parts of the API are removed.

Incidentally, is not the filter `owning_organization_guid` a **_bug_** in the light of the "non-private-domain" restriction?

**Comment by Zteve** [comment]
PS: I still cannot "re-open" this issue.

**Comment by SocalNick** [comment]
Wha

**Comment by SocalNick** [comment]
What value is provided by your client implementing deprecated end points? Why wouldn't your client expose only the recommended end points?

**Comment by Zteve** [comment]
@nebhale Can you come in here, please Ben? Do I have to justify writing client code for all the published endpoints?

**Comment by nebhale** [comment]
@SocalNick we're aiming to have parity with the CLI which still uses deprecated APIs.  In order for us to reach that parity we need to use the same endpoints they do to ensure consistent behavior.  There's probably a larger discussion to be had around getting CLI off of the deprecated endpoints and arguments.

**Comment by SocalNick** [comment]
Not sure if I agree with the "other clients do it so we have to do it" argument. I believe Domains have been deprecated for approximately two years. For this specific issue, the ability to share Private Domains with several organizations was added after Domains was deprecated. It's a feature of Private Domains, not of the deprecated Domains.

Maybe it's time to remove them from documentation?

Here are a couple CLI interactions that do not use domains:

```
CF_TRACE=true cf domains | grep "GET /v2"
GET /v2/organizations/f67e6085-3087-4879-b01e-732ca44c8379/private_domains HTTP/1.1
GET /v2/shared_domains HTTP/1.1
```

```
CF_TRACE=true cf create-domain ncalugar-a1 foo.com | egrep "(GET|POST) /v2"
GET /v2/organizations?q=name%3Ancalugar-a1&inline-relations-depth=1 HTTP/1.1
POST /v2/private_domains?async=true HTTP/1.1
```

```
CF_TRACE=true cf create-shared-domain foo.com | egrep "(GET|POST) /v2"
POST /v2/shared_domains HTTP/1.1
```

**Comment by nebhale** [comment]
@SocalNick I'm happy for you to remove any deprecated API out of the documentation at your earliest possible convenience.  A list of what you remove would be helpful and we'll be sure to flag anything that the CLI is still using that you've chosen to remove, so that it can potentially be added back until they've moved off of it.

**Comment by michaelxupiv** [comment]
Hey @Zteve and @nebhale,

Thanks for submitting this issue. We recommend using the `private_domains` endpoint as it solves your issue. It feels unnecessary to update deprecated API endpoints when the CLI looks like it has already stopped using them. We are closing this issue for now, feel free to reopen if you have any other concerns.

Thanks,
CAPI Community Pair - @ericpromislow & @michaelxupiv
