### ISSUE TITLE
The "Updating an App" documentation makes it look like I can update the `detected_start_command`

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cloud_controller_ng#597]
On the [Updating an App](http://apidocs.cloudfoundry.org/236/apps/updating_an_app.html) docs, the way the body is presented makes it look like `detected_start_command` should be in the request body, when it only makes sense as part of the response body. We should clearly separate the two in different tables.

**Comment by sax** [comment]
Hi Dan,

The doc has been fixed to exclude `detected_start_command` from the request body table, see [here](https://github.com/cloudfoundry/cloud_controller_ng/commit/be91456fc8b68eadcf4895f312af52a26de5b05d).

Please close if this resolves the issue.

Thanks
@simonleung8 && @sax

**Comment by wendorf** [comment]
Yeah, this solves it. There are still some other read-only parameters, but I'm not sure how much it matters. Thanks!
