### ISSUE TITLE
CloudController still chooses the DEA which is almost full to do app staging if the DEA number is less than 5

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/cloud_controller_ng#598]
## Issue

CC chooses the almost full DEA to do staging, and that causes "Not enough memory resources available" error.
## Context

According to this https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/dea/pool.rb#L101 , CloudController always picks up the top X (X is the max value between 5 and DEA Num \* percentage_of_top_stagers) DEAs with max available memory, and select one randomly from the top X DEAs, but for a CloudFoundry deployment with less than 5 DEAs, even if one DEA is almost full, it's still possible to be picked up, and if two CloudControllers picks up the same full DEA at the same time, that causes staging error with "Not enough memory resources available".

**Comment by ScarletTanager** [comment]
@JimmyMa - I should be submitting a PR today for this.

**Comment by ScarletTanager** [comment]
https://github.com/cloudfoundry/cloud_controller_ng/pull/603 has been merged.

**Comment by michaelxupiv** [comment]
Hey @JimmyMa ,

Thanks for submitting this issue. We are going to close it now since it looks like the PRs that fix this  have been merged. Feel free to reopen if you feel like we haven't addressed the issue.

Thanks,
CAPI Community Pair - @ericpromislow & @michaelxupiv
