### ISSUE TITLE
Listing of user-provided service instances by organization GUID does not work with IN operator

### ISSUE THREAD

**Issue by friday11** [cloudfoundry/cloud_controller_ng#602]
## Issue

Listing of user-provided service instances by `organization_guid` using the `:` operator returns the expected results, while using the `IN` operator returns an empty list.

Example: 
- `v2/user_provided_service_instances?q=organization_guid:123` returns the expected results 
- `v2/user_provided_service_instances?q=organization_guid IN 123` returns an empty list
## Context

Working as a developer at Swisscom. Found this bug while working on our application cloud project based on CloudFoundry.
## Steps to Reproduce
1. Create an organization
2. Create a space in the given organization
3. Create a user-provided service instance in the given space
4. List user-provided services by `organization guid` using the `IN` operator

`v2/user_provided_service_instances?q=organization_guid IN <organization-guid>`
## Expected result

The list of user-provided service instances associated with the provided organization guids. 
## Current result

An empty list.

**Comment by adowns01** [comment]
Hi @friday11, 

Thanks for reporting this. I was able to confirm this issue. What is odd is that if you use the `space_guid` query param you don't have this issue. We'll look into a fix soon.

@adowns01

**Comment by michaelxupiv** [comment]
Hey @friday11 ,

This issue seems to have been fixed in this [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/b63c1983de9cc88d12462ada01dbce6d1ebdd545). We are closing this issue for now, feel free to reopen this issue if you see any problems.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
