### ISSUE TITLE
Long filenames when staging fails in an unhelpful way

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cloud_controller_ng#607]
## Issue

Trying to stage an application with very long filenames fails with a very generic error message that does not help me diagnose the problem.

## Context

See the [tar-sadness readme](https://github.com/wendorf/tar-sadness)

## Steps to Reproduce

On a Cloud Foundry using Diego, push the [tar-sadness](https://github.com/wendorf/tar-sadness) app.

## Expected result

I get my app up and running! :+1:

## Current result

My app fails to stage. :-1:

## Possible Fix

George Lestaris [has an idea](https://cloudfoundry.slack.com/archives/garden/p1464300673006339)

**Comment by utako** [comment]
Hey @wendorf,

Thanks for bringing this to our attention. You'll find that this has been [solved](https://www.pivotaltracker.com/story/show/121305421) by the Diego team, so hooray! 

We're closing this now, but feel free to reopen if there's anything else. 

Happy travels,
@utako & @thausler786
