### ISSUE TITLE
Add sso default support

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/cloud_controller_ng#620]
### Command

cf login
cf login --sso

### CLI Version

cf version 6.15.0+fa1bfe2-2016-01-13

### Error
'cf login' fails to login, but works with 'cf login --sso'.  

The API server should have a 'default_authenication_method' that can be set to SSO.  Currently every single cf client continually has to add '--sso' every time they log in.

### CC API Endpoint Version

API endpoint: https://api.cloud.gov (API version: 2.53.0)

**Comment by sharms** [comment]
To further clarify:

1. When 'cf target' is run, the API default_login_type: sso should be stored in '~/.cf/config.json'
2. In the Bosh Jobs properties for CF API, a new key will be added: default_login_type
3. When default_login_type on the CF API job is set to 'sso', 'cf login' behaves just like 'cf login --sso', which the client understood because 'cf target' downloads the API version and this setting

**Comment by dkoper** [comment]
I've proposed an alternative solution in the related CLI issue:
https://github.com/cloudfoundry/cli/issues/858#issuecomment-229264018

**Comment by SocalNick** [comment]
@sharms I'm going to redirect you again to the UAA team, the CLI interacts with the UAA / login server for the login workflow.

https://github.com/cloudfoundry/uaa
https://www.pivotaltracker.com/n/projects/997278/stories/123968941

cc @sreetummidi
