### ISSUE TITLE
Clarification on List all applications Rest api

### ISSUE THREAD

**Issue by LokeshN** [cloudfoundry/cloud_controller_ng#621]
Sorry for raising this as an issue, as it is just a clarification on the Cloud Foundry - List all applications (/apps) rest api.

In the list all applications rest api call, if I don't specify the "page" and "results-per-page" option, then will the api return me all the applications or is there any limit on the number of the applications returned.

I traced this call in the cli, the options "page" and "results-per-page" is not set in the request, does that mean it will return all the apps even if there are 1000s of applications.

Thanks In Advance,
Lokesh

**Comment by SocalNick** [comment]
Default results-per-page is 50
