### ISSUE TITLE
Contributor's guide does not mention need to have correct release of capi-release

### ISSUE THREAD

**Issue by ScarletTanager** [cloudfoundry/cloud_controller_ng#623]
When developing contributions to CC, it has recently become necessary to checkout `master` of both `cloud_controller_ng` and `capi-release` - one cannot apparently rely on the commit pointed to by `cf-release:develop`.  https://github.com/cloudfoundry/cloud_controller_ng/blob/master/CONTRIBUTING.md should be updated to make this clear for contributors.
## Context

@jberkhahn and I were developing a contribution for `cloud_controller_ng`, and we attempted to deploy using an updated `cf-release:develop` and our branch (based on the latest `cloud_controller_ng:master`).  The deploy failed repeatedly, and when we inquired in #capi , we were told of the requirement to checkout the latest `capi-release:master`.

While in retrospect we probably should have realized the need to do this independently, it would nonetheless be a bit more user-friendly to have this behavior documented in the contributor's guide.
## Expected result

We expected the deploy to succeed.
## Current result

A developer attempting to contribute to CC may not know that they need to checkout `capi-release:master` (rather than using the commit pointed to by `cf-release:develop` and may similarly fail to get a successful deploy of their build.  In our case, we get failures based on missing paths in `syslog_utils.sh`.
## Possible Fix

Ideally, I'd like to see this requirement for lockstep checkouts documented clearly in https://github.com/cloudfoundry/cloud_controller_ng/blob/master/CONTRIBUTING.md.  I think it's really just a user-friendliness issue, but we probably should have realized it ourselves.

**Comment by adowns01** [comment]
Thanks @ScarletTanager, 

We have updated the contributing guide.

@adowns01 && @youreddy

**Comment by michaelxupiv** [comment]
Hey @ScarletTanager,

Thanks for the issue. We updated it to `capi-release:develop`, as we are using that now as our main dev branch. We'll close this issue now, feel free to reopen if you see any problems.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
