### ISSUE TITLE
Mapping a route to an app causes app summary to return wrong number of running_instances

### ISSUE THREAD

**Issue by MrWolfZ** [cloudfoundry/cloud_controller_ng#625]
## Issue

We encountered a race condition when mapping routes to apps. If we make a call to obtain the app summary for an app immediately after mapping a new route for the app, the app summary will sometimes return -1 as the value for `running_instances`, even though all instances are up and running. Similarly the space summary of the app's space will sometimes return 0 as the value for `running_instances` for that app, although this appears to happen less frequently than the app summary issue.
## Context

Working as a developer for the Swisscom application cloud project. Our application cloud is based on CloudFoundry.
## Steps to Reproduce
1. map a route to an app with `PUT /v2/apps/{appId}/routes`
2. query the app's summary with `GET /v2/apps/{appId}/summary`

Note that since this is a race condition you might need a couple of attempts to reproduce this.
## Expected result

The summary should contain the correct number of running instances instead of -1.
## Current result

Sometimes the app summary will have -1 as the value of the `running_instances` property, even though all app instances are up and running.
## Screenshots

![image](https://cloud.githubusercontent.com/assets/7452411/16224980/d306b71e-37a4-11e6-8a2f-1775347b0d02.png)
![image](https://cloud.githubusercontent.com/assets/7452411/16224988/da6868fe-37a4-11e6-9d6a-eb295b2002f7.png)

**Comment by luan** [comment]
Hi @MrWolfZ,

Sorry about the delay in responding to this. We're having trouble reproducing the issue with the steps provided. Is this still happening for you with latest CF? If so, could you provide us with a little more information on the environment where this happen?

It'd be good to know what exact versions you're running (CF/Diego/other OSS releases) and how many of each job (specifically, cf/api, cf/bridge(nsync/tps), diego/bbs.

Thanks,
Luan

**Comment by michaelxupiv** [comment]
Hey @MrWolfZ ,

We're closing this issue now due to inactivity. Feel free to reopen this issue if you experience problems again.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv

**Comment by nicregez** [comment]
We have just tried to reproduce the issue with the current version of Cloud Controller by using two bash sessions, the CLI and watch app-summary in one while mapping routes to the app in the second.

With this basic setup, we were not able to reproduce the issue.
