### ISSUE TITLE
Question: Is there a possibility to find out the diego cell for an application via the API?

### ISSUE THREAD

**Issue by blinse** [cloudfoundry/cloud_controller_ng#630]
This may not be the correct place to ask this question. Feel free to redirect me and close this issue. 

For monitoring purposes we would like to know for each application in our cloudfoundry installation on which diego cell it is running. Is there a possibility to find this out via the REST API?

Any help is very much appreciated.

**Comment by adowns01** [comment]
Hello @blinse, 

We don't have a way of doing this via the CC API. I recommend asking these types of questions in our open source [slack channel](https://cloudfoundry.slack.com/messages/capi/) for a quicker response.

I recommend asking this question to diego in their [slack channel](https://cloudfoundry.slack.com/messages/diego/). They will have a better idea of how to find out this info.

If you feel like this resolves your issue, please close it. 

Thanks, 
Amelia

**Comment by blinse** [comment]
Hi Amelia,

thanks for the reply and the hint with the slack channel. I will close this issue.

Benedikt

**Comment by michaelxupiv** [comment]
Hello @blinse,

We are going to close this issue now. 

Thanks,
@michaelxupiv & @rizwanreza
