### ISSUE TITLE
Improve error message when JWT signing key verification cannot be performed

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cloud_controller_ng#633]
Thanks for submitting an issue to `cloud_controller-ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Error messaging + logging should be improved when Cloud Controller receives requests signed by an invalid key (note - this does not mean an incorrect key)

## Context

Currently, if the JWT signing key is invalid, any HTTP requests to the cloud controller that contain the `Authorization: bearer <token>` header (signed by the invalid key, and using the invalid public key) will 500 with the message "Internal Server Error". I believe most API failures for the cloud controller return JSON payloads describing the error, and that would be useful in this situation. Additionally, having logging of this key parsing failure would be useful, as no errors were emitted in the cloud controller logs related to these failures.

## Steps to Reproduce

1. Generate a CF manifest to deploy to bosh-lite.
2. Update the `properties.uaa.jwt.verification_key` property, so that `BEGIN PUBLIC KEY` and `END PUBLIC KEY` are now `BEGIN RSA PUBLIC KEY` and `END RSA PUBLIC KEY`.
3. Deploy CF to bosh-lite
4. Use `cf login` to log in
5. Attempt to `cf curl /v2/info`
6. `curl api.bosh-lite.com/v2/info`

## Expected result

Step 4 should log you in, but when attempting to list orgs, return an error indicating there is an issue with your authorization token, and hopefully what that issue is.
Step 5 should fail with an error indicating there is an issue with your authorization token, and hopefully what that issue is.
Step 6 will succeed and show JSON output

## Current result

Step 4 output contains:
```
FAILED
Error finding available orgs
Server error, status code: 500, error code: 0, message:
```
Step five output is:
```
 $ CF_TRACE=true cf curl /v2/info

REQUEST: [2016-06-29T13:24:55-04:00]
GET /v2/info HTTP/1.1
Host: api.system.bosh-lite.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.18.1+a1103f0 / darwin



RESPONSE: [2016-06-29T13:24:56-04:00]
HTTP/1.1 500 Internal Server Error
Content-Length: 21
Content-Type: text/plain
Date: Wed, 29 Jun 2016 17:24:56 GMT
Server: nginx
X-Vcap-Request-Id: 2df4714e-8287-417b-5472-0520716419fc

Internal server error
```

Step 6 works as expected.
 
## Possible Fix

Catch the error caused from the invalid public key, and report it to the user in an error message, perhaps with a detailed error specific to the failure in logs for an administrator to track down?

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by utako** [comment]
Hi @geofffranks,

We've turned this into a feature and have spoken to our PM about prioritizing it. Thanks for bringing this to our attention.

@utako & @thausler786, CF CAPI Team

**Comment by geofffranks** [comment]
Sounds good to me!
