### ISSUE TITLE
removal of version information negatively impacted customers

### ISSUE THREAD

**Issue by gcoon151** [cloudfoundry/cloud_controller_ng#642]
## Issue
removal of version information from VCAP causing major problems to customers who relied on that information. 

Exact change: 
https://github.com/cloudfoundry/cloud_controller_ng/commit/85404a6335d84eab7390ebc914b2a786a23e1604#diff-ecfeb228e252d01109895fbef3dc30c5L35

## Context

Upgraded CF to 235 and customers started opening tickets that the version information is missing from VCAP and that was being used by their apps. 

## Steps to Reproduce

App that reads version information of services from VCAP

## Expected result
app can use vcap to know what version of the service it is using. 

## Current result
see above

## Possible Fix

revert behavior so that service version is consumable from VCAP data. The pivotal story behind this
https://www.pivotaltracker.com/n/projects/966314/stories/109473598 specifically said "-As much v1 code has been removed as possible **w/o changing the api**"

## `name of issue` screenshot

VCAP Version details gone.

**Comment by gcoon151** [comment]
To be clearer. I'm getting the specific before and after output but I'm refering to VCAP_SERVICES

**Comment by SocalNick** [comment]
@gcoon151 As we talked about in Slack, we think you can support this by adding arbitrary data to the [Binding Credentials](http://docs.cloudfoundry.org/services/binding-credentials.html) returned by your services broker.

As you mentioned, this was the result of the story to [remove v1 brokers](https://www.pivotaltracker.com/story/show/109473598) which was [announced in Sept 2015 on the CF-Dev mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/BYNVNVTOI3PGCEP6MHF3A5EYY5UGMLL5/#BYNVNVTOI3PGCEP6MHF3A5EYY5UGMLL5).

**Comment by gcoon151** [comment]
Understand this is closed, but I promised this. VCAP_SERVICES before (at the top/beginning of the array for a service)
 "redis-2.6": [
after
 "redis": [
