### ISSUE TITLE
app_ssh.host_key_fingerprint property should specify required format

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cloud_controller_ng#646]
Thanks for submitting an issue to `cloud_controller-ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

This job property should either specify that the required format is md5, or accept additional formats like SHA256.  Providing example(s) in the job spec would be nice, BOSH lets you specify examples in a job spec the same way you can specify a default value for the property.

## Context

Most people generate the fingerprint using commands like `ssh-keygen -lf /path/to/pubkey`.  This used to output the fingerprint in md5 format, but with newer versions of OpenSSH it will default to SHA256. http://superuser.com/a/929567/207377

**Comment by adowns01** [comment]
Done efdbc4f318c6912cf15eaf187db9dc7686c60092

**Comment by Amit-PivotalLabs** [comment]
Thanks!
