### ISSUE TITLE
"How to Create an App Using V3 of the CC API" wiki page contains stale links

### ISSUE THREAD

**Issue by ardnaxelarak** [cloudfoundry/cloud_controller_ng#647]
## Issue
The [How to Create an App Using V3 of the CC API](../wiki/How-to-Create-an-App-Using-V3-of-the-CC-API) page in this repo's wiki contains links to the old docs (apidocs.cloudfoundry.org) that no longer are there, as opposed to the new docs (v3-api.cloudfoundry.org) to the actual documentation for the v3 API.

## Expected result
Clicking on a (docs) link will take me to the v3 API page for that endpoint

## Current result
Clicking on the (docs) links takes me to the v2 API page to experimental sections that have been removed

## Possible Fix
Update the links

**Comment by SocalNick** [comment]
Thanks @ardnaxelarak !! I fixed them.
