### ISSUE TITLE
handle_local_blobstore.sh cannot create directories

### ISSUE THREAD

**Issue by rboykin** [cloudfoundry/cloud_controller_ng#654]
## Issue

The handle_local_blobstore.sh will not be able to create default directories as it is called from the cloud_controller_ng_ctl/cloud_controller_worker_ctl scripts which are launched from their monit jobs running as user vcap.

## Context

cf-release 239 fresh install

## Steps to Reproduce

cf-release 239 fresh install with local blobstore - cloud_controller_ng job will not complete successfully.  Manually create local blobstore directories and mark as owned by vcap:vcap and job can then complete.

## Expected result

handle_local_blobstore.sh would have been able to create the required directories

## Current result

handle_local_blobstore.sh cannot create directories since it is indirectly running as user vcap:vcap

## Possible Fix

handle_local_blobstore has to be run as root, perhaps from the pre-start script

**Comment by luan** [comment]
Hey @rboykin, 

We just pushed up a commit that should fix the problem you are seeing. The fix will be available in the next cf-release. If you feel that your issue has been resolved, please go ahead and close the issue.  

Thank you, 
@luan & @youreddy, 
CF CAPI Team

**Comment by rboykin** [comment]
Thanks @luan and @youreddy
