### ISSUE TITLE
Doc: `net_info` in detailed stats is undocumented

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#655]
## Issue

The documentation for 'Get detailed stats for a STARTED App' (http://apidocs.cloudfoundry.org/239/apps/get_detailed_stats_for_a_started_app.html) does not mention a `net_info` object, but one is being returned.

## Steps to Reproduce
```
$ cf curl v2/apps/6a5601d5-ae48-4b5c-b440-580b245bb4f0/stats
{
   "0": {
      "state": "RUNNING",
      "stats": {
         "name": "test-application-lclah",
         "uris": [
            "test-application-lclah.xxxx"
         ],
         "host": "x.x.x.x",
         "port": xxxx,
         "net_info": {
            "address": "x.x.x.x",
            "ports": [
               {
                  "container_port": xxxx,
                  "host_port": xxxxx
               },
               {
                  "container_port": xxxx,
                  "host_port": xxxxx
               }
            ]
         },
         "uptime": xx,
         "mem_quota": 536870912,
         "disk_quota": 536870912,
         "fds_quota": 16384,
         "usage": {
            "time": "2016-07-28T09:31:15.164895799Z",
            "cpu": 0.0018390040377131692,
            "mem": 321777664,
            "disk": 170438656
         }
      }
   }
}
```

(Customer Ref: https://github.com/cloudfoundry/cf-java-client/issues/540)

**Comment by thausler786** [comment]
@twoseat,

Thanks for bringing this to our attention!  This field was added unintentionally so we've decided to remove it instead of adding it to the documentation.  This work was done in 7685f6f, so if you continue to encounter the `net_info` field on this endpoint in the future please feel free to reopen this issue.

Best,

@thausler786
CAPI team member
