### ISSUE TITLE
Create Organization Quota Definition fails with unlimited routes and zero (default) total_reserved_route_ports

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/cloud_controller_ng#656]
## Issue

[Create Organization Quota Definition][1] with body fields `total_routes : -1` and omitted `total_reserved_route_ports` (defaulting to 0) fails with:
```
CF-QuotaDefinitionInvalid(240003): Quota Definition is invalid: total_reserved_route_ports Total reserved ports must be less than or equal to total routes.
```

## Context

I'm using API version: 2.54.0 on the latest PcfDev (0.18.0).

## Steps to Reproduce

Issue the following REST call:
```
POST /v2/quota_definitions
```
with payload
```
{   "instance_memory_limit":1024,
    "memory_limit":1024,
    "name":"test-quota-definition-psl3d",
    "non_basic_services_allowed":false,
    "total_routes":-1,
    "total_services":-1
}
```

## Expected result

201 Created, and a payload of a (fully populated) Organization Quota Definition. ([See doc][1].) 

## Current result

400 Bad Request, and the message payload:
```
{  "code": 240003,
  "description": "Quota Definition is invalid: total_reserved_route_ports Total reserved ports must be less than or equal to total routes.",
  "error_code": "CF-QuotaDefinitionInvalid"
}     
```

## Possible Fix

Make special comparisons between fields with special values.

[1]:http://apidocs.cloudfoundry.org/235/organization_quota_definitions/creating_a_organization_quota_definition.html

**Comment by thausler786** [comment]
@Zteve,

I suspect that your problem was taken care of by commit https://github.com/cloudfoundry/cloud_controller_ng/commit/ba7e08230a3448d038f623af26da3cebd93291da in April.  Am I correct in assuming that you are running a Cloud Foundry that hasn't been updated since April?  We were unable to replicate this error running against the current cloud controller.

Given that this issue appears to have been fixed by a specific commit a few months ago, I'm going to close this issue.  Please feel free to reopen it, though, if the problem persists, or if you are running on an updated CF!

Best,

@thausler786
CAPI team member

**Comment by Zteve** [comment]
It is hard for me to run on anything but the latest available PcfDev (18 as reported above) and if that doesn't have the latest Cloud Controller updates, I won't see them.  I'm currently running on PcfDev 19 (2.54.0 API) so I may have better luck. Can you please confirm which level of the API this fix went into, so I can be sure to check it when it becomes available?

**Comment by Zteve** [comment]
The code looks wrong to me, but I may not understand `x < UNLIMITED` when UNLIMITED is -1 and x is (say) 1?

**Comment by Zteve** [comment]
Well, if the fix isn't in 2.54 (currently running in Latest PcfDev 19) then what version _is_ it in? So I don't have to keep testing until it is fixed?

**Comment by SocalNick** [comment]
@Zteve that commit made it into CF-237 / CC 2.56.0. I'll ask our interrupt pair to look into your comment RE: `x < UNLIMITED`.

**Comment by youreddy** [comment]
Hello @Zteve, 

We agree that the logic around this is confusing. We just pushed up a [commit]  (225358a5250f76b71f0d778d8d0b52af7ea07aa2) that will hopefully improve the readability.

As Nick said above, you should not see this in deployments using CF-237/ CC 2.56.0

If you feel that your issue has been resolved, please go ahead and close it. 

Thank you, 
@youreddy & @thausler786  
CF CAPI Team
