### ISSUE TITLE
List all Spaces for the Space Quota Definition has unexplained space_guid parameter

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/cloud_controller_ng#659]
## List all Spaces for the Space Quota Definition has a `space_guid` parameter

It is entirely unclear to what this guid refers. If we are listing spaces, why is there a space_guid mentioned? This parameter doesn't appear to be mandatory, but the example uses it; however the guid specified does not appear in the response.
## Context

Version 214  2.33.0 of the CC REST API
## Possible Fix

Update the doc, or remove the space_guid from the description and the REST call.

**Comment by luan** [comment]
Hi @Zteve,

Thank you for pointing this out. We went ahead and removed it from the documentation as it doesn't really do anything and doesn't actually make sense in that context.

Feel free to close the issue if you think your concern has been addressed.

Thanks,
@luan | @youreddy,
CF CAPI Team

**Comment by michaelxupiv** [comment]
Hey @Zteve ,

Thanks for submitting this issue. The fix is in this [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/8f658473a8d96308338f325d955aabdc2da56655). Closing this issue for now, feel free to reopen if necessary.

Thanks,
CAPI Community - @michaelxupiv
