### ISSUE TITLE
unhelpful error message binding app/instance in different spaces

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cloud_controller_ng#661]
## Issue

POST-ing a service binding between an app and service instance in different spaces fails with:

`{u'code': 10001, u'error_code': u'UnknownError', u'description': u'An unknown error occurred.'}`

 
## Steps to Reproduce

```
cf curl /v2/service_bindings\
            -X POST\
            -d '{"service_instance_guid" : "guid-in-space-a"',\
                        "app_guid" : "guid-in-space-b}'

**Comment by SocalNick** [comment]
@erjoalgo service instances currently cannot be shared across spaces, however, this is a common request and something that we hope to work on in the near future.

**Comment by erjoalgo** [comment]
Just to clarify, this issue is not about asking for the feature of sharing service instances across spaces. It is about making the error message more descriptive. I ran into this issue while automating a bootstrap process and had to some digging to find out what was wrong.

**Comment by aashah** [comment]
Hey @erjoalgo,

This looks to have been resolved after this story: https://www.pivotaltracker.com/story/show/101942182

When we submitted a similar curl, the response now looks like the following:

```
{
   "code": 90003,
   "description": "The app space binding to service is taken: service_instance_guid app_guid",
   "error_code": "CF-ServiceBindingAppServiceTaken"
}
```

We are going to close this issue. Thanks for bringing this up!
CAPI Community Pair - @aashah @rizwanreza
