### ISSUE TITLE
CC API should not return application variables unless requested explicitelly 

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/cloud_controller_ng#662]
## Issue

Currently the CC api will return tall the environment variables defined in the application when retrieving a summary of the space or a application (see below for an example).

This is risky, as the environment variables might contain sensitive information like login passwords, which might result in accidental security leak.

## Context

An example case of an incident that we recently had was:
 * The tenant is running the deployment from a public CI system.
 * In order to troubleshoot a deployment, they added the command `CF_TRACE=true cf apps`
 * that resulted in a debug output including all the credential in environment variables.

## Steps to Reproduce

 1. Map some sensitive information to an app.
 2. Run `CF_TRACE=true cf apps`

## Expected result

All the values of the hash `apps.[*].environment_json` returned by  `/v2/spaces/[guid]/summary`, `/v2/spaces/[guid]/apps` or any other should return `[REDACTED]`.

If the consumer wants to consume the environment variables in clear text, they should execute `cf env <app>` or call `/v2/apps/[guid]/env` explicitly. That will make clear the consumer intentions and avoid accidental leakages.

## Current result

Executing `CF_TRACE=true cf apps` or `CF_TRACE=true cf app <app>`  or calling the endpoints `/v2/spaces/[guid]/summary`, `/v2/spaces/[guid]/apps` will return the environment vars in clear text.

```
$ CF_TRACE=true cf apps
Getting apps in org paas-demo / space sandbox as hector...

REQUEST: [2016-08-11T10:43:23+01:00]
GET /v2/spaces/d58bfc0d-a2e0-4394-91be-915b33d5b422/summary HTTP/1.1
Host: ...

RESPONSE: [2016-08-11T10:43:23+01:00]
HTTP/1.1 200 OK
...
{
  "guid": "d58bfc0d-a2e0-4394-91be-915b33d5b422",
  "name": "sandbox",
  "apps": [
    {
      ....
      "environment_json": {
        "MY_SECRET_URL": "http://user:secret_pa55w0rd@secret-service.com/",
        "RAILS_ENV": "development"
      },
``` 

## Possible Fix

All the values of the hash `apps.[*].environment_json` returned by  `/v2/spaces/[guid]/summary`, `/v2/spaces/[guid]/apps` or any other should return `[REDACTED]`.

If the consumer wants to consume the environment variables in clear text, they should execute `cf env <app>` or call `/v2/apps/[guid]/env` explicitly. That will make clear the consumer intentions and avoid accidental leakages.

**Comment by keymon** [comment]
The client could do some work here: https://github.com/cloudfoundry/cli/blob/master/cf/trace/trace.go#L12

But I am not sure what is the right place.

**Comment by dcarley** [comment]
Corresponding CLI change to consider: cloudfoundry/cli#926

It seems to me that the CLI change would be less intrusive, but the CC change proposed here would be more robust.

**Comment by keymon** [comment]
Any update on this?

I found out that there is a feature flag to disable access to the variables: https://apidocs.cloudfoundry.org/235/feature_flags/get_the_space_developer_environment_variable_visibility_feature_flag_%28experimental%29.html

If the intention is to protect the environment variables, more reason to fix this issue.

Thx

**Comment by SocalNick** [comment]
@keymon we appreciate your concern here, but I'm worried that this would be a fairly major change to the API that Cloud Foundry users have developed against. Would you be ok with me adding this to our plans for the V3 API? We are close to releasing the first endpoint in V3 and think the rest will fall in-line nicely after that.

**Comment by keymon** [comment]
What about adding some protection around the client, as in https://github.com/cloudfoundry/cli/pull/926

**Comment by SocalNick** [comment]
@keymon it appears that was merged?

**Comment by keymon** [comment]
@SocalNick oh, sorry, I did not see that :).

Then it is not a pbm for me if you consider that it is better to simply include it in the new version.
