### ISSUE TITLE
V3 API cannot delete droplet that has been used for running tasks

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry/cloud_controller_ng#663]
## Issue

Using Cloud Controller v238, we are trying to delete a droplet that has been used to run tasks and it fails. Looking at the logs for Cloud Controller we see it is failing because of a DB constraint.

```
{"timestamp":1470678985.0445945,"message":"PG::ForeignKeyViolation: ERROR:  update or delete on table \"v3_droplets\" violates foreign key constraint \"fk_tasks_droplet_id\" on table \"tasks\"\nDETAIL:  Key (id)=(2) is still referenced from table \"tasks\".: DELETE FROM \"v3_droplets\" WHERE \"id\" = 2","log_level":"error","source":"cc.db","data":{"request_guid":"12dd19cf-fe88-4c68-60e8-dfd204f836e7::2cf3ed50-88e3-4e3b-b69e-75b2fb448c66"},"thread_id":47204989037820,"fiber_id":47204988009060,"process_id":6293,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/sequel-4.29.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
```
## Steps to Reproduce

Using V3 API
- Create an app
- Create a package for that app
- Upload the bits for the package
- Create a droplet using the package
- Create a task for the app using the droplet's guid
- Attempt to delete the above droplet
## Expected result

I would expect that this would delete the droplet. Currently we are working around this by deleting the entire app instead but would like to just destroy the droplet.

**Comment by michaelxupiv** [comment]
Hey @bradylove,

Thanks for submitting this issue. We decided to drop the foreign key constraint as part of this [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/24fe87ab9d47ffc4916116e4b8266555a9d5ad88), so tasks retrieve the droplet guid off its own model. The changed was introduced as part of cf-release v245. Closing this issue for now, feel free to reopen this if you feel like we haven't addressed it.

Thanks,
CAPI Community - @michaelxupiv
