### ISSUE TITLE
temporary 404 not found shortly after creating route with a path and after creating a route mapping 

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cloud_controller_ng#667]
After I POST a route and a corresponding route mapping and receive an OK response for both, I expect the route to be available immediately. Instead, I see a delay of up to one minute or more before the route becomes available:

``` sh
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e/notify -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e/notify -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e/notify -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e/notify -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e/notify -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e/notify -XPOST -d 'some-json-payload'
404 Not Found: Requested route ('some-json-payload') does not exist.
$ curl https:/example.com/tenant/de62591d-c607-423c-9279-ba0cdc54140e/notify -XPOST -d 'some-json-payload'
{"response":"8ff25e91-98df-410c-936f-2617e02c6fa3"}
$ curl https:/run.asv-pr.ice.prePOST -d 'some-json-payload'^C
$ ^C
```

Also the delay seems to start after the route is used for the first time.

Is this expected?

I don't see anything about an asyncronous response in either the route creation or route mapping creation:
http://apidocs.cloudfoundry.org/237/routes/creating_a_route.html
http://apidocs.cloudfoundry.org/237/routes_mapping/mapping_an_app_and_a_route.html

I am using a non-empty path, which might make a difference. I haven't heard from others in my team having this issue with an empty path. 

Is it that the router needs time to update a path-based route? In this case, since the request is syncronous, it should block until the route is available, if it is not, it should be documented.

**Comment by erjoalgo** [comment]
Actually, it looks like the app is restarted following route binding. Is this documented somewhere?

**Comment by SocalNick** [comment]
@erjoalgo correct, this 404 is while your app comes up on the platform. Do you know if your CF deployment is using DEA or Diego backend?

**Comment by erjoalgo** [comment]
`diego=false` in the payload for this app. I assume this means my CF is using DEA. 

Do you mean that it is expected for the app to be restarted/restaged after a route is mapped to it?

**Comment by SocalNick** [comment]
@erjoalgo sorry, I meant that if the app wasn't yet started and you mapped a route to it, you would get 404 until the app started. Once the app is started, a route mapped to the app will be available very shortly.

I've just experimented with both DEA and Diego, both backends support mapping routes without downtime.

You can watch this happen by curling the stats endpoint of the app while mapping and un-mapping a route:
```
$ watch "cf curl /v2/apps/$(cf app deadora --guid)/stats"
```

**Comment by michaelxupiv** [comment]
Hey @erjoalgo ,

We are closing this issue now due to inactivity. Feel free to reopen this issue if you experience problems again.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
