### ISSUE TITLE
Wrong variable/config initialisation in VCAP::CloudController::BitsExpiration

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/cloud_controller_ng#670]
## Issue

These two lines seem to be initialising the variables wrong, they should be swapped:
  
https://github.com/cloudfoundry/cloud_controller_ng/blob/4f375ebcc902d50f3a7ca8542f9a31afc9fee5d0/lib/cloud_controller/bits_expiration.rb#L7-L8

It is not a big deal because the default is the same for both.

**Comment by michaelxupiv** [comment]
Hello @keymon,

This issue was fixed as part of this commit: https://github.com/cloudfoundry/cloud_controller_ng/commit/9c8b2ed3

Thanks,
@michaelxupiv & @rizwanreza
