### ISSUE TITLE
Last operation API invoked with stale broker credentials

### ISSUE THREAD

**Issue by smoser-ibm** [cloudfoundry/cloud_controller_ng#672]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.
## Issue

Looking at the latest cloud_controller_ng code, the client's credentials are retrieved at instantiation of the async_job and never retrieved again:  https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/actions/services/service_instance_create.rb#L42  I see the same behavior for service_instance_update and service_instance_delete.  Async job code found here https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/jobs/services/service_instance_state_fetch.rb  Credentials have to be retrieved prior to each call to the service broker.
## Context

see steps to reproduce
## Steps to Reproduce

We have test automation that verifies asynchronous provisions verified the following flow:
1. Issue an asynchronous provision (ie, the broker PROVISION API returned a 202)
2. Wait for the last operation to be invoked 1 time
3. Timed out after 10 minutes
4. At this point we deemed the provision failed (it was still in a "in progress" state)
5. Other testing updated the broker credentials and invoked "cloud-cli update-service-broker" with new credentials
6. Some time later the last operation for the instanced created in 1 was invoked on our broker
7. Broker returns a 401
## Expected result

Scenario should work
## Current result

Scenario doesnt work
## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]
## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by michaelxupiv** [comment]
Hello @smoser-ibm,

We tried reproducing this issue, but were unable to do so. We're a bit unsure what your instructions mean. What we tried was:

1. Have a service broker with an async plan.
2. Start creating a service instance with that async service plan.
3. Update the service broker with a new username/password before the above request completes.

However, for us the service instance finished creating successfully. Is there some step we're missing?

Best,
@jberkhahn @michaelxupiv

**Comment by michaelxupiv** [comment]
The linked commit should prevent this from happening. We're going to close this issue, please feel free to reopen if you continue to experience this.

Thanks,
@jberkhahn & @michaelxupiv
CF CAPI Team
