### ISSUE TITLE
configurable actor name used in events

### ISSUE THREAD

**Issue by mcelep** [cloudfoundry/cloud_controller_ng#681]
## Issue

The actor_name parameter is populated with email when the actor is a _user_. It would be nice to be able to use the username instead of email. 
## Context

In enterprise cloud foundry deployments, often the usernames are populated from a directory service and instead of emails the usernames are used as ids. In such cases, having the email in events and userid everywhere else leads to confusions.
## Possible Fix

The actor_name used in events for users should be configurable  between email and username.

**Comment by SocalNick** [comment]
@mcelep this makes sense. what if we just added another field, like `actor_username`?

**Comment by mcelep** [comment]
@SocalNick , adding that field would be good.

**Comment by SocalNick** [comment]
@mcelep we'll talk about this at IPM to see how much effort is involved.

**Comment by ljfranklin** [comment]
@mcelep we just committed the fix here: f4e10737b752c36059bbd2e2858bf37b12925eb2. We kept `actor_name` as is (contains the email) and added a new `actor_username` which contains the username from UAA. Look for this change in the next release! Closing this issue for now, feel free to reopen if you have any concerns.

Thanks,
CAPI Pair - Lyle and Mike (@michaelxupiv)
