### ISSUE TITLE
Docs for service instance updating and deleting only show the HTTP status code for accepts_incomplete=true

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cloud_controller_ng#684]
## Issue

When doing a PUT or a POST for a service instances, the HTTP status code is documented as a 202 (Status Accepted), but it is only a 202 if `accepts_incomplete` is true, otherwise it is a 201. The documentation does not mention this.

## Steps to Reproduce

`PUT /v2/service_instances/:guid` and check the status code

## Expected result

The documentation describes how the status code changes based on the value of `accepts_incomplete`

## Current result

The documentation claims that 202 is the only possible status code

**Comment by wendorf** [comment]
My description wasn't quite correct. The status code can be 201 even when setting `accepts_incomplete` in the case of a synchronous service.

**Comment by SocalNick** [comment]
@wendorf this was fixed in https://github.com/cloudfoundry/cloud_controller_ng/commit/f0dc8b9d4402614fa9720efdeaa3cf4c64842a58
