### ISSUE TITLE
Invoking PUT /v2/organizations/:guid/private_domains/:pguid with invalid private domain guid return invalid error

### ISSUE THREAD

**Issue by aambati** [cloudfoundry/cloud_controller_ng#686]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.
## Issue

Invoking PUT /v2/organizations/xxx/private_domains/a139635e-1d56-4f55-b19d-44cd3ab1a43f with invalid private domain guid returns invalid error:

 The organization could not be found: a139635e-1d56-4f55-b19d-44cd3ab1a43f

It should have returned:

The private domain could not be found:  a139635e-1d56-4f55-b19d-44cd3ab1a43f

**Comment by thausler786** [comment]
@aambati,

Thanks for bringing up this issue.  I wasn't able to reproduce the exact error message that you received (`The organization could not be found: a139635e-1d56-4f55-b19d-44cd3ab1a43f`).  Could you describe your workflow in more detail so we can replicate the error?

My attempts at replication included:

- Curling against `/v2/test-org-guid/private_domains/bad-domain`.  This returned a 500 error and logged that a `PrivateDomainNotFound` error was thrown.
- `cf share-private-domain test bad-domain` returned `Domain bad-domain not found`, and did not hit the endpoint you described.

Thanks,
@thausler786
CAPI team member

**Comment by michaelxupiv** [comment]
Hey @aambati,

We are closing this issue now due to inactivity. If this problem comes up again, feel free to reopen this issue.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
