### ISSUE TITLE
No supported way of changing the default shared domain

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cloud_controller_ng#688]
## Issue

Currently it looks like there is no way to change the default shared app domain, either from the manifest or CLI.
## Context

The documentation says "There is not technically a default shared domain. If a developer pushes an app without specifying a domain, a route will be created for it from the first shared domain created in the system. All other operations involving route require the domain be specified" (https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#shared-domains)

I checked in our lab deploy and it looks like the one with the smallest id is taken (specifically, the physical row order does not matter: the value of the id column is used)
## Possible Fix
- provide an explicit property in the manifest (e.g. DefaultAppDomain) to specify which of the shared domains is to be used as the default (the specified domain must exist in the list of shared app domains)
- provide a CLI command (probably not needed, also I tend to dislike configurations that are not reflected in the manifest)
- provide some kind of migration script that can perform the change (kinda hackish)

**Comment by SocalNick** [comment]
@CAFxX thanks for the thoughtful feature request. I think your first proposed fix is the most reasonable, although, maybe it's just the first app domain in the list that is used as the default? The tricky thing about manifest properties affecting the API is the domain can always be deleted after the deploy is run.

We currently don't have the bandwidth to tackle this feature request. If we work through the requirement, would you be willing to attempt a PR?

**Comment by CAFxX** [comment]
@SocalNick sorry for the delay, yes we can work on this but first we need to catch up with the most recent upstream version and rollout diego. Once that's done we can work on this (it would be really hard to test otherwise)

**Comment by afeld** [comment]
If anyone else runs into this, @linuxbozo and I just went with option three, and it wasn't _too_ bad. The things in all caps are placeholders.

1. Create a new shared domain.

    ```sh
    # TEMP_NAME can be something arbitrary
    cf create-shared-domain TEMP_NAME
    ```

1. Get the IDs of the old and temp/new domain rows.

    ```sql
    select * from domains;
    ```

1. Do the following is quick succession (required because of uniqueness constraints):

    ```sql
    -- point the routes to the new domain record
    update routes set domain_id=NEW_ID where domain_id=OLD_ID;
    -- remove the old domain record
    delete from domains where id=OLD_ID;
    -- copy the attributes from the old domain record to the new one
    update domains set guid=OLD_GUID, name=OLD_NAME where name=TEMP_NAME;
    ```

There's surely a more bulletproof way to do this, but it worked for us.

**Comment by thausler786** [comment]
Thanks @afeld for the find...looks pretty hacky and maybe dangerous, but I'm glad it worked for you! I'd hate to have to do that in a prod environment.

@CAFxX, if you feel like this issue has been addressed and you have what you need to write the PR, please go ahead and close the issue. We look forward to your contribution!

@thausler786 && @simonleung8, CAPI team members

**Comment by aashah** [comment]
Hey @afeld,

I'm going to close this issue due to inactivity; however, please feel free to re-open the issue if there's further information or help we can provide on the matter.

Thanks!
@aashah, CAPI team member
