### ISSUE TITLE
Doc: `net_info` in detailed stats is undocumented

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#689]
## Issue

https://github.com/cloudfoundry/cloud_controller_ng/issues/655 has returned
## Context

The issue was originally resolved by removing the `net_info` field, but since updating to the most recent version of pcfdev (0.20) it has returned. The issue history in PT (https://www.pivotaltracker.com/n/projects/966314/stories/127270725) isn't clear to me, so I don't know whether the field should be present and hence documented, or not present.
## Steps to Reproduce

`$: cf curl v2/apps/025b2318-d8ed-49cb-a676-5f89d46a88d8/stats`

```
{
  "0": {
    "state": "RUNNING",
    "stats": {
      "name": "test-application-3tbmh",
      "uris": [],
      "host": "10.0.2.15",
      "port": 60002,
      "net_info": {
        "address": "10.0.2.15",
        "ports": [
          {
            "container_port": 8080,
            "host_port": 60002
          },
          {
            "container_port": 2222,
            "host_port": 60003
          }
        ]
      },
      "uptime": 0,
      "mem_quota": 67108864,
      "disk_quota": 536870912,
      "fds_quota": 16384,
      "usage": {
        "time": "2016-09-26 12:22:01 UTC",
        "cpu": 0,
        "mem": 0,
        "disk": 0
      }
    }
  }
}
```

**Comment by thausler786** [comment]
@twoseat,
Thanks for reopening the issue.  Do you know which api version pcfdev0.20 is using? You can find it with the `v2/info` endpoint.

@thausler786 && @simonleung8

**Comment by twoseat** [comment]
Hi folks,

Here's the output from 0.20:
```
   "name": "pcfdev",
   "build": "6b3d78e6e11d546aa62e834e42b205c791216f2f",
   "support": "pcfdev@pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.local.pcfdev.io",
   "token_endpoint": "https://uaa.local.pcfdev.io",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.58.0",
   "app_ssh_endpoint": "ssh.local.pcfdev.io:2222",
   "app_ssh_host_key_fingerprint": "a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.local.pcfdev.io/routing",
   "logging_endpoint": "wss://loggregator.local.pcfdev.io:443",
   "doppler_logging_endpoint": "wss://doppler.local.pcfdev.io:443",
   "user": "9e2c0851-50f2-41e1-8dc8-5d93b4d759e9"
```
And for comparison here's the latest, 0.22, where the same thing still happens (I guess because the api version is still the same)
```
   "name": "pcfdev",
   "build": "75bb79295ca1f99e5ad185f2843b25dc3d735418",
   "support": "pcfdev@pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.local.pcfdev.io",
   "token_endpoint": "https://uaa.local.pcfdev.io",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.58.0",
   "app_ssh_endpoint": "ssh.local.pcfdev.io:2222",
   "app_ssh_host_key_fingerprint": "a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.local.pcfdev.io/routing",
   "logging_endpoint": "wss://loggregator.local.pcfdev.io:443",
   "doppler_logging_endpoint": "wss://doppler.local.pcfdev.io:443",
   "user": "d77dbb41-7b7e-4188-90e6-e9ab64b134af"
```

**Comment by michaelxupiv** [comment]
Hey @twoseat ,

It looks like your deployments are using an old version of Cloud Foundry. The fix from the related issue wasn't put in until CF V241, which corresponds to API version 2.61. It looks like you're using V239, as per the docs [here.](https://apidocs.cloudfoundry.org/239/) (note the CF version / CC_API version numbers).
Maybe you can bring this issue to the PCFdev team. Closing this issue for now, feel free to reopen if you see any other problems.

Thanks,
CAPI Community Pair - @jberkhahn & @michaelxupiv
