### ISSUE TITLE
Enhancement to Add User Change Events API

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cloud_controller_ng#691]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Provide user change events

## Context

Have the ability to query the user based events in a similar fashion to apps, service instances etc.

## Expected result

extend /v2/events to get the list of events that occur for user management.  For example, when a user has a new role added or a role removed.

## Current result

No API to be able to retrieve these event changes.

**Comment by SocalNick** [comment]
@andrew-edgar I've created some stories, I'll try to get them into the backlog shortly:

https://www.pivotaltracker.com/story/show/133060217
https://www.pivotaltracker.com/story/show/133060349
https://www.pivotaltracker.com/story/show/133066399
