### ISSUE TITLE
user messages for application actions

### ISSUE THREAD

**Issue by mcelep** [cloudfoundry/cloud_controller_ng#692]
## Issue

For application actions such as start,stop,restart,scale it would be nice to take messages from actors as input. 
## Context

During the lifetime of an app, it will be started,stopped, scaled up or down by many different actors. In the app events, the actor who triggered the action and some more details about the action such as _state: STOPPED_ is visible yet providing a message(comment) about why this actor decided to trigger this action is not possible.

An example:
`cf stop myApp -m 'stopped due to security issue foobar'`
and this action would lead to creation of an event with a description`state: STOPPED, message: stopped due to security issue foobar`

**Comment by utako** [comment]
Hi @mcelep,

This is an interesting feature. We've brought this to the attention of @SocalNick, the project's PM. 

Thanks,
@utako and @thausler786, CF CAPI Team

**Comment by SocalNick** [comment]
Hi @mcelep 

This is definitely an interesting feature. We have a number of high priority features in our queue at the moment. I'll add this to our someday / maybe list. In the meantime, you may want to try to drum up support for this on the [cf-dev mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/).
