### ISSUE TITLE
service binding http response status code: unique vs. reused credentials

### ISSUE THREAD

**Issue by mcelep** [cloudfoundry/cloud_controller_ng#696]
## Issue

Service Broker API specifies that a service binding response may be a 201 or 200(if the binding already exists). The cloud controller however seems to always to return a 201 for service binding responses and thus obfuscating some potentially valuable information. Cloud controller should propagate the http status code it receives back from service broker 'as is'.

**Comment by SocalNick** [comment]
@mcelep could you describe what a client might do differently when presented with a 200? The Cloud Controller isn't obliged to return the status codes as is from the broker.

**Comment by mcelep** [comment]
@SocalNick, the user should know if the set of credentials he gets are unique or not, as it might have security implications. If the credentials are not unique, even when a binding/service key  gets deleted, the credentials(which can be easily cached) might still continue to be valid (services are not always secured on a network access level).

**Comment by SocalNick** [comment]
@mcelep from the Cloud Controller's perspective, a `POST /v2/service_bindings` will always create a new Service Binding resource so a 201 is appropriate. The broker is responding to a `PUT /v2/service_instances/:instance_id/service_bindings/:binding_id` and can return 201 or 200. The uniqueness of credentials seems unrelated to this workflow.

@avade @shalako am I missing something here?

**Comment by shalako** [comment]
CC will generate a unique id when for each create-binding request to the broker. The only time a broker should return a 200 is if it receives a request to create a binding with a duplicate guid. This should be considered a mitigation of a failure scenario and highly unlikely (orphan created on broker, unknown to CF, or UUID collision). 

From CC's perspective a 200 response results in a binding element being created where it did not exist before. It is appropriate for CC to return a 201 to the client. 

This scenario does not imply that the credentials in the created binding are unique or not, or have been available to client before. Even in this failure scenario, it is likely that while the broker created the binding previously, these credentials were never available through CC or to an app.

**Comment by mcelep** [comment]
I see your point, my concern might probably be better covered by a special field in the binding response json returned by Service Broker.
