### ISSUE TITLE
Missing input validation on security groups

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/cloud_controller_ng#705]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.
## Issue

It is possible for an admin to create and bind a security group that is syntactically invalid.
## Context

If a `destination` field is empty, no error is thrown.  The rule gets applied to applications, and Diego components then log errors and refuse to start the app.
## Steps to Reproduce

Create a file containing this JSON

``` json
    [
        {
            "destination": "10.10.5.68",
            "ports": "60002",
            "protocol": "tcp"
        },
        {
            "destination": "",
            "ports": "8080",
            "protocol": "tcp"
        }
    ]
```

Then run

``` bash
cf create-security-group bad-group /tmp/bad-sec-group.json
```

Observe that the command succeeds:

```
Creating security group bad-group as admin
OK
```
## Expected result

I expect an error, perhaps from the CLI, but definitely from the CC API.

cc: @jaydunk

**Comment by SocalNick** [comment]
Fixed in https://github.com/cloudfoundry/capi-release/releases/tag/1.12.0
