### ISSUE TITLE
cloud controller catches a TERM regularly

### ISSUE THREAD

**Issue by felixfriedrich** [cloudfoundry/cloud_controller_ng#706]
## Issue

monit status shows the `cloud_controler_ng` process having an uptime much less then all other processes shown by monit. The logs confirm the `cloud_controller_ng` process catches a `TERM` signal quite regularly.

`{"timestamp":1477567002.2630692,"message":"Caught signal TERM","log_level":"warn","source":"cc.runner","data":{},"thread_id":47435144442120,"fiber_id":69995232163460,"process_id":28114,"file":"/var/vcap/data/packages/cloud_controller_ng/f87cb49aa2cd87792cb9c2211a79e1542502be4d.1-d3e2f623607ad9c06e28f650628de9a0bf031073/cloud_controller_ng/lib/cloud_controller/runner.rb","lineno":122,"method":"block (3 levels) in trap_signals"}`

It seems this line of code catching the `TERM`.
https://github.com/cloudfoundry/cloud_controller_ng/blob/5f5fa472bd411edd2d60750ac98a80af7f91da53/lib/cloud_controller/runner.rb#L115

The monit config seems to be opinion'ated about how much memory should be consumed:

```
check process cloud_controller_ng
  with pidfile /var/vcap/sys/run/cloud_controller_ng/cloud_controller_ng.pid
  start program "/var/vcap/jobs/cloud_controller_ng/bin/cloud_controller_ng_ctl start" 
  stop program "/var/vcap/jobs/cloud_controller_ng/bin/cloud_controller_ng_ctl stop"
  group vcap

  if totalmem > 3500 Mb for 3 cycles then alert
  if totalmem > 3500 Mb for 15 cycles then exec "/var/vcap/jobs/cloud_controller_ng/bin/restart_drain"
  if totalmem > 3750 Mb for 3 cycles then exec "/var/vcap/jobs/cloud_controller_ng/bin/restart_drain"
  if failed host 10.230.8.109 port 9022 protocol http
      and request '/v2/info'
      with timeout 60 seconds for 5 cycles
  then restart
```

I guess it's monit sending the `TERM` when restarting the process.

I cannot see any negative consequences at the moment, yet I am curious why there are hard limits in the monit config. :-)

**Comment by felixfriedrich** [comment]
I will raise now the thresholds for monit. Any advice is welcome in regards of that values :-)

**Comment by jberkhahn** [comment]
Hello,

This is to guard against memory leaks from crashing the CC over time. However, it shouldn't be restarting too regularly. How often are you seeing it killed and brought back up?

Thanks,
@jberkhahn & @rizwanreza 
CF CAPI Team

**Comment by felixfriedrich** [comment]
I've seen this happening several times an hour. We have peaks over 5 r/s to the API. But usually the requests are lower than 5 r/s. Not too many requests, I guess.

We have 6 api servers and 6 workers. The api servers have 10GB ram each. Quite some of the memory is used for buffering. I guess due to the fact that we use NFS for storing droplets.

```
root@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:~# free -m
             total       used       free     shared    buffers     cached
Mem:         10000       8912       1088          0        228       3056
-/+ buffers/cache:       5627       4372
Swap:         5004          6       4997
```

**Comment by luan** [comment]
Hi @felixfriedrich,

What does the memory usage per process looks like over time? You can see what monit thinks cloud_controller is using via `monit status` or you can see it on the process list using `ps auxww`.

We're also interested in seeing the monit logs to check if monit is actually killing CC because of the memory usage. They should be located at `/var/vcap/monit/monit.log`.

Is there anything else interesting in the cloud controller logs that precede the TERM catching? If you don't mind sharing that log file could also be very helpful for us to debug.

Lastly, which versions are you running here? Is this a vanilla CF? If so which version, otherwise how is this deployed?

Thanks,
@luan & @ericpromislow, CF CAPI Team

**Comment by luan** [comment]
@felixfriedrich When you have a chance could you provide us with that info we requested above?

Thanks!

**Comment by felixfriedrich** [comment]
Since I changed the thresholds for the CC, we don't see that behaviour anymore.

```
  cc:
    thresholds:
      api:
        alert_if_above_mb: 6000
        restart_if_consistently_above_mb: 6000
        restart_if_above_mb: 7000
```

Therefore also the logs don't contain the wanted information anymore.

Here is the `monit summary` anyway:
```
Process 'cloud_controller_ng'
  status                            running
  monitoring status                 monitored
  pid                               2032
  parent pid                        1
  uptime                            20h 14m 
  children                          12
  memory kilobytes                  2633072
  memory kilobytes total            2652740
  memory percent                    25.7%
  memory percent total              25.9%
  cpu percent                       5.2%
  cpu percent total                 5.2%
  port response time                0.008s to 10.230.8.44:9022/v2/info [HTTP via TCP]
  data collected                    Wed Jan 25 09:32:56 2017

Process 'cloud_controller_worker_local_1'
  status                            running
  monitoring status                 monitored
  pid                               1862
  parent pid                        1
  uptime                            20h 15m 
  children                          12
  memory kilobytes                  121572
  memory kilobytes total            142772
  memory percent                    1.1%
  memory percent total              1.3%
  cpu percent                       0.2%
  cpu percent total                 0.2%
  data collected                    Wed Jan 25 09:32:56 2017

Process 'cloud_controller_worker_local_2'
  status                            running
  monitoring status                 monitored
  pid                               1899
  parent pid                        1
  uptime                            20h 15m 
  children                          12
  memory kilobytes                  226996
  memory kilobytes total            246280
  memory percent                    2.2%
  memory percent total              2.4%
  cpu percent                       0.2%
  cpu percent total                 0.2%
  data collected                    Wed Jan 25 09:32:56 2017
```

And this is a screenshot from Grafana. The drops are caused by use redeploying the APIs.

![used-mem-api-24-hours](https://cloud.githubusercontent.com/assets/3330580/22284953/eb943aae-e2e9-11e6-8d78-2bee483e57c7.png)

![Uploading Used-mem-api-24-hours.png…]()

The rest of the memory which is not consumed by the api processes itself is used for caching. We mount the blobstore via NFS, thus Linux used the memory to cache that as far as I understand it.

I will discuss internally if we would lower the values again to get more insight.

**Comment by ljfranklin** [comment]
I wonder if setting the default `thresholds` values should be done as a percentage of available memory rather than a fixed amount. Intuitively I would expect moving to a larger instance size would increase the amount of usable RAM for CC, but you have to know to also increase those `thresholds` fields. Maybe @zrob has thoughts on this.

@felixfriedrich are we good to close this issue? Definitely understand if you don't want to revert a working system into a slightly degraded one. If you see this behavior again, please grab the info [listed here](https://github.com/cloudfoundry/cloud_controller_ng/issues/706#issuecomment-265318272) and we'll dig in a bit more on the memory usage issue.
