### ISSUE TITLE
Support Read-Only Slaves/Writable Master

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/cloud_controller_ng#718]
Sequel supports Read-Only Slaves/Writable Master (http://sequel.jeremyevans.net/rdoc/files/doc/sharding_rdoc.html, but current CloudController is not using it yet (https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/db.rb#L39), could CloudController to support this? this could improve the CloudControler performance dramatically for CloudFoundry production environment with CCDB master/slave cluster.

**Comment by SocalNick** [comment]
@JimmyMa this is an interesting feature, however, our team doesn't have time to prioritize in the near term. Would you consider making a PR to allow these various configurations?

**Comment by cwlbraa** [comment]
we'd probably still accept this as a contribution, but we're going to close this due to inactivity. 

thanks!
