### ISSUE TITLE
Blobstore code retries 3 times on 404 errors.

### ISSUE THREAD

**Issue by stephendotcarter** [cloudfoundry/cloud_controller_ng#729]
## Issue
Blobstore code retries 3 times on `404` errors.
This is inefficient since `404` is a valid error.

## Context
During the `/v2/resource_match` API call the `CC` makes requests to `blobstore` to see if the requested list of files exist.
If `blobstore` returns a `200 OK` the file exists and `CC` returns `true` and moves on to the next file in the list.
If `blobstore` returns a `404 Not Found` the files does not exist but `CC` retries 3 times until finally returning `false`

This is increasing the `cf push` time since `CC` is making 4 x requests for any files that to not exist.

## Steps to Reproduce
Make a request to the resource match API using a random hash that does not exist:
```
cf curl -X PUT /v2/resource_match -d '[{"sha1":"1234567890123456789012345678901234567890","size":65582}
```

I am not sure how to observe this in the logs but from looking at a network trace CC will send total of 4 HTTP head requests (initial + 3 retries)

## Expected result

I would expect if `CC` receives a `404` from the `blobstore` that it would not retry as this is a valid response.

Kind regards,
Stephen

**Comment by thausler786** [comment]
@stephendotcarter,

That does seem like an optimization the the cloud controller should be able to support.  Looking through the code, it looks like we retry for all errors communicating on a webdav client, but only some errors communicating on a fog client.  I just wanted to confirm that you are experiencing this problem on a webdav blobstore.

Best,

@thausler786 && @michaelxupiv, CAPI team members

**Comment by stephendotcarter** [comment]
@thausler786 This issue was noticed when using an Openstack Swift (S3 compatible) blobstore so I believe we use the fog client to connect.
I could also reproduce the same behaviour using the following S3 server:

- https://github.com/scality/S3

Let me know if you need any more info.

Kind regards,
Stephen

**Comment by ljfranklin** [comment]
@stephendotcarter these retries are a bit of a bandaid over eventual consistency errors from AWS S3. If you upload a file to S3, then immediately do a `HEAD` on that file, you'll often get a 404 for a couple seconds. I'm not sure if Swift has the same eventual consistency issues, but eventual consistency is a bit of a pattern for cloud blobstores (S3, Google Cloud Storage).

I'll defer to our PM @zrob about whether to close this, but I'd prefer leaning towards correctness (retry as blobstore might not be consistent) rather than performance (removing retries) especially as we support a wide range of blobstores with varying consistency guarantees.

**Comment by ljfranklin** [comment]
@stephendotcarter I'll dig into this a bit more. While in general we'd like to keep retries on 404, in the specific case of `/v2/resource_match` I agree it just slows things down. We'll see how entrenched our retry logic is and how much effort it would be to not retry in this case.

**Comment by ljfranklin** [comment]
@stephendotcarter I'm having a bit of troubling creating a nice test case for this. What command did you run to get the network trace mentioned in the description?

**Comment by stephendotcarter** [comment]
@ljfranklin I was not aware of the AWS eventual consistency issue so the retry logic might make sense but it looks like we just retry immediately 3 times. That will work if the file becomes "consistent" within the few milliseconds between retries.
Is that shown to correct a good percentage of false positive 404s?

I don't think the retry on 404 is a problem if the blobstore is performant.
In this specific case the OpenStack Swift blobstore was slow to respond, and by slow I mean multiple seconds per request. Thats the only reason I noticed the retires. Maybe the answer in this case is "fix your blobstore".

I captured the trace using `tcpdump` but I am not sure how that will fit nicely in to a test.
I am assuming you need a method to show the number of retries which can be used in a test case?

**Comment by aashah** [comment]
Hey @stephendotcarter,

We looked briefly into all of our blobstore operations and they are tightly coupled with the same retry logic. Refactors aside, we don't believe we will ever be able to differentiate a "true" 404 from one that was simply the result of cache inconsistency.

We're going to close this issue, please feel free to open a new issue.

CAPI Community Pair, @aashah @ScarletTanager
