### ISSUE TITLE
grace_period_seconds

### ISSUE THREAD

**Issue by plfx** [cloudfoundry/cloud_controller_ng#730]
## Issue

Cloud Controller accepts expired tokens with a configurable grace period

## Context

Cloud controller uses UAA access tokens and validates them offline (i.e. without further communication with the UAA). This will produce validity results that differ from the UAA and creates a second standard of when a token is "expired".
https://github.com/cloudfoundry/cloud_controller_ng/blob/654e39c6d22f99e75ba0833236c5e6a3f12ad967/lib/vcap/uaa_token_decoder.rb#L62

## Expected result

A token past its expiry time should be unilaterally rejected.

## Current result

The token will still be accepted

## Possible Fix

If the token expiry needs to be [x] seconds longer than it currently is, configure the token validity to be [x] seconds longer when registering the OAuth client with the UAA.

**Comment by aashah** [comment]
This is intended behavior. The source of this comes from https://github.com/cloudfoundry/cloud_controller_ng/commit/32966365adc3cb7e9ecd3dc031e5a873a0ca59ca on this story: https://www.pivotaltracker.com/story/show/68014448. This was meant to alleviate large file uploads.

If there is a way to mitigate this without this "grace period", we'd be interested in hearing about it.

Thanks,
CAPI Community Pair - @aashah & @michaelxupiv
