### ISSUE TITLE
cloud_controller_clock doesn't properly handle configuration errors

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/cloud_controller_ng#732]
When an error is raised in https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/background_job_environment.rb#L17-L34 the error gets swallowed by event machine and the block just re-executed.

Among other things, this has the negative side effect that it reconnects to NATS in a very tight loop, completely hogging the NATS CPU.

## Steps to Reproduce

Simply add a `raise "Some error"` somewhere in
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/background_job_environment.rb#L17-L34 and restart cloud_controller_clock.

Next, observe how gnatsd uses 100-200% CPU by doing:
    
    $ cd ~/workspace/bosh-lite
    $ vagrant ssh
    $ top

Also enable trace and debug for NATS logging to see the reconnects done by cloud_controller_clock:

```
[3850] 2016/11/29 09:42:08.481040 [DBG] 10.244.0.138:40576 - cid:3380658 - Client connection closed
[3850] 2016/11/29 09:42:08.481056 [DBG] 10.244.0.138:40578 - cid:3380659 - Client connection created
[3850] 2016/11/29 09:42:08.481096 [DBG] 10.244.0.138:40578 - cid:3380659 - Client connection closed
[3850] 2016/11/29 09:42:08.481111 [DBG] 10.244.0.138:40580 - cid:3380660 - Client connection created
```

/cc @suhlig @smoser-ibm

**Comment by zrob** [comment]
@petergtz Since the DEA's will be retired May 23, we will be able to remove NATs from this component.  So we are not going to spend more time on this, but will just remove the NATs client as soon as we can.
