### ISSUE TITLE
After Cloud Controller(CC) reboots, processing is not continued when CC is downed while processing bind service.

### ISSUE THREAD

**Issue by NAGAI-Tsuyoshi** [cloudfoundry/cloud_controller_ng#734]
## Issue
After Cloud Controller(CC) reboots, processing is not continued when CC is downed while processing bind service. 

## Context
The service broker executed processing to Create Binding API(/v2/service_instances/:instance_id/servuce_bindings/:id) and the success is returnd to CC.
When CC is downed(BOSH recreated VM) immediately after Create Binding API returns, processing after this is not done. Even when CC reboots, the processing is not done. 
The Service broker judges that Create Binding succeeded. However, it is judged that CC is not. 
My service broker's instance was not able to be deleted because of this contradiction. 

## Possible Fix
Even if CC is downed, it is necessary to continue the processing since Create Binding API is called. 
The service broker cannot detect CC being downed. CC should recover to this problem.

**Comment by aashah** [comment]
Hey @NAGAI-Tsuyoshi,

We're looking into the issue right now, but we wanted to share a CLI command that might have helped in this situation. `cf purge-service-instance` might have resolved being unable to remove the service broker.

Thanks,
CAPI Community Pair - @aashah & @michaelxupiv

**Comment by aashah** [comment]
Hey @NAGAI-Tsuyoshi,

We agree this was not the best situation, but feel the solution might be larger and better suited as a separate feature (to gracefully process requests shortly received before a redeploy of CC). I'm going to close this issue in light of that.

Thanks,
@aashah

/cc @zrob
