### ISSUE TITLE
Default settings for enable/disable ssh

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/cloud_controller_ng#735]
## Issue

When ssh access is enabled by the operator, it is enabled by default for all apps and spaces and an action from space owner or developers is required to locally disable it.

It would make sense to allow the configuration of the default setting and not having it hardcoded to true.

## Context

according to [the official documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/app-ssh-overview.html#ssh-access-control-hierarchy) there are 3 levels of configuration to enable/disable ssh access to apps running on Diego:
 
- **Entire deployment:** I guess this translates to the configuration property [cc.allow_app_ssh_access](https://github.com/cloudfoundry/cloud_controller_ng/blob/654e39c6d22f99e75ba0833236c5e6a3f12ad967/bosh/jobs/cloud_controller_ng/spec#L522)
- **Space:** cf allow-space-ssh/disallow-space-ssh
- **Application:** cf enable-ssh/disable-ssh
 
It seems that, with the current implementation, there's no way to disable ssh
by default while configuring `cc.allow_app_ssh_access` as true.

It is since the default value of `allow_ssh` for a space is true [1], and
the value of `enable_ssh` for an app becomes true if it is nil
and`cc.allow_app_ssh_access`and space.allow_ssh` is true [2].
[1] https://github.com/cloudfoundry/cloud_controller_ng/blob/f2b4118fb23665d8f021ef2f82de9952c563cddd/app/controllers/runtime/spaces_controller.rb#L12
[2] https://github.com/cloudfoundry/cloud_controller_ng/blob/f2b4118fb23665d8f021ef2f82de9952c563cddd/app/models/runtime/app.rb#L274

## Steps to Reproduce

Set `cc.allow_app_ssh_access` to true

## Expected result

I would like to have another configuration parameter, like `default_app_ssh_access` to choose if the ssh service will be enabled or disabled by default when the operator allows ssh with `cc.allow_app_ssh_access`

## Current result

Currently ssh is enabled on all spaces and applications as soon as the operator sets `cc.allow_app_ssh_access` to true.

## Possible Fix

We are working on a pull request to add the described new configuration parameter on the line already [linked](https://github.com/cloudfoundry/cloud_controller_ng/blob/f2b4118fb23665d8f021ef2f82de9952c563cddd/app/models/runtime/app.rb#L274)

**Comment by aashah** [comment]
Hey @tyyko,

We're going to close this issue in favor of discussing this in the PR (#741).

Thanks,
CAPI Community Pair - @aashah & @michaelxupiv
