### ISSUE TITLE
pps

### ISSUE THREAD

**Issue by ashpc** [cloudfoundry/cloud_controller_ng#742]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

[provide quick introduction so this issue can be triaged]

## Context

[provide more detailed introduction]

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by aashah** [comment]
Hey @ashpc,

Could you please fill out the template to let us know more about the issue.

Thanks,
CAPI Community Pair - @aashah & @michaelxupiv
