### ISSUE TITLE
Remove logger_endpoint from v2/info

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#743]
## Issue

It appears that recent loggregator and template changes means that the `logging_endpoint` in `/v2/info` no longer exists.  Perhaps it should probably be removed from /v2/info?

## Context

Cleanup

## Steps to Reproduce

Note that loggregator.(system_domain) is no longer a registered route.

## Expected result

Not see `logging_endpoint` when viewing `/v2/info`

## Current result

I see `logging_endpoint`

## Possible Fix

Remove it

**Comment by aashah** [comment]
Hey @youngm,

We have been keeping it around since the CLI had not been updated at the time. We checked their backlog and everything looks to be good on their end. We're gonna check in with our PM to see what the best way of removing this would be.

Thanks,
CAPI Community Pair - @aashah & @michaelxupiv

**Comment by michaelxupiv** [comment]
Hey @youngm,

We talked to the CLI team and they are removing loggregator support in their next release, so we should be able to get rid of this endpoint sometime in January 2017. 

Thanks,
CAPI Community Pair - @jberkhahn & michaelxupiv

**Comment by mikexuu** [comment]
Hey @youngm ,

We just pushed a commit to remove the deprecated endpoint (see [story](https://www.pivotaltracker.com/story/show/131008561)). This was mostly blocked by the CLI version and our 6 month grace period. Thanks for submitting this issue, closing this now. Feel free to reopen if you have any other concerns.

Thanks,
CAPI Community - @mikexuu
