### ISSUE TITLE
DB Password written to logs by runner.rb

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#744]
## Issue

It appears that this line of code is writing the db password to the logs: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/runner.rb#L165

Verified against release 248

Here is an example log message:
```
{"timestamp":1481144280.7965875,"message":"db config {:database=>\"mysql2://cc:mypassword@mysql.system_domain:3306/cc\", :max_connections=>25, :pool_timeout=>10, :log_level=>\"debug2\"}","log_level":"info","source":"cc.runner","data":{},"thread_id":47199175667980,"fiber_id":47199214314700,"process_id":23307,"file":"/var/vcap/data/packages/cloud_controller_ng/8c1ec2491124e0bcde0a5f0d268ff02a4b1e722b.1-2e85e8fcc1f6164b59abadcb4c7b8262c9376103/cloud_controller_ng/lib/cloud_controller/runner.rb","lineno":165,"method":"setup_db"}
```

## Context

I see the db password in the logs happens at startup or deploy time????

## Steps to Reproduce

Deploy CC and see the password in the logs.

## Expected result

Not see the password in the logs

## Current result

See the password in the logs

## Possible Fix

Remove the password from the logs

**Comment by aashah** [comment]
Hey @youngm,

Wow, you're right. We probably shouldn't be doing that, that line looks to have been present since 2012. We removed it in commit sha fc1e995.

Thanks!
CAPI Community Pair - @aashah & @michaelxupiv

**Comment by youngm** [comment]
Thanks!

**Comment by SocalNick** [comment]
Fixed in https://github.com/cloudfoundry/capi-release/releases/tag/1.12.0
