### ISSUE TITLE
cloud_controller.admin_read_only scope doesn't retrieve all the info it should for apps/services

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cloud_controller_ng#747]
## Issue

Querying `GET /v2/service_instances/<guid>` with the `cloud_controller.admin_read_only` scope returns service instance info with `space_guid` and `space_url` set to null

Querying `GET /v2/apps/<guid>` with the `cloud_controller.admin_read_only`  scope returns an unknown error.

## Context

When requesting individual apps/service instances by GUID using the CC API using the `cloud_controller.admin_read_only` authority, things do not behave as they do if using the`cloud_controller.admin ` authority

## Steps to Reproduce

1. Create a uaa client with the `cloud_controller.admin` authority, and request a token for it.
2. Retrieve a known app guid from CF
3. Retrieve a known service instance GUID from CF
4. Query CC for app info with admin token:

```
curl -H "Authorization: <admin token>" https://api.system.example.com/v2/apps/<app_guid>
```

5. Query CC for service instance info with admin token:

```
curl -H "Authorization: <admintoken>" https://api.system.example.com/v2/service_instances/<service_instance_guid>
```

6. Create a uaa client with the `cloud_controller.admin_read_only` authority and request a token for it
7. Query CC for app info with admin-read-only token:

```
curl -H "Authorization: <admin-read-only token>" https://api.system.example.com/v2/apps/<app_guid>
```

8. Query CC for service instance info with admin-read-only token:

```
curl -H "Authorization: <admin-read-only-token>" https://api.system.example.com/v2/service_instances/<service_instance_guid>
```

## Expected result

Output from step 4 should match output from step 7.
Output from step 5 should match output from step 8

## Current result

Output from step 7 is 
```
{
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}
```

Output from step 8 is
```
{
  "metadata": {
    "guid": "dc84230b-fc44-44a4-9d6f-2b1815c282dd",
    "url": "/v2/service_instances/dc84230b-fc44-44a4-9d6f-2b1815c282dd",
    "created_at": "2016-10-31T22:07:41Z",
    "updated_at": null
  },
  "entity": {
    "name": "rabbitmq-d4874fab-3dda-4f19-a4e5-2e8eea524adb",
    "credentials": {},
    "service_plan_guid": "665957a9-cca6-4699-b39e-69ba69a90e12",
    "space_guid": null,
    "gateway_data": null,
    "dashboard_url": "https://pivotal-rabbitmq.system.example.com/#/login/mu-dc84230b-fc44-44a4-9d6f-2b1815c282dd-vcmanhdmk6iojckfhdd0lrj8ot/1208307545653054799427391242347139721444",
    "type": "managed_service_instance",
    "last_operation": {
      "type": "create",
      "state": "succeeded",
      "description": "",
      "updated_at": null,
      "created_at": "2016-10-31T22:07:41Z"
    },
    "tags": [

    ],
    "service_plan_url": "/v2/service_plans/665957a9-cca6-4699-b39e-69ba69a90e12",
    "service_bindings_url": "/v2/service_instances/dc84230b-fc44-44a4-9d6f-2b1815c282dd/service_bindings",
    "service_keys_url": "/v2/service_instances/dc84230b-fc44-44a4-9d6f-2b1815c282dd/service_keys",
    "routes_url": "/v2/service_instances/dc84230b-fc44-44a4-9d6f-2b1815c282dd/routes"
  }
}
```
(space_guid + space_url are null)

Other notes - when requesting *all* apps/service_instances with `GET /v2/apps` and `GET /v2/service_instances`, these issues do not occur, they seem to be isolated to the single-intance/app retrieval APIs. Not sure what other APIs might be affected if any.

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by michaelxupiv** [comment]
Hey @geofffranks ,

Thanks for submitting this issue. It seems like this has been fixed as part of this [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/47af1c74aede40b04ebd02ff17651da0c7ba8c39). The fix was introduced in cf-release v247. Closing this issue for now, feel free to reopen if you feel like I haven't addressed your issue.

Thanks,
CAPI Community - @michaelxupiv
