### ISSUE TITLE
Fail to list all Service Plans for a service broker using q=service_broker_guid%20IN%20 filter

### ISSUE THREAD

**Issue by s-bortolussi** [cloudfoundry/cloud_controller_ng#753]
## Issue

Following [api spec](https://apidocs.cloudfoundry.org/249/service_plans/list_all_service_plans.html), it should be possible to list all Service Plans for a service broker using ?q=service_broker_guid<b>%20IN%20</b>... filter (q=filter IN value). However it always returns no result.

## Steps to Reproduce

- GIVEN an existing ```service broker SB1``` with uid 250e38d8-98b6-4901-9178-a87ee34fd7d7

- GIVEN an existing ```service plan P1``` for ``` service broker SB1 ```

- WHEN I list service plans for ```service broker SB1```
```
cf curl v2/service_plans?q=service_broker_guid%20IN%20250e38d8-98b6-4901-9178-a87ee34fd7d7&page=1
```
- THEN I should get ```service plan P1``` -> FAIL: get no result

## Expected result

I should get ```service plan P1```

## Current result

fail got no result
$ {
   "total_results": 0,
   "total_pages": 1,
   "prev_url": null,
   "next_url": null,
   "resources": []
}

## 

Notice, it works fine using ?q=service_broker_guid<b>:</b>... filter (q=filter:value).
```
cf curl v2/service_plans?q=service_broker_guid:250e38d8-98b6-4901-9178-a87ee34fd7d7&page=1
$ {
   "total_results": 2,
   "total_pages": 1,
   "prev_url": null,
   "next_url": null,
   "resources": [
      {
         "metadata": {
            "guid": "a3ea649f-52b1-4f2f-8a91-a3ae5cbaf70a",
            "url": "/v2/service_plans/a3ea649f-52b1-4f2f-8a91-a3ae5cbaf70a",
            "created_at": "2016-06-10T15:21:35Z",
            "updated_at": "2016-12-07T18:52:41Z"
         },
         "entity": {
       
         }
      },
      {
         "metadata": {
            "guid": "55347083-4056-4dc1-89fe-82bf5f3ada10",
            "url": "/v2/service_plans/55347083-4056-4dc1-89fe-82bf5f3ada10",
            "created_at": "2016-06-10T15:21:35Z",
            "updated_at": "2016-12-07T18:52:41Z"
         },
         "entity": {
            "name": "dedicated-vm",
       
         }
      }
   ]
}


```

**Comment by michaelxupiv** [comment]
Hey @s-bortolussi ,

Thanks for submitting this issue. We have added a [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/1199fc4d8a7e0eca3758fe69e1b056a521e4018c) to address it, so the fix should be available in our next release. We are closing this issue for now, feel free to reopen if you feel like we haven't addressed your issue.

Thanks,
CAPI Community - @michaelxupiv

**Comment by s-bortolussi** [comment]
@michaelxupiv Thanks for the fix
