### ISSUE TITLE
find_error needs Ruby to be added to path

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cloud_controller_ng#754]
The instructions at https://github.com/cloudfoundry/cloud_controller_ng/blob/master/scripts/find_error#L3-L12 are no longer totally accurate. Ruby must be added to the path first with something like `source /var/vcap/jobs/cloud_controller_ng/bin/ruby_version.sh`

Should this script just be pre-setup on the VMs? That'd be nice.

**Comment by thausler786** [comment]
@wendorf,

We've fixed the documentation issue in 1474c66, let us know if this is not satisfactory.  

As far as the script being pre-setup on the VM, we accept pull requests!  I'm also adding a chore to our Pantry for this item (story here: https://www.pivotaltracker.com/story/show/136760429).

If this is satisfactory please go ahead and close the issue!

**Comment by wendorf** [comment]
Thanks! I think it'd be even more slick if the sourcing happened for you. See my [coment](https://github.com/cloudfoundry/cloud_controller_ng/commit/1474c66ddec46fc55c684e78fe16f6131bdc7cda#commitcomment-20317283) on the commit.

**Comment by thausler786** [comment]
Added!  Sourcing now happens for you.

@thausler786 && @michaelxupiv
