### ISSUE TITLE
Remove payload from DELETE requests isolation segments

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cloud_controller_ng#755]
Looking at the API docs for [revoking isolation segment entitlements](http://v3-apidocs.cloudfoundry.org/version/3.3.0/index.html#revoke-entitlement-to-isolation-segment-for-one-or-more-organizations), it seems the issue reported in #609 has popped up again.

## Possible Fix

May need some redesign, either make it a PUT (replace) operation where the body specifies the isolation segments that should remain, or a multi-step delete process with the org guid in the url:
```
DELETE /v3/isolation_segments/:guid/relationships/organizations/org-guid-1
DELETE /v3/isolation_segments/:guid/relationships/organizations/org-guid-2
```

**Comment by SocalNick** [comment]
@ScarletTanager want to take a look at this and setup time to chat (or ping me on Slack)?

**Comment by ScarletTanager** [comment]
@SocalNick Yeah, I'll ping you on Slack

**Comment by ScarletTanager** [comment]
This issue will be addressed by this Story: https://www.pivotaltracker.com/story/show/137456833

**Comment by ScarletTanager** [comment]
Created (this PR)[https://github.com/cloudfoundry/cloud_controller_ng/pull/763] to resolve this.  Will close the issue once it has been merged.

**Comment by utako** [comment]
Hey @ScarletTanager,

We've reviewed and merged your PR. 

Thanks!
@utako and @jberkhahn, CF CAPI Team

**Comment by thausler786** [comment]
The PR is in CAPI release 1.16.0
