### ISSUE TITLE
Add audit events for organization lifecycle events

### ISSUE THREAD

**Issue by rossdega** [cloudfoundry/cloud_controller_ng#758]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Provide events for organization creation, deletion, update
## Context

Have the ability to query the organization based events in a similar fashion to space, apps, service instances etc.

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

extend /v2/events to get the list of events that occur for organization management. For example, when an organization is created or deleted.

## Current result

No API to be able to retrieve these event changes.

**Comment by rossdega** [comment]
@ScarletTanager FYI and help

**Comment by ScarletTanager** [comment]
@SocalNick - any objection to my doing a PR for this?

**Comment by SocalNick** [comment]
@ScarletTanager not at all

**Comment by ScarletTanager** [comment]
@SocalNick - I'm assuming I should follow the same pattern used for spaces (e.g. for event types, etc.), substituting "organization" for "space."

**Comment by SocalNick** [comment]
Yep: `audit.space.create`, `audit.space.delete-request`, and `audit.space.update`

**Comment by ScarletTanager** [comment]
I just submitted (this PR)[https://github.com/cloudfoundry/cloud_controller_ng/pull/771].

**Comment by ScarletTanager** [comment]
Correct PR is [here](https://github.com/cloudfoundry/cloud_controller_ng/pull/774).

**Comment by michaelxupiv** [comment]
Hey @rossdega ,

Thanks for submitting this issue. Looks like the PR to record organization audit events has been merged, so closing this for now. If you have any concerns, feel free to reopen this issue!

Thanks,
CAPI Community, @michaelxupiv
