### ISSUE TITLE
Setting env. var without a name breaks app container start

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/cloud_controller_ng#760]
## Issue

Currently, it is possible to set app-specific environment variable without a name: 
```cf set-env myapp '' ''```

This then prevents app containers (also staging container) to start, as garden fails with
```
runc exec: exit status 1: exec failed: setenv: invalid argument
```

This is especially bad for staging, as staging doesn't give user any output (in cf logs myapp --recent) that indicates this. 

As I find no real use of having a nameless env. var set, I think cloud controller should not allow this.

## Steps to Reproduce

```cf set-env myapp '' ''```. then `cf restage myapp` or `cf restart myapp`.

## Expected result

Cloud controller refuses to set empty env. var and returns error.

## Current result

Env. var is set and garden then fails to start container with `runc exec: exit status 1: exec failed: setenv: invalid argument`

## Possible Fix

Don't allow nameless env. vars.

**Comment by michaelxupiv** [comment]
Hey @mtekel ,

Thanks for submitting this issue. This feature was introduced in this [commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/92f499eb7dea418ab4d7eeaf991f9e3279455539), which looks to be part of CF-release v250. Closing this issue for now as it seems to be solved, feel free to reopen if you feel like we haven't addressed it.

Thanks,
CAPI Community - @michaelxupiv

**Comment by ericpromislow** [comment]
testing reopening (and closing) issues.
