### ISSUE TITLE
N+1 queries for apps endpoint in v2

### ISSUE THREAD

**Issue by samu** [cloudfoundry/cloud_controller_ng#762]
## Issue

The `/apps` endpoint on api v2 is slower compared to v3.

## Context

We experienced slow response times from the `/apps` endpoint in v2 compared to v3, while all other endpoints seem to have similar performance. We analyzed the SQL statements when running these two endpoints and found N+1 queries being performed in case of v2. Also, the `droplets` and `packages` references are causing two separate SQL statements each. Here's a SQL dump that is executed for fetching app data for a single entry:

```
(0.000267s) SELECT * FROM "apps" WHERE ("apps"."guid" = '1cfadf5f-d57c-4b03-8531-f9f53add2e5c') LIMIT 1
(0.000229s) SELECT * FROM "buildpack_lifecycle_data" WHERE ("buildpack_lifecycle_data"."app_guid" = '1cfadf5f-d57c-4b03-8531-f9f53add2e5c') LIMIT 1
(0.000511s) SELECT "droplets".* FROM "droplets" INNER JOIN "apps" ON ("apps"."droplet_guid" = "droplets"."guid") WHERE ("apps"."guid" = '1cfadf5f-d57c-4b03-8531-f9f53add2e5c') LIMIT 1
(0.000631s) SELECT "users".* FROM "users" INNER JOIN "spaces_developers" ON ("spaces_developers"."user_id" = "users"."id") WHERE ("spaces_developers"."space_id" = 1)
(0.000529s) SELECT "droplets".* FROM "droplets" INNER JOIN "apps" ON ("apps"."guid" = "droplets"."app_guid") WHERE ("apps"."guid" = '1cfadf5f-d57c-4b03-8531-f9f53add2e5c') ORDER BY "created_at" DESC, "id" DESC LIMIT 1
(0.000480s) SELECT "packages".* FROM "packages" INNER JOIN "apps" ON ("apps"."guid" = "packages"."app_guid") WHERE ("apps"."guid" = '1cfadf5f-d57c-4b03-8531-f9f53add2e5c') ORDER BY "created_at" DESC, "id" DESC LIMIT 1
(0.000261s) SELECT * FROM "packages" WHERE ("packages"."guid" = 'guid-d6b1e05d-bffd-47de-a3a3-a7549479ee30') LIMIT 1
```

## Steps to Reproduce

Run the respective tests and have a look at the sql logs.

v2: 
`bundle exec rspec spec/request/v2/apps_spec.rb:26`

v3:
`bundle exec rspec spec/request/apps_spec.rb:150`

## Expected result

Similar performance of v2 and v3.

## Current result

Inferior performance on v2.

**Comment by thausler786** [comment]
Hey @samu,

Thanks for reaching out. This is expected behavior. As of cf-245, the underlying database schema has changed tremendously to support v3, and as a result v2 endpoints require joining on many more tables than v3 endpoints.

As this performance degradation was anticipated, we'd like to close this issue. Please feel free to reach out if this is prohibiting your workflow, and we can try to work with further you to understand the pain.

- CAPI Community Pair: @thausler786 && @aashah
