### ISSUE TITLE
API Docs (v2) should have anchor links

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cloud_controller_ng#768]
When visiting http://apidocs.cloudfoundry.org/, I sometimes want to link someone to a specific group of docs (e.g. Events). If there were an anchor tag and a clickable link to it (like the "link" icon in GitHub-rendered markdown files), I could link someone to a group of docs.

**Comment by zrob** [comment]
I agree this would be nice to have, any interest in submitting a PR?

@zrob
