### ISSUE TITLE
cloud controller rejects valid service_broker_url

### ISSUE THREAD

**Issue by kirikak2** [cloudfoundry/cloud_controller_ng#775]
## Issue

Hi, Team.
I got a error when I run create-service-broker in cf-cli.

```
cf create-service-broker test-service-broker user password https://xxxxx.com/test_service --space-scoped
FAILED                                                                                                   
Server error, status code: 400, error code: 270011, message: https://xxxxx.com/test_service/ is not a valid URL
```

## Expected result

I think Service Broker URL sometimes have request path which include underscore.
In this patch, It reject valid service broker url which include underscore in request path.

https://github.com/cloudfoundry/cloud_controller_ng/commit/80edd9df92711573865bdebef3c6f15e958c1790

Thanks.

**Comment by zrob** [comment]
Hi @kirikak2 

It looks like that was a workaround for the fact that ruby uri parsing was based on rfc2396 in versions prior to 2.2.0.  In that spec underscores were invalid in hostnames. Ruby uri parsing is now based on rfc3986, which allows underscores in hostnames.

We'll take a swing at fixing this, thanks for reporting the issue.

@zrob

**Comment by michaelxupiv** [comment]
Hey @kirikak2 ,

Thanks for submitting this issue. The commit that fixes this is [here](https://github.com/cloudfoundry/cloud_controller_ng/commit/0166be517db07e2cb03234a65318ea1749b5327d). If you have any concerns feel free to reopen this issue.

Thanks,
CAPI Pair - @michaelxupiv && @jberkhahn

**Comment by kirikak2** [comment]
:+1:
