### ISSUE TITLE
Should cf update-service work from bindable service plan to non-bindable service plan?

### ISSUE THREAD

**Issue by rboykin** [cloudfoundry/cloud_controller_ng#776]
## Issue

Should an existing bindable service instance be updatable to a non-bindable service plan?  To a somewhat lesser extent, should a non-bindable service instance be updatable to a bindable service plan?

## Context

Prior to cf-release v250, the bindable nature of a service was relative to the service, not to individual service plans.  As of cf-release v250, service plans can be set as bindable or not.  This means a plan_updateable service can have two service plans, one bindable and one non-bindable.

## Steps to Reproduce

1. Create a service broker with a plan_updateable service with two plans, one bindable and one non-bindable
2. Create a service instance of the bindable plan
3. Bind an application to the service instance
4. Update the service instance to the non-bindable plan

## Expected result

I would have expected the update service instance to fail since I am trying to change a bindable service instance to a non-bindable service instance.  To compound the problem, in this case I have an application bound to the service instance.  

## Current result

Succeeds.  Now I surprisingly have an application bound to a non-bindable service instance.

**Comment by zrob** [comment]
@rboykin i agree this sounds pretty wonky, is it resulting in any errors for you, or is it just a surprising edge case?

**Comment by rboykin** [comment]
@zrob No errors yet.  But, when we move up to cf-release 250, it could cause some unexpected behavior that in my opinion should be prevented at the CC REST API level.

**Comment by zrob** [comment]
@rboykin does this sound like it would meet reasonable expectations?

1. When `cf update-service` would update from a bindable to a non-bindable plan, it **fails** if there are **existing** bindings.
1. When `cf update-service` would update from a bindable to a non-bindable plan, it **succeeds** if there are **no existing** bindings.
1. When `cf update-service` would update from a non-bindable to a bindable plan, it **succeeds**.

**Comment by rboykin** [comment]
@zrob That is one possibility which is the least restrictive.  

Alternative is to completely disallow moving between a non-bindable and bindable plan and between a bindable and non-bindable plan. 

 Is it considered a requirement to be able to move between bindable and non-bindable plans?  From the point of view of a service broker provider, that also seems "wonky"

**Comment by zrob** [comment]
@rboykin I'm more in favor of the permissive model from CF side and letting brokers choose to accept or fail updates.

I'm going to mark this as open for contribution using my criteria from above in case somebody is interested in PRing this.  I'll also schedule it in the backlog, but it won't be a high priority.

**Comment by zrob** [comment]
Resolved in referenced commit above.
