### ISSUE TITLE
Why does the usage-memory of Java-application  do not decrease

### ISSUE THREAD

**Issue by jiheyangying** [cloudfoundry/cloud_controller_ng#779]
## Issue
In java application, malloc space first and then free them. The memory of application(use command "cf app javademo") will not decrese.

## Steps to Reproduce
1.Make a java application. The function is malloc 100MB buffer and keep the memory space about 5 minutes. Then free and collect these memory space.
2.Push this java application to cloudfoundry. ("cf push javademo ....")
3.Get application memory by command "cf app javademo".
     state      since                    cpu    memory           disk         details   
#0   crashing   2017-02-15 02:17:28 PM   0.1%   476.1M of 512M   131M of 1G      
4.The max of memory is 476MB
5.After 5 minutes , application run method to  free and collect memory.
After running these steps, I found the memory of 476MB didn't decrease.

I'd like to know why memory do not decrease?
I think maybe the value of memory contain the cache,so it shows the max of past records.

thank you very much！

**Comment by zrob** [comment]
@jiheyangying It is normal for many JVMs to allocate heap and then keep it for the duration of its runtime, even if no objects are actually consuming that space.  This allows the JVM to more quickly allocate objects in the future.

For more information you'll want to search the googles regarding JVM heap allocation and tuning.
