### ISSUE TITLE
MEMORY_LIMIT environment variable change during staging on Diego

### ISSUE THREAD

**Issue by opiethehokie** [cloudfoundry/cloud_controller_ng#782]
## Issue

Starting with CF v245 I'm observing that the MEMORY_LIMIT environment variable is set to a minimum of 1G during staging when pushing an app to a Diego cell. Prior to v245, it was set to the amount of memory I allocated to the app like 256M, 512M, etc.

Apps pushed to a DEA continue to have MEMORY_LIMIT set to the app's memory even in the latest CF versions, so it's now different DEA vs. Diego.

## Context

I could be wrong, but I thought that apps have been given a minimum of 1G memory for staging for a long time but that the MEMORY_LIMIT environment variable was still set to reflect the amount of memory they would have at runtime.

## Steps to Reproduce

1. Setup CF v244 and CF v245 on bosh-lite with Diego v0.1487.0.
2. Push a Java app to CF v244, for example https://github.com/IBM-Bluemix/java-helloworld could be used
  i. use 512M memory
  ii. use the buildpack https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack
  iii. set the JBP_LOG_LEVEL environment variable to 'info' and MEMORY_LIMIT is logged during 
staging
3. Enable Diego for the app and restage
4. Repeat steps 2-3 for CF v245

## Expected result

MEMORY_LIMIT environment variable during staging:
- v244 and DEA = 512M
- v244 and Diego = 512M
- v245 and DEA = 512M
- v245 and Diego = 512M

## Current result

MEMORY_LIMIT environment variable during staging:
- v244 and DEA = 512M
- v244 and Diego = 512M
- v245 and DEA = 512M
- v245 and Diego = 1G

**Comment by michaelxupiv** [comment]
Hey @opiethehokie ,

Thanks for submitting this issue. It seems like our current behavior is to return a staging `MEMORY_LIMIT` environment variable that is `max(requested_limit, minimum_staging_limit)`. My understanding is that this has always been our behavior, with `minimum_staging_limit` being the value from your manifest `dea_next.staging_memory_limit_mb` or a default of 1024. I am curious about the `minimum_staging_limit` value in your v244 manifest, maybe it's being overwritten to 512 somehow? Please let us know if this helps.

Thanks,
@michaelxupiv

**Comment by opiethehokie** [comment]
Thanks for the response Michael. Everyone keeps telling me this has always been the behavior so I'm starting to think I'm crazy.

In my v244 manifest `dea_next.staging_memory_limit_mb` is 1024.
In my v245 manifest `dea_next.staging_memory_limit_mb` is 1024.

The 512M was just the memory I pushed my app with, it could be 256M or 768M or whatever and with v244 and older I would have that as my MEMORY_LIMIT during staging.

Is there anything else you can think of that would cause me to see this change in behavior, even if it's just in my manifest? I was following https://github.com/cloudfoundry/diego-release/blob/master/examples/bosh-lite/README.md to try several different CF releases to figure out when it happened (first discovered in v247 in a non-bosh-lite CF that wasn't setup by me), so these are the default manifests that get created.

**Comment by ematpl** [comment]
Is CC changing the memory allocation for a staging task itself to match that BOSH-configured memory limit (or some other minimum)? I'm inspecting this on my BOSH-Lite running the latest CF and Diego release candidates, and when staging the Dora test app from the CATs the staging task itself is allocated 1024 MB of memory, even if I push the app to have, say, 128MB of memory for its instances. (This is straightforward to observe by pushing the app to stage with [my investigation buildpack](https://github.com/ematpl/investigation-buildpack) and then dumping the running Diego tasks with the `tasks` command on the [cfdot](https://github.com/cloudfoundry/cfdot) tool from one of the Diego VMs.) I haven't gone back to try this with CF v244 or earlier to see if the behavior is different.

Thanks,
Eric, CF Diego PM

**Comment by aashah** [comment]
Hey @opiethehokie,

One big change between v244 and v245 was the migration work for the v2 -> v3 api. This included several changes related to how staging values were calculated.

I believe I found one difference with respect to the staging TaskDefinition's `memory_mb`. In v244, this value was calculated roughly as: `max(requested_limit, minimum_staging_limit)`, and as a correction to a prior comment, `minimum_staging_limit` was calculated directly from `staging. minimum_staging_memory_mb`. In v245, we still took a maximum, but `minimum_staging_limit` was calculated as: `staging. minimum_staging_memory_mb OR 1024`.

That said, I wanted to make sure that the discrepancy you're observing is specifically the `MEMORY_LIMIT` environment variable, is that correct? I'm currently looking into whether there was a change in how that environment variable was passed in, just wanted to update on a different part of this issue.

- Aakash

**Comment by opiethehokie** [comment]
Hey @aashah, thanks for the update. The discrepancy I'm observing is specifically the `MEMORY_LIMIT` environment variable and not how much memory is actually available during staging (Diego only).

Based on what you're saying, if I'm requesting, say, 386M and seeing `MEMORY_LIMIT` set to that in v244, then my `minimum_staging_limit` could maybe have been unset. In v245 if it's unset I get 1024 which seems to match up with what I'm seeing.

I guess the question then becomes, how can I configure this? The only thing I see in my manifest is `dea_next.staging_memory_limit_mb` and that's already set to 1024.

**Comment by aashah** [comment]
Hey @opiethehokie,

We took another deep dive into figuring out what changed between 244 and 245.

DEAs never seemed to respect `dea_next.staging_memory_limit_mb` (in 244, 245 and beyond), seems to be a pretty blatant bug.
For Diego, 245 seems to have the correct behavior in ensuring the memory is not below `dea_next.staging_memory_limit_mb`. 

If you actually wanted 512M, you'd want to set `dea_next.staging_memory_limit_mb` to something low such as 0. We are unsure why 244 allowed `MEMORY_LIMIT` to be lower than the property's value.

As this is expected behavior, we don't see any potential changes to the code. Please feel free to keep the questions coming!  We can certainly explore this discrepancy in what 244 ought to have done, if you think this should have been expected behavior. Otherwise, please close if you feel like we have reached a consensus.

@aashah & @ScarletTanager
CAPI Community Pair

**Comment by opiethehokie** [comment]
I really appreciate you investigating. Since the current behavior is the intended behavior I'll close this.

**Comment by zrob** [comment]
I am able to reproduce this as a change in behavior, reopening to take another look.

**Comment by michaelxupiv** [comment]
@opiethehokie @zrob ,

We took another look at CF v244 and traced how we were sending staging requests to Diego. 
When we create the staging request, the environment variable `MEMORY_LIMIT` uses `process.memory` (as shown [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/a79b5588345bac8f1f2f7d05e06c05ef8666bb0c/lib/cloud_controller/diego/environment.rb#L17). `process.memory` is specified using `-m` when pushing an app.
However, in the same staging request, `staging_request.memory_mb` uses `max(process.memory, minimum_staging_memory_mb)`, where `minimum_staging_memory_mb` is the limit specified in manifest property`dea_next.staging_memory_limit_mb`. This behavior is shown [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/a79b5588345bac8f1f2f7d05e06c05ef8666bb0c/lib/cloud_controller/diego/protocol.rb#L29). 
In your case, this explains why the environment variable shows 512MB, but the `staging_request.memory_mb` field would still be different and defaulted to 1024.

In CF v245,  we build the environment variables in staging request using [StagingMemoryCalculator](https://github.com/cloudfoundry/cloud_controller_ng/blob/1077b959f9472a5614f44739cdf130b16ca12a81/lib/cloud_controller/backends/staging_memory_calculator.rb#L7). And the behavior in CF v245 is to use the same memory_mb calculation in the staging request as well as the staging request's `MEMORY_LIMIT` environment variable. This explains why you are seeing different values for the environment variable over the two versions.

Let us know if this helps!
@michaelxupiv && @ericpromislow

**Comment by zrob** [comment]
@opiethehokie can you share what you use the MEMORY_LIMIT for?

currently it correctly represents the memory available for the staging process.  it does not represent the expected memory for the running process.

**Comment by opiethehokie** [comment]
@zrob We were using it during staging to calculate JVM settings like heap size for runtime, where the heap size would be a fraction of the expected memory for the running process.

**Comment by zrob** [comment]
So in that case you would prefer the runtime memory which was part of the previous behavior. 

I'm fairly skeptical of using information from staging to determine the running behavior. App scaling  would cause this to be pretty unreliable if exact numbers matter.  Has this change caused strange behaviors in apps?

**Comment by opiethehokie** [comment]
Doing the memory calculations during staging has caused some confusion because a restage is needed after scaling the memory up or down and with all the other buildpacks that I know of (including the java buildpack) a restart is all that's necessary, so yeah when people don't know this they can end up with strange behavior.

I think that's a valid enough reason for us to move the buildpack's memory calculations to runtime. It was good to get to the bottom of what happened, though, and understand that the current behavior really is the desired behavior. Thanks for investigating.
