### ISSUE TITLE
Filter problem on List all Service Plans for the Service

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#788]
## Issue

The `service_broker_guid` filter described in the [docs](https://apidocs.cloudfoundry.org/252/services/list_all_service_plans_for_the_service.html) gives the error "org.cloudfoundry.client.v2.ClientV2Exception: CF-BadQueryParameter(10005): The query parameter is invalid: service_broker_guid"

## Context

I'm currently integration testing the services functionality in the cf java client. All filters on the endpoint above are valid except for `service_broker_guid`, which gives the error.

## Steps to Reproduce

1. Find a valid service id
2. cf curl v2/services/0b6fc13d-831d-4360-8a6e-1aebce900f18/service_plans?q=service_broker_guid%20IN%20385d43d9-6b3a-461b-844b-2f2021a96e6c
3. Error
```
{
   "code": 10005,
   "description": "The query parameter is invalid: service_broker_guid",
   "error_code": "CF-BadQueryParameter"
}
```

## Expected result

Filtered by service broker id.

## Current result

Error

## Possible Fix

Remove filter from documentation, or implement it.

**Comment by ScarletTanager** [comment]
@twoseat - we looked at this and verified that the docs are, in fact, wrong.  We are adding tests for the other parameters and removing `service_broker_guid` from the list of accepted parameters for that path.

Thanks,

@ScarletTanager & @ericpromislow, CF CAPI team
