### ISSUE TITLE
Get a better error when attempting to map a route owned by another space

### ISSUE THREAD

**Issue by thecircularboard-engineering** [cloudfoundry/cloud_controller_ng#789]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Attempting to map a route which is controlled by another space (under the same org) gives a 400 error with a confusing message (Server error, status code: 400, error code: 210003, message: The host is taken: mandala)

When attempting to promote our staging app to production, we ran into this error. Additionally, attempting to hit the requested route in a browser returned a 404, indicating that the route was not actually in use.

In this case, the solution was to delete the route in the staging space and then mapping it was successful.  A nicer error message would have helped diagnose this problem quicker!

**Comment by aashah** [comment]
Hey @thecircularboard-engineering,

Thanks for opening this issue. It seems to be a popular one. I picked up the work for this via a different issue (cloudfoundry/cli#977). I believe it will address this issue as well, and am going to close this issue in favor of the discussion that has happened in the other.

Story: https://www.pivotaltracker.com/story/show/138649897

Thanks!
