### ISSUE TITLE
Cloud Controller API does not use UAA user_ids - uniqueness of users is not guaranteed.

### ISSUE THREAD

**Issue by Essenpreis** [cloudfoundry/cloud_controller_ng#790]
## Issue
Hi experts. We have a tricky issue. In our UAA deployment we have two SAML IDPs trusted. Both contain users having the same e-mail address. Let's say peter@company.com. Now we have an external tool that provisions the access-controls lists. We want peter@company.com of IDP 1 to be space developer where peter@company.com   of IDP 2 should be space auditor. Our finding: Cloud Controller permission provisioning API (One example is https://apidocs.cloudfoundry.org/252/organizations/associate_user_with_the_organization_by_username.htm) Does not have a field like "origin" or that it would allow UAA user_ids (a 36 character UUID (universally unique identifier))

We can only supply peter@company.com but upon logon it seem the first entry of UAA is taken.
https://github.com/cloudfoundry/cloud_controller_ng/blob/052be00bef97ec6dacf094fcb00e4485278881cf/lib/cloud_controller/uaa/uaa_client.rb#L50
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/controllers/runtime/organizations_controller.rb
https://github.com/cloudfoundry/cloud_controller_ng/blob/bad1db0740fbdded616d8100da6a8853f7045744/app/controllers/runtime/organizations_controller.rb#L138-L156
https://github.com/cloudfoundry/cloud_controller_ng/blob/bad1db0740fbdded616d8100da6a8853f7045744/app/controllers/runtime/organizations_controller.rb#L276-L287
How can we make sure the right peter@company of the right IDP is considered?

It seems that CC API is considering username instead of user_id. 

Example: https://apidocs.cloudfoundry.org/252/organizations/associate_user_with_the_organization_by_username.html   gets {
  "username": "user@example.com"
}

## Context
As given above. It's natural to have a

## Steps to Reproduce
Call an API that takes a user name, e.g. https://apidocs.cloudfoundry.org/252/organizations/associate_user_with_the_organization_by_username.htm and assign a role.

## Expected result
It should be possible in CC to exactly sp

## Current result
it seems the first user in the list is returned.

## Possible Fix
Instead of using user_names, UAA user_ids should be possible to be supplied - see Filip Haniks comment: https://cloudfoundry.slack.com/archives/uaa/p1489442026902371

**Comment by zrob** [comment]
@Essenpreis take a look here http://apidocs.cloudfoundry.org/253/organizations/associate_user_with_the_organization.html

does that help your use case?

**Comment by sashoz** [comment]
@zrob that API would work in that particular case, however, it does not solve the issue in a consistent way, e.g. _"cf set-org-role"_ command accepts also just the username and there is no guarantee which userID would be assigned.

**Comment by Essenpreis** [comment]
+1. Yes. It's an issue that covers many aspects and APIs.

**Comment by zrob** [comment]
@dkoper 

Should we consider an alternative cli workflow?  We have the APIs available to support this, but the cli would need to be able to select the correct uaa-id and not make the association by username.

**Comment by cnelson** [comment]
+1 We have a configuration we can't change due to external factors where different IDPs provide different LOAs for the same users.  It's very hard for users to ensure they are adding the right IDP-backed account when using the cf-cli

**Comment by dkoper** [comment]
Late to the party - missed the github notification..

@Essenpreis In your scenario, is IDP 1 used for users in one org and IDP 2 for users in another org?
In other words, are "peter" with IDP 1 and "peter" from IDP 2 different people and part of different orgs (and just happened to share the same username)?

If so, at least for where a SpaceManager or OrgManager assigns roles using the cf CLI, we could assume that the user being assigned has the same origin as the user running the command and pick the right origin that way, without the user needing to know about the origin and needing to provide it explicitly on each CLI call.

I understand this would not be a solution for admins, but I imagine in a corporate environment with multiple IDPs you would have an external tool like you said that uses the APIs directly to administer roles and not have admins doing this manually with the CLI?

**Comment by Essenpreis** [comment]
@dkoper 
As I understand you want to derive the org/origin from the user issuing the commands. Interesting. Let me first describe my scenario in detail and why we have it.

In my scenario usually the IDPs come from different orgs. I used the example just for illustration.
Here's our setup. where we have the issue of having the same username for two origins for same human person in the UAA coming from two origins. Here's how. Ultimately the Active Directory is our primary user store. 
1. SAML Login via browser - We configured our IDP against AD and the UAA trusts the IDP. So peter  gets his SAML assertion with a subject peter@company.com.
2. LDAP Login for username/password flow in the cli (cli does not support SAML). We configured UAA directly against AD. Peter logs on with peter@company.com

With this we have two peter@company.com users in the UAA database and with the cli commands there should be a way to assign roles like SpaceManager to them.
Still I think the example of having the same user in two different IDPs is valid in real life.


Now assuming Peter (origin LDAP) logged on via CLI. If he runs an command to assign roles the peter of origin LDAP will be modified. The one coming from SAML will not be modified. There's pros and cons into this.

Pro
- Easy to use and less complexity the user needs to deal with
Contra
- User does not know which origin he/she assigned permissions to. I rate this as an issue.

So all in all the question is if it would not be better to ask the user interactively for which origin he/she wants to assign the permissions to.  And this interactive mode would only occur if there's a duplicate. If there's no duplicate the command would just go through.

For automated external tools (as we have them) the origin always must be specified. If they don't maybe code works with first origin. Then another origin with duplicate users come and code breaks. Don't know how to enforce this.

**Comment by sreetummidi** [comment]
I have a follow up question. Since the same user can log in both via the browser and the CLI which results in two accounts. How are both these accounts associated with CF roles. 

Dies and I had a chat yesterday and we felt that this configuration is not a standard occurrence with other CF deployments. In order to fix the immediate security issue, we will start with displaying the error in the CLI stating that two users are present and the next step is to use the cf curl command and pass the origin. 

Is that an acceptable solution?

**Comment by Essenpreis** [comment]
Yes, this solution fits. So user will be asked to provide the origin in case of duplicates and only in case of duplicates.

**Comment by zrob** [comment]
@Essenpreis 

As of capi-release 1.45.0 we now support supplying origin when assigning users.

See [here](http://apidocs.cloudfoundry.org/280/organizations/associate_auditor_with_the_organization_by_username.html) for an example of assigning a user.
See [here](http://apidocs.cloudfoundry.org/280/organizations/remove_auditor_from_the_organization_by_username_experimental.html) for an example of removing a user.

If this does not resolve your concerns, then please re-open this issue.

**Comment by Essenpreis** [comment]
@zrob. 
Hmm. I am more concerned about the actual login when two users e.g. have same e-mail address and if in this case cloud controller would just select the first one.

Is this fixed as well?

**Comment by zrob** [comment]
@Essenpreis 
login is done completely via the UAA and it handles this case correctly.

you can not log in to another user acct with your own password
