### ISSUE TITLE
service_bindings corrupts values containing %

### ISSUE THREAD

**Issue by adborden** [cloudfoundry/cloud_controller_ng#796]
## Issue

The `/v2/service_bindings` endpoint will mangle values containing the `%` character. In some cases, this can result in invalid JSON. It resembles a string format call with missing argument values.

## Context

My user provided service contains the string `"hello%world"` which becomes `"hello%!w(MISSING)orld"`. The value is fine when read from the application and `cf env app`.

Here's a snippet from the response:
```
{
      "metadata": {
        "guid": "9bdbffd9-48fe-49a8-8edc-1a00f3788150",
        "url": "/v2/service_bindings/9bdbffd9-48fe-49a8-8edc-1a00f3788150",
        "created_at": "2017-03-21T16:43:20Z",
        "updated_at": "2017-03-21T16:43:20Z"
      },
      "entity": {
        "app_guid": "65935225-ba35-4f86-bcc3-0467218baea7",
        "service_instance_guid": "53f1f12d-9563-481d-93d9-b79af96d48fd",
        "credentials": {
          "secret": "hello%!w(MISSING)orld"
        },
        "binding_options": {

        },
        "gateway_data": null,
        "gateway_name": "",
        "syslog_drain_url": "",
        "volume_mounts": [

        ],
        "app_url": "/v2/apps/65935225-ba35-4f86-bcc3-0467218baea7",
        "service_instance_url": "/v2/user_provided_service_instances/53f1f12d-9563-481d-93d9-b79af96d48fd"
      }
    }
```

If the `%` occurs at the end of the value, this will result in invalid JSON being returned:
```
{
  "secret": "helloworld%"!(MISSING),
}
```

## Steps to Reproduce

Create a user provided service containing `%`.

    $ cf cups my-service -p '{"secret": "hello%world"}'

Bind the service to an app.

    $ cf bind-service my-app my-service

Hit the service_bindings endpoint.

    $ curl 'https://api.fr.cloud.gov/v2/service_bindings' | grep hello

## Expected result

Valid JSON response with un-modified string `"hello%world"`.

## Current result

String is mangled: `"hello%!w(MISSING)orld"`

**Comment by aashah** [comment]
Hey @adborden,

What version of CF is this happening on?

We were unable to reproduce this with the steps provided above. Using the most recent code from the master branch, we correctly saw `hello%world` in the call to `/v2/service_bindings`.

Thanks,
CAPI Community Pair @aashah & @jenspinney

**Comment by adborden** [comment]
Thanks for looking into it. We have a thin proxy in front of our API and it looks like that's where the problem is, thank you!
