### ISSUE TITLE
500 Internal Server Error when invoking 'cf apps' while deleting apps

### ISSUE THREAD

**Issue by marwinski** [cloudfoundry/cloud_controller_ng#799]
## Issue

Please find the full description in issue #717. It appears that the bug is not fixed. "cf apps" randomly fails when invoked while applications are deleted. The original problem was labeled with "cf services" but it was the "cf apps" part that was invoked by "cf services" that failed. 

## Context

See issue #717

## Steps to Reproduce

Push some apps

    #!/bin/bash

    for i in `seq 1 50`; do
       cf push hello-node-$i --random-route
    done

Deletion of apps:

    #!/bin/bash

    for i in `seq 1 50`; do
       cf delete hello-node-$i  -f -r
    done

Invoke throughout cf apps:

    #!/bin/bash

    for i in `seq 1 1000`; do # Can be any high number, should run until the deletion is finished
       cf apps >apps-$i.log
    done

This will cause most invocations to succeed but some do fail:

    Getting apps in org trial / space dirk as dirk...
    FAILED
    Server error, status code: 500, error code: 10001, message: An unknown error occurred.

## Expected result

No failured 

## Current result

see above

**Comment by zrob** [comment]
@marwinski 

Thanks for reporting this issue.  It should have just recently been resolved here https://github.com/cloudfoundry/cloud_controller_ng/pull/793
