### ISSUE TITLE
Paginated Events API response next_url value does not work in v2 API calls

### ISSUE THREAD

**Issue by dave-malone** [cloudfoundry/cloud_controller_ng#803]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Events API next_url value does not work, as it seems to contains invalid parameters.

## Context

Running this command against PWS. `cf api https://api.run.pivotal.io`

## Steps to Reproduce

`cf curl "/v2/events?order-by=timestamp&order-by=id&order-direction=asc&page=2&q=type:audit.app.update&results-per-page=50"`

## Expected result

Using the `next_url` value returned from paginated `/v2/events` response brings me to the actual next page of results

## Current result

`cf curl /v2/events?q=type:audit.app.update`

Obtain the `next_url` value from previous result, and use that value to run the next `cf curl` command. Example:

```cf curl "/v2/events?order-by=timestamp&order-by=id&order-direction=asc&page=2&q=type:audit.app.update&results-per-page=50" 
{
   "description": "Cannot order by: id",
   "error_code": "CF-OrderByParameterInvalid",
   "code": 10012
}
```

## Possible Fix

Remove `order-by` parameters, and any other unsupported parameters, from the server-side generated `next_url` value in paginated responses.

**Comment by aashah** [comment]
Hey @dave-malone,

Thanks for opening this issue. An internal team also noticed this and we have an existing story for this: https://www.pivotaltracker.com/story/show/142107213

I'll check with our PM (@zrob) about which one he'll prioritize!

Thanks,
CAPI Community Pair - @aashah
