### ISSUE TITLE
Task Containers incorrectly overwrite `DATABASE_URL`

### ISSUE THREAD

**Issue by zaksoup** [cloudfoundry/cloud_controller_ng#804]
## Issue

**This is not urgent as there is a simple workaround.**

When using `run-task` the container created does not correctly set the `DATABASE_URL` environment variable: 
* If `DATABASE_URL` is unset by the user and there is no service binding, the container will have `DATABASE_URL` present, but null.
* if `DATABASE_URL` is set by the user, but not a service binding, the container will have `DATABASE_URL` present, but null.
* if `DATABASE_URL` is set by the user, and there *is* a service binding, the container will provide the service binding as the value.

## Context

When attempting to deploy a rails app with an external database service and use a CF Task to run migrations the rails app will successfully connect to the external database given a `database.yml` but the migrations will fail.

Rails also seems to have a misbehavior here: it always uses DATABASE_URL if the variable is present on the system, even if `database.yml` contains conflicting info.

## Steps to Reproduce

deploy a rails app that expects `DATABASE_URL` to contain the info about the external database service.

use `run-task` to run migrations. Watch the app come up and *connect to the database* but return 500s because expected tables do not exist. Watch the migration fail.

### Simpler steps to reproduce

Using the ruby buildpack push ANY app and set `DATABASE_URL` via the `cf set-env`. Use `cf ssh` and run the `env` command to see that it has the proper value.

run `cf run-task 'env'` and see that DATABASE_URL is set to `''`.

## Expected result

After manually setting `cf set-env DATABASE_URL` the result of `cf run-task 'env'` should show the value provided in `set-env`.

## Current result

The value of `DATABASE_URL` in `cf run-task` containers is `''`

## Workaround

Using `cf run-task 'DATABASE_URL bundle exec rails db:migrate` correctly provides the variable to rails and overwrites the incorrect system env var.

**Comment by zrob** [comment]
resolved in this commit https://github.com/cloudfoundry/cloud_controller_ng/commit/3240642036b5fa8e751e5d9b90ace60115e3686c
