### ISSUE TITLE
API endpoint goes down randomly

### ISSUE THREAD

**Issue by KshitijaRadke** [cloudfoundry/cloud_controller_ng#807]
## Issue

We are using Pingdom in order to monitor our CF API endpoint, and pingdom reports that the API endpoint is switching states randomly. Attaching the report for the same.

## Context

We have CF v254 running on AWS. All the VMs are running according to bosh. Upon SSHing onto the API VM we didn't find any error logs onto the API. The only log file which gets regularly updated is cloud_controller_ng.log. We have API running in HA. We are also monitoring other CF endpoints like Login server, UAA server, Application pool. There is zero downtime for these components.

We have another environment with similar configuration running on CF v254. However the API endpoint is very stable for that particular environment according to pingdom.

Both our environments are running in same AWS region.

## `name of issue` screenshot
![api_down](https://cloud.githubusercontent.com/assets/7641157/25127860/26fdf358-2455-11e7-8446-5d6986a39007.PNG)

![bosh_vms](https://cloud.githubusercontent.com/assets/7641157/25128043/e49d113c-2455-11e7-9b0d-1bad11fd4baa.PNG)
![l_b6aa tmp](https://cloud.githubusercontent.com/assets/7641157/25128373/29180708-2457-11e7-8ee2-dde650df5600.PNG)

**Comment by nicregez** [comment]
Hello @KshitijaRadke 

Thanks for reporting issues here. To understand the precise nature of the issues you encounter and be able to analyze further, please provide us more details, such as:

1. What is the exact request you are sending from pingdom? Is is the same for both environments?
2. What is the exact response when the pingdom tests fail?
3. Are you also using a HA/load balancer setup in the environment which is always up?
4. Are the endpoints which are always up (login, uaa, apps) also routed over load balancers? Are they using an analogous configuration on the load balancers, like retry-on-error or similar options?

Regards
Mike & Nic

**Comment by zrob** [comment]
closing due to inactivty.

@KshitijaRadke if you are still having issues with this, please consider reaching out to the [mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/) or visiting the [CAPI team on slack](https://cloudfoundry.slack.com/messages/C07C04W4Q/)
