### ISSUE TITLE
Doc: `detected_buildpack_guid` is undocumented for Get Space Summary

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#809]
## Issue

The `detected_buildpack_guid` field is undocumented for Get Space Summary

## Context

The `detected_buildpack_guid` field is not mentioned on https://apidocs.cloudfoundry.org/253/spaces/get_space_summary.html, but is returned (in line with, for example, Get Application Summary, where it is documented)

## Steps to Reproduce

* Push an app to a space
* ` cf curl /v2/spaces/<spaceId>/summary`

## Possible Fix

Add field to doc

**Comment by ericpromislow** [comment]
Fixed in https://github.com/cloudfoundry/cloud_controller_ng/commit/82d5daa01c5637d547bf7e7ea65d4fd58e60215c

Thanks for reporting this.

Eric Promislow, CAPI Community Response Center
