### ISSUE TITLE
Remove resources from /appguid/bits body params if resources values is empty

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry/cloud_controller_ng#810]
Using `python requests library`. A put payload including form data as part of files data result in `Too many values to unpack`
```
data = {'application': open(filepath, 'rb'), 'resources': []}
```

using `python requests library`. A put payload including files data without `resources` form data raised `{"code": 160001, "error_code": "CF-AppBitsUploadInvalid", "description": "The app upload is invalid: missing :resources"}` from CF
```
data = {'application': open(filepath, 'rb')}
``` 

It'll be nice if `/appguid/bits` handler can separate the sent data between a payload that contains the binary and a payload that contains form data. For example:
Instead of:
`data = {'application': filepath, 'resources': []}`
I think this is more appropriate for http client libraries:
`file = {'application': filepath}`
`data = {'resources': []}`

**Comment by charyorde** [comment]
Alternatively, sometimes `resources` is set to empty list. Therefore, please exclude it from post params if empty.

**Comment by ljfranklin** [comment]
Making sure I understand, your issue is that your python HTTP library is unable to send a file and extra data as part of the same body? Or more a general observation that the API feels a bit awkward?

If the former, does something [like this](http://stackoverflow.com/a/13015529) work?

If the latter, we're working on adding new v3 endpoints now and this is useful feedback on the API design. cc @zrob

**Comment by charyorde** [comment]
I got around it with this:
```
data = {'resources': '[]'} # Notice the quoted list. 
files = {'application': open('file.zip', 'rb')}
requests.put('appguid/bits', data=data, files=files)
```
The entire `resources` data is removed if it's not quoted. That's why I get `missing :resources` error from CF.

But I think my argument about making `resources` less required if its empty should still stand.

**Comment by zrob** [comment]
We're glad to hear you were able to resolve your issue.
