### ISSUE TITLE
"http" url config leads to failing cf-routing smoke tests in HTTPS only environment

### ISSUE THREAD

**Issue by x6j8x** [cloudfoundry/cloud_controller_ng#820]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

The hardcoded "http" protocol in https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_worker/templates/cloud_controller_worker.yml.erb#L399 leads to errors while running the cf-routing smoke-tests in a HTTPS-only environment. 

[2017-04-26 02:46:50.98 (UTC)]> cf delete-shared-domain TCP-2-DOMAIN-1e7dbb90-4da8-4b48-5.apps.sandbox.6e109e.be -f 
Deleting domain TCP-2-DOMAIN-1e7dbb90-4da8-4b48-5.apps.sandbox.6e109e.be as admin...
FAILED
Error deleting domain TCP-2-DOMAIN-1e7dbb90-4da8-4b48-5.apps.sandbox.6e109e.be
The Routing API is currently unavailable

This error only happens if a cc_worker tries to delete the TCP routes. Everything works when deleting the routes interactively and the request is handled by CC itself.

The CC configures "https" as protocol for the same attribute:

https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_ng/templates/cloud_controller_api.yml.erb#L235

## Context

The error occurs if a cc_worker tries to talk to the routing api. 

## Steps to Reproduce

Disable Port 80 on the LB in front of your gorouter (only leave port 443 enable) and run the cf-routing smoke-test errand.

## Expected result

cc_worker should expose the same behaviour as cc (using https to talk to the routing api)

## Current result

cc_worker currently uses http to talk to routing_api which fails in environments where http is  disabled.

## Possible Fix

#811

**Comment by nicregez** [comment]
The mentioned PR was merged
