### ISSUE TITLE
When calling /v2/spaces/:spaceGuid/services, space-scoped services return an empty array for their service plans

### ISSUE THREAD

**Issue by jberney** [cloudfoundry/cloud_controller_ng#821]
## Issue

When we call `/v2/spaces/:spaceGuid/services`, any services that are space-scoped will return an empty array in the `service_plans` key, even when they do have service plans.

## Context

* When calling `/v2/spaces/:spaceGuid/services` on the same service when it is not space-scoped, this endpoint does return the service plans as expected.
* When calling `/v2/services/:serviceGuid/service_plans` on such space-scoped services, they do return their service plans.
* Our expectation is that these service plans should also be provided for space-scoped services by the `/v2/spaces/:spaceGuid/services` endpoint, but they are not.

**Note:** we are using the parameter, `inline-relations-depth=1`. Here is an example call we are making:

```https://apps.sys.scar.gcp.appsman.cf-app.com/proxy/api/v2/spaces/b409aae2-048b-44be-b023-0d2db3ecf684/services?results-per-page=100&inline-relations-depth=1&page=1```

## Steps to Reproduce

* Deploy a space-scoped service that has one or more service plans to an org/space in a CF installation
* Call `/v2/spaces/:spaceGuid/services` on the space to which the space-scoped service was deployed

## Expected result

* The `service_plans` key for the space-scoped service should contain an array of service plan details, that is:
 * similar to the data returned by `/v2/services/:serviceGuid/service_plans` for the service
 * the same as the data returned in `service_plans` key when the service is not space-scoped

## Current result

* The `service_plans` key for the space-scoped service is an empty array

**Comment by Gerg** [comment]
Hey @jberney 

Thanks for submitting this issue. We were able to reproduce it as you described and are working on a fix.

Thanks,
@gerg && @ericpromislow

**Comment by zrob** [comment]
Resolved.
