### ISSUE TITLE
Add support for connecting to CC DB over TLS

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry/cloud_controller_ng#830]
We have a few environments which have strict security policies in place which only allow secure database connections regardless of the data classification or even if the data itself is encrypted.

A recent commit for the UAA release has enabled TLS connections for the UAA DB.
https://www.pivotaltracker.com/n/projects/997278/stories/145563953

Jon Price
Intel Corp

**Comment by zrob** [comment]
Support for SSL is available in [capi-release 1.41.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.41.0)
