### ISSUE TITLE
Misleading documentation for Resource Match API ?

### ISSUE THREAD

**Issue by abh1kg** [cloudfoundry/cloud_controller_ng#831]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue
The API doc for the `/v2/resource_match` API says the content type of the request must be `application/x-www-form-urlencoded`. However, sending a request with this content type, leads to an HTTP internal server error from the controller. Changing the content type to `application/json` leads to a successful request.
Is this just wrong documentation or a problem with the API itself?

## Context
This API is used to find the resources in the uploaded archive, which are already cached in the CF Blob Store. The API call needs to be successful for an app upload.

## Steps to Reproduce

1.  Create an HTTP PUT request with content type `application/x-www-form-urlencoded`, attach the array of objects containing the file SHA1s and sizes in the request entity

2. Check the output- it is an internal server error from the CF Controller API 

## Expected result

The API call must be successful or the documentation must be fixed

## Current result

Due to misleading documentation (or a possible CF Controller error), app uploads via the REST APIs are affected

## Possible Fix

Documentation fix or proper handling of the request MIME types

**Comment by aashah** [comment]
Hey @abh1kg,

A quick scan of our docs shows this to be a pretty re-occurring issue. I'll update all of them!

- Aakash
