### ISSUE TITLE
Space-scoped service brokers: Unique URLs and plan IDs

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/cloud_controller_ng#837]
## Issue

When trying out space-scoped service brokers (http://docs.cloudfoundry.org/services/managing-service-brokers.html#register-broker) we found that Cloud Controller refuses to register a space-scoped service broker if the broker URL has been used already for registering the same broker in another space.

Also, working around this by adding another route to our broker deployed as a CF app, we found that the next check that is done is the uniqueness of plan IDs returned by the broker. Also those seem to have the constraint that they need to be unique across the entire CF deployment.

## Context

There's many service brokers people are interested in using, however, the above behavior requires them to deploy the service brokers themselves (as opposed to using an already deployed broker managed by somebody else), tweaking the broker URL and plan IDs.

## Steps to Reproduce

Register the very same service broker twice as a space-scoped broker inside a CF deployment.

## Expected result

It would be desirable to allow people to register the same broker instance as a space-scoped broker in more than one space inside a CF deployment.

## Current result

Error message refusing to register the broker complaining about URL and plan ID non-uniqueness. 

## Possible Fix

Extend Cloud Controller tables dealing with service broker registrations by org/space key fields.

## `name of issue` screenshot

n/a

**Comment by zrob** [comment]
Hi @bkrannich 

The service broker [spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.12/spec.md) specifies that plan ids must be globally unique within a market place.  This makes sense when we think about service brokers being added globally to a platform without the `--space-scoped` flag.

The original use case for space scoping was to allow broker authors to quickly develop brokers, which would later be added globally to a platform to provide services.

It sounds like your use-case is for space developers to manage a broker for their space only.  

This isn't something we have on our road map, but is an interesting use case.

@zrob

**Comment by mattmcneeney** [comment]
Hey @bkrannich 
Could you take a look at this doc when you have a chance? I'd like to make sure that we're covering this use case in our investigation into how we can resolve this. Thanks!

**Comment by rboykin** [comment]
@mattmcneeney I would guess you would have a similar uniqueness problem with the dashboard_client for space-scoped service brokers: https://github.com/openservicebrokerapi/servicebroker/blob/v2.12/spec.md#dashboard-client-object

**Comment by mattmcneeney** [comment]
Interesting. I've never actually seen this cause an issue, but maybe it does. cc @Samze @zrob in case you've heard of the `dashboard_client` object (`.id`?) causing a conflict?

**Comment by georgi-lozev** [comment]
Yes, it seems that the [db model](https://github.com/cloudfoundry/cloud_controller_ng/blob/6ef21b06e7c6acfd293b8aafa79646f4e630c5ce/app/models/services/service_dashboard_client.rb#L7) requires that dashboard client id to be unique.

**Comment by bkrannich** [comment]
@mattmcneeney - thank you very much for the concise write-up! I have left a couple of comments inside the document.

**Comment by mattmcneeney** [comment]
As you know @bkrannich we are going to resolve this issue with the [multi-service-registration](https://www.pivotaltracker.com/epic/show/3979252) epic that the team are currently working on (see [design proposal](https://docs.google.com/document/d/1_OBnFCsL3ru43PEXocsCc3EuGaM0YLHjr0iAoXnakt4)).

We will leave this open until that track of work is complete.

**Comment by norshtein** [comment]
Hi @mattmcneeney , when will the development finish? Is there an estimated time we can use it in Cloud Foundry?

**Comment by mattmcneeney** [comment]
Hey @norshtein. We are just working through some CLI refactoring work, but we're hoping to get round to this as soon as that is done.
Keep an eye on this track of work for updates: https://www.pivotaltracker.com/epic/show/3979252

Does that help?

**Comment by norshtein** [comment]
Hi @mattmcneeney , thanks for the quick response. We're receiving customers' request for using multi-tenant [OSBA](https://github.com/Azure/open-service-broker-azure) in Cloud Foundry on Azure. So we'd like to know **an estimated finish time** of this feature. And if it takes a long time, we may temporarily make some change to OSBA to enable multi-tenant. But we're trying to avoid making temporary change and rolling back later. We definitely prefer to use your solution if it's coming soon.

**Comment by bkrannich** [comment]
@mattmcneeney - awesome, thank you very much for pulling this in!

**Comment by mattmcneeney** [comment]
Hey all. Just an FYI that we are currently working on this epic, and you'll be able to follow [this release marker](https://www.pivotaltracker.com/story/show/161050836) if you want to be notified when this is completed.

**Comment by mattmcneeney** [comment]
Hey all (inc @bkrannich)
The API work required for this feature is now done, so if you're consuming the CF API directly, you should be able to do this now!
The CLI work is underway and will likely take us a couple more months.

**Comment by laurzca** [comment]
Hi all, the CLI work is finished! It will be in the next CLI release, which should land sometime this week.
