### ISSUE TITLE
The `cc.default_to_diego_backend` property has a default value of `false`

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/cloud_controller_ng#841]
## Issue

The [`cc.default_to_diego_backend`](https://github.com/cloudfoundry/cloud_controller_ng/blob/b5491f42fe31d654f05c106496a850ebebe0c555/bosh/jobs/cloud_controller_ng/spec#L546-L548) property has a default value of `false`, which is non-intuitive becase DEA has long since been deprecated.

## Context

We run open source Cloud Foundry and were upgrading from v257 to v265. We excluded this property to simplify our manifest and use the default, only to find the default was not as expected.

## Steps to Reproduce

N/A

## Possible Fix

Change the default to true so people can exclude it from their manifest.

**Comment by tusing** [comment]
Hi @henrytk,

We resolved this issue [in this commit.](https://github.com/cloudfoundry/cloud_controller_ng/commit/866fc37a7e8f92b3eb54702bbe362c97bbcacaef)

This will be available in the next release.

Thanks,
@tusing & @mikexuu
