### ISSUE TITLE
service_bindings encodes '&' into '\u0026'

### ISSUE THREAD

**Issue by zhongyi-zhang** [cloudfoundry/cloud_controller_ng#846]
## Issue

Character '&' in service credentials is encoded into '\u0026'.

## Context

Hit the issue in both user-provided services and services created by a service broker.
All the '&' in service credentials are encoded into '\u0026' when binding to an app.

## Steps to Reproduce

Create a user provided service containing '&':

```
$ cf cups my-service -p '{"a": "&&"}'
```

Bind the service to an app:

```
$ cf bind-service my-app my-service
```

Check environment variables of the app:

```
$ cf env my-app
```
--

## Expected result

```
{
 "VCAP_SERVICES": {
  "user-provided": [
   {
    "credentials": {
     "a": "&&"
    },
    "label": "user-provided",
    "name": "my-service",
    "syslog_drain_url": "",
    "tags": [],
    "volume_mounts": []
   }
  ]
 }
}
```

## Current result

```
{
 "VCAP_SERVICES": {
  "user-provided": [
   {
    "credentials": {
     "a": "\u0026\u0026"
    },
    "label": "user-provided",
    "name": "my-service",
    "syslog_drain_url": "",
    "tags": [],
    "volume_mounts": []
   }
  ]
 }
}
```

**Comment by Gerg** [comment]
Hey @zhongyi-zhang,

We investigated this issue and it looks like the credentials are correct in the app environment. You can verify this by pushing an app that echoes its environment variables. 

Furthermore, if you query `/v2/service_bindings/:guid`, you should see that the API presents the environment variables correctly. We believe this is an issue with the cf cli. 

@dkoper @nickwei84 can you investigate this issue?

Thanks,
@gerg && @tusing

**Comment by zhongyi-zhang** [comment]
Hi @Gerg ,

Yes, confirmed that querying `/v2/service_bindings/:guid` gives the correct env variables. It should be a display issue in CF CLI.

Thanks,
Zhongyi

**Comment by dkoper** [comment]
@zhongyi-zhang I have created the following story in our cf CLI tracker:
https://www.pivotaltracker.com/story/show/149543325

Although I've placed the story in our backlog, it will likely take several months until we get to it due to other priorities.
