### ISSUE TITLE
CPU and Disk Usage should be present in app_usage_event api

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry/cloud_controller_ng#851]
Is it possible to give the CPU and Disk Usage in /v2/app_usage_event api?

**Comment by zrob** [comment]
Hello @cfmagnum,

That api is intended to be used for billing purposes.  There are multiple [blog](https://www.cloudfoundry.org/how-to-bill-on-cloud-foundry/) [posts](http://www.starkandwayne.com/blog/billing-your-cloud-foundry-users/) and [docs](https://docs.cloudfoundry.org/running/managing-cf/usage-events.html) that contain good information about how to use these events.

Are you attempting to bill users based on cpu and disk usage?  Currently all providers that do billing are able to bill based on memory and instance usage.

Today we do not have a good way of reporting reserved cpu for billing, but it would be possible to provide the reserved disk per app instance as seen on the `disk_quota` field of /v2/apps.

If that is what you are asking for it is something I could schedule, but it would be low in priority.  We could also accept a PR that added `disk_in_mb_per_instance` and `previous_disk_in_mb_per_instance`.

Thanks,
@zrob

**Comment by cfmagnum** [comment]
Thanks @zrob 

Yes, I am also using /v2/app_usage_event api for  billing purpose. 

I am applying the billing based on memory and instance usage. But now I want to apply billing for cpu and disk usage as well.

If it's possible to provide the _disk_in_mb_per_instance_ and _previous_disk_in_mb_per_instance_ in /v2/app_usage_event it will be very help full. Can you please schedule this for implementation. 

For CPU usage we will find a way.

Thanks,
**@cfmagnum**

**Comment by cfmagnum** [comment]
Is there any other component apart from cloud_controller_ng, In which we need to make changes to add disk_in_mb_per_instance and previous_disk_in_mb_per_instance?

**Comment by Gerg** [comment]
@cfmagnum All of the app usage events are handled within Cloud Controller.

**Comment by cwlbraa** [comment]
we'd still accept this as a contribution, but we're going to close this due to inactivity.

thanks!
