### ISSUE TITLE
Filtering Space Services by Broker causes DB error

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#856]
## Issue

Filtering space services by service broker id causes a Database Error

## Context

Note that making calls to this endpoint that are unfiltered, or filtered by the other options, works fine. Similarly the equivalent call for `organisations` rather than `spaces` also works fine.

## Steps to Reproduce
1. Find space id ad service broker id.

2. Curl the endpoint as follows:
`cf curl /v2/spaces/<spaceId>/services?q=service_broker_guid:<serviceBrokerId>`

## Expected result
A list of services in the space, filtered by service broker id

## Current result
```
{
   "description": "Database error",
   "error_code": "CF-DatabaseError",
   "code": 10011
}
```

## Possible Fix
Make it work in the same way that the equivalent call in `organisations` does.

**Comment by ericpromislow** [comment]
Hi @twoseat 

Thanks for reporting this issue. It was straightforward to reproduce, and I was able to come up with a fix and write a unit test to verify, committed in https://github.com/cloudfoundry/cloud_controller_ng/commit/e9a080c0b8e7f51fe59ee3e770fdcc93f88428fe

Regards,
Eric Promislow, CloudFoundry Community Support Team
