### ISSUE TITLE
Shouldn't be able to create a route that conflicts with another org's private domain

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cloud_controller_ng#857]
## Issue

I am able to create a route that matches an existing private domain in another org on CF release 266.  I would think that having a private domain for a given host should be like creating a route with that host.

## Steps to Reproduce

1. Create a private domain in an org that is a sub domain of a shared domain. (e.g. Shared Domain: test.com Private Domain: foo.test.com)
2. Attempt to create a route in another org that matches that private domain name. (e.g. test.com -n foo)

Assert: That you were able to successfully create that route.

3. Delete the route just created (foo.test.com)
4. Switch to the org that owns the private domain.
5. Attempt to create a route that conflicts with the private domain using the shared domain ( test.com -n foo)

Assert: That creating the route fails with the error `The route is invalid: host domain_conflict`

## Expected result

The attempt to create `test.com -n foo` should fail in the org that owns the private domain and outside that org.

## Current result

It fails when creating the route inside the private domain owning org and is allowed outside.

**Comment by zrob** [comment]
@youngm 

I'm not able to reproduce
```
$ cf create-shared-domain test.com
Creating shared domain test.com as admin...
OK

$ cf create-domain system foo.test.com
Creating domain foo.test.com for org system as admin...
OK

$ cf target -o test
api endpoint:   https://api.wind-bone.capi.land
api version:    2.90.0
user:           admin
org:            test
space:          test

$ cf create-route test test.com -n foo
Creating route foo.test.com for org test / space test as admin...
FAILED
Server error, status code: 400, error code: 210001, message: The route is invalid: host domain_conflict
```

Am I following the repro correctly?

**Comment by youngm** [comment]
You're right.  It was a typo on my side when I experienced the issue.  Thanks and sorry for spending your time. :)
