### ISSUE TITLE
Problem with CF event lifecycle

### ISSUE THREAD

**Issue by JuergenFrank** [cloudfoundry/cloud_controller_ng#861]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Instead of creating new audit events when spaces resp. orgs are deleted, I experienced that no events were created and existing ones deleted. This is not what I expect from and audit event log!

## Context

I intend to inspect the events defined in the Cloud Foundry API https://apidocs.cloudfoundry.org/268/ in order to verify that the deletion of an org or a space including all service instances has been successful. The defined CF events should in principle provide most of the information. (Organization lifecycle events are still missing, cf. cloudfoundry/cloud_controller_ng#758)

I had created a space with a few deployed apps and service instances bound to the apps. The first command showed me the corresponding audit. The third command, after deletion of the space and everything contained therein, did not yield any event.

## Steps to Reproduce

Execute following steps:
```
cf curl "/v2/events?q=space_guid:<my-space-guid>"
cf curl "/v2/spaces/<my-space-guid>?recursive=true&async=true" -X DELETE
cf curl "/v2/events?q=space_guid:<my-space-guid>"
```

I used CLI version 6.29.0+ff886fa.2017-07-24 and CC API Endpoint Version 2.89.0.

## Expected result

I had expected to see all events for the space I had seen previously plus the ones resulting from the deletion of all entities in the space including the space deletion event itself. 

## Current result

The third command, after deletion of the space and everything contained therein, did not yield any event. It looks like that no audit events for the deletion have been created and old ones deleted. 

## Possible Fix

./.

## `name of issue` screenshot

./.

Note: I had originally opened the issue on the CLI, cf. https://github.com/cloudfoundry/cli/issues/1190.

**Comment by zrob** [comment]
@JuergenFrank thanks for submitting this issue.

I was able to reproduce your issue. However, I did find that if you curl /v2/events then the events related to the deleted space do still exist, it is just the query parameter that is broken.

If you have an immediate auditing concern you can still page through /v2/events and look for events within the space you need. 

We will look at making the query parameter work regardless of the existence of the space.

Thanks,
@zrob

**Comment by tusing** [comment]
Hello @JuergenFrank,

Thanks for reporting this error. We've fixed it, and the fix will be in an upcoming Cloud Controller release.

@ericp && @tusing, CAPI Community Support Team
