### ISSUE TITLE
details field not documented in response of GET /v2/apps/:guid/instances

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cloud_controller_ng#862]
Prior submitted in  #497 by @glyn (I can't reopen it):

The [GET instance information for a STARTED app REST interface](http://apidocs.cloudfoundry.org/268/apps/get_the_instance_information_for_a_started_app.html) does not document a details response field.
* See [example output](https://github.com/cloudfoundry/cli/issues/1155) and from @kkellner [here](https://github.com/cloudfoundry/cloud_controller_ng/issues/497#issuecomment-318799837)
* See [suggestion](https://github.com/cloudfoundry/cli/issues/1155#issuecomment-305927499) from @zrob for the CLI to use this field

**Comment by ljfranklin** [comment]
Thanks for reporting the omission. I've added it to examples for CRASHED and DOWN instances.

@ericpromislow - CAPI community team
