### ISSUE TITLE
List Packages for an app has an invalid example payload

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#868]
Currently the [List Packages for an App](http://v3-apidocs.cloudfoundry.org/version/3.27.0/index.html#list-packages-for-an-app) has an example payload that lists `data.error` and `data.checksum`, which are not listed as part of the [Bits Package object](http://v3-apidocs.cloudfoundry.org/version/3.27.0/index.html#packages). Either the description of the Bits Package object or the example needs to be updated so that they are consistent with each other.

**Comment by zrob** [comment]
object updated to match the examples
