### ISSUE TITLE
Packages table has 58K records and this Query is not returning for ever 

### ISSUE THREAD

**Issue by amulyas** [cloudfoundry/cloud_controller_ng#869]
https://github.com/cloudfoundry/cloud_controller_ng/blob/3286333334275ff19bc2396fe81f6f3402bc724b/lib/cloud_controller/backends/runners.rb#L97-L101

**Comment by ljfranklin** [comment]
@amulyas CF has stopped supporting the DEA and all code involving the DEA, including that snippet, has since been removed. We'd suggest moving all your environments over to diego at this time.

Closing this out, but let us know if there's anything else we can help with.
