### ISSUE TITLE
List Processes has an invalid example payload

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#870]
Currently the [List Processes](http://v3-apidocs.cloudfoundry.org/version/3.27.0/index.html#list-processes) has an example payload that lists `ports`, which is not listed as part of the [Process object](http://v3-apidocs.cloudfoundry.org/version/3.27.0/index.html#the-process-object). Either the description of the Process object or the example needs to be updated so that they are consistent with each other.

**Comment by zrob** [comment]
examples updated to match the object
