### ISSUE TITLE
"cf curl" still shows old names after doing a "cf rename"

### ISSUE THREAD

**Issue by David-Pivotal** [cloudfoundry/cloud_controller_ng#874]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

When do a `cf rename` APP, the new app name isn't getting reflected by command `cf curl /v2/apps/app_guid/stats`.

## Context
Customer is using opensource/github version of cloud foundry. 
https://bosh.io/releases/github.com/cloudfoundry/cf-release?version=253
Customer's release version:

Name | Versions | Commit   Hash
-- | -- | --
al-broker | 3.0.1 | 6b86f129
app-usage-service | 1.0.0 | 67d3f31d+
bosh | 256.2 | 3a800144+
bosh-aws-cpi | 39 | eb9f26d4
buildpack-tests | 1.0.3* | 4d7ae191+
buildpacks | 2* | 3f9af993+
cf | 237 | 87f11091+
  | 243 | ee7d0088+
  | 253* | 82fb38a8+
cf-autoscaling | 28 | caf0ca8d
cf-haproxy | 5 | 443d2093+
cf-mysql | 24* | 3a438bdb+
cf-rabbitmq | 106 | c6ac7d52
  | 106.3 | d130782b+
  | 210.1.0* | 47c2e795+
  | 218.0.0+dev.13* | 4a39e187+
cf-redis | 328 | 70fbb07f+
  | 393 | 102f31fc
  | 397* | c322b232
cf-riak-cs | 9* | d522ba47+
  | 10 | 5e7e46c9+
cf-sensu-client | 1* | c10f89e6+
  | 1.6.0+dev.1* | c72f0f11+
  | 1.6.1* | 9f3615c6+
  | 1.6.5* | a5e081bd+
  | 1.6.9* | 5ef478e2
  | 1.7.3 | c45abf6a+
  | 1.7.10* | 036687b2+
  | 1.7.11* | f739a0d1+
  | 1.7.12* | e3778a9d
  | 1.7.17* | 7b79efc7
  | 1.7.18 | 21879b87+
cf-splunk | 0+dev.1* | 6f65ffe7
cflinuxfs2-rootfs | 1.29.0 | f48ec781+
  | 1.53.0* | a80feaae+
concourse | 0.59.0 | 139a34a9
  | 0.62.0 | 00bf26ea
diego | 0.1485.0 | d71de542
  | 1.9.0* | 4ff4b651
docker | 13 | 36417643+
  | 15* | 7fef8aba+
  | 23* | 82346881+
elasticdump | 1.1 | 46e8b2cd+
  | 2* | bf66080a+
es-smoketest | 1* | 5f0ce813+
etcd | 67 | 7d1135d0+
garden-linux | 0.303.0 | 63e18100
  | 0.342.0 | b03a9abc
garden-runc | 0.8.0 | e4af7434
  | 1.2.0* | 2b3dedc5
ge-logsearch-filter | 1.4* | c85d3dd5+
ha-rabbitmq | 214.1.2 | aef8b1af+
  | 214.1.4 | 9e863438+
logsearch | 202.1.0 | c9b81dcb
  | 202.1.1 | 37949824
  | 202.2.5* | b0cf3acd
logsearch-for-cloudfoundry | 4 | 9d1ce487+
  | 6 | 0fd08bec+
logsearch-for-cloudfoundry-operators | 9 | 284a2c2d+
  | 20.0.0* | da4348ed
logstash-docker | 1 | ff8edd3d+
metrics | 1 | 8e3d31f6+
monitor-server | 1* | 60bd01d1
  | 2* | 8ccd0ec9+
node-exporter | 1.0.0 | 412d59ec+
notifications | 20+dev.1 | fbfe4fad
  | 21* | a9ce13e2+
nxlog | 0.1.0* | e774a9ff+
play | 2 | 208c96eb+
  | 4 | 208c96eb+
postgres | 1.0.4 | b9fe4ae8+
postgres-smoke-tests | 2* | 6ab289bc+
  | 3* | 077ebd49+
postgresql-docker | 1.1* | c973a81d+
prometheus | 14.0.0 | 95965f63+
push-apps-manager-release | 629.6 | 38cda85c+
push-console-release | GE-341a* | bd95b2fd+
rabbitmq-smoke-tests | 3 | c189e967+
  | 4* | 07fe3bb4+
rdpg | 0.3.7 | 2c94df87
  | 0.3.8 | 39f9bfad
  | 0.4.1* | da8bf3be
root-env | 1+dev.1 | a2faf4c6
route-registrar | 1 | 913c3424+
  | 2 | 2ee70e65
  | 3* | f7132692+
routing | 0.145.0 | dfb44c41+
shield | 6.2.2* | c810c4b1+
  | 6.3.3* | 37ab272f+
  | 6.5.2 | 6204de71+
  | 6.6.0 | 3e3458e6+
  | 6.7.0* | 7c0b9b4c+
ssh | 1* | 3a5daba9+
stannis | 5 | 97d29b07+
  | 7 | 295e7ed1+
  | 8* | 6685a5b0+
syslog | 11* | 0e06601
toolbelt | 3.2.7 | 40164d79+
  | 3.2.10* | fa002b53
uaa | 37 | 0c84a0e4
  | 40* | 60dc7308

## Steps to Reproduce
`bash-3.2$ cf rename spring-music-Ram-Example1 spring-music-Ram-Example2 `
`Renaming app spring-music-Ram-Example1 to spring-music-Ram-Example2 in org cloudservices / space RamS-Test as ramakrishna.sajja@ge.com... `
`OK `

`bash-3.2$ cf app spring-music-Ram-Example2 `
`Showing health and status for app spring-music-Ram-Example2 in org cloudservices / space` `RamS-Test as ramakrishna.sajja@ge.com...`
`name: spring-music-Ram-Example2 `
`requested state: started `
`instances: 1/1 `
`usage: 1G x 1 instances `
`routes: spring-music-ram-example1.run.aws-usw02-dev.ice.predix.io `
`last uploaded: Mon 14 Aug 11:51:39 PDT 2017 `
`stack: cflinuxfs2 `
`buildpack: java-buildpack=v3.9-https://github.com/cloudfoundry/java-buildpack.git#b050954 
java-main open-jdk-like-jre=1.8.0_101 open-jdk-like-memory-calculator=2.0.2_RELEASE 
spring-auto-reconfiguration=1.12.0_RELEASE`
`state since cpu memory disk details `
`#0 running 2017-08-14T18:52:41Z 0.1% 565M of 1G 155.3M of 1G `

`bash-3.2$ cf curl /v2/apps/78cd7023-3766-455b-a876-2d5a070aa188/stats `
`{ 
"0": { 
"state": "RUNNING", 
"stats": { 
"name": "spring-music-Ram-Example1", 
"uris": [ 
"spring-music-ram-example1.run.aws-usw02-dev.ice.predix.io" 
], 
"host": "10.72.132.195", 
"port": 62383, 
"uptime": 357, 
"mem_quota": 1073741824, 
"disk_quota": 1073741824, 
"fds_quota": 16384, 
"usage": { 
"time": "2017-08-14 18:58:27 +0000", 
"cpu": 0.0007941637272834026, 
"mem": 592424960, 
"disk": 162869248 
} 
} 
} 
}`

## Expected result

The output of command `cf curl` should be `"name": "spring-music-Ram-Example2"`

## Current result

`"name": "spring-music-Ram-Example1"`

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by David-Pivotal** [comment]
Hi,

May I have an update on this issue?

**Comment by Gerg** [comment]
Hey @David-Pivotal,

Is this app running on DEA? This would explain why it is not reproducible in recent cf releases (since support for DEA was dropped). If you want the rename to propagate on DEA, you will need to restart the app. You can also change to running the app on Diego, and the name will update immediately.

Thanks,
@gerg && @tcdowney

**Comment by emalm** [comment]
@Gerg the erroneous output is coming from the CC API (`/v2/apps/APP_GUID/stats`) so I don't see why the backend (DEA vs Diego) would be relevant.

**Comment by Gerg** [comment]
@emalm The CC generates the output differently depending on the backend. For DEA, it pulled the app name from the instance in DEA. For Diego, the name just comes from the CCDB.

**Comment by emalm** [comment]
Thanks, @Gerg, that makes more sense!

**Comment by David-Pivotal** [comment]
@Gerg Thank you for your comments here. Really appreciate your help! 
I have conveyed this to the end user and is still waiting for his reply.

**Comment by David-Pivotal** [comment]
@Gerg You are right that customer confirms his app is running in DEA! 
Thanks for your help and let's close this issue.
