### ISSUE TITLE
Allow Global auditor role to access logs for all applications  

### ISSUE THREAD

**Issue by ronakbanka** [cloudfoundry/cloud_controller_ng#875]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

As of now `cloud_controller.global_auditor` role can audit spaces & orgs but no access to application logs.

## Context

As a global auditor, I want to access application logs for security purpose, check if applications are not leaking any confidential data or for analytics.

Only platform admin role and few roles from orgs/spaces have [permission](https://github.com/cloudfoundry/cloud_controller_ng/blob/130f6dd58276b392356ec9a116a954d2c0e4514a/app/controllers/internal/log_access_controller.rb#L10) to access logs.

## Steps to Reproduce
1. Create a new client and assign `cloud_controller.global_auditor` role
2. Try to access logs from any application (stream/recent)

## Expected result

Expected result is global auditor should be able to access application log stream/recent logs.
```
[ronak.banka ~]$ cf logs helloworld-vqpca --recent
Retrieving logs for app helloworld-vqpca in org test-logs / space development as auditor...
2017-08-16T13:02:48.54+0530 [APP/PROC/WEB/0] OUT 192.168.50.4, 127.0.0.1 - - - [16/Aug/2017:07:32:48 +0000] "GET / HTTP/1.1" 200 13
```
## Current result
Cloud controller tries to find user access permission and nginx returns 404 , cf cli fails with unknown issue
```
nginx cc logs

2017/08/16 05:56:21 Non 200 response from CC API: 404 for 49c63a74-6828-4ac2-943e-09ab51fbfeec
2017/08/16 05:56:21 Non 200 response from CC API: 404 for 49c63a74-6828-4ac2-943e-09ab51fbfeec
```
```
[ronak.banka ~]$ cf logs helloworld-vqpca --recent
Retrieving logs for app helloworld-vqpca in org test-logs / space development as auditor...

unknown issue when making HTTP request to Loggregator
FAILED
```
## Possible Fix
Add global auditor role for access [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/130f6dd58276b392356ec9a116a954d2c0e4514a/app/controllers/internal/log_access_controller.rb#L10)
```
if roles.admin? || roles.global_auditor?
```

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by zrob** [comment]
@ronakbanka 

Rather than make changes to how existing roles function, we are working on allowing users to create custom roles.  This is a long term effort and is being run by the [perm project](https://github.com/cloudfoundry-incubator/perm-release)

/cc @xoebus
