### ISSUE TITLE
[Feature request] Job run time metric 

### ISSUE THREAD

**Issue by combor** [cloudfoundry/cloud_controller_ng#878]
## Feature request

**It would be useful to have a Cloud Controller job run time metric emitted.**

## Context

We use `job_queue_length.total` metric to spot problems with Cloud Controller performance. However it's not a perfect match as user experience may differ based on submitted job type. Some jobs are of course more resource hungry and can create a bottle neck in CC queue processing. For instance such a job is [organisation delete](https://apidocs.cloudfoundry.org/268/organizations/delete_a_particular_organization.html) request. 
Additionally `cf delete-org` uses `async` parameter which makes measuring API response time pointless.  

Emitting `job_run_time` metric would allow us to spot jobs that run abnormally long and react proactively when situation gets bad.

**Comment by zrob** [comment]
Hi @combor 

We also use `job_queue_length.total` along with `failed_job_count.total` to help us assess the health of the system.  We've never found it interesting to worry about how long a job runs as long as the queue isn't backing up and failures aren't increasing. 

It also seems like with some jobs running quickly and some taking a long time, it would be hard to understand how to react to changes in an average run time for different types of jobs.  Increases and decreases could just indicate different usage patterns where certain jobs are happening more or less often than they were prior.

Could you provide a concrete example of a slow job that caused you to take action and what that action was to help me understand how this would provide ongoing value to monitoring this value?  

It currently seems like monitoring the queue length and failed jobs is enough to indicate that action needs to be taken.

Thanks,
@zrob

**Comment by Gerg** [comment]
We haven't heard anything on this issue for a while. I'm going to go ahead and close this. Please re-open if you want to continue the discussion.

Thanks,
Greg
