### ISSUE TITLE
Add routing endpoint to root payload

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cloud_controller_ng#881]
Currently, the root payload (e.g. `https://api.run.pivotal.io`) contains a number of endpoints and their versions.  Based on the latest version available it appears that it's still missing a link to the routing API (`routing_endpoint` in the `/v2/info` response payload).  This should be added, preferably with a version number.

**Comment by ljfranklin** [comment]
@nebhale Sorry for the delay in getting to this. CC exposes the routing API endpoint under `/v2/info` if [routing_api.enabled](https://github.com/cloudfoundry/cloud_controller_ng/blob/68148214ee4850d98bd6a8d0f297192b4d624054/bosh/jobs/cloud_controller_ng/spec#L692) is true. You'll have to open a support ticket with PWS to understand why they have chosen to not expose the routing API at this time.

I'm going to go ahead and close this issue as it is unrelated to OSS CF but please re-open if you have any more questions.

**Comment by nebhale** [comment]
@ljfranklin You might have missed what the issue is about.  The routing API _is_ exposed via the `/v2/info` endpoint.  I’d like the Cloud Controller to *also* expose it in the root payload `/`.  This is not related to PWS, this is a Cloud Controller issue.

**Comment by ljfranklin** [comment]
@nebhale whoops, yep I misread. Thanks for re-opening.

Sounds like an oversight on our part. Pinging @zrob to prioritize this in our backlog or this would be an easy PR if someone's up for it. Would need to copy the logic from [info_controller](https://github.com/cloudfoundry/cloud_controller_ng/blob/07bba985f349d52fd8dcaa15cb0c140973d0009f/app/controllers/runtime/info_controller.rb#L28-L30) to [v3 root_controller](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/controllers/v3/root_controller.rb) and add one unit test.

**Comment by anniesing** [comment]
Bumping @Gerg while @zrob is out.

**Comment by zrob** [comment]
resolved in 00ac604
