### ISSUE TITLE
Looking at the app rather than a package to determine the package's lifecycle type

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cloud_controller_ng#884]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

While on CLI, this failed with the error message "Failed to get blobstore download url for package ...":

    cf v3-create-app APP 
    cf v3-create-package APP -o cloudfoundry/diego-docker-app-custom
    cf v3-stage APP --package-guid PACKAGE_GUID

The last command translates to a `POST /v3/build -d { "package" :  "guid": GUID } }`

Why does the default code in https://github.com/cloudfoundry/cloud_controller_ng/blob/56922f1f95cf382c235c1b1f0592f49610aba7fd/lib/cloud_controller/diego/lifecycles/lifecycle_provider.rb#L16 consult `package.app.lifecycle_type` and not `package.type` to 
determine the type of the package when it was created?

## Context

CLI XTP work on `cf v3-stage`

## Steps to Reproduce

See above

## Expected result

The thing stages

## Current result

The thing doesn't stage -- details above

## Possible Fix

Rework `LifecycleProvider.provide` to consult the current package if the message doesn't have a lifecycle field.

**Comment by mariash** [comment]
It seems like the app should be created with lifecycle `docker` for docker type package to work with it.
