### ISSUE TITLE
quota_definitions hash should become an array

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry/cloud_controller_ng#889]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

When the hash order on the `properties.cc.quota_definitions` its changed, it will trigger a deployment in the `cc` instance_group, and all related ones, like `clock_global`.

## Context

The issue is that the order in a hash cannot be guaranteed. Sometimes, depending on the YAML parser being used, the hash order will change, and every time a deployment its trigger with a different hash order, will cause that the `instance_groups` mentioned above will be updated. This is not the intended behaviour, because none configuration its changing.  

## Steps to Reproduce

- 1 have in the manifest the following property:
```yaml
properties:
  cc:
    quota_definitions:
      q256MB:
      q2GB:
      q4GB:
      q8GB:
      q16GB:
      q32GB:
      q64GB:
      q128GB:
      q256GB:
      q512GB:
```
- 2 Do something with your file, process it using something like https://github.com/go-yaml/yaml/tree/v2 or deploy it using the https://github.com/cloudfoundry/bosh-cli

  For example:

  The issue is not so obvious, for example, if you run it as follows for several times:

  `bosh2 interpolate manifest.yml --path /properties/cc/quota_definitions`

- 3 Order of the hash will be changed, causing an update of the CC `instance_group`, plus related ones.

  I would expect to have the exact `properties.cc.quota_definitions` hash structure, without any change.

## Current result
The hash change the order.

## Possible Fix

While I agree that a change in the hash order its due to the YAML parser used, I think the order inside `properties.cc.quota_definitions`should never change, and the only way I see to ensure that, its to move that to an `array` structure.

## `name of issue` screenshot

quota_definitions hash should become an array

**Comment by ljfranklin** [comment]
@qu1queee interesting find, unnecessarily rolling the CC VMs is definitely something we'd like to avoid. However, this seems like a problem with BOSH treating key order as significant in hashes when it shouldn't. Looks like you already opened an issue on the BOSH CLI that is getting some traction: https://github.com/cloudfoundry/bosh-cli/issues/290. In order to avoid duplicate effort, I'm going to close out this issue in favor of that one. If the BOSH team concludes that something should change on the CC side, please re-open.

**Comment by aashah** [comment]
`cc.quota_definitions` was also removed from the clock and worker jobs too as part of https://www.pivotaltracker.com/story/show/136759317
