### ISSUE TITLE
List UPS Routes documents invalid query parameter

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cloud_controller_ng#900]
## Issue

List all routes for a user provided service instance, filtering by organization id, fails with `CF-BadQueryParameter(10005): The query parameter is invalid: organization_guid`

## Steps to Reproduce

GET https://api.local.pcfdev.io/v2/user_provided_service_instances?q=organization_guid%20IN%20{org id here}

## Expected result

Lists routes filtered by org id (but not really, see possible fix)

## Current result

`CF-BadQueryParameter(10005): The query parameter is invalid: organization_guid`

## Possible Fix

1. Remove the `organization_guid` filter from the documentation, as I don't believe it's valid.
2. Check all places where routes are listed for the same failure. The same basic problem has been reported and fixed at least twice, it's inefficient for everyone to keep reporting it.

**Comment by ljfranklin** [comment]
@twoseat in your "Steps to Reproduce", did you intend for your URL to be `https://api.local.pcfdev.io/v2/user_provided_service_instances/SERVICE_GUID/routes`? The `/v2/user_provided_service_instances` endpoint does support `organization_guid` as a query param but `/v2/user_provided_service_instances/SERVICE_GUID/routes` does not. This does seem like a docs bug as a service instance is already scoped to a space and org so all routes implicitly belong to the same org.

> The same basic problem has been reported and fixed at least twice

Are you talking specifically about past issues related to routes or a more general issue around docs? I'm not sure what type of audit you're asking for here.

**Comment by twoseat** [comment]
My mistake, apparently I'm really bad at copy/paste! `/v2/user_provided_service_instances/SERVICE_GUID/routes` is indeed what I meant.

I'm referring specifically to routes-related issues. For example, I just tried the same query as this but for 'normal' services (i.e. /v2/service_instances/SERVICE_GUID/routes) and get the same error.

**Comment by zrob** [comment]
document will be updated in the next capi-release.  thanks for the report!
