### ISSUE TITLE
API: arbitrary metadata for organizations and spaces

### ISSUE THREAD

**Issue by giner** [cloudfoundry/cloud_controller_ng#905]
Would it be possible to extend schema for arbitrary metadata for organizations and spaces so that operators don't need keep it separately in a different database? The simplest thing would be just "description" field which that could be modified directly.

**Comment by Gerg** [comment]
Please see https://github.com/cloudfoundry/cloud_controller_ng/issues/904#issuecomment-337038502

**Comment by cwlbraa** [comment]
this is towards the tail end of a set of planned features that is scheduled and in progress! you can follow along with the initial bits here if you'd like: https://www.pivotaltracker.com/story/show/160942050

The very first pass on this will be labels & selectors for apps, which are queryable and have length-constrained values. After that will come the the rest of the api resources. Eventually we also plan on adding an equivalent of the k8s annotations API, which will be unqueryable and less length-constrained on the values.

We'll come back here and close this once we have some tracker markers for those annotations.

**Comment by gberche-orange** [comment]
See related documentation at https://docs.cloudfoundry.org/adminguide/metadata.html

**Comment by cwlbraa** [comment]
yeah, this is done!
