### ISSUE TITLE
Add support for multiple route services

### ISSUE THREAD

**Issue by sorenh** [cloudfoundry/cloud_controller_ng#906]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

A route should be able to have multiple route service instances associated with it.

## Context

Route services are an extemely handy way of providing shared functionality across many applications.  E.g. http://docs.cloudfoundry.org/services/route-services.html gives a couple of examples: Request logging and rate limiting. Other examples could be virus scanners, authn/authz, etc. A given application could benefit from mulitple services. They should not be mutually exclusive. 

## Steps to Reproduce

Trying to add a second route service to a route yields:

    Server error, status code: 400, error code: 130007, message: A route may only be bound to a single service instance

## Expected result

I expected the route services to be stacked so requests would pass through all the route services.

## Current result

I think I explained this already.

## Possible Fix

To achive this, we need to obviously allow multiple route services to be configured for a route. For the request flow to work, I suggest:
1. A request comes to the gorouter.
2. The gorouter builds a list of route services the request must go through. This list is added to `X-CF-Proxy-Metadata`.
3. The gorouter pops the first one off the list, and sends the request to that URL following the exact same protocol we use right now for route services.
4. The route service follows the same protocol as always, i.e. eventually forwards the request to `$X-CF-Forwarded-Url`.
5. The gorouter receives the request from the route service, decodes the `X-CF-Proxy-Metadata` header and finds that there are more route services in the list and goes back to step 3.

This adds an extra roundtrip to the gorouter for each additional route service. It, however, is entirely transparent to route services, so we maintain backwards compatibility.

To prevent this extra roundtrip each time, we can:
1. Make gorouter add a `X-CF-Route-Services` header containing the list remaining services. The final element in the list will be identical to `X-CF-Forwarded-Url`.
2. If a given route service supports this new protocol, instead of sending the request to `X-CF-Forwarded-Url`, it may pop off the first element of X-CF-Route-Services and use it instead of `X-CF-Forwarded-Url`.
3. If a given route service does not support it, it will simply send the request to `X-CF-Forwarded-Url`, i.e. the gorouter.
4. If the gorouter receives a request (with correct proxy signature) and a non-empty `X-CF-Route-Services`, it knows it comes from a route service which did not support this new protocol. Using the value of `X-CF-Route-Services` and the route service list in `X-CF-Proxy-Metadata` (established above) it knows how many elements to strip off its list and then it proceeds as usual.

Example flow:

5 route services:
  `https://svc1.example.com/`
  `https://svc2.example.com/`
  `https://svc3.example.com/`
  `https://svc4.example.com/`
  `https://svc5.example.com/`

Route: https://app.example.com/

A client sends a request to https://app.example.com/. The gorouter receives it, and constructs these headers:

    X-CF-Forwarded-Url: https://app.example.com/
    X-CF-Route-Services: https://svc2.example.com/, https://svc3.example.com/, https://svc4.example.com/, https://svc5.example.com/, https://app.example.com/
    X-CF-Proxy-Signature: d8d469f3e6b9c9bee2b20deed9824b21ee8ace1
    X-CF-Proxy-Metadata: (encrypted route service list: https://svc2.example.com/, https://svc3.example.com/, https://svc4.example.com/, https://svc5.example.com/)

...and sends the request to https://svc1.example.com/ which supports this new protocol. It pops https://svc2.example.com/ off the X-CF-Route-Services header and sends these headers to svc2:

    X-CF-Forwarded-Url: https://app.example.com/
    X-CF-Route-Services: https://svc3.example.com/, https://svc4.example.com/, https://svc5.example.com/, https://app.example.com/
    X-CF-Proxy-Signature: d8d469f3e6b9c9bee2b20deed9824b21ee8ace1
    X-CF-Proxy-Metadata: (encrypted route service list: https://svc2.example.com/, https://svc3.example.com/, https://svc4.example.com/, https://svc5.example.com/)

svc2 also supports this new protocol and eventaully sends these headers to svc3:

    X-CF-Forwarded-Url: https://app.example.com/
    X-CF-Route-Services: https://svc4.example.com/, https://app.example.com/
    X-CF-Proxy-Signature: d8d469f3e6b9c9bee2b20deed9824b21ee8ace1
    X-CF-Proxy-Metadata: (encrypted route service list:  https://svc2.example.com/, https://svc3.example.com/, https://svc4.example.com/, https://svc5.example.com/)

svc3 does not support this new protocol. It sends the request to X-CF-Forwarded-Url, i.e. the gorouter using the exact same headers:

    X-CF-Forwarded-Url: https://app.example.com/
    X-CF-Route-Services: https://svc4.example.com/, https://svc5.example.com/, https://app.example.com/
    X-CF-Proxy-Signature: d8d469f3e6b9c9bee2b20deed9824b21ee8ace1
    X-CF-Proxy-Metadata: (encrypted route service list:  https://svc2.example.com/, https://svc3.example.com/, https://svc4.example.com/, https://svc5.example.com/)

The gorouter detects a valid Signature and Metadata and a non-empty X-CF-Route-Services.
First it checks if the last element (`https://app.example.com`) matches the route it's currently handling. It does, so we're happy. Otherwise, we bail out.
Ignoring the last element of X-CF-Route-Services, the gorouter goes backwards through each element comparing it to the list in the metadata header. I.e. does https://svc5.example.com/ from `X-CF-Route-Services` match the last element of route services list? Yes. Does https://svc4.example.com/ match the next element? Yes. As there are no more elements in X-CF-Route-Services to compare, we must be receiving this request from the next element in the list from the metadata header (i.e. svc3) after having gone through svc1 and svc2.

The gorouter then removes svc2, and svc3 from the list in the metadata header and sends these headers to svc4:

    X-CF-Forwarded-Url: https://app.example.com/
    X-CF-Route-Services: https://svc5.example.com/, https://app.example.com/
    X-CF-Proxy-Signature: e4a9591221b78fbf55f68c82d7f9a767085e7c
    X-CF-Proxy-Metadata: (encrypted route service list: https://svc5.example.com/)

svc4 supports the new protocol, so ends up sending this to svc5:

    X-CF-Forwarded-Url: https://app.example.com/
    X-CF-Route-Services: https://app.example.com/
    X-CF-Proxy-Signature: e4a9591221b78fbf55f68c82d7f9a767085e7c
    X-CF-Proxy-Metadata: (encrypted route service list: https://svc5.example.com/)

svc5 also supports the new protocol so sends this to the app route:

    X-CF-Forwarded-Url: https://app.example.com/
    X-CF-Proxy-Signature: e4a9591221b78fbf55f68c82d7f9a767085e7c
    X-CF-Proxy-Metadata: (encrypted route service list: https://svc5.example.com/)

The gorouter sees an empty (or non-existing) X-CF-Route-Services list and a valid proxy signature and finally sends the request to the application.

I hope this is clear. I'm in a bit of a rush, so did not have much time for editing.

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by zrob** [comment]
Hey @sorenh 

It's great to hear that you're able to achieve so many use cases with route services!  Since this feature request is mostly a routing concern I'm going to ping @shalako, the PM for CF Routing.  It may make sense to move this over to the [gorouter repository](https://github.com/cloudfoundry/gorouter), since that is where this would mostly land, but let's see what Shannon has to say.

Thanks!

**Comment by sorenh** [comment]
@zrob Agreed, this is mostly a gorouter issue, but let's see what Shannon has to say.

**Comment by shalako** [comment]
Hello @sorenh 
Thank you for your feedback regarding chaining of route services. I have recorded your interest. At this time we don't have a timeline for delivery but we have recently been considering again how we might deliver on this in the context of other efforts under way. 

Thank you also for putting some thought into a solution. We have considered something like this before but it helps to have your documented workflow. We are also considering a solution whereby each node in the chain receives individualized routing rules from a central API, requiring no coordination by Gorouter.

I would expect the app developer facing UX to be the same whatever the solution. This UX may be provided by CAPI or another API. Moving this issue to routing-release or gorouter is fine. Or keep it here. I'm going to link to it from my evidence documentation wherever it lives.

**Comment by zrob** [comment]
Closing now that we have a response.  If you would like to further pursue this please create an issue with the gorouter.

Thanks!
