### ISSUE TITLE
Network info not available in staging tasks

### ISSUE THREAD

**Issue by salv-orlando** [cloudfoundry/cloud_controller_ng#911]
## Issue

Network properties for tasks, i.e:

  "properties": {
    "app_id": "<app_id>",
    "org_id": "<org_id>",
    "policy_group_id": "<app_id>",
    "space_id": "<space_id>"
  }

show up only for app tasks, and not for staging tasks. This information might be used by 3rd parties to provide network connectivity for staging tasks.

## Context

Commit https://github.com/cloudfoundry/cloud_controller_ng/commit/bc3afaf3a519b2a76fa5bfba50ed19a10b2e2aaf add support for network info in tasks, but it was limited to app tasks. This support should actually be provided also for staging tasks. Currently in the BBS no network info for staging tasks is seen (and we ensured temporary_local_staging is set to True in cloud controller configuration)

Also, note that the commit above brings also changes to protocol.rb and other module that send task info to the stager, but there's no related commit for the stager service, meaning that when temporary_local_staging is disabled, no task info is anyway sent to the BBS (this is however a side note and not the focus of this issue report)

## Steps to Reproduce

Push an app. Use cfdot to list tasks.
Checkout task info for the app's staging tasks.
No network properties will be found.

## Expected result

Task info should have a network attribute filled with a data structure like the following:

  "properties": {
    "app_id": "<app_id>",
    "org_id": "<org_id>",
    "policy_group_id": "<app_id>",
    "space_id": "<space_id>"
  }

## Current result

Task info are populated but there is no network attribute for staging tasks.

## Possible Fix

Trivial: add network_info to build_staging_task

## `name of issue` screenshot

N/A

**Comment by Gerg** [comment]
Hey @salv-orlando,

Looks like this issue was fixed by your PR. Please re-open if I am mistaken.

Thanks,
Greg
