### ISSUE TITLE
Emit number of apps running

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cloud_controller_ng#920]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

It seems currently CC does not emit the number of applications running. 

## Context

The number of running apps was previously emitted by the HM, but this was lost with the move to Diego: the only metrics available now are for LRPs but they don't directly correlate to the number of apps.

## Expected result

The following metrics should be available in the component metrics:
- number of applications in desired state: STARTED
- number of total applications

Ideally the metrics should be emitted both aggregated and broken down by isolation segment and 
stack.

## Current result

These metrics seem to be not available. No such metric is described on https://docs.cloudfoundry.org/running/all_metrics.html.

**Comment by Gerg** [comment]
Hey @CAFxX,

Can you expand on your use-case for these metrics? Unlike HM, Diego does not have the concept of an "app," so it cannot emit this metric.

Thanks,
Greg

**Comment by CAFxX** [comment]
@Gerg the use case is knowing how many applications are running. It's a good KPI that our management wants to track.

To clarify, he STARTED/STOPPED *desired* states I'm referring to ("number of applications in desired state: STARTED", "number of total applications") are those stored by the cc in ccdb for each app.

**Comment by Gerg** [comment]
Currently the metrics that we emit are focused on resource usage and system health. I can see the value in metrics like this that show general platform usage, however they are not currently in our roadmap. 

For now, you can construct this metric as follows: `cf curl /v3/apps?per_page=1 | jq .pagination.total_results`

Thanks,
Greg

**Comment by giner** [comment]
As of now we use cfdot for this:

```
    # Get metrics from bbs, parse them and build json
    #
    # Sample value of $bbs_actual_lrp_json:
    # {
    #   "num_of_applications": 62,
    #   "num_of_instances": {
    #     "crashed": 1,
    #     "running": 78
    #   }
    # }
    #
    bbs_actual_lrp_json=$(
        timeout $TIMEOUT \
        cfdot actual-lrp-groups |
        jq -s '[ .[] | .instance, .evacuating | values ] |
               { "num_of_applications": ( group_by(.process_guid) | length ),
                 "num_of_instances": [ group_by(.state)[] | {"key": .[0].state | ascii_downcase, "value": length} ] | from_entries
               }'
    )
```

**Comment by cwlbraa** [comment]
cfdot is a great way to solve this, and there's also that nice [hacky curl](https://github.com/cloudfoundry/cloud_controller_ng/issues/920#issuecomment-337056334) that gerg provided about.
