### ISSUE TITLE
500 Internal Server Error Python Flask

### ISSUE THREAD

**Issue by VenkatArra** [cloudfoundry/cloud_controller_ng#921]
I am using Cloud Foundry and deployed Python Flask app to BlueMix. But after running the app from the URL link, I am getting 500 Internal Server Error. I ran the Python model from DSX and it worked fine.

Please help to resolve this issue.

**Comment by Gerg** [comment]
Hey @VenkatArra,

I suggest you contact BlueMix support. You can reach them here: https://support.ng.bluemix.net/gethelp/

Thanks,
Greg
