### ISSUE TITLE
Support softlayer fog lib.

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry/cloud_controller_ng#924]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue
I am not able to use softlayer fog lib after upgrade cf v235 to v254.

## Context
I got an error message on API job while upgrading cf v235 to v254.
/var/vcap/sys/log/cloud_controller_ng/post-start.stderr.log:[2017-09-29 17:42:52+0000] ArgumentError: softlayer is not a recognized provider

**Comment by Gerg** [comment]
Hey @YunSangJun 

We moved to supplying a specific sub set of fog providers due to incompatibilities between the core fog set and certain providers. We would be happy to add softlayer support back into CC.

Thanks,
Greg

**Comment by YunSangJun** [comment]
Hello.

I connected to softlayer swift obejct storage using openstack fog v1.
So i close this issue.

The following is sample for v1.
      fog_connection: &fog_connection
        provider: OpenStack
        openstack_username: ((sl_swift_storage_username))
        openstack_api_key: ((sl_api_key))
        openstack_auth_url: ((sl_swift_storage_auth_url))
        openstack_temp_url_key: ((sl_swift_storage_temp_url_key))
