### ISSUE TITLE
api docs for app events include non-app related events?

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cloud_controller_ng#925]
## Issue

API docs have two entries for events:
http://apidocs.cloudfoundry.org/272/events/list_all_events.html
http://apidocs.cloudfoundry.org/272/events/list_events_associated_with_an_app_since_january_1,_2014.html

Although the latter looks like an example usage of the first (bit strange to include it on the main API list), "list events associated with an app" would be a useful entry as it's used by `cf events`.

The issue is that it's not clear what events to expect from the latter API response. The title is "associated with an app" but the table of event types include types that sound unrelated:

* audit.service_broker.create
* audit.service_broker.delete
* audit.service_broker.update
* audit.service_dashboard_client.create

## Context

I'm looking for a (canonical) list of possible types returned in `cf events` to include in the docs, so looking for a list of types returned when `q=actee:<app-guid>` is used.

## Possible Fix

Rename latter entry to only filter by `q=actee:<app-guid>` and adjust response details accordingly.

**Comment by elenasharma** [comment]
@dkoper Thanks for pointing this out. We're going to clean up and update the event types listed in the latter document you link to.

**Comment by tcdowney** [comment]
The team made an editing pass on the docs here: https://github.com/cloudfoundry/cloud_controller_ng/commit/2f528d0cbdaad3c970c7abde40a34f949b71bbb0. Closing this out as fixed, but please re-open if something looks off.
