### ISSUE TITLE
`cf push -b null` fails with Bad Request

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/cloud_controller_ng#927]
## Issue

When using `cf push` with `-b null` as documented in the [cf CLI documentation](http://cli.cloudfoundry.org/en-US/cf/push.html) ("To use built-in buildpacks only, specify `default` or `null`"), current versions of CC return the following error:

```
Server error, status code: 400, error code: 100001, message: The app is invalid: Must specify either a buildpack_url or an admin_buildpack_name`
```

This seems to be a regression introduced in https://github.com/cloudfoundry/cloud_controller_ng/commit/9adc16469e6a4579e5ec72554f393a0f2d234543 where the `validate` method explicitly rejects an empty `buildpack_url` even though the cf CLI sets it to empty when it gets `-b null` as can be seen in https://github.com/cloudfoundry/cli/blob/master/cf/commands/application/push.go#L726-L732

Expected behavior is that this CLI option still works as documented.

**Comment by Gerg** [comment]
Hey @petergtz 

I believe we recently fixed this issue as part of this story: https://www.pivotaltracker.com/story/show/150502954

Can you check an see if this is still broken on the most recent CAPI release?

Thanks!

**Comment by petergtz** [comment]
Hi @Gerg,

Thanks for your response. I will check as soon as I can, but it might still be a while. So I'll close this for now, given that you actually had a story for this. Will re-open if necessary.

Thanks,
Peter
