### ISSUE TITLE
Emit metrics / events for monitoring service brokers

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/cloud_controller_ng#929]
## Issue

cloud_controller_ng does not emit metrics relating to interactions with service brokers. More specifically, it does not allow for the monitoring of failed interactions with service brokers.

## Context / Why

We want to be able to monitor and alert on failed service bindings, and possibly in the future monitor  other failed interactions with service brokers.

At first we are looking at alerting on 5xx errors received by Cloud Controller from any service broker. We have explored solutions, such as:

* having the brokers emit the metric: this does not cover situations where a request manages to get through to a broker which is completely down.
* parsing logs: this would fail silently if the messages failed to log or the message format changes.
* parsing service binding events from the CF API: not feasible. Events are not created for failed bindings. This is because the _creation_ of a service binding is the event, not the request to bind.

## Possible Fix

Two suggested solutions:

* emitting metrics relating to interactions with service brokers, specifically providing failure metrics for use in monitoring (4/5xx error responses from the different endpoints).
* extending the existing events to include requests for service bindings (and other operations) _and_ their outcome, not just the creation events.

**Comment by Gerg** [comment]
Hey @henrytk.

I think emitting more metrics would be the best way to provide additional visibility into service broker interactions. What types of metrics would you be most interested in? How would you want them to be bucketed?

Thanks!

**Comment by LeePorte** [comment]
Hi Gerg

To give you a little more context around this, we had an issue where a code change to one of our service brokers caused tenants to not be able to bind or unbind the backing service provided by that broker for existing instances, new instances were unaffected though. We managed to track this down after a while, however being able to trigger alerting of non normal status would have helped significantly.

Ideally focussing on the broker API would seem like a good place to start so emitting metrics and events regarding the different broker API operations.

 - Create
 - Bind
 - Unbind
 - Delete
 - Last Operation
 - Catalogue
 - Service ID
 - Plan name

Success, failure and time taken would be an excellent start. By having both the success and failure status would enable us to calculate success rates on which we can report.

If you are planning on adding events, it would be great if the success and error messages were passed.

In a normal situation all of these should succeed, it is only in a non-normal situation where failures would be expected. e.g. provider is in degraded service, code change has broken / is impacting on the time taken for an operation.

In terms of bucketing, grouping by broker or service name/UUID and a 1 minute interval for emitting the data would be perfect.

Thanks

Lee

**Comment by henrytk** [comment]
Sounds good to me @LeePorte

**Comment by christarazi** [comment]
Closing in favor of #1243
