### ISSUE TITLE
Cannot register same service-broker in multiple spaces using `--space-scoped`

### ISSUE THREAD

**Issue by avade** [cloudfoundry/cloud_controller_ng#935]
## Issue

The same service-broker cannot be registered for multiple spaces as a `space-scoped` broker.

## Steps to Reproduce

```
cf target -s space-a

cf create-service-broker my-broker user pass https://mybroker.cfapps.io --space-scoped
SUCCESS

cf target -s space-b

cf create-service-broker my-broker user pass https://mybroker.cfapps.io --space-scoped
Creating service broker mybroker in org demo / space space-b as example@pivotal.io...
FAILED
Server error, status code: 400, error code: 270003, message: The service broker url is taken: https://mybroker.cfapps.io
```

## Expected result

That I can register the same broker in multiple spaces using `--space-scoped`, as multiple spaces may want to use the same service-broker, but it is not a global service-broker.

## Current result

It fails with the above error

## Possible Fix

Allow the same broker to register in multiple spaces, as long as there is no global broker that conflicts.

**Comment by Gerg** [comment]
@avade Can you expand on your use-case? When would you want a space-scoped broker in multiple spaces rather than a global broker with limited visibility?

**Comment by avade** [comment]
The use case is:

I am a space developer in two spaces, I want to register an external broker
or broker I have pushed, in two spaces.

I do not want to talk to the admin and likely can't get it registered
globally as I am using a public Cloud Foundry provider.

**Comment by Gerg** [comment]
It looks like this is the same as this issue: #837. I think Zach's comment still holds, but we we reconsider this since this is the second time we have heard this request.

**Comment by mattmcneeney** [comment]
Closing this in favour of #837
