### ISSUE TITLE
Where is the best place to submit suggestions?

### ISSUE THREAD

**Issue by MFranca** [cloudfoundry/cloud_controller_ng#936]
Hello folks, 
I would like to submit a suggestion to the next version of the API. I'm a PhD student here in Brazil, and I'm using CF API as one of the tools supporting my research.
By the way, I have already asked this in the Slack channel (Cloud Foundry #general), but no reply so far... =)
Thanks in advance.

**Comment by Gerg** [comment]
Hey @MFranca 

If you have a feature request, you can create an issue here on github. If you want to discuss things about the API, #capi in the Cloud Foundry slack is the correct channel.

Thanks,
Greg
