### ISSUE TITLE
New OpenAPI Specification Field (New Request)

### ISSUE THREAD

**Issue by MFranca** [cloudfoundry/cloud_controller_ng#939]
Hey @Gerg ,  I, also, would like to suggest an additional field on the next API version... I hope there is no problem to "get a ride" on this one (#904) since I believe it'similar... 

So, **my suggestion is to add a field, to the Service JSON, that would store the link for the OpenAPI (former Swagger) specification for the service - https://www.openapis.org/.** 

E.g., 
`GET /v2/services`
```
{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "1993218f-096d-4216-bf9d-e0f250332dc6",
        "url": "/v2/services/1993218f-096d-4216-bf9d-e0f250332dc6",
        "created_at": "2016-06-08T16:41:31Z",
        "updated_at": "2016-06-08T16:41:26Z"
      },
      "entity": {
        "label": "label-57",
        "provider": null,
        "url": null,
        "description": "desc-134",
        "long_description": null,
        "version": null,
        "info_url": null,
        "active": true,
        "bindable": true,
        "unique_id": "4ab67d2e-18c0-4a36-8eed-fdee36fdd61b",
        "extra": null,
        "tags": [

        ],
        "requires": [

        ],
        "documentation_url": null,
        "openapi_url": null, # <====== HERE
        "service_broker_guid": "34b94a65-3cd3-4655-8c07-e2bd94ae21c5",
        "plan_updateable": false,
        "service_plans_url": "/v2/services/1993218f-096d-4216-bf9d-e0f250332dc6/service_plans"
      }
    }
  ]
}
```
**Justification**: As far as I understand, differently than "traditional" SOAP/XML webservices that you could just append "?wsdl" to an endpoint to retrieve all method signatures (operations available), for new RESTful services using **Swagger/OpenAPI standard** for documenting purpose, there is no way to automatically discover the url for the specification... :-( So, developers would benefit from knowing where to look for the OpenAPI specification, and applications could dynamically find and consume specific operations...

Ref.: https://apidocs.cloudfoundry.org/272/services/list_all_services.html

**Comment by gberche-orange** [comment]
Relates to https://github.com/cloudfoundry/cc-api-v3-style-guide/issues/46

**Comment by christarazi** [comment]
Closing in favor of cloudfoundry/cc-api-v3-style-guide#46.
