### ISSUE TITLE
`users_can_select_backend` defaults to true

### ISSUE THREAD

**Issue by njbennett** [cloudfoundry/cloud_controller_ng#942]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue
`users_can_select_backend` defaults to true

## Context
The DEAs are gone. Trying to set the backend will only bring sadness.

## Possible Fix
`users_can_select_backend` should default to false

**Comment by ljfranklin** [comment]
@zrob sounds reasonable to me. WDYT?

**Comment by zrob** [comment]
We should just go ahead and remove this property entirely

**Comment by zrob** [comment]
it's gone!
