### ISSUE TITLE
cfdreddbot double posts

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/cloud_controller_ng#960]
## Issue

In pull requests to this repo, cfdreddbot is repeating itself. 

## Context

Bots will never manage to take over the world with illogical behaviour like this.

## Steps to Reproduce

1. Open a Pull Request
1. Observe cfdreddbot responding twice immediately

## Screenshot

![image](https://user-images.githubusercontent.com/3200507/31944087-ce4f0384-b8c2-11e7-8065-b0ea4f543a82.png)

**Comment by ljfranklin** [comment]
@jenspinney huh, totally didn't notice that. Turns out we had the dredd bot webhook configured twice on this repo. We've taken care of the imposter, let us know if you see him again...
