### ISSUE TITLE
CC is not emitting the CEF logs

### ISSUE THREAD

**Issue by ArthurHlt** [cloudfoundry/cloud_controller_ng#962]
This is directly related to the story on pivotal tracker [#151811590](https://www.pivotaltracker.com/n/projects/966314/stories/151811590).

I do not use the issue template only because maybe I can bring precision about this issue, I saw how it has been corrected by pushing CEF logs in a file instead of syslog.

On CC api vm there is a file called `/etc/rsyslog.d/00-syslog_forwarder.conf` inside this file there is this line: `:programname, startswith, "vcap." ~` 
This is actually what causing this issue. If we remove it, it obviously emitting logs to the syslog set in a [syslog-release](https://github.com/cloudfoundry/syslog-release) deployment because CEF logs are sent as `vcap.cloud_controller_ng`. 

There is also another way to make it works, if the [file](https://github.com/cloudfoundry/syslog-release/blob/master/jobs/syslog_forwarder/templates/pre-start.erb#L14) created by syslog release (called `/etc/rsyslog.d/rsyslog.conf`) is renamed to be the first the file loaded by rsyslog like `/etc/rsyslog.d/00-syslog.conf` CEF logs will be correctly emitted (because `:programname, startswith, "vcap." ~` is applied after). We have a created a syslog-release tweaked in this way which can be found here: https://github.com/orange-cloudfoundry/syslog-release/releases/tag/v12 (I don't like that much the fix here but it was the only way to make it works in older cloud foundry version)

And finally there is a third way, program name given by CEF middleware could use another name than `vcap.cloud_controller_ng` which could be simply `cloud_controller_ng.cef`. 

I hope it can help to be more generic because the file `/etc/rsyslog.d/00-syslog_forwarder.conf` is present in all cf-release vms and this issue could be found in another components.

**Comment by ljfranklin** [comment]
@ArthurHlt Appreciate you opening an issue to clarify things. Just to make sure, does the writing CEF logs to a file work for you?

Our working theory is that the environments which were missing CEF logs had both syslog-forwarder release co-located AND had metron-agent configured as a syslog forwarder. In envs where both these components were enabled, the CEF logs might be missing. Do you have multiple forwarders enabled in your environment?

**Comment by zrob** [comment]
closed due to inactivity
