### ISSUE TITLE
'Invalid Auth Token' errors after changing 'uaa.issuer'

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/cloud_controller_ng#977]
## Issue

Changing the `uaa.issuer` (in [uaa-release](https://github.com/cloudfoundry/uaa-release/blob/390fd06ed8bbc05fa198c88febed4de08d2adda8/jobs/uaa/spec#L113)) results in cloud controller rejecting tokens.

## Context

As cloud controller [caches the issuer](https://github.com/cloudfoundry/cloud_controller_ng/blob/3052dc9fc0bbd0026eae090385b8ad1fba14f2c4/lib/cloud_controller/uaa/uaa_token_decoder.rb#L94), an update of uaa leads to a mismatch between new issuer and cached issuer that results in `Invalid Auth Token` errors (caused by a [`BadToken` exception](https://github.com/cloudfoundry/cloud_controller_ng/blob/3052dc9fc0bbd0026eae090385b8ad1fba14f2c4/lib/cloud_controller/uaa/uaa_token_decoder.rb#L76)).

Of course, restarting cloud controller fixed this problem, but this will not work without downtime in a production environment.

## Steps to Reproduce

- Change `uaa.issuer` and re-deploy `cf`.
- Login with `cf cli`.

## Expected result

Login and all other operations should be working.

## Current result

`Invalid Auth Token` error is shown.

## Possible Fix

- Configuration property to optionally specify the issuer or a list of valid issuers.
- Configuration switch to temporarily disable issuer verification.
- Refresh cached issuer, i.e. if a mismatch between issuer specified in the token and cached issuer is detected, retrieve current issuer again from uaa (if not already done within e.g. the last hour).

**Comment by ssisil** [comment]
Fixed here - https://www.pivotaltracker.com/story/show/152673415
