### ISSUE TITLE
cf share-domain should allow for ownership reassignment

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/cloud_controller_ng#986]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

cf allows the sharing of a domain using `share-domain`, however once other organizations use the domain and create routes, if the original sharing organization requests to be deleted, all depending domain users will have their domains removed during the org deletion.  This operation can sometimes fail per Issue #985, but if it doesn't fail they are all gone.

## Possible Fix

`cf share-domain` should allow for full transfer of ownership, or otherwise allow the record to remain if the origin org is deleted but other organizations are still using the domain.

**Comment by christarazi** [comment]
Is this something we want to do in v3 @Gerg?

@christarazi && @cwlbraa

**Comment by Gerg** [comment]
It's certainly something we could consider. I don't think we have any prior art for migrating resources between orgs/spaces, but certainly something we could explore. For example, I imagine there could be some people are interested in migrating apps/service instances between spaces.

**Comment by sethboyles** [comment]
Considering we recently hit the 3-year mark on this issue without any movement, I'm going to close this issue.
