### ISSUE TITLE
How to query the event by timestamp

### ISSUE THREAD

**Issue by maoyi8212** [cloudfoundry/cloud_controller_ng#991]
## Issue
Currently I am trying to query the audit.app.create events by calling CC V2 API. when I only query the events by type by following command, it works well.
`curl --header 'Authorization:  bearer XXXXX' -k https://<ENTRY_OF_CF>/v2/events?q=type:audit.app.create`

But when I tried to add a query condition for the timestamp, it seems not works. I have tried several different ways to do the query, but none of them works. Could you please tell me how to do the query for the timestamp?

`curl --header 'Authorization:  bearer XXXXXX' -k https://<IP_OF_CF_ENTRY>/v2/events?q=type:audit.app.create&q=timestamp%3E2017-11-08+00%3A00%3A00-00%3A00`

`curl --header 'Authorization:  bearer XXXXXX' -k https://<IP_OF_CF_ENTRY>/v2/events?q=type:audit.app.create&q=timestamp>2017-11-08T00:00:00.00000Z`

Many thanks!

**Comment by elenasharma** [comment]
@maoyi8212 Looking at your question, the [docs](https://apidocs.cloudfoundry.org/272/events/list_app_create_events.html) for that endpoint might be helpful. In particular, the format for `timestamp` that we use is like "2016-06-08T16:41:23Z". 

If this doesn't work, we'd be happy to help you in the [#capi Slack channel](https://cloudfoundry.slack.com/messages/C07C04W4Q/).

**Comment by maoyi8212** [comment]
@elenasharma I have tried your format, but it seems still not works. Just like the filter condition is not exisit. The same results outputs just like the only query condition is "type=audit.app.create "

And it seems that I can not join the capi slack channel, because   @get-an-invite-at.slack.cloudfoundry.org or @vmware.com email address is required.

**Comment by elenasharma** [comment]
@maoyi8212 Hmm, that is odd behavior from the endpoint. You can get an invite by going to `http://slack.cloudfoundry.org/`.

**Comment by maoyi8212** [comment]
@elenasharma I have put a request in Slack, but got no response yet. 
Actually now I can query the events by timestamp, for example: curl --header 'Authorization: bearer XXXXX' -k https://api.run.pivotal.io/v2/events?q=timestamp%3E2017-11-14T08%3A55%3A53Z
I can also query the events by the type, for example: curl --header 'Authorization: bearer XXXXX' -k https://api.run.pivotal.io/v2/events?q=type:audit.app.create

But when I combined the two query condition together, the second query condition seems never take effect. So my question is that whether the combination query is supported by CC API event entry? My CC API version is 2.98. Many thanks!

**Comment by elenasharma** [comment]
@maoyi8212 did you post in the #capi Slack channel in the Cloud Foundry organization? Here is [the link](https://cloudfoundry.slack.com/messages/C07C04W4Q/) to that channel. I might have missed your question, but I don't see one.

As to your question, we do support using multiple query parameters. An example request for querying for events by type and timestamp would be: `cf curl '/v2/events?q=type:audit.organization.create&timestamp%3e2017-11-17:22:06:00'`.

**Comment by maoyi8212** [comment]
@elenasharma I have found the issue. When I use curl command directly to call the API, the issue happens, but when I switch to "cf curl", the results seems no problem. But I do not know why the curl command has the issue.
Thanks a lot for your great support!
