### ISSUE TITLE
CF update-service has no option to update dashboard URL

### ISSUE THREAD

**Issue by kamath-prasad** [cloudfoundry/cloud_controller_ng#995]
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

"cf update-service" does not provide any option to update the dashboard URL

## Context

1. Currently we use the dashboard_url parameter (https://apidocs.cloudfoundry.org/272/service_instances/creating_a_service_instance.html) to set the service instance dashboard URL while creating a new service instance .

2. We provide the instance id , plan id and other needed details in the URL that can be used to render the details in the dashboard. The dashboard is rendered by the custom code in the service broker.

3. When the instance plan gets updated via "cf update-service" , we see that the dashboard url remains unchanged since there is no option to update the value for dashboard_url . This leads to incorrect rendering of details in the instance dashboard.

## Steps to Reproduce

1. create an instance by passing a value for dashboard_url in the response body.
2. update of the same instance has no option to take in updated value for dashboard_url.

## Expected result

update of the same instance should have an option to take in updated value for dashboard_url.

## Current result

update of the same instance does not have an option to take in updated value for dashboard_url.

## Possible Fix

Enhanced the update service code to provide an option to read the dashboard_url from the response body of broker and keep updating the value of dashboard_url that is set during instance provisioning.

**Comment by zrob** [comment]
Hi @kamath-prasad 

The dashboard url is a field that is managed by the broker and not by users.  It is not intended for a user to update this field, since this could cause it to no longer match what the broker is expecting to present a management interface.

When you run `cf update-service` this results in a call to the broker.  If the broker were to return a new dashboard url, then the value would be updated.

**Comment by kamath-prasad** [comment]
@zrob : We tried sending a value for dashboard_url attribute in the response body , but see that the cloud controller code does not have any hook to update the value of dashboard_url and the value never gets updated . 

Hook only present in create - https://github.com/cloudfoundry/cloud_controller_ng/blob/11be238bceb1d3f0dd6b9ae913eac4225345ef59/lib/services/service_brokers/v2/client.rb#L43

No hook to update the value in update method -

https://github.com/cloudfoundry/cloud_controller_ng/blob/11be238bceb1d3f0dd6b9ae913eac4225345ef59/lib/services/service_brokers/v2/client.rb#L185-L231

Can you please confirm this understanding ?

**Comment by zrob** [comment]
@kamath-prasad 

The service broker api recently merged a change to allow this here https://github.com/openservicebrokerapi/servicebroker/pull/437

Pinging the SAPI team about plans to add support @mattmcneeney

**Comment by kamath-prasad** [comment]
@zrob : Thanks for the update ! We actually made a workaround recently in our broker to handle the flow in update case as well - https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/277 .

However it will be great if platform handles this as we can avoid additional calls to CC !!

@mattmcneeney : please let us ETA once this item gets picked up implementation.

**Comment by mattmcneeney** [comment]
Hey @kamath-prasad 
I'm glad to hear this will help the service-fabrik-broker and avoid additional calls back into the platform!
You can track the story [here](https://www.pivotaltracker.com/story/show/158071828) (let me know if you can't access that story) and we're hoping to have that in a CF deployment in the next couple of weeks. We'll make sure to close this issue when it's ready.

**Comment by zrob** [comment]
Another request for this: https://cloudfoundry.slack.com/archives/C07C04W4Q/p1528394325000440
