### ISSUE TITLE
Is it possible to close Cloud Controller resource cache?

### ISSUE THREAD

**Issue by jiangchuan1220** [cloudfoundry/cloud_controller_ng#999]
## Issue
When using cf push, the package uploaded from cf cli is not the origin package.

## Context
We need to validate the integrity of packages uploaded from cf push. Our current idea is put a Nginx between cfcli and CC API and validate the package uploaded to Nginx.  But we found the package is not complete because the Cloud Controller has a resource cache. If a file is cached, it will not be uploaded. We want to know more detailed information about the resource cache. When will a file be cached and remove from the cache? Is it possible to close the cache function?
Thanks,
Jiang Chuan.

**Comment by elenasharma** [comment]
Hi @jiangchuan1220, thanks for the question! You actually have two questions here, one on how resource caching works, and a second requesting a feature to disable resource caching. Could you please ask the first question in our [#cf-capi](https://cloudfoundry.slack.com/messages/C07C04W4Q/) Slack channel?

**Comment by jiangchuan1220** [comment]
Hi @elenasharma , I asked the first question in the Slack channel. Do you have any idea about the how to disable the resource caching? Thanks.

**Comment by jiangchuan1220** [comment]
A possible solution is to return empty body ("[]") for resource match API from interceptor. Then the resource cache will not take effect.

**Comment by tcdowney** [comment]
@jiangchuan1220

I haven't personally had a chance to test this yet, but I believe in the short term you could configure Cloud Controller to have mutually exclusive min/max allowed file sizes for resource matching with the `cc.


https://www.pivotaltracker.com/story/show/152662647

**Comment by tcdowney** [comment]
Sorry, I accidentally hit "close and comment"... reopening. 😔
